### ISSUE TITLE
Support complex WSDL

### ISSUE THREAD

**Issue by kapsule** [mvantellingen/python-zeep#10]
Hi,

Does the library support files with complex structure? I'm trying to import a WSDL url and generates me errors.

`  File "/usr/local/lib/python3.5/dist-packages/zeep-0.5.0.dev0-py3.5.egg/zeep/wsdl/definitions.py", line 103, in parse kwargs[tag_name] = definitions.messages[param_msg.text]
KeyError:'{http://www.parkaregroup.com/PublisherService/1.0}IPublishServiceV10_startSession_InputMessage'
`

Thanks,

**Comment by mvantellingen** [comment]
Hi @kapsule, it should support all valid wsdl files. 

Are you able to provide the wsdl document? If not, can you check if it works in soap-ui?

**Comment by kapsule** [comment]
Hi @mvantellingen 

Thank you very much for reply. This is the url of the WSDL service.

https://hosting.parkaregroup.com/PublisherService/PublisherService.svc?wsdl=wsdl2

**Comment by mvantellingen** [comment]
Seems like soap-ui doesn't like this wsdl either: https://www.soapui.org/

Might just be an invalid wsdl, i'll can check later if that is teh case

**Comment by kapsule** [comment]
Hi @mvantellingen.

No need. Thank you very much for the information.

**Comment by mvantellingen** [comment]
@kapsule Just noticed that you are pointing to wsdl2. I assume if you use 

    https://hosting.com/PublisherService/PublisherService.svc?wsdl

That it works. That file includes wsdl2 normally.

**Comment by mvantellingen** [comment]
Ah, I see that the wsdl only offers http bindings and not soap. That isn't finished yet, so that might explain
