### ISSUE TITLE
unable to perform -mzeep with basic authentication

### ISSUE THREAD

**Issue by Colleoni** [mvantellingen/python-zeep#102]
Hi,

thank you very much for your library.
I have some troubles with basic authentication, in particular I am not able to run the command

`python -mzeep <url-to-wsdl>`

**Comment by mvantellingen** [comment]
Yeah it should support the python mzeep https://username:password@host/ variant (which actually might already work in requests?)

**Comment by Colleoni** [comment]
I tried it by I was not able to connect. Anyway, after some investigations I think I have some problems due to the fact that the password contains strange characters. So, I will close the issue

**Comment by mvantellingen** [comment]
Just tested it to be sure, but it seems to work. Perhaps you need to escape special characters? Did you try to wrap the url in single quotes? Anyway closing for now :-)
