### ISSUE TITLE
Support calling operations with non valid python literals

### ISSUE THREAD

**Issue by joshuaduffy** [mvantellingen/python-zeep#103]
Hi,

I am working with a WSDL file that contains characters that would be illegal in a Python method in the operation name (for example `DoSomeThingPH-v2-0`). So I cannot do the following to action an operation:

`>>> from zeep import Client
>>> client = Client(
...     'http://www.webservicex.net/ConvertSpeed.asmx?WSDL')
>>> print(client.service.ConvertSpeed(
...     100, 'kilometersPerhour', 'milesPerhour'))
62.137`

How can I send a message in for an operation that is defined against a service? I am doing the following to get all the services but I cannot see a method to send a message in.
`zeep.wsdl.services.values()`

**Comment by mvantellingen** [comment]
Yeah this needs to be fixed, thanks.

In the meantime you can do something like this:

```python
import zeep
from zeep.client import OperationProxy

client = zeep.Client(...)
OperationProxy(client.service, 'DoSomeThingPH-v2-0')(args, kwargs)

```

**Comment by mvantellingen** [comment]
You can now use ``client.service['DoSomeThingPH-v2-0'](foo, bar)``

**Comment by joshuaduffy** [comment]
Thank you!
