### ISSUE TITLE
Multithreading cache

### ISSUE THREAD

**Issue by Colleoni** [mvantellingen/python-zeep#105]
Hi,

this is not a real issue but more a suggestion for the future. I am writing an application using a framework that uses multiple threads, unfortunately zeep has a sqlite3 based cache which cannot be accessed from different threads. As a result I cannot use the cache.

**Comment by mvantellingen** [comment]
Ah good point yes. The cache is only used when the wsdl is loaded (during the zeep.Client() call). Are you initialising the client from multiple threads? It doesn't support reusing the same sqlite connection from different threads right? So closing/opening on every cache call is also possible (with a mutex around it)?

**Comment by Colleoni** [comment]
Hi, 
in order to better explain what I am doing, I am using the framework django and I do not have control over thread execution. You are right I am using multiple clients. Basically I am trying to convert SOAP responses from a server that I do not own to Json responses for an android application. As a result I thought it was better to use several different clients in order to avoid queue on a single client. I am still not sure this is the best approach.

I have read some online posts about multithreading with sqlite3 and I am not sure about multiple connections, I know there are some limitation but I am still trying to figure out about this topic.
At the moment the error I receive is: "SQLite objects created in a thread can only be used in that same thread" which I thing is due to the fact that  multithread is disable by default in python. The documentation reports that there were concurrency issues with previous sqlite versions.

**Comment by Colleoni** [comment]
Ok now I figure out a little bit more. The problem in my case comes out of uwsgi as it launches different Django instances, 4 in my cases. 
I was declaring a single SqliteCache object and a Transport object inside a .py file and outside any class so that there were only a single instance. while I was declaring the client object inside a class __init__ method so that at the end each thread has its own. As far as I understood there are different ways to enable multithreading with sqlite3, but if I have correctly understood in my case the problem could be solved simply creating a database connection for each thread. Python does not allow to share the same connection between different threads, but it is perfectly fine to have a connection in each thread. Thus since sqliteCache object is the one that own the connection, I simply have to create a SqliteCache object and a Transport object inside the __init__. At the beginning I thought this was a duplicate object but it is not as the database will still remain the same.

As a result, if I am correct there is no need for modify your library. I only one final observation on the SqliteCache class, during my investigation I noticed that you miss a self._db.commit() at the end of the __init__ method.

**Comment by mvantellingen** [comment]
Hi @Colleoni,

I've just done some changes that should make it possible to re-use the same sqlite backend cache between different threads. See https://github.com/mvantellingen/python-zeep/commit/2ba323fa06dc85948f6ed2cddc9ffbc13dce961b

**Comment by Colleoni** [comment]
Awesome, I will certainly check it. Thank you very much
