### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by brot** [mvantellingen/python-zeep#1055]
Are there any news on this topic? Python 3.8.0 was release 2019-10-14.  
Currently zeep is the only SOAP client which is still maintained as far as I know.  So support for the latest Python version would be highly appreciated.  

Maybe a good start would be to add 3.8 to `tox.ini` and see which tests are failing? 

Related issue regarding Tornado support:
https://github.com/mvantellingen/python-zeep/issues/990

**Comment by ThreePinkApples** [comment]
Have you had any issues with Python 3.8 and Zeep? I've used it with 3.8 and haven't noticed any issues my self.

**Comment by ThreePinkApples** [comment]
Looks like #1034 is all that is needed

**Comment by brot** [comment]
Yes, #1034 is one of the missing peaces. But not sure if the project is able to promote Zeep as Python 3.8 ready as long as there is an issue with the optional Tornado support: #990  
We are not using Zeep with Tornado, so I cannot help with a PR for this issue, but I really would love to see Zeep with official Python 3.8 support. The first step would be to merge #1034

**Comment by akeeman** [comment]
As I see it these are the options:
1. Merge #1034 with the side note that one optional and very outdated dependency is not supported
2. Still merge #1034, do it in a new major version and remove tornado support all together
3. Wait for someone to upgrade tornado to v6 (apparently not much community interest) , then release a new version with #1034 merged
4. Never let Zeep be compatible with Python 3.8

@mvantellingen What is your opinion here?

**Comment by mbello** [comment]
I hope you will choose #2. No need for Tornado as async transport these days. Should also drop python2 support.
I would also suggest a migration to httpx as the transport, it has both sync and async clients. Or, better yet, just start taking an http client as parameter and avoid requiring a specific one. The interface offered by aiohttp, requests and httpx is very very similar.

**Comment by mvantellingen** [comment]
Yeah agree, next version I want to make it py35+ and see if we can make httpx the default. Now to find some time :-)

**Comment by mvantellingen** [comment]
The next version (4.0) drops support for aiohttp altogether. One of the reasons development of zeep stagnated was the addition of all the async transports which made it a maintenance hell.

From zeep 4.0 and onwards only httpx will be supported for async operations (wsdl loading will be kept sync)
