### ISSUE TITLE
WSDL with X509 auth.

### ISSUE THREAD

**Issue by nbordin** [mvantellingen/python-zeep#1067]
Hello all!

I am facing some issues connecting to a WSDL server using X509 auth.

With the following code

```python
from zeep.wsse.username import UsernameToken
from zeep.wsse.signature import Signature
signature = Signature(key_file='path/Myprivate.pem', certfile='path/Mycert.pem') 
username_token = UsernameToken(username, pwd)
client = Client(wsdl=WSDL,wsse=[username_token, signature])
```

the error I receive is

`OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]`

To fix the first error I added Trasport with Session.verify = False

```python
from zeep import  Client
from requests import Session
from zeep.transports    import  Transport
from zeep.wsse.signature import Signature
from zeep.wsse.username import UsernameToken
session = Session()
session.verify = False
signature = Signature(key_file='path/Myprivata.pem', certfile='path/Mycert.pem') 
username_token = UsernameToken(username, pwd)
client = Client(wsdl=WSDL,wsse=[username_token, signature], transport=Transport(session=session))
```

Using the second snippet I received an error from the partner server (500 invalid XML).

Do you think this code is right and the problem is on the partner's side or there is another way to fix it?

Thanks for your support

**Comment by Bliph** [comment]
Could this be related to timestamp or wrong response certificate? Please have look at #996

**Comment by nbordin** [comment]
I resolved the issue. It was a problem on the server side.

Thanks for your kind response.
