### ISSUE TITLE
header parameter is not being passed to the server

### ISSUE THREAD

**Issue by siddharth2395** [mvantellingen/python-zeep#1078]
Please keep the issues that real bug reports only. Please request help/support on a relevant channel like stackoverflow. This issue will most likely be closed.

This is my expected Soap request data:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:ser="http://www.peddle.com/services">
   <soapenv:Header>
   <ServiceLocatorApiToken>SomeAPIKey</ServiceLocatorApiToken>
   </soapenv:Header>
   <soapenv:Body>
      <tem:GetService>
         <!--Optional:-->
         <tem:getServiceRequest>
            <!--Optional:-->
            <ser:ServiceRequested>SomeService</ser:ServiceRequested>
         </tem:getServiceRequest>
      </tem:GetService>
   </soapenv:Body>
</soapenv:Envelope>
```

To do this I have create below mentioned script: 

Note: for the security reasons I have not mentioned the Soap WSDL URL or Method

```
client = Client(wsdl=wsdl_url)
header = xsd.Element('Authentication', xsd.ComplexType([
    xsd.Element('ServiceLocatorApiToken', xsd.String()),
]))
header = header(ServiceLocatorApiToken='CounterBidService')
payload = {
    "getServiceRequest":
        {
            "ServiceRequested": u"SomeService"
        }
}
response = client.service[method](payload, _soapheaders=[header])
```

When I execute the script and inspecting server log it seems that header value is not being passed as expected due to which my authorization fails.

I am not able to check the constructed XML of the request, Can anyone help if am I constructing the header in right way or am I missing something?

**Comment by adamwojt** [comment]
Try below:
``` python
client.set_default_soapheaders([header])
response = client.service[method](payload)

**Comment by siddharth2395** [comment]
Completely discarded the usage of Soap APIs and moved the entire thing to REST APIs. 🏳
