### ISSUE TITLE
Documentation website is down.

### ISSUE THREAD

**Issue by FilBot3** [mvantellingen/python-zeep#1080]
The documentation website is down that is linked in the about, and PyPi. https://docs.python-zeep.org/

**Comment by selvanram** [comment]
Bumping this. I can't access the docs.

**Comment by kamichal** [comment]
> The page isn't redirecting properly
> An error occurred during a connection to python-zeep.readthedocs.io. 

The same occurs for https://docs.python-zeep.org/

**Comment by klamir** [comment]
I beleave you can build the docs locally.
just 'cd' to docs folder and 'make html', the output will be in 'docs/_build/html', just open the index.html file in your browser.

**Comment by joshwiseman** [comment]
There is a PDF version available in the meantime https://readthedocs.org/projects/python-zeep/downloads/pdf/master/

**Comment by mvantellingen** [comment]
Seems like changed at readthedocs.org. Initially I had a AWS cloudfront running in front of readthedocs but that doesn't seem necessary anymore, removing that and enabling https support at readthedocs fixed it
