### ISSUE TITLE
Issue with multiple namespaces

### ISSUE THREAD

**Issue by tgalery** [mvantellingen/python-zeep#11]
Hi and thanks for the awesome library. We are using zeep for a project that integrates with [ID3 Global](http://www.id3globalsupport.com/Website/content/Sample%20Code/Web%20Dev%20Guide%20HTML/developers%20guide.html) via SOAP.  We instantiate a client from a wsdl file, however the file defines services for different namespaces.

```
from zeep import Client
soap_client = Client('https://pilot.id3global.com/ID3gWS/ID3global.svc?wsdl')
```

Now, if we try to use the ID3 global's authenticate method (e.g. `soap_client.service.AuthenticateSP(some_data)`), spits back an `Operation Not Found` error.

It seems that `soap_client.service` uses methods available to some namespaces, but not all.
Looking at the wsdl object gives me some extra info:

```
soap_client.wsdl.schema._prefix_map

    {
    	'ns0': 'http://www.id3global.com/ID3gWS/2013/04/Imports',
    	'ns1': 'http://www.id3global.com/ID3gWS/2013/04',
    	'ns2': 'http://schemas.microsoft.com/2003/10/Serialization/',
    	'ns3': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
    	'ns4': 'http://schemas.microsoft.com/Message',
    	'ns5': 'http://schemas.datacontract.org/2004/07/GlobalCheck.DataLib'
    }
```

The authenticate sp type seems to be available on namespace 1 `auth_type = soap_client.get_element('ns1:AuthenticateSP')`, but it seems that in order to use that method I would need to navigate a really complex data structure. For example, :

```
client.wsdl.services['{http://www.id3global.com/ID3gWS/2013/04}ID3global'].ports.keys()
    ['{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalCredentials',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalCredentials',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalConfig',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalConfig',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalDocImage',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalProfile',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalProfile',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalAuthenticate',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalAuthenticate',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalSearch',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalOrganisation',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalOrganisation',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalMembership',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalMembership',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalSupplier',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalSupplier',
     '{http://www.id3global.com/ID3gWS/2013/04}basicHttpBinding_GlobalCaseManagement',
     '{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalCaseManagement']
```

Then if I go to `soap_client.wsdl.services['{http://www.id3global.com/ID3gWS/2013/04}ID3global'].ports['{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalAuthenticate'].binding` I can see:

```
<Soap12Binding(name=u'{http://www.id3global.com/ID3gWS/2013/04}wsHttpBinding_GlobalAuthenticate', port_type=<PortType(name=u'{http://www.id3global.com/ID3gWS/2013/04}IGlobalAuthenticate')>)>
```

Now these bindings seem to be the ones that would allow me to use the authenticate sp method (see here http://www.id3globalsupport.com/Website/content/Sample%20Code/Web%20Dev%20Guide%20HTML/html/64401bb3-c606-d2b4-9e49-08cebe9376da.htm) . But I'm still unsure how to use it to make the request.

Can someome help me understand / navigate through this ?

**Comment by mvantellingen** [comment]
Hi, Thanks for the detailing issue report 👍 

I'll check this in detail later, but my initial thinking is that the issue is due toe the facet that client.service is by default bound to the first service/port (see client.py). If you use `python -mzeep <wsdl file>` then you can see a list of all ports and the operations within each port.

**Comment by tgalery** [comment]
No worries, I will take a look at the operations from the cli interface. We are also happy to contribute by submitting a pr the retrieves services by operations or something (if you point us the way).

**Comment by tgalery** [comment]
Also, sorry to nag you about this, but are there any docs on how to send secure headers using zeep?

**Comment by mvantellingen** [comment]
Do you mean ws-security headers?

**Comment by tgalery** [comment]
yep

**Comment by mvantellingen** [comment]
I've implemented support for the username token profile in #13 Could you give that a go? If you need wsse x509 support then that is one of the next things on my list (which I have created for suds earlier: https://github.com/mvantellingen/py-soap-wsse)

**Comment by mvantellingen** [comment]
The master branch now has better support for multiple service/port combinations:

```python
from zeep import Client

client = Client(
    'https://pilot.id3global.com/ID3gWS/ID3global.svc?wsdl')

service = client.bind('ID3global', 'wsHttpBinding_GlobalCredentials')
service.CheckCredentials('foo', 'bar')
```

Let me know if you run into any more issues :-)

**Comment by tgalery** [comment]
Cool, will test that now and ping you as soon as possible.

**Comment by benzolius** [comment]
Hi Michael,

Thanks for this great package and for the recently added features.

We tested it on the ID3 Global service and it works.

Hopefully we will have more feedback soon.

**Comment by benzolius** [comment]
Hi Michael,

Please help me:
http://stackoverflow.com/questions/37122096/python-zeep-how-can-i-find-out-easier-the-binding-a-method-property-belongs-to
