### ISSUE TITLE
Value "true" parsed as Python boolean "False"

### ISSUE THREAD

**Issue by malusm** [mvantellingen/python-zeep#1105]
1. The version of zeep - 3.4.0
2. WSDL - https://betaapi.tracelink.com/soap/som?wsdl

Hi,

It seems that Zeep incorrectly parses string "true" as Python boolean False (which is the default Python behavior).
Is there any way to avoid that except for setting raw_response=True and parsing it yourself?

Attaching the code though it's not runnable without an endpoint.

```
settings = Settings(extra_http_headers={'Authorization': 'Bearer XYZ')

client = Client('https://betaapi.tracelink.com/soap/som?wsdl', settings=settings)
service = client.create_service('{urn:tracelink:soap}somPortBinding', 'http://internal_endpoint')

lot_query_params_type = client.get_type('ns1:LotQueryParamsType')
lot_query_request = lot_query_params_type(ItemCode='AAA', ItemCodeType='BBB', Lot='CCC', IncludePackageLevelQuantities='true')

response = service.GetLotStatus(LotQueryRequest=lot_query_request)

```

Best Regards,
Mike

**Comment by malusm** [comment]
It seems the value has leading and trailing white characters.
I printed the value in Boolean.pythonvalue and it's

```
"
          true
        "
```

Is it a good idea to add strip in the method?

`return value.strip() in ("true", "1")`

**Comment by da1910** [comment]
> It seems the value has leading and trailing white characters.
> I printed the value in Boolean.pythonvalue and it's:
> 
> ```
> '
>           true
>         '
> ```
> 
> Is it a good idea to add strip in the method?
> 
> `return value.strip() in ("true", "1")`
> 
Yes, this would be the behaviour intended by the standard, the whitespace behaviour for simple types is specified [here](https://www.w3.org/TR/xmlschema11-2/#built-in-primitive-datatypes). All whitespace before and after should be removed.

> Or maybe even to strip all values? Is there any setting for that?
The standard enforces the same behaviour for all builtin simple types except "string"

> Seems that all values in this endpoint are returned in the same way, e.g.:
> 
> `'ExpirationDate': '\n 2025-05-05\n '`
> 
> Seems that e.g. SoapUI is stripping all values by default:
> 
> `<ExpirationDate>2025-05-05</ExpirationDate>`
> 
> I think that could be implemented in AnySimpleType.parse_xmlelement as
> 
> `return self.pythonvalue(xmlelement.text.strip())`
 Personally it would better be enforced on a per-type basis in xsd/types/builtins.py, that would tally with the regex validation already done for those types that enforce specific formats.

Are you interested in putting a pull request together? If not then I'm happy to do so.
