### ISSUE TITLE
Import collision with asyncio

### ISSUE THREAD

**Issue by da1910** [mvantellingen/python-zeep#1123]
Fresh install of zeep from PyPi, attempting to use other features of the asyncio package fails.

Zeep imports aiohttp, which fails typing checks in aiohttp.tcp_helpers on line 13, since python tries to import zeep.asyncio.

A quick workaround is to rename the zeep asyncio folder to something else, along with the three references in the zeep source, but a better solution ought to be found.

**Comment by mvantellingen** [comment]
The next version (4.0) drops support for aiohttp altogether. One of the reasons development of zeep stagnated was the addition of all the async transports which made it a maintenance hell.

From zeep 4.0 and onwards only httpx will be supported for async operations (wsdl loading will be kept sync)
