### ISSUE TITLE
Cannot import zeep.wsse.MemorySignature

### ISSUE THREAD

**Issue by sahuagin** [mvantellingen/python-zeep#1127]
Thanks for taking the time to report an issue!

Please before continuing read http://docs.python-zeep.org/en/master/reporting_bugs.html

Since Zeep is a module I've created and currently maintain in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)

> less .env/lib/python3.8/site-packages/zeep/__init__.py                                                                                      [13:51:15]
> from zeep.client import CachingClient, Client  # noqa
> from zeep.transports import Transport  # noqa
> from zeep.plugins import Plugin  # noqa
> from zeep.settings import Settings  # noqa
> from zeep.xsd.valueobjects import AnyObject  # noqa
>
> __version__ = "3.4.0"

**version = "3.4.0"**

2. The WSDL you are using
None.

3. And most importantly, a [runnable example script](http://docs.python-zeep.org/en/master/reporting_bugs.html) which exposes the problem.

```python
from zeep.wsse import BinarySignature
from zeep.wsse import MemorySignature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MemorySignature' from 'zeep.wsse' (.env/lib/python3.8/site-packages/zeep/wsse/__init__.py) 
```

```bash
cat .env/lib/python3.8/site-packages/zeep/wsse/__init__.py 
from .compose import Compose  # noqa
from .signature import BinarySignature, Signature  # noqa
from .username import UsernameToken  # noqa
```
Note that issues without a runnable example script are likely to be closed
without further research. This is done to keep the number of issues 
manageable and focus my time on actually fixing issues instead of analyzing
the exact nature of the issue.

Also please don't paste WSDL/XSD file contents directly into the issue since 
that makes it hard to read. Please make it available somewhere public where your example script can retrieve it form (so not behind a company firewall)

**Comment by da1910** [comment]
I've submitted a PR for this issue, in the meantime you can do
`from zeep.wsse.signature import MemorySignature`
