### ISSUE TITLE
Duplicate XML Node sent by zeep

### ISSUE THREAD

**Issue by nivels** [mvantellingen/python-zeep#1129]
[zeep 3.4]
[ABACUS_Customer_2017.zip](https://github.com/mvantellingen/python-zeep/files/5078406/ABACUS_Customer_2017.zip)

Hi all

I have the following problem

Using the attached WSDL file causes zeep to duplicate the node "AbaConnectParam". Is the a way to suppress this?

Best regards
Rolf <rolf@weon.ch>

```xml
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
	<soap-env:Body>
		<ns0:FindRequest xmlns:ns0="http://www.abacus.ch/abaconnect/2017.00/debi/Customer">
			<ns0:AbaConnectParam xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns0:RequestType">
				<ns0:AbaConnectParam>
					<ns1:Login xmlns:ns1="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">
						<ns1:LoginToken>2c0597f3d148843a008413edc3ba842d4dd8ef85</ns1:LoginToken>
					</ns1:Login>
					<ns2:Revision xmlns:ns2="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">0</ns2:Revision>
					<ns3:Level xmlns:ns3="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">Information</ns3:Level>
				</ns0:AbaConnectParam>
				<ns0:FindParam>
					<ns4:Index xmlns:ns4="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">2</ns4:Index>
					<ns5:Operation xmlns:ns5="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">GREATER_EQUAL</ns5:Operation>
					<ns6:KeyFields xmlns:ns6="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">
						<ns6:IntData Name="CustomerNumber">0</ns6:IntData>
						<ns6:StringData Name="CustomerID">Customer Name</ns6:StringData>
					</ns6:KeyFields>
				</ns0:FindParam>
			</ns0:AbaConnectParam>
		</ns0:FindRequest>
	</soap-env:Body>
</soap-env:Envelope>
```

**Comment by da1910** [comment]
I wasn't able to reproduce this using the WSDL linked, here's what I did and the request text I got from zeep 3.4.0. How did you generate the request object, perhaps I generated it differently to you? Can you give the code below a go and see if you get a valid output, if not then can you provide the code you use to generate the incorrect xml?

```
import zeep
from lxml import etree
connection_parameter = {
    'Login': {
        'LoginToken': '2c0597f3d148843a008413edc3ba842d4dd8ef85',
        'UserLogin': None
    },
    'Revision': 0,
    'Level': 'Information',
    'Additional': None
}
find_parameter = {'Index': 2,
 'Operation': 'GREATER_EQUAL',
 'KeyFields': {
     'IntData': {
         '_value_1': 0,
         'Name': 'CustomerNumber'
     },
     'LongData': [],
     'StringData': {
         '_value_1': 'Customer Name',
         'Name': 'CustomerID'
     },
     'DateData': [],
     'DateTimeData': [],
     'BooleanData': [],
     'DecimalData': []
 }}
client = zeep.Client(wsdl='path/to/wsdl/Customer.wsdl')
node = client.create_message(client.service, 'find', AbaConnectParam=connnection_parameter, FindParam=find_parameter)
print(etree.tostring(node, pretty_print=True))
```
which gave:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:FindRequest xmlns:ns0="http://www.abacus.ch/abaconnect/2017.00/debi/Customer">
      <ns0:AbaConnectParam>
        <ns1:Login xmlns:ns1="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">
          <ns1:LoginToken>2c0597f3d148843a008413edc3ba842d4dd8ef85</ns1:LoginToken>
        </ns1:Login>
        <ns2:Revision xmlns:ns2="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">0</ns2:Revision>
        <ns3:Level xmlns:ns3="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">Information</ns3:Level>
      </ns0:AbaConnectParam>
      <ns0:FindParam>
        <ns4:Index xmlns:ns4="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">2</ns4:Index>
        <ns5:Operation xmlns:ns5="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">GREATER_EQUAL</ns5:Operation>
        <ns6:KeyFields xmlns:ns6="http://www.abacus.ch/abaconnect/2007.10/core/AbaConnectTypes">
          <ns6:IntData Name="CustomerNumber">0</ns6:IntData>
          <ns6:StringData Name="CustomerID">Customer Name</ns6:StringData>
        </ns6:KeyFields>
      </ns0:FindParam>
    </ns0:FindRequest>
  </soap-env:Body>
</soap-env:Envelope>
```

**Comment by nivels** [comment]
I used the following code:

`service_binding = abaconnectClient.service._binding.name
service_address = abaconnectClient.service._binding_options['address'].replace( 'http://localhost:40000', 'https://abacus.github.com' )
service2 = abaconnectClient.create_service( service_binding, service_address )

#
# First retrieve the factories
#
abaConnectFactory = abaconnectClient.type_factory( 'ns1' )
customerFactory = abaconnectClient.type_factory( 'ns0' )
customerTypeFactory = abaconnectClient.type_factory( 'ns2' )

abacusToken = "2c0597f3d148843a008413edc3ba842d4dd8ef85"
loginTokenObj = abaConnectFactory.LoginTokenType(abacusToken)
loginObj = abaConnectFactory.LoginType( LoginToken = loginTokenObj )
levelObj = abaConnectFactory.LevelType("Information")
requestParameterObj = abaConnectFactory.RequestParameterType(Login=loginObj, Level=levelObj, Revision=0)

stringDataList = [abaConnectFactory.StringDataType(Name="Name", _value_1="CustomerID")]
intDataList = [abaConnectFactory.IntDataType(Name="CustomerNumber", _value_1=0)]
objectData = abaConnectFactory.ObjectDataType(StringData=stringDataList, IntData=intDataList)
operationType = abaConnectFactory.OperationType("GREATER_EQUAL")
findTypeObj = abaConnectFactory.FindType(Index=2, Operation=operationType, KeyFields=objectData)

findRequestObj = customerFactory.RequestType(AbaConnectParam=requestParameterObj, FindParam=findTypeObj)

#
# Let's search
#
try:
    findResp = service2.find(findRequestObj)
except zeep.exceptions.Fault as fault:
    details = abaconnectClient.wsdl.types.deserialize(fault.detail[0])
    print(details.Code)
    print(details.Message)
    userLogoutObj = abaConnectFactory.LoginTokenType(abacusToken)
    logoutResp = service2.logout(LoginToken=userLogoutObj)
    exit(0)

#
# DEBUG Result Data
#
if resultData:
    print(resultData)
else:
    print("Not found!!!")

#
# Now logout
#
userLogoutObj = abaConnectFactory.LoginTokenType(abacusToken)
try:
    logoutResp = service2.logout(LoginToken=userLogoutObj)
except zeep.exceptions.Fault as fault:
    details = abaconnectClient.wsdl.types.deserialize( fault.detail[0] )
    print(details.Code)
    print(details.Message)
    exit(0)

`

This produces the output from the original request.
