### ISSUE TITLE
Ability to send pre-build xml document

### ISSUE THREAD

**Issue by bookbound** [mvantellingen/python-zeep#1130]
Is there a way to send a pre-cooked xml document to the SOAP endpoint?  I know there's `client.create_message` to see the xml zeep generates. But no separate call to send an xml doc.

For most calls, I'm happy generating the dict object for zeep to translate to xml.  But one method is extremely picky about capitalization, order of attributes, etc. (And these restrictions are not defined in the wsdl.) I'd like to use an existing tool to generate that xml, and use zeep to send it.

Thanks

**Comment by sivagalem** [comment]
You should be able to achieve that by simply using the PlugIn as described in https://docs.python-zeep.org/en/master/plugins.html
In egress method, you can load your custom XML file into lxml.element and return that newly loaded element as envelope. Hope that helps!

**Comment by sivagalem** [comment]
> Is there a way to send a pre-cooked xml document to the SOAP endpoint? I know there's `client.create_message` to see the xml zeep generates. But no separate call to send an xml doc.
> 
> For most calls, I'm happy generating the dict object for zeep to translate to xml. But one method is extremely picky about capitalization, order of attributes, etc. (And these restrictions are not defined in the wsdl.) I'd like to use an existing tool to generate that xml, and use zeep to send it.
> 
> Thanks

You should be able to achieve that by simply using the PlugIn as described in https://docs.python-zeep.org/en/master/plugins.html
In egress method, you can load your custom XML file into lxml.element and return that newly loaded element as envelope. Hope that helps!

**Comment by fnicollet** [comment]
Hello,

I had an issue with how the Zeep request was sent to the WebService. Basically using:

`client.create_message(...)`

Would create the right XML Envelope, but once sent in the SOAP request some information was missing (an array of ComplexType items).
Using @sivagalem technique, I created a simple plugin:
```
raw_xml_envelope = None

# send pre-built XML document
class SendCustomResponsePlugin(Plugin):
    def ingress(self, envelope, http_headers, operation):
        #logger.info("ingress: " + get_xml_node_as_str(envelope))
        return envelope, http_headers

    def egress(self, envelope, http_headers, operation, binding_options):
        if raw_xml_envelope is not None:
            envelope = raw_xml_envelope
        return envelope, http_headers
...
client = zeep.Client(wsdl=wsdl, settings=settings, plugins=[SendCustomResponsePlugin()])
...
# generate RAW XML sent via SOAP
    raw_xml_envelope = client.create_message(client.service, 'setBonCommande', acces=accessToken, bonCommande=bonCommande)
    # a custom plugin is used to send the XML from create_message instead
    webserviceResult = client.service.setBonCommande(accessToken, bonCommande)
```

And it works great, thanks @sivagalem ! I hope @bookbound  can mark this issue as fixed

Fabien

**Comment by bookbound** [comment]
Yes, this works. Thank you!

I also end up sending a dummy argument to the service method since the WSDL does not match the actual needs of my endpoint/server.  That is, I pass an object that validates for another method, then stuff the envelope with a totally different method where the WSDL is causing problems.

e.g.
```client = Client(str(Path.home() / 'foo.wsdl'), plugins=[SendCustomResponsePlugin(), history], settings=settings)
qservice = client.create_service('{http://example.com/xml/wsdl}QuerySoapBinding',
                                 ('https://example.com/center/xml/query'))
...
    qstring = {'_value_1': {'DeleteByID': {'_value_1': {'ID': '000'}}}}
    raw_xml_envelope = True
    resp=qservice.submit(**qstring)
```
