### ISSUE TITLE
SharePoint 2010 - UpdateListItem, updates XML is not sent

### ISSUE THREAD

**Issue by sebasmonia** [mvantellingen/python-zeep#114]
If I run the update manually with requests, it works but when I use zeep, I can't find a way for it to include the XML inside the updates tag (checking with requests). I tried Any,  AnyObject, passing the XML as second parameter to client.service.UpdateListItem(), nothing seems to work. I'm not sure it's a bug though, maybe I'm using it wrong...

template_update = "xml_listed_below"
h = { "Content-Type": "text/xml", "SOAPAction": "http://schemas.microsoft.com/sharepoint/soap/UpdateListItems" }
url = "sharepoint_url"

requests.post(update, data=template_update, headers=h)

```
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <UpdateListItems xmlns="http://schemas.microsoft.com/sharepoint/soap/">
      <listName>{83810A7D-65C0-457E-8E50-29A378356CD7}</listName>
      <updates>
        <Batch OnError="Continue">
           <Method Cmd="Update" ID="1">
              <Field Name="ID">26</Field>
              <Field Name="DM_x002f_BAU_x002f_Ticket_x0020__x0023_">25</Field>
           </Method>
       </Batch>
       </updates>
    </UpdateListItems>
  </soap:Body>
</soap:Envelope>

**Comment by sebasmonia** [comment]
WSDL is the same than in issue #99

**Comment by mvantellingen** [comment]
Just did a commit so that you can now pass lxml.etree.Element() objects to any types.

For example::

```python
from lxml.builder import E
from lxml import etree

from zeep import Client

any_type = E.Batch(
    E.Method(
        E.Field('26', Name='ID'),
        E.Field('25', Name='DM_x002f_BAU_x002f_Ticket_x0020__x0023_'),
        Cmd='Update', ID='1'
    ),
    onError='Continue'
)

client = Client('sharepoint.wsdl')
response = client.service.UpdateListItems(
    listName='{83810A7D-65C0-457E-8E50-29A378356CD7}',
    updates={'_value_1': any_type})

```

**Comment by sebasmonia** [comment]
And it worked. Awesome and thank you so much for finally providing an easy to use SOAP lib for Python :)
