### ISSUE TITLE
Documentation is stale

### ISSUE THREAD

**Issue by WhyNotHugo** [mvantellingen/python-zeep#1147]
Both the [`latest`](https://docs.python-zeep.org/en/latest/changes.html) and [`master`](https://docs.python-zeep.org/en/master/changes.html) version show 3.2.0 as the latest version.

However, [`CHANGES`](https://github.com/mvantellingen/python-zeep/blob/master/CHANGES) have been documented and released since.

Maybe readthedocs hasn't been building all this time?

**Comment by mvantellingen** [comment]
Seems something was wrong with the readthedocs <-> GitHub integration, fixed now

**Comment by WhyNotHugo** [comment]
Thanks!

`latest` still seems to indicate that 3.2.0 is the last version though.
