### ISSUE TITLE
How to add wsa headers

### ISSUE THREAD

**Issue by utkarshohm** [mvantellingen/python-zeep#117]
While Zeep's python docs states that WS-Addressing is in development, I have been trying to add custom headers using Elements to implement it on my own. 

But I feel there is insufficient documentation for a noob like me in http://docs.python-zeep.org/en/latest/in-depth.html#using-soap-headers to implement it. I have to include the wsa:To tag. This is my code currently. 
`header = xsd.Element('{http://www.w3.org/2005/08/addressing}To', xsd.String())`
`header_value = header(To=api_direct_url)`
`print(client.service.getPassword(userId='XXX',password='XXX',_soapheader=header_value))`

Please help!

**Comment by mvantellingen** [comment]
Could you give the master branch a try and use the following:

```python
header = xsd.Element('{http://www.w3.org/2005/08/addressing}To', xsd.String())
header_value = header(To=api_direct_url)
print(client.service.getPassword(userId='XXX',password='XXX',_soapheaders=[header_value]))
```

**Comment by utkarshohm** [comment]
@mvantellingen - Thanks for the quick reply and bearing with my preliminary queries!

I tried the code with the master branch but my service method getPassword's signature obviously doesn't account for the keyword argument '_soapheaders'. What am I missing?
Code:
`header1 = xsd.Element('{http://www.w3.org/2005/08/addressing}Action',xsd.String())`
`header2 = xsd.Element('{http://www.w3.org/2005/08/addressing}To',xsd.String())`
`header1_value = header(Action=api_direct_url)` 
`header2_value = header(To=svc_url)`
`print(client.service.getPassword(UserId='XXX',Password='XXX',_soapheaders=[header1_value, header2_value]))`
Error:
`TypeError:__init__() got an unexpected keyword argument _soapheaders. Signature: (UserId: xsd:string, Password: xsd:string)`

**Comment by mvantellingen** [comment]
Doesn't seem like you are using the latest version. Could you try:

    pip uninstall zeep
    pip install -U https://github.com/mvantellingen/python-zeep/archive/master.zip#egg=zeep

**Comment by utkarshohm** [comment]
You were right. I am using the latest version now. Same code as above. Error in first line only.
`TypeError: String() got an unexpected keyword argument 'Action'. Simple types expect only a single value argument` 

Thanks in advance for helping out so much!

**Comment by mvantellingen** [comment]
Ah yes, you are passing it a keyword argument, but since the elements use a SimpleType (xsd.String) you need to pass it a positional arg (or use the value kwarg)
so ``header1_value = header1(api_direct_url)`` etc

**Comment by utkarshohm** [comment]
Yes I tried that too, but then I get: 
```
ValueError: Invalid value given to _soapheaders
```
Sorry, if this is troubling you! Really appreciate your library and help!

**Comment by mvantellingen** [comment]
My bad; try the following: https://github.com/mvantellingen/python-zeep/commit/9ea6c50c298c5d0a74254b4d81268b39b39a5e0f#diff-d621daedec82c9970a15b65089a491feR375

**Comment by utkarshohm** [comment]
Works like a charm! Best library for SOAP
Thanks @mvantellingen, will contribute to this library in whatever way I can :)
