### ISSUE TITLE
wsu:Timestamp

### ISSUE THREAD

**Issue by NdYGA** [mvantellingen/python-zeep#119]
Hello Dear Mr. van Tellingen,
I want to test Your library as a lightweight solution to replace Java in my project.
My problem is:
`<soapenv:Envelope xmlns:ser="http://services.getdev.com" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header>
      <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <wsu:Timestamp wsu:Id="TS-F7A76418937B4B1FE914679819717104">
            <wsu:Created>2016-07-08T16:21:28+00:00</wsu:Created>
            <wsu:Expires>2016-07-08T16:30:28+00:00</wsu:Expires>
         </wsu:Timestamp>...
`

How do I add the "Timestamp" into the header?
I would be very grateful if You could help.

**Comment by mvantellingen** [comment]
Is this a complete snippet? Can you try to format it a bit better in the future? ;-)

Anyway, if this is a wsse username token header then the additional headers are automatically added. If not then you can add manual headers via http://docs.python-zeep.org/en/latest/in-depth.html#using-soap-headers. But it seems there is missing some content from the snippet

**Comment by NdYGA** [comment]
Thanks! I do appreciate the very quick response.
ps . My apologize for the "messy" code snippet - done by accident :)

**Comment by andreixk** [comment]
I have the same question, where does TimeStamp come from? I am adding `wsse=UsernameToken(...)` but the TimeStamp doesn't get added to the output.

**Comment by ovnicraft** [comment]
A good enhancement its implement this token, i am working in this, will give a try to Header metioned before and look how implement Timestamp.

**Comment by sacingle** [comment]
@mvantellingen  @ovnicraft 
I am still facing this issue, i am unable to add timestamp to my security header and the link shared above seems to be broken 

following is my code, it needs timestamp to be added
`from datetime import datetime 
from datetime import timedelta   
from zeep import Client
from zeep.wsse import UsernameToken
from lxml import etree
from zeep.wsa import WsAddressingPlugin
from zeep.wsse import utils

url="https://ess/esswebservice?WSDL"
client = Client(url,wsse=UsernameToken('user', 'Welcome.1'),plugins=[WsAddressingPlugin()])

result = client.service.submitInstantRecurringRequest(description='TestESS1',jobDefinitionId = {
    'name': 'BulkImportJob',
    'packageName': '/oracle/apps/ess/cdm/foundation/bulkImport/',
	'type': 'JOB_DEFINITION'
} ,iCalSchedule='FREQ=DAILY;INTERVAL=2;',application='CrmEss',requestedStartTime=datetime.now(),requestedEndTime=datetime.now()+timedelta(days=1), requestParameters={} )
print (result) ## shows the details of this service

`
