### ISSUE TITLE
WSSE x.509 support (BinarySecurityToken)

### ISSUE THREAD

**Issue by Volo7** [mvantellingen/python-zeep#120]
Hello,

When WSSE x.509 support (BinarySecurityToken) will be released?

**Comment by mvantellingen** [comment]
I wanted the core to be stable first. But the idea is to integrate https://github.com/mvantellingen/py-soap-wsse or github.com/orcasgit/py-wsse/

**Comment by blaggacao** [comment]
I'm new to SOAP, can you suggest any dirty hack, if I need this right now, but want to use your library?

**Comment by 452** [comment]
please add support directly .pem auth files
```
import httplib
CERT_FILE = '/home/striker/tmp/good.pem'
conn = httplib.HTTPSConnection('10.10.10.15','443', cert_file =CERT_FILE)
```

**Comment by kmiloaguilar** [comment]
Hello, any news on this one?

**Comment by mvantellingen** [comment]
Should now be available on the master branch, see http://docs.python-zeep.org/en/master/wsse.html#signature-x509 for the documentation.

Note that I wasn't able to test it against a server, but I think it should work so feedback appreciated

**Comment by stephendwolff** [comment]
Looks useful. I'll try it out.

Another approach might be to do something similar to https://gist.github.com/erikbern/756b1d8df2d1487497d29b90e81f8068 - for use with pfx files (which is the use case that brought me here!)

**Comment by mvantellingen** [comment]
Yeah but that isn't xml signing right? That just pins the ssl connection to a specific certificate

**Comment by stephendwolff** [comment]
yes, you're quite right. i realised after looking at the code

**Comment by mvantellingen** [comment]
I'm closing this ticket for now as it should be fixed. If there are still any issues then please let me know so that I can re-open the issue.

**Comment by rouge8** [comment]
@mvantellingen this looks like it's just signing, not encryption right?
