### ISSUE TITLE
serializing objects with several levels does not work

### ISSUE THREAD

**Issue by YAmikep** [mvantellingen/python-zeep#123]
Hello

Since I upgraded to 0.12, I am having issues serializing the zeep objects into python types.
It seems like it's not working when there are several levels: the deeper levels are not serialized.

Do the dynamic zeep objects inherit from a common class like `zeep.objects.Object`?
That would allow to use `isinstance(obj, zeep.objects.Object)` when going through the data and transform the zeep objects recursively?

Thanks

**Comment by mvantellingen** [comment]
Not entirely sure what you mean. Is the XML send to the server invalid or are is the helpers.serialize_object() broken?

**Comment by YAmikep** [comment]
I think `helpers.serialize_object()` is broken as it does not serialize all the inner objects.

For example:

```
# The object returned by zeep
result = {
    'AAA': [
        {
            'ID': 111,
            'BBB': {
                'CCC': [
                    {
                        'FromDate': datetime.datetime(2016, 7, 3, 0, 0),
                        'ToDate': datetime.datetime(2016, 7, 12, 0, 0),
                        'Desc': 'bla',
                    },
                    {
                        'FromDate': datetime.datetime(2016, 7, 13, 0, 0),
                        'ToDate': datetime.datetime(2016, 7, 20, 0, 0),
                        'Desc': 'hello',
                    },
					...
                ]
            }
        },
		...
	]
}

type(result)
zeep.objects.ArrayOfAAA

result2 = zeep.helpers.serialize_object(result)

type(result2)
collections.OrderedDict

# After serializing the object, the inner objects are still zeep objects
type(result2['AAA'][0])
Out[15]: zeep.objects.AAA

type(result2['AAA'][0]['BBB'])
zeep.objects.ArrayOfCCC

type(result2['AAA'][0]['BBB']['CCC'][0])
zeep.objects.CCC

```

As a workaround, if all the dynamic classes would inherit from a common `zeep.objects.Object` class, it would be easier for me to go through the data and convert them manually.

Thanks

**Comment by mvantellingen** [comment]
Ok thanks, will fix it asap. All objects actually do extend from zeep.xsd.valueobjects.CompoundValue

**Comment by mvantellingen** [comment]
Should be fixed in master, if not then let me know

**Comment by YAmikep** [comment]
Hum I don't think it completely fixes the issue.
My object is:
```
> type(o)
zeep.objects.ArrayOfCompanies
> o
{
    'Companies': [
        {
            'ID': 111,
            'Name': None
        },
        {
            'ID': 222,
            'Name': None
        },
        {
            'ID': 333,
            'Name': 'Inc.'
        }
    ]
}
```

After I use the `serialize_object` helper, nested objects are still zeep objects:
```> type(o['Companies'][0])
zeep.objects.ManagementCompanies```

I am doing this in the meanwhile:
```
def convert_zeep_object(obj):
    if isinstance(obj, zeep.xsd.valueobjects.CompoundValue):
        obj = zeep.helpers.serialize_object(obj)

    if isinstance(obj, list):
        return [convert_zeep_object(sub) for sub in obj]

    if isinstance(obj, dict):
        return {k: convert_zeep_object(v) for k, v in obj.items()}

    return obj
```

**Comment by mvantellingen** [comment]
Should really be fixed now 👍

**Comment by YAmikep** [comment]
I found an example where this does not work:

WSDL
```
<s:element name="GetResponse">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="0" maxOccurs="1"
                       name="GetResponseResult"
                       type="tns:ArrayOfInt"/>
        </s:sequence>
    </s:complexType>
</s:element>
<s:complexType name="ArrayOfInt">
    <s:sequence>
        <s:element minOccurs="0" maxOccurs="unbounded" name="int" type="s:int"/>
    </s:sequence>
</s:complexType>
```

Which returns:
```
In [31]: result
Out[31]: [218342, 217234, 218341]

In [32]: type(result)
Out[32]: list

In [33]: type(result[0])
Out[33]: int
```

So this error is raised when calling the `serialize_object` function
```In [35]: zeep.helpers.serialize_object(result)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-bde830acf76d> in <module>()

/var/beyond/venv/lib/python3.5/site-packages/zeep/helpers.py in serialize_object(obj)
     18
     19     result = OrderedDict()
---> 20     for key in obj:
     21         value = obj[key]
     22         if isinstance(value, (list, CompoundValue)):

TypeError: 'int' object is not iterable```
```

The user could check the type of the output but it might be better to handle this directly in the function so that the user could do directly:
```
result = client.service.method(...)
result = serialize_object(result)
```

I created a pull request to fix this and I added at the same time a parameter to allow the user to pass the dict type if he wants something different than OrderedDict.

Thanks

**Comment by extym** [comment]
And after 7 years... We have it's error
