### ISSUE TITLE
Is it possible to use a local wsdl file and then specify a custom remote url?

### ISSUE THREAD

**Issue by MastaG** [mvantellingen/python-zeep#1233]
I was going through the documentation but couldn't find a straight answer.
The developers basically send us the wsdl and xsd files.
I can open them using:
envClient = Client("file:///myfile.wsdl", transport = envtransport, settings = settings) 
But how do I specify the remote url to interface with?

**Comment by MastaG** [comment]
I figured it out :)

**Comment by jcassee** [comment]
Can you post your solution? I am looking for the same thing and this is the first search hit. :slightly_smiling_face:

**Comment by trombone761229** [comment]
I am looking for the same question , Please help
