### ISSUE TITLE
Zeep fails when detail is missing in Fault

### ISSUE THREAD

**Issue by moonhouse** [mvantellingen/python-zeep#124]
When doing a search using a web service which yields no result it returns HTTP error 501[sic!] and a SOAP message with a fault. 

`<?xml version="1.0" encoding="UTF-8"?>
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
<S:Body>
<S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
<faultcode>S:Server</faultcode>
<faultstring>Sökningen gav inga träffar                                            </faultstring>
</S:Fault>
</S:Body>
</S:Envelope>`

When I happen upon this "error" when calling the web service using zeep my program aborts with a traceback.

(I guess it can be discussed that this error actually relates to the body and not the header and therefore should have a `detail` element as stated by section 4.4 in the SOAP spec.) But I suspect the same error would occur if the fault was related to information in the header which wouldn't require `detail`. Also the XML Schema at http://schemas.xmlsoap.org/soap/envelope/ has `minOccurs` set to zero for this element.

The traceback from zeep ends with:
>   File "/usr/local/lib/python2.7/site-packages/zeep/client.py", line 24, in \__call\__
    self._op_name, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 94, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 123, in process_reply
    return self.process_error(doc)
  File "/usr/local/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 202, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault

Trying to access the non-existing element `detail` in https://github.com/mvantellingen/python-zeep/blob/29af5cac8b468b56c01f929ace0b5f0bc350a26d/src/zeep/wsdl/soap.py#L202 is where it fails I guess.

Would it be possible to add some error handling when detail isn't present?

**Comment by mvantellingen** [comment]
I might be overlooking something, but isn't the library correctly raising the ``zeep.exceptions.Fault ``exception? This is intended. The detail will be ``None`` here since it doesn't exist.

**Comment by moonhouse** [comment]
OK. I'm probably not accustomed to how acceptable an exception is in the Python world. I realized now that I could check the _message_ attribute of the exception and combine with try…accept to identify the specific "error". 

Thanks for your good work!
