### ISSUE TITLE
BinarySignature problem with zeep 4.0.0

### ISSUE THREAD

**Issue by kajala** [mvantellingen/python-zeep#1242]
This minimal BinarySignature usage example fails for me on Ubuntu 20.04 LTS (Python 3.8.10):

```
from lxml import etree
from zeep.wsse import BinarySignature

body_bytes = open('./body.xml', 'rb').read()
envelope = etree.fromstring(body_bytes)
binary_signature = BinarySignature('./key.pem', './cert.pem')
envelope, soap_headers = binary_signature.apply(envelope, {})
signed_body_bytes = etree.tostring(envelope)
```
The code and files are available at https://github.com/kajala/zeep-test to replicate the problem.

The output is:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    envelope, soap_headers = binary_signature.apply(envelope, {})
  File "/zeep-test/venv/lib/python3.8/site-packages/zeep/wsse/signature.py", line 104, in apply
    _sign_envelope_with_key_binary(
  File "/zeep-test/venv/lib/python3.8/site-packages/zeep/wsse/signature.py", line 287, in _sign_envelope_with_key_binary
    bintok.text = x509_data.find(QName(ns.DS, "X509Certificate")).text
AttributeError: 'NoneType' object has no attribute 'text'
```

So it X509Certificate is clearly not found from x509_data, but if I dump the data before that "x509_data.find(...)" it seems that X509Certificate is there, and with correct namespace. Any ideas?

**Comment by kajala** [comment]
Update: I tried my example on another Ubuntu 20.04 LTS computer, same Python 3.8.10, and it works fine. So this seems to be related to some lower level binary used by zeep. My first suspect was libxmlsec1-dev but both are running the same version (1.2.28-2). Any ideas what's going on, what other dependencies I should check?

**Comment by kajala** [comment]
Found one difference between non-working and working:

working:
libxml2=2.9.10

non-working:
libxml2=2.9.12

After sudo apt install libxml2=2.9.10, the test started working.

**Comment by goahe** [comment]
@kajala same issue here, but on focal with libxml2 2.9.10+dfsg-5ubuntu0.20.04.1, though. No idea what's going on. Did you get any wiser on the subject? I'm even using the same binary as you, so I have no idea how this could be going wrong.

Debugging `wsse/signature.py` gives
```xml
<ns0:X509Data xmlns:ns0="http://www.w3.org/2000/09/xmldsig#">
<ns0:X509IssuerSerial>
<ns0:X509IssuerName>{some issuer}</ns0:X509IssuerName>
<ns0:X509SerialNumber>{some serialnumber}</ns0:X509SerialNumber>
</ns0:X509IssuerSerial>
<ns0:X509Certificate>sdfksdl......sdfsdkfjsdkf</ns0:X509Certificate>
</ns0:X509Data>
```
on version `4.0.0` on `x509_data` on line `287`:
```python
bintok.text = x509_data.find(QName(ns.DS, "X509Certificate")).text
```
`ns.DS`, in my case, correctly gives:
`http://www.w3.org/2000/09/xmldsig#`, which is `ns0` from the XML above.

So the find is for:
`{http://www.w3.org/2000/09/xmldsig#}X509Certificate` on x509_data, which oddly crashes into:

```
bintok.text = x509_data.find(QName(ns.DS, "X509Certificate")).text
AttributeError: 'NoneType' object has no attribute 'text'
```

Am I missing something? When I parse the same XML in a separate python script and try to find the same element, I simply get the expected result:
```
sdfksdl......sdfsdkfjsdkf
```

**Comment by 0x42h** [comment]
@kajala same issue here, but on focal with libxml2 2.9.10+dfsg-5ubuntu0.20.04.1, though. No idea what's going on. Did you get any wiser on the subject? I'm even using the same binary as you, so I have no idea how this could be going wrong.

Debugging `wsse/signature.py` gives
```xml
<ns0:X509Data xmlns:ns0="http://www.w3.org/2000/09/xmldsig#">
<ns0:X509IssuerSerial>
<ns0:X509IssuerName>{some issuer}</ns0:X509IssuerName>
<ns0:X509SerialNumber>{some serialnumber}</ns0:X509SerialNumber>
</ns0:X509IssuerSerial>
<ns0:X509Certificate>sdfksdl......sdfsdkfjsdkf</ns0:X509Certificate>
</ns0:X509Data>
```
on version `4.0.0` on `x509_data` on line `287`:
```python
bintok.text = x509_data.find(QName(ns.DS, "X509Certificate")).text
```
`ns.DS`, in my case, correctly gives:
`http://www.w3.org/2000/09/xmldsig#`, which is `ns0` from the XML above.

So the find is for:
`{http://www.w3.org/2000/09/xmldsig#}X509Certificate` on x509_data, which oddly crashes into:

```
bintok.text = x509_data.find(QName(ns.DS, "X509Certificate")).text
AttributeError: 'NoneType' object has no attribute 'text'
```

Am I missing something? When I parse the same XML in a separate python script and try to find the same element, I simply get the expected result:
```
sdfksdl......sdfsdkfjsdkf
```

**Comment by 0x42h** [comment]
Obviously this is not the right place to post this, I suppose, as it has nothing to do with `zeep`, other than that it's affected by this bug, but apparently `ns0` is indexed as key `None` in `nsmap`, which _most_ probably is the reason why this is going wrong.

I'm guessing that means `xmlsec` Python's module is the root cause of this, right or is it really something underlying all this?

![image](https://user-images.githubusercontent.com/24974331/151071432-223779ef-ddaf-48b6-9161-514fbcf0e81e.png)

**Comment by 0xVK** [comment]
@0x42h Hi. Did you find any solution here?

**Comment by 0x42h** [comment]
@0xVK Half a year later (forgive me, please); I had to hack the `xmlsec` (python) library to parse out the field with a query. As far as I can see, it seems to be a bug in `xmlsec` or, probably more like (since otherwise there would be more problems), zeep is using it wrong. I remember it being an empty key that, for that reason, is not found when looking up the namespace, if I don't remember incorrectly. Hope that helps.
