### ISSUE TITLE
Retrieving password protected WSDL raises error

### ISSUE THREAD

**Issue by tooh** [mvantellingen/python-zeep#128]
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

```
client = Client('<url>?wsdl',wsse=UsernameToken('username','password'))
```
When I use the same url in a browser and provide the same user and password I can retrieve the WSDL.

When I use zeep:
```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:
```

**Comment by mvantellingen** [comment]
Perhaps you require basic auth? Try http://<username>:<password>@url/ for the wsdl. You can also pass http_auth to the transport class. See http://docs.python-zeep.org/en/latest/transport.html#transport-options

**Comment by mvantellingen** [comment]
btw; if i'm totally wrong and it isn't working then please let me know (also counts for your other issue)

**Comment by tooh** [comment]
Added http_auth to Transport options: 
```
NameError: name 'http_auth' is not defined
```
Perhaps I have the syntax wrong.

BTW : this option is missing in the docs
 http://docs.python-zeep.org/en/latest/transport.html#transport-options

Tried providing the basic authentication with user:password@url syntax and this took me further.

I get response from the WSDL URL but then it tries to retrieve some schema info and that gives a 401 again

```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: service.asmx?schema=ServiceAgreementFullDataSet
```

**Comment by mvantellingen** [comment]
Can you place the code you are trying to run here? Placing the complete traceback is also better since I can't determine if this is a library error or a user error.

The docs are indeed missing the http_auth it seems. I'll add that.

**Comment by mvantellingen** [comment]
See also https://github.com/mvantellingen/python-zeep/blob/master/examples/http_basic_auth.py btw

**Comment by tooh** [comment]
this helped
