### ISSUE TITLE
python -m zeep does not use basic authentication

### ISSUE THREAD

**Issue by tooh** [mvantellingen/python-zeep#130]
Enhancement request.

python -m zeep <wsdlurl) does not have an option for providing basic_auth.

I have a use case where the wsdl is behind authentication. After receiving the tip to pass http_auth to Transport I can reach the WSDL. But I want to inspect the wsdl and python - m zeep does not provide the option to pass authentication.

**Comment by janos97** [comment]
Workaround:
Download the WSDL to your local PC along with any XSD's that require authentication. 
Run against the local file, works perfectly.

**Comment by mvantellingen** [comment]
This should be supported. The credentials used to fetch the main wsdl should be re-used for subsequent fetches

**Comment by mvantellingen** [comment]
Should be fixed in master :)

**Comment by tooh** [comment]
Thx

**Comment by gatmac** [comment]
Thanks for all your efforts. Any suggestions on using basic authentication? Would I create a custom SOAP header?

**Comment by mvantellingen** [comment]
hi @gatmac, basic auth information is extract from the default url scheme: https://<username>:<password>@<hostname>/<path>
