### ISSUE TITLE
How to handle Web Services Addressing (WS-Addressing)

### ISSUE THREAD

**Issue by jmrbcu** [mvantellingen/python-zeep#134]
Hi, after  searching around the internet for a nice python library for SOAP, I landed in zeep. We are using it now for some integrations with third party web services but, we have one use case that is using Web Services Addressing (WS-Addressing). I know that zeep does not support this out of the box but, how is it possible to address this case with it, like adding the proper namespace and headers?

**Comment by mvantellingen** [comment]
You can for now create a custom soap header. See https://github.com/mvantellingen/python-zeep/blob/523df386c9155d6571d16cc966e8f5f66a256c63/tests/test_wsdl_messages_document.py#L374 for a rough example

**Comment by jmrbcu** [comment]
Can you provide an example of how to generate this SOAP message, I've been trying to do it with zeep but I can't:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <s:Header>
       <a:Action s:mustUnderstand="1">http://ADPNetworkSolutions/CARPort/GetCallsByTime</a:Action>
       <a:MessageID>urn:uuid:{messageid}</a:MessageID>
       <a:ReplyTo>
           <a:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>
       </a:ReplyTo>
       <a:To s:mustUnderstand="1">https://www.mynetworkphone.com/carport/carport.asmx</a:To>
       <o:Security xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" s:mustUnderstand="1">
           <o:UsernameToken u:Id="uuid-{tokenid}-1">
               <o:Username>{username}</o:Username>
               <o:Password>{password}</o:Password>
           </o:UsernameToken>
       </o:Security>
   </s:Header>
   <s:Body xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
       <GetCallsByTime xmlns="http://ADPNetworkSolutions/CARPort">
           <request>
               <StartTime>{timestamp}</StartTime>
           </request>
       </GetCallsByTime>
   </s:Body>
</s:Envelope>
```

**Comment by mvantellingen** [comment]
The security header can be added via http://docs.python-zeep.org/en/latest/wsse.html#usernametoken. The other header via the example in the earlier linked data. I'll can try to create an example for you sometime later.

**Comment by jmrbcu** [comment]
This is what I did and it seems to be working, is there a better what of adding the headers?

``` python
import uuid
import datetime
import zeep
from zeep.wsse.username import UsernameToken
from lxml.builder import ElementMaker


def get_wsa_headers():
    WSA_NS = 'http://schemas.xmlsoap.org/ws/2004/08/addressing'
    return [
        ElementMaker(namespace=WSA_NS).Action('http://ADPNetworkSolutions/CARPort/GetCallsByTime'),
        ElementMaker(namespace=WSA_NS).MessageID('urn:uuid:' + str(uuid.uuid4())),
        ElementMaker(namespace=WSA_NS).To('https://www.mynetworkphone.com/carport/carport.asmx')
    ]


def main():
    now = datetime.datetime.now()
    start = now - datetime.timedelta(minutes=10)
    wsdl = 'https://www.mynetworkphone.com/carport/carport.asmx?WSDL'
    client = zeep.Client(wsdl=wsdl, wsse=UsernameToken('Paramus_SMDR', 'P@ramus1'))

    start = client.get_type('ns0:GetCallsByTimeRequest')(StartTime=start)
    result = client.service.GetCallsByTime(start, _soapheaders=get_wsa_headers())

    for call in result.CallDetailItems.CallLogItem:
        print call


if __name__ == '__main__':
    main()
```

**Comment by mvantellingen** [comment]
Seems like a good way for now! you might want to create the elementmaker once but that is just minor. Hoping to add wsa support when I have some time.

**Comment by hmngwy** [comment]
@mvantellingen 

I'm confused, the [test](https://github.com/mvantellingen/python-zeep/blob/523df386c9155d6571d16cc966e8f5f66a256c63/tests/test_wsdl_messages_document.py#L374) says to use `xsd.Element(None, ...)`, but [here](https://github.com/mvantellingen/python-zeep/blob/359ed4b5789f4f64d4ff262ab62360d34434d91c/src/zeep/xsd/elements/element.py#L24) it it checks if that argument is `None` then raises an error.

**Comment by hmngwy** [comment]
Ok so apparently that method in the test is no longer supported.

How does one replicate that - `xsd.Element(None)` - in the current API?
