### ISSUE TITLE
Invalid JAXP API or implementation

### ISSUE THREAD

**Issue by ori-o** [mvantellingen/python-zeep#135]
Hello,
I'm trying to use Zeep in order to access the following WS:
http://ws-api.adtech.de/WSWebsiteAdmin_v15?wsdl

And I receive the following error when attempting to run a function along the lines of client.service.getPlacementList(1,1,True,[]):
Fault: You are running with invalid JAXP api or implementation. JAXP api/implementation of version 1.3.1 (included in JDK6) or higher is required. In case you are using ant, make sure ant 1.7.0 or higher is used - older versions of ant contain JAXP api/impl version 1.2 (in xml-apis.jar). If you want to keep using older ant versions, you have to configure it to use higher the JAXP api/impl versions.

Is there any way I could configure the library in order to comply with the server's request?

**Comment by mvantellingen** [comment]
I have no idea. Does this work when you use soap-ui? It seems more like the server is tripping over something else

**Comment by mvantellingen** [comment]
Closing due to lack of info.
