### ISSUE TITLE
cgi module removal

### ISSUE THREAD

**Issue by decaz** [mvantellingen/python-zeep#1352]
`DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13`

cgi is used here:
https://github.com/mvantellingen/python-zeep/blob/4e5ebad9eb355281cf3ae73cf83f666dc4b8bb00/src/zeep/utils.py#L91-L94

As a replacement of `parse_header` function [PEP 594](https://peps.python.org/pep-0594/#cgi) suggests to use `email.message.Message`.

**Comment by arveitch** [comment]
Could I request a release please as Python 3.13 is getting quite close. Thanks so much for an excellent product!
