### ISSUE TITLE
little curiosity

### ISSUE THREAD

**Issue by arthoryuss** [mvantellingen/python-zeep#1354]
I was using ChatGPT to check a possibility using the Zeep library... And then I received the following responses:

![Screenshot from 2023-01-02 10-41-29](https://user-images.githubusercontent.com/32274515/210239736-a294c9a0-13c9-4674-8a9a-2d1985332308.png)
![Screenshot from 2023-01-02 10-53-57](https://user-images.githubusercontent.com/32274515/210240625-39e42869-684b-4d15-874b-b12585d24143.png)
![Screenshot from 2023-01-02 10-45-17](https://user-images.githubusercontent.com/32274515/210239749-8d061424-de7c-4458-baf1-c34df9cf9b1a.png)
![Screenshot from 2023-01-02 10-46-15](https://user-images.githubusercontent.com/32274515/210239751-5517479b-31c3-4c13-9fc4-72226ccff14c.png)

I couldn't find anything about the real existence of this method... Did it really exist or does it exist?

**Comment by ba1dr** [comment]
Of course you may use ChatGPT to write programs. Just note that these programs not guaranteed to work.
Bot does not care about correctness of the answers, this is why this is just a joke. Do not trust a single line created by the bot - when it does not know the answer it just makes it up.
Of course this method does not exist.

**Comment by Peter-developer01** [comment]
> Of course you may use ChatGPT to write programs. Just note that these programs not guaranteed to work. Bot does not care about correctness of the answers, this is why this is just a joke. Do not trust a single line created by the bot - when it does not know the answer it just makes it up. Of course this method does not exist.

is it written by chatgpt? hahaha)
