### ISSUE TITLE
Unrecognised ISO 8601 time format: '  :  :  '

### ISSUE THREAD

**Issue by js1972** [mvantellingen/python-zeep#137]
My web service responds with empty values in time fields:

```
Unrecognised ISO 8601 time format: '  :  :  '
```

This causes exceptions in zeep.

Wondering if there's any way around this?

**Comment by mvantellingen** [comment]
I'll need to check the RFC if this is valid. We should probably log a warning and return None instead of raising an exception however. I'll need to look at this later this week. (or you can submit a pr)

**Comment by js1972** [comment]
Ok. Now remembering that I'm not a python coder (yet)  ;-)  It seems that in file zeep/xsd/builtins.py we can change the following in the Time class to trap the exception and return None...
According to Python3 " : : " is not an allowed value for a time (haven't checked the RFC whether it should or not).
Now this may not be the best place to handle this architecturally, but I can submit a pull request for it. I just gotta work out how to get it installed on my local system.

Looks like I can make the change locally then do `pip install -e .` to install it as a quick hack.   ;-)
```
def pythonvalue(self, value):
        return isodate.parse_time(value)
```

**Comment by mvantellingen** [comment]
Finally fixed this! Thanks again for the report!
