### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by arunbansal-cpi** [mvantellingen/python-zeep#1373]
tests/test_flex_mes_soap.py:223: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
factorystand/lib/mes/flex/soap/soap.py:193: in save_result
    return self._service.SaveResult(ffTesterXmlRequest=fftester_xml_request_data,
../../.cache/pypoetry/virtualenvs/factorystand-2HaIuAjt-py3.8/lib/python3.8/site-packages/zeep/proxy.py:40: in __call__
    return self._proxy._binding.send(
../../.cache/pypoetry/virtualenvs/factorystand-2HaIuAjt-py3.8/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py:130: in send
    return self.process_reply(client, operation_obj, response)
../../.cache/pypoetry/virtualenvs/factorystand-2HaIuAjt-py3.8/lib/python3.8/site-packages/zeep/wsdl/bindings/soap.py:195: in process_reply
    return self.process_error(doc, operation)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def process_error(self, doc, operation):
        fault_node = doc.find("soap-env:Body/soap-env:Fault", namespaces=self.nsmap)
    
        if fault_node is None:
>           raise Fault(
                message="Unknown fault occured",
                code=None,
                actor=None,
                detail=etree_to_string(doc),
            )
E           zeep.exceptions.Fault: Unknown fault occured

-------------------------------------
This error is occurring when mocking soap wsdl request via zeep client in unittest

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
