### ISSUE TITLE
Invalid login attempt error while using Netsuite Suitetalk SOAP API.

### ISSUE THREAD

**Issue by kompal20** [mvantellingen/python-zeep#1374]
I am trying to fetch the records from Netsuite using Python. I am able to run the same script on Postman but when I try to run the same script on python it throws an error - "Invalid Login Attempt.

The code is as follows -
import os
import requests
import hashlib
import hmac
import time
import random

# Environment variables
account = "account"
consumer_key = "consumer_key"
consumer_secret = "consumer_secret"
token_id = "token_id"
token_secret = "token_secret"

# Calculate signature
nonce = str(random.getrandbits(64))
timestamp = str(int(time.time()))
base_string = f"{account}&{consumer_key}&{token_id}&{nonce}&{timestamp}"
key = f"{consumer_secret}&{token_secret}"
signature = hmac.new(key.encode(), base_string.encode(), hashlib.sha256).digest().hex()

headers = {
    "Content-Type": "text/xml",
    "SOAPAction": "get",
    "recordType": "job"
}

body = f"""
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Header>
    <tokenPassport>
      <account>{account}</account>
      <consumerKey>{consumer_key}</consumerKey>
      <token>{token_id}</token>
      <nonce>{nonce}</nonce>
      <timestamp>{timestamp}</timestamp>
      <signature algorithm="HMAC-SHA256">{signature}</signature>
    </tokenPassport>
    <preferences>
      <runServerSuiteScriptAndTriggerWorkflows>false</runServerSuiteScriptAndTriggerWorkflows>
    </preferences>
    <searchPreferences>
      <pageSize>1000</pageSize>
      <bodyFieldsOnly>false</bodyFieldsOnly>
    </searchPreferences>
  </soap-env:Header>
  <soap-env:Body>
    <get xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:platformCore="urn:core_2017_1.platform.webservices.netsuite.com">
      <baseRef internalId="4364" type="job" xsi:type="platformCore:RecordRef">
        <platformCore:name/>
      </baseRef>
    </get>
  </soap-env:Body>
</soap-env:Envelope>
"""

# Make the request
url = "https://{account}.suitetalk.api.netsuite.com/services/NetSuitePort_2017_1"
response = requests.post(url, headers=headers, data=body)

# Handle the response
if response.status_code == 200:
    # Request was successful
    print(response.text)
else:
    # Request failed
    print(f"Error: {response.status_code} - {response.text}")

Error- 500 is being thrown and while using GET request we are able to establish the connection using same credentials.

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
