### ISSUE TITLE
Performance speedup

### ISSUE THREAD

**Issue by NKMatha** [mvantellingen/python-zeep#1375]
Hi team,

I was trying to make soap call to fusion cloud, when i was trying to establish client its getting time out so i have saved the wsdl in local and trying to make sopa calls but the client.server.xxxxx() is taking too long for just small task.

from zeep import Client
from zeep.transports import Transport
import logging
logging.basicConfig(level=logging.DEBUG)

url = r"C:\Users\user\Downloads\SecurityService.xml"
client = Client(url)

req = client.service.login(userID='user',password='passwd')     #taking long time

**Comment by aaronleggett96** [comment]
Hey NKMatha, 

I'm experiencing the same for Oracle Fusion. I had a script that ran perfectly, but now does not run. I swapped it out for suds and the auth worked near instantly to return the session key. Did you find a fix yourself? I'm going to run some more tests by returning the session key with suds and parsing in the SK into zeep.

**Comment by NKMatha** [comment]
Hi @aaronleggett96,
Even i have shifted to suds, thats look better for me.

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
