### ISSUE TITLE
Adding Attribute 

### ISSUE THREAD

**Issue by YairThuAung** [mvantellingen/python-zeep#1377]
How to Add attribute for Item Using Zeep

The following is an xml code for my SOAP request:

```
<Item actionCode="01">
    <TypeCode>002</TypeCode>
    <Quantity unitCode="EA">1.0</Quantity>
</Item>
```

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
