### ISSUE TITLE
The nginx/openresty SOAP to REST library based on zeep.

### ISSUE THREAD

**Issue by kingluo** [mvantellingen/python-zeep#1382]
Hi, All. I'm glad to share my openresty library based on zeep. Any suggestion is welcome, thank you all.

https://github.com/kingluo/lua-resty-ffi-soap

![soap](https://github.com/mvantellingen/python-zeep/assets/4401042/54449a7e-ef4a-4f97-b60f-19555b1a9ba4)

![soap_callflow](https://github.com/mvantellingen/python-zeep/assets/4401042/9f6c5c76-4961-4a7b-b3cf-12bfa0d17243)

**Comment by mvantellingen** [comment]
Nice work :-)
