### ISSUE TITLE
How to pass complexType parameters

### ISSUE THREAD

**Issue by tooh** [mvantellingen/python-zeep#139]
I have a problem to pass the findCriteria

Below a result from SoapUI that is working.
I do not master python enough to figure out how achieve the Critera element

```
<sup:Criteria>
        <sup:ColumnName>Closed</sup:ColumnName>
        <sup:Value>0</sup:Value>
    </sup:Criteria>

```

```  
 <soapenv:Header/>
   <soapenv:Body>
      <sup:GetCount>
         <!--Optional:-->
         <sup:findCriteria>
            <!--You may enter ANY elements at this point-->
            <sup:Criteria>
        <sup:ColumnName>Closed</sup:ColumnName>
        <sup:Value>0</sup:Value>
    </sup:Criteria>
         </sup:findCriteria>
      </sup:GetCount>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by mvantellingen** [comment]
You really need to post more information. Did you check the suggest call via the python -mzeep route? And http://docs.python-zeep.org/en/latest/in-depth.html#any-objects?

**Comment by tooh** [comment]
Yes I tried this but I could not make this work due to insufficient python knowledge.

**Comment by mvantellingen** [comment]
Sorry, but I can't do anything with the information provided. Closing for now
