### ISSUE TITLE
Zeep POST request returns 500 error, same XML works on Postman/SOAP UI

### ISSUE THREAD

**Issue by adasCFI** [mvantellingen/python-zeep#1418]
Hi I am attempting to use the following WSDL ([https://pilot.id3global.com/ID3gWS/ID3global.svc?wsdl](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpilot.id3global.com%2FID3gWS%2FID3global.svc%3Fwsdl&data=05%7C02%7Cy.serhal%40cfifinancial.com%7Cbf7211f786a74bba2d6208dc5de4346f%7C093337e7d567434b819257e61a060473%7C0%7C0%7C638488482435687786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WtDOaVbiYFvIrAz0EKMGFXpoP3nnml48xHNDiX%2Bo4Lc%3D&reserved=0))

I am attempting to use the Service - AuthenticateSP. But, with zeep the response I get back is 500 error
```
"2024-05-20T07:01:13.016383Z", "message": "Username unknown or incorrect password"
```

It is quite weird as I have tried the XML collected from the history plugin through SOAP UI/Postman and I get back a 200 Ok response with the correct response XML.

The code:
```
    soap_client = Client(
        wsdl=wsdl,
        wsse=wsse,
        plugins=[history],
    )
    soap_client.set_ns_prefix("ns", "http://www.id3global.com/ID3gWS/2013/04")
    service = soap_client.bind(
        service_name="ID3global",
        port_name="basicHttpBinding_GlobalAuthenticate",
    )
```

**Comment by mvantellingen** [comment]
This seems to be an issue within the WSDL specifications you are using. There are unfortunately a lot of broken/invalid WSDL's available in the world and it's really impossible to help debugging ant of these issues.

If you believe the WSDL is valid but this is really an issue in Zeep then please submit an easy to reproduce bug report
