### ISSUE TITLE
Error: Definition not found, but WSDL is working

### ISSUE THREAD

**Issue by erenirmak** [mvantellingen/python-zeep#1424]
WSDL URL: https://api.ibb.gov.tr/iett/UlasimAnaVeri/HatDurakGuzergah.asmx?wsdl

Generate error:
```python
from zeep import Client

wsdl_url = "https://api.ibb.gov.tr/iett/UlasimAnaVeri/HatDurakGuzergah.asmx?wsdl"
client = Client(wsdl=wsdl_url)
```
I suspect this is some kind of bug with open-source WSDL.
I tried modifying WSDL via deleting headers and Client was able to process modified WSDL, but it couldn't use functions.

**Comment by mvantellingen** [comment]
Yeah this seems to be an issue with the wsdl
