### ISSUE TITLE
Not getting headers from SOAP response

### ISSUE THREAD

**Issue by damianstaro** [mvantellingen/python-zeep#143]
Are headers in SOAP response currently supported?

This is a part of the type of responses I am trying to process:

```

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">

   <s:Header>

      <h:Metadata s:mustUnderstand="1" xmlns:h="http://miteksystems.com" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">

         <SessionReferenceId xmlns="http://miteksystems.com/">***************</SessionReferenceId>

         <TransactionReferenceId xmlns="http://miteksystems.com/">*****************</TransactionReferenceId>

         <XIPVersion xmlns="http://miteksystems.com/">XIP 2.0</XIPVersion>

      </h:Metadata>

      <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">

         <u:Timestamp u:Id="_0">

            <u:Created>2016-04-29T11:30:42.917Z</u:Created>

            <u:Expires>2016-04-29T11:35:42.917Z</u:Expires>

         </u:Timestamp>

      </o:Security>

   </s:Header>

   <s:Body>
****************
   </s:Body>
</s:Envelope>
```

**Comment by mvantellingen** [comment]
No it isn't at the moment. Haven't encountered it myself yet which is the only reason it isn't implemented :-)

If you have a wsdl and example response I can look at it next week

**Comment by damianstaro** [comment]
Hi,

Looks like I am going to need this for my project. Will this happen soon? 

If not, a possible mitigation is if I had direct access to the response XML. Would that be something the API would currently allow?

Thanks!

**Comment by mvantellingen** [comment]
@damianstaro do you have an example wsdl? A reference wsdl can considerably speed up my development time for new features, and since time is always an issue :-)

0.15 offers support for Plugins which should make this relatively easy to implement yourself

**Comment by damianstaro** [comment]
Hi, I sent a sample WSDL along with a sample message to your email address. Let me know if I can do anything else to help.

I am not sure how to do a plugin, but I will look into it. For now I've overcome the issue with a custom transport that XML-scraps the field I need.

Thanks!

**Comment by MattFaus** [comment]
+1 exposing the response headers would be useful for my application. The service I'm interacting with returns an authentication token in the headers. I've worked around with a simple plugin.

**Comment by mvantellingen** [comment]
See #180 (closing this one in favour of that one). Thanks for the reports
