### ISSUE TITLE
Please make a release of the current state (to support Python 3.13)

### ISSUE THREAD

**Issue by mbehrle** [mvantellingen/python-zeep#1430]
The last release was 4.2.1 in Nov 20, 2022. 

Distributions are heading towards Python 3.13 and requests like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1084695 are queuing up, that are already solved with https://github.com/mvantellingen/python-zeep/issues/1352.

Could you please make a release to support Python 3.13?

Thank you!

**Comment by decaz** [comment]
@mvantellingen FYI

**Comment by mvantellingen** [comment]
Just release 4.3.0 :-)

**Comment by mbehrle** [comment]
Thanks!

**Comment by zeha** [comment]
> Just release 4.3.0 :-)

Many thanks! 🎸
