### ISSUE TITLE
Docs: Replace script code examples by programmatic ones

### ISSUE THREAD

**Issue by dr-leo** [mvantellingen/python-zeep#147]
Hello,

most people will work in an environment such as the Jupyter notebook. There it is painful to execute scripts unless really needed. Can you pls revamp the code examples in the docs so that they are interactive?, i.e. starting with 'import zeep' or something?

Moreover, I do not see why I should inspect the WSDL. Pls explain in the docs. I would hope zeep will some day shield me from tons of technicalities...Wishful thinking?
 
Leo

**Comment by mvantellingen** [comment]
Hi, as someone who has never used jupyter notebook i can't relate ;-)  I really do agree that the docs need to be better, but i'm already putting so much time into this library that I can't find the extra time to update the docs or improve them.  I really do welcome all the help I can get on this area.

**Comment by dr-leo** [comment]
Understood. You guys are doing great work and I am optimistic zeep
will soon become for SOAP what requests is for http.

Hopefully, once I have a better grasp of SOAP, I can help out with a
short tutorial. That said, I am fairly busy with my own side-project:
http://pandasdmx.readthedocs.io which has given rise to my so far not
really successful SOAP experiments.

On Jupyter: You don't have to use it to agree that code examples
executable in a Python program are more useful than a Shell command.
zeep is a library after all... I could not send a PR for this as I
have no Clou how to inspect a WSDL with zeep from the Python prompt.

That said, even if you don't see the Point in using a webapp like
Jupyter Notebook just to work in Python (and many other languages)
interactively, I would recommend to give a try at least to the
terminal Version called IPython. It is phantastic for any interactive
work both with Python and the shell.

Leo

**Comment by mvantellingen** [comment]
python -mzeep actually just calls ``client.wsdl.dump()``. That should be added to the docs.

**Comment by mvantellingen** [comment]
Closing for now, help on the docs is appreciated though
