### ISSUE TITLE
Invalid handling of complexContent restriction (wsdl:arrayType)

### ISSUE THREAD

**Issue by luisdemarchi** [mvantellingen/python-zeep#155]
I'm getting a message "unknown error" when I try to include a parameter with a list (employees) objects (employee)

> python -mzeep http://www.ahgora.com.br/ws/service.php?wsdl
> 
>  sincFuncionarios(empresa: xsd:string, funcionarios: FuncionariosArray) -> totaisFuncionarios
> 

```
wsdl = 'http://www.ahgora.com.br/ws/service.php?wsdl'
        client = Client(wsdl=wsdl)

        employee_type = client.get_type('ns0:funcionario')
        employee = employee_type(matricula="000000000",
                                  pis="50728746995",
                                  nome="Luis Marchi",
                                  dataAdmissao='01012016', )

        employee_array_type = client.get_type('ns0:FuncionariosArray')
        employees = employee_array_type(employee)


        result = client.service.sincFuncionarios(empresa='xxxxxxxxxxxxx', funcionarios=employees)


        print(result)
```

Result:

>   File "/Users/luisdemarchi/Git/ERPS/erps_webservice/.env/lib/python3.5/site-packages/zeep/xsd/types.py", line 40, in render
>     raise NotImplementedError
> **NotImplementedError**

**Comment by mvantellingen** [comment]
Could you give the master branch a try: See https://github.com/mvantellingen/python-zeep/commit/a1b24c39c2addc755a7548e30a6a996e7370f984#diff-2894148e8d59152287ffabb1a0eced42R548 for example

**Comment by luisdemarchi** [comment]
In the XML structure I'm working, it did not work. I made Several types of codes, even sent an email to your gmail. I'm still unsure if I'm not doing it right or is this a bug.

pip show zeep

Metadata-Version: 2.0
Name: zeep
Version: 0.13.0

**Comment by mvantellingen** [comment]
See #158
