### ISSUE TITLE
Improve handling of wsdl:arrayType

### ISSUE THREAD

**Issue by mvantellingen** [mvantellingen/python-zeep#158]

**Comment by luisdemarchi** [comment]
There is a forecast for this? Without this invalidates the use of the library.

**Comment by mvantellingen** [comment]
Nope no idea yet sorry, really busy with other stuff. Contract work before voluntarily work and all that :-).

**Comment by mvantellingen** [comment]
See is #181

**Comment by mvantellingen** [comment]
Fix added in 0.17
