### ISSUE TITLE
attributeGroup references are not followed

### ISSUE THREAD

**Issue by ZeWaren** [mvantellingen/python-zeep#160]
When the XSD part of the library parses an attribute group with a `ref` attribute, the reference if not followed, and thus the attribute group is not taken into account in the resulting schemas and messages.

Group declaration:

```
<xsd:attributeGroup name="SomeAttributeGroup">
	<xsd:attribute ref="xsd1:a"/>
	<xsd:attribute ref="xsd1:b"/>
</xsd:attributeGroup>
```

Group reference example:

```
<xsd:complexType name="SomeComplexType">
	<xsd:sequence>
		<xsd:element ref="xsd1:Foo"/>
		<xsd:element ref="xsd1:Bar"/>
	</xsd:sequence>
	<xsd:attributeGroup ref="xsd1:SomeAttributeGroup"/>
</xsd:complexType>
```

What should happen:
The attribute group relation should be resolved, and the list of attributes of the group should be appended to the schema's attribute list.

What happens:
The relation is not followed. No attributes are added to the schema, and thus they are not parsed from the responses messages.

**Comment by mvantellingen** [comment]
Thanks, I remember never really finishing the attributeGroup implementation, will do asap

**Comment by mvantellingen** [comment]
Should be available in master now, let me know if you run into any issues

**Comment by ZeWaren** [comment]
I've just tested on the project I was working on.
The WSDL is now interpreted completely.
Everything is now working fine.
Thanks for the patch.
