### ISSUE TITLE
zeep.exceptions.TransportError: Server returned HTTP status 200 (b'')

### ISSUE THREAD

**Issue by cesclondon87** [mvantellingen/python-zeep#162]
Hi,
I follow documentation and try all available options but i always get HTTP 200 response with empty body.
I use python 3.4.

service: login(credentials: Credentials) -> serverInfo: ServerInfo[], PartialErrors: PartialErrors()
global type: ns3:Credentials(user: xsd:string, password: xsd:string)

My code is:
`import zeep

wsdl = "http://....?wsdl"
client = zeep.Client(wsdl=wsdl)
credentials_object = client.get_type('ns3:Credentials')
credentials = credentials_object(user='xxx',password='xxx')
client.service.loginSSO(credentials=c)
`
**With PHP, this simple wsdl works correctly.

Thanks
Francesco

**Comment by mvantellingen** [comment]
Do you have the wsdl for me? To fix this I need to reproduce it first.

**Comment by cesclondon87** [comment]
Hi Michael,
I added wsld and xsd inside zip attachment.
[wsdl-xsd.zip](https://github.com/mvantellingen/python-zeep/files/445134/wsdl-xsd.zip)
Thanks

**Comment by mvantellingen** [comment]
It's missing a number of xsd files unfortunately. Could you also give the master branch a try, fixed numerous bugs in the last few days

**Comment by mvantellingen** [comment]
Closing this for now. If this is still an issue can you let me know?
