### ISSUE TITLE
Parse response incorrectly with array type elements

### ISSUE THREAD

**Issue by kylezhou** [mvantellingen/python-zeep#163]
I have the following wsdl

    <wsdl:definitions ...>
    <wsdl:types>
	<xs:complexType name="FlagDetailsStruct">
		<xs:sequence>
			<xs:element name="Name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="512"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FlagDetailsList">
		<xs:complexContent>
			<xs:restriction base="soapenc:Array">
				<xs:sequence>
					<xs:element name="FlagDetailsStruct" type="tns:FlagDetailsStruct" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute ref="soapenc:arrayType" use="required"/>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
    </wsdl:types>
    </wsdl:definitions>

A call to the service returns

    {
    '_value_1': [
        <Element FlagDetailsStruct at 0xb65fbf6c>,
        <Element FlagDetailsStruct at 0xb66030ec>
    ],
    'FlagDetailsStruct': [],
    'arrayType': None
    }

The FlagDetailsStruct field is empty.

The soap response is as follows:

    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:nsp="urn:www.abcd.com/nsp:1.2">
       <SOAP-ENV:Body>
          <nsp:GetFlagsResponse>
             <FlagDetailsList>
                <FlagDetailsStruct>
                   <Name>flag1</Name>
                   <Value>value1</Value>
                </FlagDetailsStruct>
                <FlagDetailsStruct>
                   <Name>flag2</Name>
                   <Value>value2</Value>
                </FlagDetailsStruct>
             </FlagDetailsList>
          </nsp:GetFlagsResponse>
       </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

Anything is wrong here?

**Comment by mvantellingen** [comment]
Should be fixed in #181
