### ISSUE TITLE
Error compiling zeep 0.14

### ISSUE THREAD

**Issue by mgaby25** [mvantellingen/python-zeep#167]
Hi guys, 

I noticed this error while installing zeep with pip. It seems a little bit strange that zeep/wsdl.py exists in the package since I saw it was moved, but the install process is still successful. I am using python 3.4.3 and the print statement fails of course. Any thoughts about this error?

$ pip install zeep
Downloading/unpacking zeep
  Downloading zeep-0.14.0-py2.py3-none-any.whl (65kB): 65kB downloaded
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.0.0 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): pytz in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): defusedxml>=0.4.1 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): cached-property>=1.0.0 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): isodate>=0.5.4 in /home/mujini/.virtualenvs/lengow-v3-env/lib/python3.4/site-packages (from zeep)
Installing collected packages: zeep
*** Error compiling '/home/mujini/.virtualenvs/lengow-v3-env/build/zeep/zeep/wsdl.py'...
  File "/home/mujini/.virtualenvs/lengow-v3-env/build/zeep/zeep/wsdl.py", line 40
    print "Types: "
                  ^
SyntaxError: Missing parentheses in call to 'print'

Successfully installed zeep
Cleaning up...

**Comment by mvantellingen** [comment]
Which version of pip are you using? It might be that an old package is still in the build dir

**Comment by mgaby25** [comment]
You are right! I updated pip and everything is ok now, thanks!

**Comment by mvantellingen** [comment]
💃
