### ISSUE TITLE
Connection pool is full, discarding connection

### ISSUE THREAD

**Issue by AmineCherrai** [mvantellingen/python-zeep#169]
Hello,

I have problem I am using threads to make a lot of asynchronous HTTP requests (<3M)

```
  for key in my_dict:
    t = Thread(target=foo, args=(my_dict[key],))
    t.start()
```

I get a warning message "**Connection pool is full, discarding connection**"

Is there a way to increase the "connection pool"?

Thanks

**Comment by mvantellingen** [comment]
This might fix it for you: http://stackoverflow.com/a/18845952/106570

You can access the request.Session() via client.transport.session

**Comment by Koubae** [comment]
Thanks for the help, Just to save some people time here a quick recipe in how to actually do it you can check this answer [`here](https://stackoverflow.com/a/70699922/13903942)`
