### ISSUE TITLE
Some Types are note decoded correctly

### ISSUE THREAD

**Issue by cheuel-novero** [mvantellingen/python-zeep#17]
When I try to call a service provided by [this](http://almdemo.polarion.com/polarion/ws/services/TrackerWebService?wsdl) WSDL, specifically the `getCustomField`, the Python objects seem to be of the type "None".

I just printed the return value, which looks like this:
```
{   'key': None,
    'parentItemURI': 'subterra:data-service:objects:/default/linux${WorkItem}LI-321',
    'value': None}
```

For debugging purpose I caught the packets send by the server with WireShark:
```
<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <getCustomFieldResponse xmlns="http://ws.polarion.com/TrackerWebService-impl">
      <getCustomFieldReturn>
        <ns1:parentItemURI xmlns:ns1="http://ws.polarion.com/TrackerWebService-types">subterra:data-service:objects:/default/linux${WorkItem}LI-321</ns1:parentItemURI>
        <ns2:key xmlns:ns2="http://ws.polarion.com/TrackerWebService-types">solution</ns2:key>
        <ns3:value xmlns:ns3="http://ws.polarion.com/TrackerWebService-types" xmlns:ns4="http://ws.polarion.com/types" xsi:type="ns4:Text">
          <ns4:type xsi:type="xsd:string">text/html</ns4:type>
          <ns4:content xsi:type="xsd:string">Test Solution </ns4:content>
          <ns4:contentLossy xsi:type="xsd:boolean">false</ns4:contentLossy>
        </ns3:value>
      </getCustomFieldReturn>
    </getCustomFieldResponse>
  </soapenv:Body>
</soapenv:Envelope>
```

I can't see any problems with the response, except that the server opens different namespaces for the same namespace. At least for the "key" I would expect that zeep returns the string without hassle.

**Comment by mvantellingen** [comment]
Thanks, the issue seems to be that the soap server returns the elements in an invalid order:
```
<complexType name="CustomField">
    <sequence>
        <element name="key" type="xsd:string"/>
        <element name="parentItemURI" type="xsd:string"/>
        <element name="value" nillable="true"/>
    </sequence>
</complexType>```

**Comment by mvantellingen** [comment]
SoapUI also throws errors regarding the wrong order, will investigate further

```
line 6: Expected element 'key@http://ws.polarion.com/TrackerWebService-types' instead of 'parentItemURI@http://ws.polarion.com/TrackerWebService-types' here in element getCustomFieldReturn@http://ws.polarion.com/TrackerWebService-impl
line 8: Expected element 'parentItemURI@http://ws.polarion.com/TrackerWebService-types' instead of 'value@http://ws.polarion.com/TrackerWebService-types' here in element getCustomFieldReturn@http://ws.polarion.com/TrackerWebService-impl
line 13: Expected element 'parentItemURI@http://ws.polarion.com/TrackerWebService-types' before the end of the content in element getCustomFieldReturn@http://ws.polarion.com/TrackerWebService-impl

**Comment by mvantellingen** [comment]
Seems to be a bug in the generated wsdl: https://issues.apache.org/jira/browse/AXIS-2677

Now a real bug is that the `value` element is not handled as an anyType, which should be the default for non-typed elements.

**Comment by mvantellingen** [comment]
I've just added some logic to handle xsi:type attributes on any-types so that the correct objects are created. 

Closing this ticket for now, but please re-open if it isn't working for you

**Comment by cheuel-novero** [comment]
Unfortunately the new commits don't fix this issue. The value element is decoded as "None".

I can't re-open the issue because I don't have the permissions.

**Comment by mvantellingen** [comment]
Ok, but that is still due to the fact that the server returns the elements in the wrong order right?

**Comment by cheuel-novero** [comment]
No, I use a static WSDL file in which I changed the order of the elements. So the error for now is that the element "value" is set to "None". "key" and "parentItemURI" contain correct values.

**Comment by mvantellingen** [comment]
I'm pretty sure I fixed the issue. Let me know if that isn't the case (again :P)

**Comment by cheuel-novero** [comment]
Yes, this is now fixed! Thank You!

**Comment by jonasstoetzel** [comment]
I'm sitting in front of the problem that the server returns the elements in wrong order, using the same wsdl:
```zeep.exceptions.XMLParseError: Unexpected element '{http://ws.polarion.com/TrackerWebServicetypes}parentItemURI', expected '{http://ws.polarion.com/TrackerWebService-types}key'```
I'm calling ```getCustomField``` like it should be called. There used to be the flag ```strict``` in ```Client()```, but it is gone. How would you proceed here? Should I open a new ticket?
