### ISSUE TITLE
ValueError: No visitor defined for '{http://www.w3.org/2001/XMLSchema}include'

### ISSUE THREAD

**Issue by tyler-8** [mvantellingen/python-zeep#18]
I'm having trouble interpreting what this error is telling me when typing this:
`client = Client('http://www.urlgoesshere.com/aabbcc?wsdl')`

**Error:**
[visitor.txt](https://github.com/mvantellingen/python-zeep/files/258115/visitor.txt)

I suspect I'm not passing some argument that is expected.

**Comment by Kozubi** [comment]
Yesterday I have same problem (but my web service is deployed locally) I updated zeep from github (0.6) and everything is ok.

**Comment by mvantellingen** [comment]
Just implemented support for xsd:include in the master branch, can you give that a try?

**Comment by mvantellingen** [comment]
Closing for now, if you still have problems you can re-open it.

**Comment by tyler-8** [comment]
Apologies for the delayed response. That fix seems to have resolved the issue. I appreciate you taking the time to looking into it.
