### ISSUE TITLE
Fix handling of multiple message parts per operation

### ISSUE THREAD

**Issue by dtougas** [mvantellingen/python-zeep#180]
I tried using this library for the first time today on a rather complex web service. It appears to not be reading the WSDL properly. This is the URL to the WSDL:

https://secure-wms.com/webserviceexternal/contracts.asmx?wsdl

When I run that through the Zeep WSDL examiner, I see that almost all of the services are showing exactly the same list of parameters, when in fact they should be quite different from each other. Zeep appears to be just taking the first parameter (which is a custom data type ns0:UserLoginData) and using that as the parameters for the service.

Is it just me? Or can you confirm this on your end as well.

**Comment by mvantellingen** [comment]
Seems something weird is going on indeed :-) I'll look at it later

**Comment by dtougas** [comment]
Thanks for the quick reply. No rush, due to time constraints I am going to be using a different library.

**Comment by mvantellingen** [comment]
I'm working on a fix in #205. It required some refactoring, are you able to give it a try for me?
