### ISSUE TITLE
ValueError: No visitor defined for '{http://www.w3.org/2001/XMLSchema}notation'

### ISSUE THREAD

**Issue by dr-leo** [mvantellingen/python-zeep#183]
Hi,

a similar issue had been opened, then closed. Still, I run into the following problem (zeep 0.16.0, Py352, 32bit, Win7):

Consider the following script named imf_session.py. It tries to connect to the IMF's 
SOAP data service

import zeep
url = 'http://dataservices.imf.org/sdmx21/SDMX_WCF_Service21.svc?wsdl'
c = zeep.Client(wsdl=url)

In [1]: run imf_session
C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\visitor.py:53: ZeepWarning: Skipping import of schema located at 'http://da
taservices.imf.org/sdmx21/schemas/xml.xsd' for the namespace 'http://www.w3.org/
XML/1998/namespace', since the namespace was already imported with the schema lo
cated at 'https://registry.sdmx.org/schemas/v2_1/xml.xsd'
  result = visit_func(self, node, parent)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\stefan\Documents\dev\pysdmx\imf_session.py in <module>()
      3 url = 'http://dataservices.imf.org/sdmx21/SDMX_WCF_Service21.svc?wsdl'
      4 location = 'https://registry.sdmx.org/schemas/v2_1/SDMXMessage.xsd'
----> 5 c = zeep.Client(wsdl=url)

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\client.py in __init__(self, wsdl, wsse, transport, service_name, port_name, plu
gins)
     50
     51         self.transport = transport or Transport()
---> 52         self.wsdl = Document(wsdl, self.transport)
     53         self.wsse = wsse
     54         self.plugins = plugins if plugins is not None else []

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\wsdl\wsdl.py in __init__(self, location, transport)
     59         document = self._load_content(location)
     60
---> 61         root_definitions = Definition(self, document, self.location)
     62         root_definitions.resolve_imports()
     63

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\wsdl\wsdl.py in __init__(self, wsdl, doc, location)
    152         self.parse_imports(doc)
    153
--> 154         self.parse_types(doc)
    155         self.messages = self.parse_messages(doc)
    156         self.port_types = self.parse_ports(doc)

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\wsdl\wsdl.py in parse_types(self, doc)
    266         schema_nodes = findall_multiple_ns(
    267             doc, 'wsdl:types/xsd:schema', namespace_sets)
--> 268         self.types.add_documents(schema_nodes, self.location)
    269
    270     def parse_messages(self, doc):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\schema.py in add_documents(self, schema_nodes, location)
     34             document = SchemaDocument(
     35                 node, self._transport, self, location,
---> 36                 self._parser_context, location)
     37             documents.append(document)
     38

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\schema.py in __init__(self, node, transport, schema, location, parser_conte
xt, base_url)
    217
    218             visitor = SchemaVisitor(self, parser_context)
--> 219             visitor.visit_schema(node)
    220
    221     def __repr__(self):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\visitor.py in visit_schema(self, node)
    110         parent = node
    111         for node in node.iterchildren():
--> 112             self.process(node, parent=parent)
    113
    114     def visit_import(self, node, parent):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\visitor.py in process(self, node, parent)
     51         if not visit_func:
     52             raise ValueError("No visitor defined for %r" % node.tag)
---> 53         result = visit_func(self, node, parent)
     54         return result
     55

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\visitor.py in visit_import(self, node, parent)
    190         schema = self.document.__class__(
    191             schema_node, self.document._transport, self.schema, location
,
--> 192             self.parser_context, base_url)
    193
    194         self.document._imports[namespace] = schema

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\schema.py in __init__(self, node, transport, schema, location, parser_conte
xt, base_url)
    217
    218             visitor = SchemaVisitor(self, parser_context)
--> 219             visitor.visit_schema(node)
    220
    221     def __repr__(self):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\visitor.py in visit_schema(self, node)
    110         parent = node
    111         for node in node.iterchildren():
--> 112             self.process(node, parent=parent)
    113
    114     def visit_import(self, node, parent):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.16.0-py3.5.egg\zeep
\xsd\visitor.py in process(self, node, parent)
     50         visit_func = self.visitors.get(node.tag)
     51         if not visit_func:
---> 52             raise ValueError("No visitor defined for %r" % node.tag)
     53         result = visit_func(self, node, parent)
     54         return result

ValueError: No visitor defined for '{http://www.w3.org/2001/XMLSchema}notation'

**Comment by mvantellingen** [comment]
Might be fixed now 👍

**Comment by mvantellingen** [comment]
Should now be in 0.17 (just released)

**Comment by dr-leo** [comment]
Thanks. Looks good!


Am 12.09.2016 um 10:33 schrieb Michael van Tellingen:
