### ISSUE TITLE
LookupError: No type 'xxx' in namespace

### ISSUE THREAD

**Issue by SlippingAway** [mvantellingen/python-zeep#184]
Using python-zeep 0.16. I am getting the error `LookupError: No type 'CountryItemType' in namespace http://schemas.xmlsoap.org/soap/encoding/`.

This is what I am doing (link to the WSDL in the code below):

```python
from zeep import Client
from from zeep.transports import Transport
transport = Transport(http_auth=('***', '***'))
client = Client('http://www.visahq.com/wsdl.wsdl', transport=transport)
# Failing operation
client.service.doGetCountries()
```

If I check with `client.wsdl.dump()`, I can see this global type:
`     ns0:CountryItemType(code: xsd:CountryCodeType, name: xsd:string)`

The failing operation is also defined there:
`            doGetCountries() -> _value_1: CountryItemType[], arrayType: psd:string`

I verified at least one operation that is working, so it's not in the service itself. I tried also the master branch, but got the same results. Let me know if you need more information.

**Comment by mvantellingen** [comment]
It seems the request can be generated but the error occurs when processing the response. Do you have the response XML for me? Thanks :-)

**Comment by SlippingAway** [comment]
A fairly long response, but it's made of repetitive elements so I removed a few:

```xml
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:VisaHQTravelService" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <SOAP-ENV:Body>
    <ns1:doGetCountriesResponse>
      <countries SOAP-ENC:arrayType="ns1:CountryItemType[232]" xsi:type="ns1:CountriesArrayType">
        <item xsi:type="ns1:CountryItemType">
          <code xsi:type="ns1:CountryCodeType">AF</code>
          <name xsi:type="xsd:string">Afghanistan</name>
        </item>
        <item xsi:type="ns1:CountryItemType">
          <code xsi:type="ns1:CountryCodeType">AL</code>
          <name xsi:type="xsd:string">Albania</name>
        </item>
        <item xsi:type="ns1:CountryItemType">
          <code xsi:type="ns1:CountryCodeType">DZ</code>
          <name xsi:type="xsd:string">Algeria</name>
        </item>
        <item xsi:type="ns1:CountryItemType">
          <code xsi:type="ns1:CountryCodeType">AS</code>
          <name xsi:type="xsd:string">American Samoa</name>
        </item>
        <item xsi:type="ns1:CountryItemType">
          <code xsi:type="ns1:CountryCodeType">AD</code>
          <name xsi:type="xsd:string">Andorra</name>
        </item>
        <item xsi:type="ns1:CountryItemType">
          <code xsi:type="ns1:CountryCodeType">AO</code>
          <name xsi:type="xsd:string">Angola</name>
        </item>
        <!-- ...and many more... -->
      </countries>
    </ns1:doGetCountriesResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by mvantellingen** [comment]
Thanks! Should be fixed in master (let me know if you run into any other issues)

**Comment by SlippingAway** [comment]
Works perfectly. Thank you!

**Comment by dhke** [comment]
I get a similar error when parsing array types. It is related, but maybe another issue. The error happens when trying to parse the [Sympa WSDL](https://www.sympa.org/documentation/manual/doc-5.2.3/html/node12.html#SECTION001240000000000000000):

Changing:

    <complexType name="ArrayOfString">
        <complexContent>
            <restriction base="SOAP-ENC:Array">
                <attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="string[]"/>
            </restriction>
        </complexContent>
    </complexType>

to

    <complexType name="ArrayOfString">
        <complexContent>
            <restriction base="SOAP-ENC:Array">
                <attribute ref="SOAP-ENC:arrayType" wsdl:arrayType="xsd:string[]"/>
            </restriction>
        </complexContent>

makes the problem go away.

**Comment by iopoz** [comment]
@mvantellingen Hi. I faced with the same issue.
Server sends me  response like that
<?xml version="1.0" encoding="windows-1251"?>                            
<ns0:ROOT xsi:type="xsd:ROOT" xmlns:ns0="urn:DAX_Contracts_WS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <ns0:ContractsList>
        <ns0:Entry_ID xsi:type="xsd:string">000000010611696</ns0:Entry_ID>
    </ns0:ContractsList>
    <ns0:ContractsList>
        <ns0:Entry_ID xsi:type="xsd:string">000000010611709</ns0:Entry_ID>
    </ns0:ContractsList>
    <ns0:ContractsList>
        <ns0:Entry_ID xsi:type="xsd:string">000000010611717</ns0:Entry_ID>
    </ns0:ContractsList>
    <ns0:ContractsList>
        <ns0:Entry_ID xsi:type="xsd:string">000000010611719</ns0:Entry_ID>
    </ns0:ContractsList>

but lib returs me error {LookupError}No type 'ROOT' in namespace http://www.w3.org/2001/XMLSchema. Available types are: {http://www.w3.org/2001/XMLSchema}string, {

I've tried to add this type to any.py, and to builtins.py. It didn't help me, just error closed up. Could you help me with solution
