### ISSUE TITLE
Element can only be used in _soapheaders once

### ISSUE THREAD

**Issue by gavinwahl** [mvantellingen/python-zeep#188]
I have a service that takes authentication in a SOAP header. I can pass the authentication in zeep using the _soapheaders argument. However, if I pass the same value to two service calls, it doesn't work the second time. 

```python
client = Client('https://api.example.com/?wsdl')
UserCredentials = client.get_element('{https://api.example.com/}UserCredentials')
header_value = UserCredentials(UserName='foo', Password='foo')

client.service.Foo(_soapheaders=[header_value])

client.service.Foo(_soapheaders=[header_value])
```

On the second call, zeep is sending a request with an empty `<UserCredentials/>` element. I expect it to use the same UserName and Password as the first request.

Additionally, it would be very useful if I could pass headers to the Client and have them automatically be used on every service call, instead of passing them every time.

**Comment by mvantellingen** [comment]
With which versions was this? This might have been fixed by https://github.com/mvantellingen/python-zeep/commit/5612109f10775357820d2cf0dcc4a739873a59ba

**Comment by gavinwahl** [comment]
0.18.1

**Comment by mvantellingen** [comment]
Thanks, should be fixed now
