### ISSUE TITLE
zeep.exceptions.TransportError: Server returned HTTP status 415 (no content available)

### ISSUE THREAD

**Issue by johnlage** [mvantellingen/python-zeep#189]
WSDL:  https://clientservice-v6-beta.curse.com/ClientLoginService.svc?wsdl
Version: latest git as of post time
Error: If I try to use the Login endpoint of that service, I get the error in the title. Further investigation using a debugger shows that the 'reason' that the server is giving is "Cannot process the message because the content type 'application/soap+xml; charset=utf-8' was not the expected type 'application/soap+msbin1'."
What do I need to do to be able to use this SOAP service?

**Comment by mvantellingen** [comment]
So the application/soap+msbin1' content type is a new one for me. I did do some changes to the content-type header in master branch (for soap 1.2) Maybe that will also work here? Could you give it a spin? THanks

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue

**Comment by johnlage** [comment]
Sorry for the delayed response, but as far as i can tell, this msbin type is a proprietary microsoft binary XML, meaning that SOAP apps that require this type will most likely need more than just headers (AKA may need to convert from the XML to MSBIN before sending, and convert the response back). I still need to find my testing code to check if what you did solved it, but it seems unlikely with these complications.
