### ISSUE TITLE
Zeep does not parse the result

### ISSUE THREAD

**Issue by arturzangiev** [mvantellingen/python-zeep#190]
I am trying to access BetDaq api "http://api.betdaq.com/v2.0/API.wsdl" and call method ListTopLevelEvents

`client = zeep.Client('http://api.betdaq.com/v2.0/API.wsdl')
data = client.service.ListTopLevelEvents(_soapheaders={'ExternalApiHeader': {'version' : '2', 'languageCode' : 'en', 'username' : 'testname', 'password' :'password'}})`

When I use logging.config I can see that I get XML response, but it seems zeep does not parse it and I can't print(data)

**Comment by mvantellingen** [comment]
Can you create an example script which exposes the problem? The following is an example:

```
import pretend

from zeep import Client
from zeep.transports import Transport

transport = Transport()
client = Client('http://www.visahq.com/wsdl.wsdl', transport=transport)

response = pretend.stub(
    status_code=200,
    headers=[],
    content="""
The XML response
""")

result = client.service._binding.process_reply(
    client,
    client.service._binding._operations['ListTopLevelEvents'],
    response)

print(result)
```

If you could create something like that for your request I can probably fix it pretty quickly

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
