### ISSUE TITLE
NotImplementedError: QName.xmlvalue() not implemented

### ISSUE THREAD

**Issue by vashek** [mvantellingen/python-zeep#191]
I'm getting "NotImplementedError: QName.xmlvalue() not implemented" after this:

```
s = Client("WSDScannerService.wsdl")
svc = s.create_service("{http://schemas.microsoft.com/windows/2006/08/wdp/scan}ScannerServiceBinding", "http://10.0.4.105:8080/ScannerService/")
qnStatus=lxml.etree.QName("http://schemas.microsoft.com/windows/2006/08/wdp/scan", "ScannerStatus")
svc.GetScannerElements(s.get_element("ns0:GetScannerElementsRequest")(RequestedElements={"Name": qnStatus}))
```
The WSDL and XSDs are from http://msdn.microsoft.com/en-us/windows/hardware/gg463146.aspx, the link titled "Scan Service Definition V1.0 for Web Services on Devices".

Even if I just do:

`svc.GetScannerElements(RequestedElements={"Name": "asd:qwe"})`

the result is the same.
zeep 0.17.0, lxml.etree 3.6.4, python 3.5.2 on 64bit Windows
Am I doing something wrong?
Thanks.

**Comment by vashek** [comment]
I am also getting NotImplementedError in other contexts, not just with the QName. Either I'm missing something very important, or the functionality is indeed not implemented...??

**Comment by mvantellingen** [comment]
Should be fixed in master. However the usage of etree.QName doesn't seem to work here since it seems to lose it's value in copy.deepcopy

This works
```
import logging

from zeep import Client

logging.basicConfig(level='DEBUG')

s = Client("~/Downloads/ScanService/WSDScannerService.wsdl")
svc = s.create_service("{http://schemas.microsoft.com/windows/2006/08/wdp/scan}ScannerServiceBinding", "http://10.0.4.105:8080/ScannerService/")

qnStatus = "http://schemas.microsoft.com/windows/2006/08/wdp/scan/ScannerStatus"
svc.GetScannerElements(
    s.get_element("ns0:GetScannerElementsRequest")(RequestedElements={"Name": qnStatus})
)
```
