### ISSUE TITLE
Support for decoding XOP responses

### ISSUE THREAD

**Issue by vashek** [mvantellingen/python-zeep#194]
I need support for decoding [XML-binary Optimized Packaging (XOP)](https://www.w3.org/TR/xop10/) responses. I will probably have to cobble up something pretty soon unless someone already has anything like this. Thanks.
Also, streaming the data would be nice because the response could be large.

**Comment by mvantellingen** [comment]
Hi Vashek, it's seems like it's not something I'm going to implement in my spare time. I will of course accept a pull request for it.  

If you want to sponsor this (as in contracting work) then you can contact me at info@mvantellingen.nl

**Comment by vashek** [comment]
Just letting you know I have a working prototype. I will push it to github once I've had some sleep.

**Comment by vashek** [comment]
My implementation is here: https://github.com/vashek/python-zeep/tree/xop

**Comment by mvantellingen** [comment]
@vashek cool! Do you think this can be implemented as a Zeep Plugin? See http://docs.python-zeep.org/en/master/plugins.html

**Comment by vashek** [comment]
I thought about that. Not with the way plugins work today, unfortunately, because `plugins.apply_ingress` is only called in `process_reply` AFTER the response is parsed and made into an ElementTree. But that will fail, because a XOP response wraps the XML in a MIME multipart message.

Now that I think about it again, maybe at least the second part of the processing (the replacement of the `<xop:Include>` elements with the actual binary data) might be done in a plugin. I don't know how much sense it makes though.

**Comment by mvantellingen** [comment]
I've taken a better look at your code. I think if we add an additional entry point in the plugins so that you can pre-process the response that most of it can be moved to a plugin. 

I can try to convert your code to a plugin, but if you want to do it yourself then you are of course more then welcome :-)

**Comment by mvantellingen** [comment]
Implemented on master
