### ISSUE TITLE
NotImplementedError: parse_xmlelement not defined for UnionType

### ISSUE THREAD

**Issue by moiseshiraldo** [mvantellingen/python-zeep#195]
I'm getting that error when `zeep` tries to parse an XML union element like this one: `<supplyDate>032002</supplyDate>`. This is the specification:

``` xml
<xs:simpleType name="Date">
    <xs:union memberTypes="xs:date xs:gYear xs:gYearMonth MMYY MMYYYY"/>
</xs:simpleType>
<xs:simpleType name="MMYY">
    <xs:restriction base="xs:string">
      <xs:pattern value="(0[123456789]|1[012]){1}\d{2}"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="MMYYYY">
    <xs:restriction base="xs:string">
      <xs:pattern value="(0[123456789]|1[012]){1}\d{4}"/>
    </xs:restriction>
</xs:simpleType>
```

If I've understood properly what union types are, it means the field can be any of the supplied `memberTypes` and we have no simple way of knowing which one to parse. So I think the only workaround here is returning the `xmlelement.text` as it is. I've done that for the `UnionType` class and it's working fine in my case. If you agree that's an acceptable generic solution I can push the code and do a pull request.

Oh god, I hate SOAP. Thank you for your work making it less painful!

**Comment by mvantellingen** [comment]
Just added a fix for this in #192. For now I just try the first member type. Can you give that a try?

**Comment by moiseshiraldo** [comment]
Hi @mvantellingen, thank you for your response.

I'm getting a `parse_xmlelement() got an unexpected keyword argument 'allow_none'` error. But even adding the `allow_none` argument to the `parse_xmlelement` method, it doesn't work properly in my case.

The API is returning `<supplyDate>032002</supplyDate>`, and if you try to parse that with the first member type (`xs:date`, see the specification on my initial message), it will just get a wrong date. In other cases could even throw an error (for example if you're expecting an int for the first member type but the xml element contains a string type http://www.w3schools.com/xml/el_union.asp).

We're facing an XML/SOAP bad design and like I said I think there's nothing you can do apart from returning the XML element text as it is.

**Comment by mvantellingen** [comment]
@moiseshiraldo can you let me know if the current implementation works for you?

**Comment by moiseshiraldo** [comment]
@mvantellingen Yes, it returns the raw value now, as expected. Thank you!
