### ISSUE TITLE
NTLM Support

### ISSUE THREAD

**Issue by Orangensaft** [mvantellingen/python-zeep#196]
Are there plans for supporting NTLM-Auth?

**Comment by RichardRirie** [comment]
NTLM-Auth can be done by providing your own transport class to zeep.Client and using the requests_ntlm package.

I'll send you a gist when I get to a computer in a bit.

**Comment by RichardRirie** [comment]
https://gist.github.com/RichardRirie/4437d802320c9b6d631a081ddfee61bb

**Comment by mvantellingen** [comment]
Thanks @RichardRirie, do you want to add an example to the documentation?

**Comment by RichardRirie** [comment]
Hi @mvantellingen, I should have some time over the weekend to have a look.

**Comment by mvantellingen** [comment]
This http://docs.python-zeep.org/en/master/transport.html#http-authentication might just cover it for now. If you are able to better document it then I'll happily accept the PR :-)

**Comment by scorpioGusTx** [comment]
I was able to get it to work by installing requests_ntlm and using it with the following code, which needs to have url, userid and password assigned. Note that userid needed to be in the form of DOMAIN\UserName for me.

```
from requests import Session
from requests_ntlm import HttpNtlmAuth

from zeep import Client
from zeep.transports import Transport

session = Session()
session.auth = HttpNtlmAuth(userid, password)

client = Client(url, transport=Transport(session=session))

```

**Comment by DMLoy** [comment]
^^ This still works.
