### ISSUE TITLE
Check lxml.etree version in cleanup_namespaces call

### ISSUE THREAD

**Issue by jjmurre** [mvantellingen/python-zeep#197]
We are using lxml 3.3.5, because our system (Zato) has pinned that version of lxml.
However, the latest (since 0.15.0) zeep versions are not compatible anymore with this lxml version because of a call to etree.cleanup_namespaces (in wsa.py). The keyword argument top_nsmap has been added to cleanup_namespaces somewhere after lxml version 3.3.5

Is it possible to check for lxml version or do a try except and call cleanup_namespaces with the top_nsmap if needed? Or does that not make any sense?

For now we downgrade to zeep 0.14.0 to avoid this issue.

And, the lxml constraint needs to be updated (top_nsmap argument added in lxml 3.5.0b1).

**Comment by mvantellingen** [comment]
hm, yeah I think we can do that. Are you able to provide a PR for this?

**Comment by jjmurre** [comment]
I get a regression here:

TypeError: cleanup_namespaces() takes no keyword arguments
Introduced in:
https://github.com/mvantellingen/python-zeep/commit/c9acf5b158c65914d2ab98c8520e8fb417e57df1

**Comment by mvantellingen** [comment]
I think the cleanup_namespaces should just be removed altogether. Although the result xml looks nicer it also introduces some issues (like qualified names in attribute values which is not supported)

**Comment by mvantellingen** [comment]
Fixed in last release
