### ISSUE TITLE
'IndexError: list index out of range' following message_node = node.getchildren()[0]

### ISSUE THREAD

**Issue by twisbrogan** [mvantellingen/python-zeep#200]
I receive this error message above when inspecting the file attached. After amending the flow of code [here](https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/wsdl/http.py#L146) with a try/except then I'm able to inspect and execute code as required (with no known consequences to my application so far)

[wsdl_to_inspect.txt](https://github.com/mvantellingen/python-zeep/files/500392/wsdl_to_inspect.txt)

**Comment by mvantellingen** [comment]
This seems related to #185 right?

**Comment by twisbrogan** [comment]
So it does. Apologies for missing that. 

In my instance the suggested codes changes in #185 (to http.py) resolved my issue

**Comment by mvantellingen** [comment]
Should be fixed in master! Thanks for reporting
