### ISSUE TITLE
[Question] Is there any way to use zeep without install Microsoft Visual C++ Build Tools?

### ISSUE THREAD

**Issue by GeorgeFischhof** [mvantellingen/python-zeep#201]
Hi There,

[Question] Is there any way to use zeep without install Microsoft Visual C++ Build Tools?
On windows lxml library can be installated only if this build tool is installed. The build tools says that it occupies 4 GB (!) space. 
I would not like to install a 4 GB compiler on my PC. 
But the worse thing is that actually I would like to use zeep for testing purposes on a virtaul machine, which is snapshotted to a clean state. It means that this 4 GB should be installed every times, I clean the environment...

BR,
George

**Comment by RichardRirie** [comment]
Hi George, 

I ran into the same problem, when running zeep locally on my windows machine. I didn't want to install the build tools even though it was a one-off.

I installed a python wheel package for lxml (see: http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml).
You should be able to install it using pip using the wheel package:
`pip install wheel`
`pip install filename.whl'

**Comment by GeorgeFischhof** [comment]
Hi Richard,

it works, thank You :-)
