### ISSUE TITLE
Does not complete encode complex requests

### ISSUE THREAD

**Issue by CrabbyPete** [mvantellingen/python-zeep#203]
I am programming Google DFP and trying to implement a complex query. https://developers.google.com/doubleclick-publishers/docs/soap_xml
https://developers.google.com/doubleclick-publishers/docs/reference/v201605/InventoryService.Statement

I am passing in 
{'query': 'WHERE status = :status LIMIT 1 OFFSET 0', 'values': [{'value': {'value': 'ACTIVE', 'xsi_type': 'TextValue'}, 'key': 'status'}]} 

but I only get 

b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<soap-env:Envelope xmlns:ns0="https://www.google.com/apis/ads/publisher/v201605" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">\n  soap-env:Header\n    ns0:RequestHeader\n      ns0:networkCode1234567/ns0:networkCode\n      ns0:applicationNameTEST DFP/ns0:applicationName\n    /ns0:RequestHeader\n  /soap-env:Header\n  soap-env:Body\n    ns0:getAdUnitsByStatement\n      ns0:filterStatement\n        ns0:queryWHERE status = :status LIMIT 1 OFFSET 0/ns0:query\n        ns0:values\n          ns0:keystatus/ns0:key\n          ns0:value/\n        /ns0:values\n      /ns0:filterStatement\n    /ns0:getAdUnitsByStatement\n  /soap-env:Body\n/soap-env:Envelope\n'

**Comment by mvantellingen** [comment]
Do you have a script which I can run to test it?

**Comment by CrabbyPete** [comment]
You need a Google DFP account.  I believe they do offer a small business account. The important part is I don't get the values from the string I am passing in.

**Comment by mvantellingen** [comment]
yeah but the important part for me is that I need a script so that I can reproduce it :-)

**Comment by CrabbyPete** [comment]
I’ll see if I can isolate the code that does it

**Comment by mvantellingen** [comment]
Something like the following: 

```python
from zeep import Client
from zeep.transports import Transport

wsdl = '<url-to-wsdl>'
client = Client(wsdl)

node = client.service._binding.create_message('operation-name', *args, **kwargs)

from lxml import etree
print etree.tostring(node, pretty_print=True)
```

**Comment by CrabbyPete** [comment]
Wish it was that simple. Here is the library I am using
https://github.com/googleads/googleads-python-lib <https://github.com/googleads/googleads-python-lib> 

It uses suds, and I want to replace it with zeep

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
