### ISSUE TITLE
Better support for duplicate targetNamespaces

### ISSUE THREAD

**Issue by kc-hyperaxes** [mvantellingen/python-zeep#204]
I was trying to use Zeep for a client application against Oracle Sales Clound. 
`try:
    client = zeep.Client(
        wsdl='https://cafk-test.crm.us2.oraclecloud.com/crmCommonSalesParties/AccountService?WSDL',
        transport=transport_with_basic_auth
    )`

yields:
C:\Python27\lib\site-packages\zeep\xsd\visitor.py:53: ZeepWarning: Skipping import of schema located at 'https://cafk-test.crm.us2.oraclecloud.com:443/crmCommonSalesParties/AccountService?XSD=/oracle/apps/crmCommon/salesParties/commonService/SalesTeamMember.xsd' for the namespace 'http://xmlns.oracle.com/apps/crmCommon/salesParties/commonService/', since the namespace was already imported with the schema located at 'https://cafk-test.crm.us2.oraclecloud.com:443/crmCommonSalesParties/AccountService?XSD=/oracle/apps/crmCommon/salesParties/commonService/PrimaryAddress.xsd'
  result = visit_func(self, node, parent)
C:\Python27\lib\site-packages\zeep\xsd\visitor.py:53: ZeepWarning: Skipping import of schema located at 'https://cafk-test.crm.us2.oraclecloud.com:443/crmCommonSalesParties/AccountService?XSD=/META-INF/wsdl/BC4JServiceCS.xsd' for the namespace 'http://xmlns.oracle.com/adf/svc/types/', since the namespace was already imported with the schema located at 'https://cafk-test.crm.us2.oraclecloud.com:443/crmCommonSalesParties/AccountService?XSD=/META-INF/wsdl/BC4JService.xsd'
  result = visit_func(self, node, parent)
No type 'SalesTeamMember' in namespace http://xmlns.oracle.com/apps/crmCommon/salesParties/commonService/. Available types are: {http://xmlns.oracle.com/apps/crmCommon/salesParties/commonService/}PrimaryAddress

which is pretty much what -mzeep said.

I don't think I can share the basic auth but the first level namespace that returns definitely doesn't contain  'SalesTeamMember'

https://cafk-test.crm.us2.oraclecloud.com/crmCommonSalesParties/AccountService?WSDL

**Comment by mvantellingen** [comment]
As the warnings mention multiple schema's are defined for the same target namespace. This is actually invalid.

I might want to add support for it later by merging them or something, i'll need to decide how to handle duplicate elements in that case.

**Comment by mvantellingen** [comment]
This should now work in the master branch, although I didn't really test it in depth.

So let me know if this still causes errors :-)
