### ISSUE TITLE
Support SOAP 1.2 Fault attributes, especially Subcode

### ISSUE THREAD

**Issue by vashek** [mvantellingen/python-zeep#206]
Support SOAP 1.2 Fault attributes, especially Subcode.

**Comment by vashek** [comment]
Pull request opened, are you OK with this @mvantellingen?

**Comment by vashek** [comment]
Actually, the subcode values should be QNames, so this is not yet complete, sorry.

**Comment by vashek** [comment]
@mvantellingen: I would appreciate advice here. How best to get a string like `sca:ClientErrorFormatNotSupported` (from a part of a SOAP 1.2 Faul that looks like this: `<soap:Subcode><soap:Value>sca:ClientErrorFormatNotSupported</soap:Value></soap:Subcode>`), and turn it into a QName representation independent on the namespace map?

**Comment by vashek** [comment]
OK, I think I got it now. Feedback pls?

**Comment by mvantellingen** [comment]
Thanks for the work. I'll give it a look asap, but that might be a few days since I'm pretty busy atm

**Comment by mvantellingen** [comment]
It's merged! Thanks again
