### ISSUE TITLE
Force ns0 removal from envelope sent

### ISSUE THREAD

**Issue by wmehanna** [mvantellingen/python-zeep#208]
I'm having an issue when using zeep-python, the envelope sent has a bunch of **ns0** added as namespacing.

I tried using the etree.register_namespace() method but it doesn't seems to apply it to the envelope.

I'm using fiddler to debug, so here's what doesn't work, and what's working :
## Not working:

`
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns0="http://www.myurl.com/Integration/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
    <soap-env:Body>
        <ns0:GetList>
            <ns0:entity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns0:Employee">
                <ns0:ID xsi:nil="true"/>
                <ns0:Delete>false</Delete>
            </ns0:entity>
            <ns0:returnFullEntities>false</ns0:returnFullEntities>
        </ns0:GetList>
    </soap-env:Body>
</soap-env:Envelope>
`
## Working :

`
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns="http://www.myurl.com/Integration/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
    <soap-env:Body>
        <GetList>
            <entity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Employee">
                <ID xsi:nil="true"/>
                <Delete>false</Delete>
            </entity>
            <returnFullEntities>false</returnFullEntities>
        </GetList>
    </soap-env:Body>
</soap-env:Envelope>
`
## My python code

`
from zeep import Client
from zeep.transports import Transport
from lxml import etree
from xml.etree import ElementTree as etree

transport = Transport(verify=False)
wsdl = 'https://my.urlcom/Integration/?WSDL' #Private wsdl
client = Client(wsdl, transport=transport)
etree.register_namespace("", "http://www.myurl.com/Integration/")
client.service.Login('username', 'password', 'schema', 'smtn', 'EN-US') #need to login (works with the ns0 added)

DepartmentCls = client.get_type('ns0:Department')
department = DepartmentCls()
department["Delete"] = False
resDepartments = client.service.GetList(department, False) #crashes
`
## Here's the output :

> zeep.exceptions.Fault: System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.AddListField(XmlDocument document, String entityType, FieldNode field, XmlNode fieldElementValue, XmlAttribute typeAttribute, XmlElement fieldElement)
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.AddFields(XmlDocument document, XmlNode entity, IEnumerable`1 fields, String entityType)
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.TransformEntityNode(XmlDocument document, XmlNode entity, String parent, String fieldName, String type)
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.TransformInputMessage(XmlDocument document)
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.TransformInputMessage(XmlReader input, XmlWriter output, String oldNamespace, String newNamespace)
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.TransformSoapMessage(XmlReader input, XmlWriter output, String oldNamespace, String newNamespace, Action`4 transformer)
>    at PX.Api.ContractBased.Soap.EntityTransformExtension.ProcessMessage(SoapMessage message)
>    at System.Web.Services.Protocols.SoapMessage.RunExtensions(SoapExtension[] extensions, Boolean throwOnException)
>    at System.Web.Services.Protocols.SoapServerProtocol.ReadParameters()
>    at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()
>    --- End of inner exception stack trace ---
>   Process finished with exit code 1

Any help would be appreciated

**Comment by mvantellingen** [comment]
Hmm, not really understanding this one. The working version is actually the same as the non-working except that you set a default xml namespace and the non working has one explicitly defined. Do you have the wsdl available?

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue

**Comment by kitab15** [comment]
I'm having exactly the same problem. 

A bunch of ns0 namepsacing marks are added to the sent envelope and the remote server is responding with a 400 - Bad Request. If I remove this marks the response is as expected...

**Comment by xeor** [comment]
I have this issue as well (I think).

The error I get back from the server I am talking to is like;

```
End element 'anID' from namespace 'http://url.for/namespace/v1' expected.
Found element 'ns0:anID' from namespace 'http://url.for/namespace/v1'. Line 6, position 18.
```

**Comment by xeor** [comment]
Never mind me, my problem is gone. I got my types wrong. Enabling debugging showed me my mistake

**Comment by suzenhan** [comment]
I'm having the same problem.

**Comment by martindahlborg** [comment]
I am having the same problem.

The remote server (not under my control) refuses to return data when "ns0:" is present in request.

Is there a way to turn off these "namespacing marks"?

**Comment by chirag82** [comment]
> I am having the same problem.
> 
> The remote server (not under my control) refuses to return data when "ns0:" is present in request.
> 
> Is there a way to turn off these "namespacing marks"?

I am having the same issue, just wanted to check if anyone found the solution to this.

**Comment by buntine** [comment]
+1

**Comment by pashkone** [comment]
I have the same issue.

Need to send data structure in request that will look like this
```
<ns1:MethodName>
    <ns1:Request>
        <Param>12345</Param>
    </ns1:Request>
</ns1:MethodName>
```
But it sends like:
```
<ns1:MethodName>
    <ns1:Request>
        <ns1:Param>12345</ns1:Param>
    </ns1:Request>
</ns1:MethodName>
```

As a result i get a deserialization error

> 'EndElement' 'request' from namespace 'ns1' is not expected. Expecting element 'Param'.'

Schema look like this
```
...
<xs:element name="MethodName">
    <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="0" name="Request" nillable="true" type="MethodNameRequest"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
...
```

**Comment by miverson** [comment]
I am struggling with this as well. Anyone resolve this issue?

**Comment by da1910** [comment]
I had this same problem as well, we had an element which was not a type. It was being serialized as a type which was causing internal service errors. Our solution was to use an egress plugin - register the pluign when creating the client and you can rewrite outgoing requests.

`self._dataExportClient = zeep.Client("/path/to.wsdl", transport=some_transport, plugins=[PatchXml()])`

Where, in your case:

`class PatchXml(Plugin):
    def egress(self, envelope, http_headers, operation, binding_options):
        request_message = etree.tostring(envelope, encoding="unicode")
        # Check whether envelope contains incorrect XML:
        if '<soap-env:Body>' in request_message:
            request_message = re.sub(r' xsi:type="ns[\d]+:does_not_need_namespace"', 'does_not_need_namespace', request_message)
            parser = etree.XMLParser()
            new_envelope = etree.XML(request_message, parser=parser)
            return new_envelope, http_headers
        # If no patching required, return unmodified envelope:
        else:
            return envelope, http_headers`

This will remove the `ns:0` declaration from the element `does_not_need_namespace`.

**Comment by jeroen7s** [comment]
Quite annoying that there's no proper way to remove namespaces without writing patches like this.
I need to remove the namespaces for 10 different elements for my implementation
Shouldn't this be re-opened?
Or is there a better way available now?

**Comment by EmpireofKings** [comment]
@jeroen7s Yeah man, its very annoying i agree with you, this repository is misleading, as its not a genuine SOAP client, its a weak SOAP parser with the added ability of making requests. 

A good Soap client will generate the object for you, having to create all of these little patches for each WSDL file is cumbersome,  i recommend just using beautifulsoup and the requests library.

**Comment by ralffunk** [comment]
I had the same symptom (in the outgoing envelope of the SOAP call, zeep added 'ns0' as namespace for all the elements, zeep version 4.1); in my case it was solved by using the method https://docs.python-zeep.org/en/master/api.html#zeep.Client.set_ns_prefix of the zeep client.

I got the answer from stackoverflow https://stackoverflow.com/questions/56022962/make-zeep-use-default-namespace-instead-of-named-namespace-in-some-cases and https://stackoverflow.com/questions/55812660/how-to-set-default-xmlns-with-zeep-in-python/56158276#56158276

Maybe this does not work for everyone that sees the symptoms described in this thread, but I am adding this comment because it might help someone.
