### ISSUE TITLE
Problem sending generated xml's

### ISSUE THREAD

**Issue by Kozubi** [mvantellingen/python-zeep#21]
Hello again
Wll I'm trying to generate xml file then open it and send it using zeep. It's almost working but I have problem with serializing some parameters
The code 

`f = open("test.xml");`
`c = client.service.MyMethod(f);`
`print(c)`

Fault code:

>zeep.exceptions.Fault: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://tempuri.org/:Parameter_in_Method. 
The InnerException message was 'There was an error deserializing the object of type System.Int32. The value '<_io.TextIOWrapper name='test.xml' mode='r' encoding='cp1250'>' cannot be parsed as the type 'Int32'.'

**Comment by mvantellingen** [comment]
Can you try:

```python
with open("test.xml") as f:
    c = client.service.MyMethod(f.read());
    print(c)
```
?

**Comment by Kozubi** [comment]
Still the same error appear for same parameter

> The InnerException message was 'There was an error deserializing the object of type System.Int32. The value '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">

>+my_xml_file

>  cannot be parsed as the type 'Int32'.'.  Please see InnerException for more details.

**Comment by mvantellingen** [comment]
It seems that the endpoint expects an integer and you might be sending a string?

**Comment by Kozubi** [comment]
Yes this is true but is there possibility tu put Integrer in file?

**Comment by mvantellingen** [comment]
Sorry, i'm not sure i'm following you. What is it you want to achieve? If the method argument is supposed to be an integer you should pass an integer, not a string.

**Comment by Kozubi** [comment]
Well i try to pass xml document and send it to webservice. Just checking if this is possible

**Comment by mvantellingen** [comment]
Ah, yeah you can't pass pre-generated soap documents into zeep currently. Not sure what the exact use-case would be for that. Is the document generated by zeep incorrect?

**Comment by mvantellingen** [comment]
Closing for now. Sending pre-generated soap documents isn't supported (generating the documents is what this lib is for).
