### ISSUE TITLE
Action in Content-Type header and not SOAPAction. Soap 1.2.

### ISSUE THREAD

**Issue by RubenSchmidt** [mvantellingen/python-zeep#211]
Is there any way to specify that action should be put in the Content-Type header and not in the SOAPAction header?

The http_headers look like this:
{'SOAPAction': '"http://www.***.no/Services/TestService/TestService/HelloSimple"', 'Content-Type': 'application/soap+xml; charset=utf-8'}

And i need it to be like this:
{'Content-Type': 'application/soap+xml;charset=UTF8;action="http://www.***.no/Services/TestService/TestService/HelloSimple"'}

Right now a fix for me is to just add the correct CT header in a plugin like this:
```python
class SoapactionContentType(Plugin):
    def egress(self, envelope, http_headers, operation, binding_options):
        http_headers['Content-Type'] = 'application/soap+xml;charset=UTF-8;action="{}"'.format(operation.soapaction)
        return envelope, http_headers
```

**Comment by mvantellingen** [comment]
Thanks, it seems that SOAP 1.2 requires the action to be set via the Content-Type header instead of the separate SOAPAction header as in 1.1. Fixed that in master. Please let me know if that doesn't work for you.

**Comment by RubenSchmidt** [comment]
I did not work for me. It seems the service i am using demands that the action is wrapped in double qoutes like this: `application/soap+xml;charset=UTF-8;action="actionhere" `. However i don't know if this is just the service that i am using beeing old and stubborn.

**Comment by mvantellingen** [comment]
Ok, i've updated the code to wrap it in double quotes. I can't find ANY official documentation about this, but I saw some examples which also had double quotes. Let me know :-)

**Comment by RubenSchmidt** [comment]
Now it works :) Thank you very much! Yes the documentation is really lacking regarding this..

Thanks again for the great work!

**Comment by naranns** [comment]
I have the same issue in JAVA while I am trying to create SOAP message with SOAP 1.2 content type header where I need to pass action in the header. Any idea how it can work? Below is how I am writing but it doesn't work.
headers.addHeader("Content-Type", "application/soap+xml;charset=UTF-8;action=\"http://URLValue\"");
