### ISSUE TITLE
Getting MIME encapsulation of SOAP Faults

### ISSUE THREAD

**Issue by samwyse** [mvantellingen/python-zeep#212]
In zeep.wsdl.soap, I'm getting response content that looks like an encapsulated MIME object:

```
--uuid:43702d53-5f06-493d-9f1c-b260953076b2
Content-Id: <rootpart*43702d53-5f06-493d-9f1c-b260953076b2@example.jaxws.sun.com>
Content-Type: application/xop+xml;charset=utf-8;type="text/xml"
Content-Transfer-Encoding: binary
<<...>>
--uuid:43702d53-5f06-493d-9f1c-b260953076b2--
```

This is breaking SoapBinding.process_reply() so I've hacked together something to extract the embedded XML and parse that instead.  I'd fork and issue a pull request, but it's all pretty ugly right now.  Does anyone have any suggestions to make this better/more generic?

```
        if response.content.endswith(b'--'):
            end = response.content.rfind(b'--', 0, -2)
            start = response.content.find(b'\r\n\r\n') + 4
            doc = parse_xml(response.content[start:end], recover=True)
        else:
            doc = parse_xml(response.content, recover=True)
```

**Comment by mvantellingen** [comment]
This seems to be XOP, I have no experience with it but @vashek is working on it, see #194

**Comment by mvantellingen** [comment]
Closing this for now (xml/xop work will continue in #194)
