### ISSUE TITLE
zeep uses pretty_print before sending request

### ISSUE THREAD

**Issue by sdpickett** [mvantellingen/python-zeep#216]
Hi,
wsdl/utils.py etree_to_string is hardcoded to use pretty_print=True when generating the soap request. This is causing issues with the way a service I am calling is interpreting information in the header. Is it possible to make this optional?

**Comment by mvantellingen** [comment]
You can subclass the zeep.Transport class and override the post_xml method. See https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/transports.py#L63
