### ISSUE TITLE
Support for POST requests when instantiating a Client

### ISSUE THREAD

**Issue by arijeetmkh** [mvantellingen/python-zeep#218]
When instantiating a `zeep.client.Client`, SalesForce SOAP APIs return the following:

```
HTTPError: 405 Client Error: GET not supported for url: https://test.salesforce.com/some-url
```

I propose that either at the Client level or at the transport level, we get to select a `method` to use when fetching the WSDL file.

I'd be more than happy to contribute.

**Comment by mvantellingen** [comment]
Do you have an example wsdl?

**Comment by arijeetmkh** [comment]
Here is the service definition:

```
    <service name="SforceService">
        <documentation>Sforce SOAP API</documentation>
        <port binding="tns:SoapBinding" name="Soap">
            <soap:address location="https://test.salesforce.com/services/Soap/c/38.0/0DFp00000008Oct"/>
        </port>
    </service>
```

**Comment by mvantellingen** [comment]
Yeah but that is the URL to the endpoint, that indeed requires a POST request. However the client needs to be initiated with the url to the WSDL. That should always be available via a GET request

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
