### ISSUE TITLE
AssertionError: No node found with name ....

### ISSUE THREAD

**Issue by teopost** [mvantellingen/python-zeep#219]
Hi,
  I'm trying to call this WS.

http://crm.wedoit.io/WS_CSTICKETS/CIMWSApplication.asmx?wsdl

this is the code I have write

```python
from zeep import Client
from zeep import xsd

client = Client('http://crm.wedoit.io/WS_CSTICKETS/CIMWSApplication.asmx?wsdl')

print client.service.GetSegnalazione('fake_auth_string', '11628')
```

but I have this error.

`AssertionError:` No node found with name {http://www.progamma.com}GetSegnalazioneSoapOut

Can you help me ?

**Comment by anjingbin** [comment]
yeah, I met the same problem when using the newest version of zeep, is it a bug?

**Comment by mvantellingen** [comment]
Should be fixed in master, let me know if you run into any issues with it

**Comment by teopost** [comment]
Yes! Now works
Thank you.
