### ISSUE TITLE
Unable to resolve attribute xsd:lang. (exchange)

### ISSUE THREAD

**Issue by matteoredaelli** [mvantellingen/python-zeep#220]
I get this error. in attachment the wsdl of microsoft exchange

python3 -mzeep exchange.wsdl

[exchange.wsdl.txt](https://github.com/mvantellingen/python-zeep/files/526449/exchange.wsdl.txt)

**Comment by mvantellingen** [comment]
Do you have the messages.xsd to which the wsdl refers?

**Comment by matteoredaelli** [comment]
here it is

thanks
matteo

[messages.xsd.txt](https://github.com/mvantellingen/python-zeep/files/540938/messages.xsd.txt)

**Comment by mvantellingen** [comment]
And now it is missing types.xsd. Can you check it yourself via ``python -mzeep exchange.wsdl`` ? Thanks!

**Comment by tomas-sk** [comment]
I am experiencing the same issue and hope it will be resolved. Here are all files together:
[types.xsd.txt](https://github.com/mvantellingen/python-zeep/files/569147/types.xsd.txt)
[messages.xsd.txt](https://github.com/mvantellingen/python-zeep/files/569148/messages.xsd.txt)
[services.wsdl.txt](https://github.com/mvantellingen/python-zeep/files/569149/services.wsdl.txt)
Thanks

**Comment by mvantellingen** [comment]
I've just committed a workaround, could you try again and let me know if it turns out to not work?

**Comment by tomas-sk** [comment]
It works, I successfully made some requests to exchange server. Thanks!
