### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by josvromans** [mvantellingen/python-zeep#225]
in zeep/xsd/elements.py line 144, is an error in the string formatting, that will raises the TypeError from the title.

            raise TypeError((
                "Received object of type %r, " +
                "expected %s or etree.Element"
            ) % (type(self.restrict)))

I believe that the '%s or' should be deleted, and only etree.Element is expected. ?

**Comment by mvantellingen** [comment]
Should be fixed now, thanks!
