### ISSUE TITLE
serialize_object doesn't work with an array of lxml.etree._Element

### ISSUE THREAD

**Issue by gregLibert** [mvantellingen/python-zeep#255]
Hi,
I'm having the following error while using serialize_object method on a complex object containing an array of lxml.etree._Element :

>   File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 23, in serialize_object
>     value = serialize_object(value)
>   File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 23, in serialize_object
>     value = serialize_object(value)
>   File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 13, in serialize_object
>     return [serialize_object(sub) for sub in obj]
>   File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 23, in serialize_object
>     value = serialize_object(value)
>   File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 23, in serialize_object
>     value = serialize_object(value)
>   File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 13, in serialize_object
>     return [serialize_object(sub) for sub in obj]
>    File "/home/glibert/code/KYC/Service/Server/.venv/local/lib/python2.7/site-packages/zeep/helpers.py", line 16, in serialize_object
>     value = obj[key]
>   File "src/lxml/lxml.etree.pyx", line 1176, in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:53194)
> TypeError: 'lxml.etree._Element' object cannot be interpreted as an index

Any ideas of the why and how ?

FYI, I temporarily solve this problem by modifying the following function in helpers.py:

```
def serialize_object(obj):
    """Serialize zeep objects to native python data structures"""
    if obj is None:
        return obj

    if isinstance(obj, list):
        return [serialize_object(sub) for sub in obj]

    result = OrderedDict()

    if(isinstance(obj, ET._Element)):
        def recursive_dict(element):
            return element.tag[element.tag.find('}')+1:], dict(map(recursive_dict, element)) or element.text
        return recursive_dict(obj)

    for key in obj:
        value = obj[key]
        if isinstance(value, (list, CompoundValue)):
            value = serialize_object(value)
        result[key] = value
    return result
```

**Comment by mvantellingen** [comment]
Thanks, see ec943552eab180e93a2ddcf473a182315e4c6299
