### ISSUE TITLE
Missing items when parsing Choice

### ISSUE THREAD

**Issue by ri8on** [mvantellingen/python-zeep#257]
- zeep 0.22
- [wsdl.zip](https://github.com/mvantellingen/python-zeep/files/591572/wsdl.zip)
- [script](https://gist.github.com/ri8on/38fcbcbd1edaac2977243b767f10d972)

response type looks like:
```
<xs:element name="getStateResult">
  <xs:complexType>
    <xs:complexContent>
      <xs:extension base="base:BaseAsyncResponseType">
        <xs:choice minOccurs="0">
          <xs:element ref="base:ErrorMessage"/>
          <xs:element name="NsiItem" type="nsi-base:NsiItemType"/>
          <xs:element name="NsiList" type="nsi-base:NsiListType"/>
        </xs:choice>
        <xs:attribute ref="base:version" use="required" fixed="10.0.1.2"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:element>
```

`RequestState` and `MessageGUID` must be present, as defined in `BaseAsyncResponseType`, and one of `ErrorMessage`, `NsiItem` or `NsiList` can be present. However, only one (the first) element is in the output.

In the example the number of elements is limits here:
zeep.xsd.indicators.Choice#parse_xmlelements:
```
        if self.accepts_multiple:
            result = {name: result}
        else:
            result = result[0] if result else {}
```

**Comment by mvantellingen** [comment]
Hi @ri8on, could you give the master branch a try? It should be fixed now. Thanks btw for the all the provided data! :-)

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue

**Comment by 766dt** [comment]
Thanks, the issue now is not reproduced anymore.
I apologize for the delay, and thank you for your work! =)

**Comment by ri8on** [comment]
Thanks, the issue now is not reproduced anymore.
I apologize for the delay, and thank you for your work! =)
