### ISSUE TITLE
Struggling to Login to SOAP service that has a login element

### ISSUE THREAD

**Issue by byoungunf** [mvantellingen/python-zeep#259]
Very cool looking SOAP module for Python :)

I'm trying to use it to query from Blackbaud's Luminate platform and running into some issues logging in.  I need to authenticate and get a sessionID that I can then use to make other queries but I'm struggling with the login.  I think it may be because the Login element is passed in the body of an XML request vs using something like WSEE.  I'm new to SOAP though so that may not be the issue.  I'm getting an error back when I run this of "zeep.exceptions.Fault: Invalid username and/or password" but I've verified the username and password work via SOAPUI.  Thanks for any help you can give!!

1. Version: 0.22
2. WSDL: https://webservices.cluster2.convio.net/1.0/unf/wsdl
3. Code:

from zeep import Client

client = Client('https://webservices.cluster2.convio.net/1.0/unf/wsdl')
sessionID = client.service.Login('username','password')

print(sessionID)

**Comment by mvantellingen** [comment]
I'm unable to open the wsdl due to IP whitelisting

Can you place the soapui request you send and the output of 

```python
from lxml import etree
from zeep import Client

client = Client('https://webservices.cluster2.convio.net/1.0/unf/wsdl')

# client.service.OPERATION_NAME(args, kwargs) becomes
node = client.service._binding.create_message(
    'Login', 'username', 'password')

print(etree.tostring(node, pretty_print=True))
```

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
