### ISSUE TITLE
Unexpected element 'item0', expected u'{http://ws.myhost.com}return'

### ISSUE THREAD

**Issue by eyesoftsys** [mvantellingen/python-zeep#267]
trying to parse below xml and get error : **"Unexpected element"**

using zeep version 0.22.0

getResponse(return: xsd:string[])

this is returned xml  :
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
        <soapenv:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Action>urn:getResponse</wsa:Action>
                <wsa:RelatesTo>urn:uuid:test1234</wsa:RelatesTo>
        </soapenv:Header>
        <soapenv:Body>
                <urn:getResponse xmlns="http://ws.myhost.com">
                        <item0 xmlns="">Header1</item0>
                        <item0 xmlns="">Header2</item0>
                        <item0 xmlns="">Header3</item0>
                        <item0 xmlns="">Header4</item0>
                        <item0 xmlns="">Header5</item0>
                        <item0 xmlns="">Header6</item0>
                        <item0 xmlns="">Header7</item0>
                        <item1 xmlns="">1</item1>
                        <item1 xmlns="">2</item1>
                        <item1 xmlns="">3</item1>
                        <item1 xmlns="">4</item1>
                        <item1 xmlns="">5</item1>
                        <item1 xmlns="">6</item1>
                        <item1 xmlns="">7</item1>
                        <item2 xmlns="">1</item2>
                        <item2 xmlns="">2</item2>
                        <item2 xmlns="">3</item2>
                        <item2 xmlns="">4</item2>
                        <item2 xmlns="">5</item2>
                        <item2 xmlns="">6</item2>
                        <item2 xmlns="">7</item2>
                </getResponse>
        </soapenv:Body>
</soapenv:Envelope>

```

the problem is that a cannot modify output of WS i'm stuck with it.
can do some magic on this ?

 output is something like :

--------------------------------------------------------------------------------------------
| Header1 | Header2 | Header3 | Header4 | Header5 | Header6 | Header7 |
|------------|-------------|------------|------------|-------------|------------|-------------|
|      1       |       2       |      3       |        4     |       5        |      6      |       7        |
|      1       |       2       |      3       |        4     |       5        |      6      |       7        |
--------------------------------------------------------------------------------------------

**Comment by mvantellingen** [comment]
Hi, can you write a test script for me as documented at http://docs.python-zeep.org/en/master/reporting_bugs.html#errors-when-parsing-the-response ?

Thanks!

**Comment by eyesoftsys** [comment]
this is outout of that script :

  File "zeep/wsdl/bindings/soap.py", line 151, in process_reply
  File "zeep/wsdl/bindings/soap.py", line 311, in process_reply
  File "zeep/wsdl/messages/soap.py", line 75, in deserialize
  File "zeep/wsdl/messages/soap.py", line 359, in _deserialize_body
  File "zeep/xsd/elements.py", line 272, in parse
  File "zeep/xsd/types.py", line 318, in parse_xmlelement
zeep.exceptions.XMLParseError: Unexpected element 'item0'

Thanks!

**Comment by mvantellingen** [comment]
But I really need the wsdl file to see why it is an unexpected element. So I need you to attach the script so that I can reproduce it. Otherwise I can't really fix it :)

**Comment by eyesoftsys** [comment]
ok if i understand correctly beside this script you need also access to web service to check and or reproduce if that the case for other reasons i cannot expose this ws and cannot reproduce elsewhere ... so i'm stuck and need to find other solutions ... if that's the case you can close this issue.

anyway here you go

```
#!/usr/bin/env python
import pretend  # pip install pretend

from zeep import Client
from zeep.transports import Transport

# Replace YOUR-WSDL and OPERATION_NAME with the wsdl url
# and the method name you are calling. The response
# needs to be set in the content=""" """ var.

transport = Transport(verify=False, timeout=60, cache=None)

wdslurl = 'https://ws.myhost.com:8443/web/wsTest?wsdl'
client = Client(wsdl=wdslurl, transport=transport)
response = pretend.stub(
    status_code=200,
    headers=[],
    content="""
        <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Action>urn:getResponse</wsa:Action><wsa:RelatesTo>urn:uuid:test1234</wsa:RelatesTo></soapenv:Header><soapenv:Body><getResponse xmlns="http://ws.myhost.com"><item0 xmlns="">Header1</item0><item0 xmlns="">Header2</item0><item0 xmlns="">Header3</item0><item0 xmlns="">Header4</item0><item0 xmlns="">Header5</item0><item0 xmlns="">Header6</item0><item0 xmlns="">Header7</item0><item1 xmlns="">89</item1><item1 xmlns="">121</item1><item1 xmlns="">101</item1><item1 xmlns="">2010</item1><item1 xmlns="">479</item1><item1 xmlns="">449</item1><item1 xmlns="">438</item1></getResponse></soapenv:Body></soapenv:Envelope>
    """)

operation = client.service._binding._operations['getResponse']
result = client.service._binding.process_reply(
    client, operation, response)

print(result)
```

thank you

**Comment by mvantellingen** [comment]
Sorry for my late response. The wsdl isn't available (anymore?). So I can'y really help in this case.

Perhaps it is already solved by a more recent release

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
