### ISSUE TITLE
How to set timestamp and digest

### ISSUE THREAD

**Issue by ovnicraft** [mvantellingen/python-zeep#27]
I want to test this lib as alternative from suds.
I have an specific issue, i need to set wsdl wsse request my specific timestamp and digest (this comes from auth wsdl).

this code from suds for reference: https://gist.github.com/ovnicraft/69dccd4aaf8de09dac91071a3305a28d#file-gistfile1-txt

line 7 and 11 as you see i set nonec and timestamp. I read the code from wsse but not found the way.

any hint around ?

**Comment by mvantellingen** [comment]
Should be possible using the following:

```python
from zeep import Client
from zeep.wsse.username import UsernameToken

client = Client(
    wsdl, wsse=UsernameToken(CEDULA, response.Digest, use_digest=True))
```
See https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/wsse/username.py#L84. Or do you need to supply custom values to the none/created/exired headers?

**Comment by ovnicraft** [comment]
I check your code, and yes i need to pass custom values for date, nonce, digest.

**Comment by mvantellingen** [comment]
Just update the UsernameToken class to accept nonce, created, and password_digest kwargs

Let me know if any more problems arise :)

**Comment by ovnicraft** [comment]
@mvantellingen great i will check it
