### ISSUE TITLE
How to set namespace in Element

### ISSUE THREAD

**Issue by shaukat72** [mvantellingen/python-zeep#271]
I'm having an issue when using zeep-python, I want to add ns0 to the elements in which its is missing.

**My python test code:**

    # these are the header elements
    username = 'myusername'
    password = 'mypassword'
    header = xsd.Element(
        'HeaderSession',
        xsd.ComplexType([
            xsd.Attribute(
                'username', xsd.String()
            ),
            xsd.Attribute(
                'password', xsd.String()
            ),
            xsd.Attribute(
                'CodeService', xsd.String()
            )
        ])
    )

    header_value = header(
        username=username,
        username=password,
        CodeService='AB1234',
        
	
    # These are the body elemets
    MyTest = xsd.Element(
        'MyTest',
        xsd.ComplexType([
            xsd.Sequence([
                xsd.Element(
                'MyTests_IN',
                xsd.ComplexType([
                    xsd.Attribute(
                        'CodeService', xsd.String()
                        )
                    ]),
                min_occurs=1,
                max_occurs="unbounded"
                )
            ])
        ])
    )
    MyTest_value = MyTest(
        MyTests_IN=['AB1234']
    )

    history = HistoryPlugin()
    header_plugin = LoggingPlugin()
	
    client = Client(
        'https://localhost/AccesEntrpr/Z1/Annuaire.asmx?WSDL',
        plugins=[history, header_plugin])

    client.service.MyUrlsServices(_soapheaders=[header_value] ,MyTest=MyTest_value)
	
**Here's the output :**

&lt;soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"&gt;
  &nbsp;&lt;soap-env:Header&gt;
    &nbsp;&nbsp;&nbsp;&lt;HeaderSession username="myusername" username="mypassword" CodeService="AB1234"/&gt;
  &nbsp;&lt;/soap-env:Header&gt;
  &nbsp;&lt;soap-env:Body&gt;
    &nbsp;&nbsp;&nbsp;&lt;ns0:MyUrlsServices xmlns:ns0="http://localhost/Z1B/04222911/Annuaire"&gt;
      &nbsp;&nbsp;&nbsp;&nbsp;&lt;ns0:MyTest&gt;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;MyTests_IN CodeService="AB1234"/&gt;
      &nbsp;&nbsp;&nbsp;&nbsp;&lt;/ns0:MyTest&gt;
    &nbsp;&nbsp;&nbsp;&lt;/ns0:MyUrlsServices&gt;
  &nbsp;&nbsp;&lt;/soap-env:Body&gt;
&lt;/soap-env:Envelope&gt;

**The missing ns0 is in:**

&lt;ns0:MyTest&gt;
	&nbsp;&nbsp;&lt;MyTests_IN CodeService="AB1234"/&gt;
&lt;/ns0:MyTest&gt;

so in code (&lt;MyTests_IN CodeService="AB1234"/&gt;) the ns0 is missing. It should be like &lt;ns0:MyTests_IN CodeService="AB1234"/&gt;

Any help would be appreciated

**Comment by mvantellingen** [comment]
If you want to set a namespace then you can do the following:

```python
header = xsd.Element(
    '{http://localhost/Z1B/04222911/Annuaire}HeaderSession',
    xsd.ComplexType([
        xsd.Attribute(
            '{http://localhost/Z1B/04222911/Annuaire}username', xsd.String()
        ),
        xsd.Attribute(
            '{http://localhost/Z1B/04222911/Annuaire}password', xsd.String()
        ),
        xsd.Attribute(
            '{http://localhost/Z1B/04222911/Annuaire}CodeService', xsd.String()
        )
    ])
)
```

So when creating the xsd objects you will need to pass in full qname's instead of only the localname

**Comment by icduicdu** [comment]
The code:
```
header = zeep.xsd.Element(
            '{http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd}Security',
            zeep.xsd.ComplexType([
                zeep.xsd.Element(
                    'UsernameToken',
                    zeep.xsd.ComplexType([
                        zeep.xsd.Element('Username',zeep.xsd.String()),
                    ])
                ),
            ])
        )
```

Created this:

> <ns0:Security xmlns:ns0="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">...

But i need this:
<o:Security xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">...

What i need to do?

Thank you in advance!

**Comment by olegeech** [comment]
Same question, I need "<v4:ClientInformation..." but got "<ns0:ClientInformation...".

**Comment by diegoug** [comment]
@mvantellingen I have the same issue when forming the body, do you have any suggestion?

```
<soap-env:Body
        xmlns:ns0="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        ns0:Id="id-436e2b27-9eee-4976-b0fc-b1543e3096bf">
```

but I need is this:

```
<soap-env:Body
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        wsu:Id="id-436e2b27-9eee-4976-b0fc-b1543e3096bf">
```

I was reviewing the code that signs and that happens on line 280 of signature.py, but it does so automatically, I can not see where I can change ns0 by wsu

`ctx.register_id(target, 'Id', ns.WSU)`

**Comment by ayatsss** [comment]
`client.set_ns_prefix('wsu', namespace)` ?

**Comment by karstengo** [comment]
Same here
getting ns0 too. But i need the other namespace only in the header for one element.

**Comment by uuip** [comment]
settings = Settings(strict = False, xml_huge_tree = True)
        client = Client(wsdl_path, transport = self.transport, wsse = self.wsse,settings = settings)
        client.set_ns_prefix(ns_prefix,namespace)
        service = client.create_service('{{{}}}{}'.format(namespace, binding_name), xaddr)


I soloved this , no ns0 appear again.

**Comment by chirag82** [comment]
> Sorry to revive this but anyone got the solution for that prefix ns0 issue?

Any solution anyone got? Please share..

**Comment by uuip** [comment]
`<xs:schema xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
           xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"
           targetNamespace="http://www.onvif.org/ver10/schema" elementFormDefault="qualified" version="18.06">`

import zeep
from zeep import Client, Settings, Transport
from zeep.cache import SqliteCache
from zeep.wsse import UsernameToken

    def __init__(self, ip, port, username, password):
        self.transport = Transport(cache = SqliteCache())
        self.transport.operation_timeout = 10
        if username:
            self.wsse = UsernameToken(username, password, use_digest = True)
        else:
            self.wsse = None
def creta_service(self,a,b,c)
        settings = Settings(strict = False, xml_huge_tree = True)
        client = Client(wsdl_path, transport = self.transport, wsse =self.wsse, settings = settings)
        client.set_ns_prefix(ns_prefix, namespace)
So, this weill fill with the right ns: for example:
        client.set_ns_prefix('tt', 'http://www.onvif.org/ver10/schema')
        client.set_ns_prefix('xs', "http://www.w3.org/2001/XMLSchema")
