### ISSUE TITLE
How to represent a SOAP envelope element with multiple attributes?

### ISSUE THREAD

**Issue by mmesnjak** [mvantellingen/python-zeep#272]
Hi,

Btw, great SOAP client, simple and elegant.

I can't find this in the documentation so maybe you can point me in the right direction...
I need to create a part of the SOAP envelope that looks like this (taken from the SoapUI):
```
<supportedServices>
      <!--1 or more repetitions:-->
      <service vn="?" serviceClass="?"/>
</supportedServices>
```

I'm using plain python structures to pass to the service method call:
```
CCG_DATA = {
        'entityId': 'G13 12C S2 20-RTN CG',
        'lowerFreqHz': 6214000000,
        'upperFreqHz': 6227000000,
        'supportedServices': [
            {'vn': vnv.testVnName, 'serviceClass': sv.serviceName}
        ],
        'satelliteBandId': sbv.satBandName
}
```
but that does not work since this is the envelope that gets created:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:provisionCarrierCapacityGroup xmlns:ns0="http://ntc.nms.slm.hub.provisioning">
      <carrierCapacityGroup>
        <entityId>G13 12C S2 20-RTN CG</entityId>
        <lowerFreqHz>6214000000</lowerFreqHz>
        <upperFreqHz>6227000000</upperFreqHz>
        <satelliteBandId>testBand1</satelliteBandId>
        <supportedServices>
          <service/>
        </supportedServices>
      </carrierCapacityGroup>
    </ns0:provisionCarrierCapacityGroup>
  </soap-env:Body>
</soap-env:Envelope>
```
so the `service` tag does not include any attributes.

How can I represent such input? Do I need to use a factory method? An example, please.

**Comment by mmesnjak** [comment]
I examined the wsdl dump from `client.wsdl.dump()`
[wsdl.dump.txt](https://github.com/mvantellingen/python-zeep/files/624203/wsdl.dump.txt)
and adjusted my input structure like this:
```
    {
        'entityId': 'G13 12C S2 20-RTN CG',
        'lowerFreqHz': 6214000000,
        'upperFreqHz': 6227000000,
        'satelliteBandId': sbv.satBandName,
        'supportedServices': {
            'service': [
                {'vn': vnv.testVnName, 'serviceClass': sv.serviceName}, 
                {'vn': vnv.testVnName, 'serviceClass': sv.serviceName} 
            ] 
        }
    }
```

but still a no-go :(

I need to find out if this is even possible to achieve the way I started or do I need to change course completely.

**Comment by mvantellingen** [comment]
Can you give master and the latest released version a change? Fixed some stuff which might also make this one work

**Comment by mvantellingen** [comment]
I'm closing this ticket for now as it should be fixed. If there are still any issues then please let me know so that I can re-open the issue.
