### ISSUE TITLE
Missing files in tarball on pypi

### ISSUE THREAD

**Issue by mbehrle** [mvantellingen/python-zeep#275]
While packaging python-zeep for Debian the following files were missing from the zeep-0.23.0.tar.gz tarball on pypi (needed for running the tests):

+++ python-zeep/tests/wsdl_files/soap-enc.xsd
+++ python-zeep/tests/wsdl_files/test_import_2.xsd	
+++ python-zeep/tests/wsdl_files/soap_import_2.wsdl	
+++ python-zeep/tests/wsdl_files/soap_import_main.wsdl	

Could you please include them?

Thanks!

**Comment by mvantellingen** [comment]
Added to the manifest (which was actually not even there..)
