### ISSUE TITLE
Failing wsdl inspection with unknown transports

### ISSUE THREAD

**Issue by nyov** [mvantellingen/python-zeep#277]
`python -mzeep 'api/wsdl'` fails with
`NotImplementedError: Only soap/http is supported for now`.

Sadly this error message is rather useless without digging through the source code! It could at least say what it encountered instead ;)
In my case it could have said `Transport 'http://schemas.microsoft.com/soap/tcp' is unsupported`.

But mainly, this behavior seems counter to having multiple transport bindings, when the client fails on the first thing it _doesn't_ understand.

The WSDL (excerpt) in this case looks something like
```xml
<wsdl:binding name="BasicHttpBinding_IPublicInterfaceServiceContract" type="tns:IPublicInterfaceServiceContract">
	<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
	<wsdl:operation name="abc"></wsdl:operation>
</wsdl:binding>

<wsdl:binding name="NetTcpBinding_IPublicInterfaceServiceContract" type="tns:IPublicInterfaceServiceContract">
	<wsp:PolicyReference URI="#NetTcpBinding_IPublicInterfaceServiceContract_policy"/>
	<soap12:binding transport="http://schemas.microsoft.com/soap/tcp"/>
	<wsdl:operation name="abc"></wsdl:operation>
</wsdl:binding>
```

While I'm not too knowledgeable in the world of SOAP, I think the client should just skip the unknown and continue with the transport that _does_ define `soap/http`, here.

As I now need to get this manually, I also lament the shortness of the "Non-default bindings" docs section. A code example there would be nice!

**Comment by nyov** [comment]
Actually I just noticed I can't even get to the stage of using the other binding manually.
Just instancing `Client('api/wsdl')` is enough to throw the exception. Now this seems even more serious.
Looks like I have to chew and spoonfeed the WSDL to the client, for the time being.

**Comment by mvantellingen** [comment]
> python -mzeep 'api/wsdl' fails with
> NotImplementedError: Only soap/http is supported for now.
> 
> Sadly this error message is rather useless without digging through the source code! It could at least say what it encountered instead ;)
> In my case it could have said Transport 'http://schemas.microsoft.com/soap/tcp' is unsupported.

Yes agreed, pull-requests are more then welcome :-)

> While I'm not too knowledgeable in the world of SOAP, I think the client should just skip the unknown and continue with the transport that does define soap/http, here.

Yup also agreed,  I will also accept happily accept a pull-request for this.

> As I now need to get this manually, I also lament the shortness of the "Non-default bindings" docs section. A code example there would be nice!

Yeah the documentation is lacking. Still hoping to fix this some time but most of my time currently goes into solving issues.

**Comment by nyov** [comment]
> Yup also agreed, I will also accept happily accept a pull-request for this.

Okay, I looked. But there seems to be so much indirection, I couldn't quite figure out where this stuff happens. Very smoke and mirrors :)
Sorry, actually fell asleep while working on it. I may have to try again some other time.

**Comment by mvantellingen** [comment]
fixed in master

**Comment by nyov** [comment]
Thank you!
