### ISSUE TITLE
ValueError on optional choice

### ISSUE THREAD

**Issue by ri8on** [mvantellingen/python-zeep#279]
- zeep 0.22
- [wsdl](https://github.com/mvantellingen/python-zeep/files/591572/wsdl.zip)
- [script](https://gist.github.com/ri8on/5827884dd4207a2bc9d4b8ea9d45ca83)

I got an exception during envelope creation: `ValueError: max() arg is an empty sequence`
Exception raised in `zeep.xsd.indicators.Choice#accept`, on optional `choice` element rendering.

UPD: Run it on v0.23 and got the same result

**Comment by mvantellingen** [comment]
Should be fixed in master (see commit). If not can you let me know (i'll reopen the issue in that case)
