### ISSUE TITLE
Spyne Interop

### ISSUE THREAD

**Issue by plq** [mvantellingen/python-zeep#280]
Hello!

Spyne author here. I take SOAP compatibility seriously, so try to run as many tests as I can against different client libraries.

I'm here to tell you that I just ported our SUDS tests to ZEEP. I'm happy to report that it's working mostly OK. I added comments where I think ZEEP should improve things in the test module that I gave the link below.

Let me know whether there is anything else I can do. Pull requests for zeep tests are most welcome!

Happy hacking!

PS: Here is the info you requested:

1. The version of zeep: 0.23
2. The WSDL you are using: https://github.com/arskom/spyne/blob/ae3c2b88808b2f11e558d2d3bb7ddb8a594a837c/spyne/test/wsdl.xml
3. An example script: https://github.com/arskom/spyne/blob/ae3c2b88808b2f11e558d2d3bb7ddb8a594a837c/spyne/test/interop/test_zeep.py

Here is the link that always points to the latest zeep test results: https://spyne.ci.cloudbees.com/job/spyne/PYFLAV=cpy-2.7/lastCompletedBuild/testReport/spyne.test.interop.test_zeep/TestZeep/

**Comment by mvantellingen** [comment]
Hi!,

Thanks!! Really cool stuff. I'll be fixing these issues asap and will send a PR with the updated tests when all tests pass.

Relevant commits:
 - f44256c36ae3171638a7d9f0f66a79362bca842b (microsecond support)
 - 7811753e2b7324ea11d2e96dbcaa1dfdbdd90b8a (don't modify values when passed to ops)
 - 46531f489d228d2b43b05b0b9e3fdfb5114a41b0 (don't modify values when passed to ops)

**Comment by mvantellingen** [comment]
Just released 0.24 with the changes
