### ISSUE TITLE
No support for nested elements and namespaces

### ISSUE THREAD

**Issue by AlmightyOatmeal** [mvantellingen/python-zeep#288]
It's unfortunate that Zeep doesn't support nested elements in the same fashion that lxml etree does. I've been struggling for several hours trying to setup a simple soap authentication header of <SessionHeader><session>...</session></SessionHeader>. Each and every time I've tried, I get:

```
ValueError: Invalid value given to _soapheaders
```

And I can't simple create an element and append it to another one.

I can't add an appropriate namespace to the <session> element either. This is immensely frustrating and disappointing. Why not leverage more of lxml's power instead of writing your own classes? My personal preference is lxml's objectify rather than etree.

PS,
`set_default_soapheaders` has no documentation within it so I have absolutely no idea what type 'headers' is supposed to be. It's rather painful to have to go and reverse engineer everything just to do something simple.

**Comment by mvantellingen** [comment]
Hi, thanks. Your tone is also immensely frustrating and disappointing ;-)

Try again later

**Comment by AlmightyOatmeal** [comment]
How are you not embarrassed by that response? I've reported a number of issues and you closed this without considering any of them with some issues being serious initial design flaws. With that in mind, I am not going to commit my changes for customizing SSL contexts that are beneficial for use with services that disabled TLS 1.0. I was more than willing to help fix, with your assistance, but I am going to leave this project as-is and use a different project.
