### ISSUE TITLE
Nested Type is send as "pretty print" of Python Structure

### ISSUE THREAD

**Issue by cheuel-novero** [mvantellingen/python-zeep#29]
I try to set a nested Type with Python Zeep. But the send Content to the Server seems to be the Pretty Print from Python of the Structure. Specifically I try to do a "setCustomField" of the [WSDL](http://almdemo.polarion.com/polarion/ws/services/TrackerWebService?wsdl):

```python
edp = Client(url, username, password)
edp.service.getCustomField(uri, "solution")

new_value_type = edp.get_type("{http://ws.polarion.com/types}Text")                                                                                                                                       
val = new_value_type(type = "text/html", content="This is a first Test", contentLossy=False)                                                                                                                         
new_solution_type = edp.get_type("{http://ws.polarion.com/TrackerWebService-types}CustomField")                                                                                                           
sol = new_solution_type(key="solution", parentItemURI=uri, value=val)                                                                                                                                           

edp.service.setCustomField(sol, _soapheader=sh)             
```

And here the content of the Packet send to the server:

```
<soap-env:Envelope xmlns:ns0="http://ws.polarion.com/TrackerWebService-impl" xmlns:ns1="http://ws.polarion.com/types" xmlns:ns2="http://ws.polarion.com/TrackerWebService-types" xmlns:ns3="http://ws.polarion.com/ProjectWebService-types" xmlns:ns4="http://ws.polarion.com/PlanningWebService-types" xmlns:ns5="http://ws.polarion.com/TrackerWebService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soap-env:Header><pols:sessionID xmlns:pols="http://ws.polarion.com/session">2803906303964766973</pols:sessionID></soap-env:Header>
<soap-env:Body>
<ns0:setCustomField>
<ns0:customField>
<ns2:parentItemURI>subterra:data-service:objects:/default/sw${WorkItem}LI-66</ns2:parentItemURI><ns2:key>solution</ns2:key>
<ns2:value>{   'content': 'This is a first Test',
    'contentLossy': False,
    'type': 'text/html'}</ns2:value>
</ns0:customField>
</ns0:setCustomField>
</soap-env:Body>
</soap-env:Envelope>
```

The server responds then "Value can't be null". As it seems, the value is only a pretty print of the Python structure.

Am I doing something wrong, when I construct the structure with Zeep?

**Comment by mvantellingen** [comment]
Just a quick initial guess: The value is an anyType, can you use the following: http://docs.python-zeep.org/en/latest/#any-objects (that is wrap the value in an xsd.anyObject)

**Comment by cheuel-novero** [comment]
I changed the code so that I use the AnyObject class, but still does not convert it to the correct values:

```python
new_value_type = edp.get_type("{http://ws.polarion.com/types}Text")

any_val = xsd.AnyObject(new_value_type, new_value_type(type = "text/html", content="This is a first Test", contentLossy=False))
new_solution_type = edp.get_type("{http://ws.polarion.com/TrackerWebService-types}CustomField")

sol = new_solution_type(key="solution", parentItemURI=uri, value=any_val)
edp.service.setCustomField(sol)
```
The send packet looks like this:
```
<ns0:setCustomField>
<ns0:customField>
<ns2:parentItemURI>subterra:data-service:objects:/default/sw_team_linux${WorkItem}SWTLI-664</ns2:parentItemURI>
<ns2:key>solution</ns2:key>
<ns2:value>&lt;zeep.xsd.types.AnyObject object at 0x7f995e4f89b0&gt;</ns2:value>
</ns0:customField>
</ns0:setCustomField>
```

**Comment by mvantellingen** [comment]
So the issue was that I used xsd.String() as default type for elements while it should have been anyType (ur-type).

This seems to generate valid xml:

```python
import zeep
from lxml import etree
from zeep import xsd

client = zeep.Client('http://almdemo.polarion.com/polarion/ws/services/TrackerWebService?wsdl')
new_value_type = client.get_type("{http://ws.polarion.com/types}Text")
value = xsd.AnyObject(
    new_value_type,
    new_value_type(type="text/html", content="This is a first Test", contentLossy=False))

new_solution_type = client.get_type("{http://ws.polarion.com/TrackerWebService-types}CustomField")
sol = new_solution_type(
    key='solution',
    parentItemURI='subterra:data-service:objects:/default/sw${WorkItem}LI-66',
    value=value)

# Dump the message which would be created
node = client.service._binding.create_message('setCustomField', sol)
print(etree.tostring(node, pretty_print=True))
```

**Comment by cheuel-novero** [comment]
I tried the master branch, but it gives me an error:

  File "/usr/lib/python3/dist-packages/zeep/wsdl/definitions.py", line 224, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/zeep/wsdl/messages.py", line 70, in serialize
    self.body.render(body, body_value)
  File "/usr/lib/python3/dist-packages/zeep/xsd/elements.py", line 99, in render
    return self.type.render(node, value)
  File "/usr/lib/python3/dist-packages/zeep/xsd/types.py", line 130, in render
    element.render(parent, sub_value)
  File "/usr/lib/python3/dist-packages/zeep/xsd/elements.py", line 99, in render
    return self.type.render(node, value)
  File "/usr/lib/python3/dist-packages/zeep/xsd/types.py", line 130, in render
    element.render(parent, sub_value)
  File "/usr/lib/python3/dist-packages/zeep/xsd/elements.py", line 99, in render
    return self.type.render(node, value)
  File "/usr/lib/python3/dist-packages/zeep/xsd/builtins.py", line 444, in render
    parent.text = self.xmlvalue(value)
  File "src/lxml/lxml.etree.pyx", line 1031, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:55347)
  File "src/lxml/apihelpers.pxi", line 711, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:24667)
  File "src/lxml/apihelpers.pxi", line 699, in lxml.etree._createTextNode (src/lxml/lxml.etree.c:24516)
  File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src/lxml/lxml.etree.c:32414)
TypeError: Argument must be bytes or unicode, got 'Text'

**Comment by mvantellingen** [comment]
Did you wrap the Text type in an AnyObject() like in my code snippet?

Error message should be more helpful nonetheless :-)

**Comment by cheuel-novero** [comment]
Arg, sorry, no, I didn't. I thought I didn't change my code.
Wrapping it with AnyObject fixes this. Thanks!

Is this somehow related to #17 ?
