### ISSUE TITLE
Zeep not working on Openshift

### ISSUE THREAD

**Issue by pmesgari** [mvantellingen/python-zeep#292]
Hi,

I am using zeep 0.24.0, the program works perfectly on localhost, not when used on Openshift
The code I tried:
```

import zeep

wsd="mywsdl"
client = zeep.Client(wsdl=wsdl)
```

The error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/openshift/585c2e2989f5cf184c000007/python/virtenv/venv/lib/python3.3/site-packages/zeep/client.py", line 84, in __init__
    self.transport = transport or Transport()
  File "/var/lib/openshift/585c2e2989f5cf184c000007/python/virtenv/venv/lib/python3.3/site-packages/zeep/transports.py", line 29, in __init__
    self.cache = SqliteCache() if cache is NotSet else cache
  File "/var/lib/openshift/585c2e2989f5cf184c000007/python/virtenv/venv/lib/python3.3/site-packages/zeep/cache.py", line 74, in __init__
    self._db_path = path if path else _get_default_cache_path()
  File "/var/lib/openshift/585c2e2989f5cf184c000007/python/virtenv/venv/lib/python3.3/site-packages/zeep/cache.py", line 152, in _get_default_cache_path
    os.makedirs(path)
  File "/opt/rh/python33/root/usr/lib64/python3.3/os.py", line 258, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/rh/python33/root/usr/lib64/python3.3/os.py", line 269, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/openshift/585c2e2989f5cf184c000007/.cache'

```

**Comment by nyov** [comment]
Looks like `SqliteCache` has no permission to create a database on your system.

This is also something I dislike: That a library tries to create files on the filesystem.
IMHO that should only happen when the user explicitly requested it.
Default HTTP Cache class should be `InMemoryCache`, `SqliteCache` only if the user instanced it that way.

**Comment by pmesgari** [comment]
Yes true! I have found a temporary solution to make it work on Openshift. Here it is:
1. Do not use pip install zeep in the requirements, setup.py or even locally on the server.
2. Download the source zeep from here on Github
3. Copy the zeep folder inside src, where the __init__.py file is included to your git location used for Openshift.
4. In cache.py comment out the path and change it to a location with write permissions:
```
def _get_default_cache_path():
    #path = appdirs.user_cache_dir('zeep', False)
    path = 'path/to/location/where/you/have/write/permissions'
    try:
        os.makedirs(path)
    except OSError as exc:
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else:
            raise
    return os.path.join(path, 'cache.db')
```

This is quite an important issue once people use Zeep anywhere other than local dev machine. I use Zeep on a daily basis, using a heavy SOAP ERP, and it works like a charm. So it is a pity when an issue like this renders Zeep useless on a PAAS such as Openshift!

I hope to hear something back from @mvantellingen , and let me know if this temporary solution is a right thing to do without damaging the rest of the package.

**Comment by mvantellingen** [comment]
This seems to be more a documentation issue then something else. I will think about chaging the default caching, but for now it is so easy to adjust that it shouldn't be a problem for the few users who don't want this.

The path to the sqlite db is easy to adjust via https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/cache.py#L61 (but this should be documented better).

So this can be easily solved via:

```python
import zeep
from zeep.cache import SqliteCache

transport = zeep.Transport(cache=SqliteCache(path='/some-path/cache.db'))
client = zeep.Client('your.wsdl', transport=transport)
```

I'm also have to ask to exaggerate a bit less. Calling this module useless because you run into a small issue is not really encouraging me to provide (free) help.

**Comment by pmesgari** [comment]
Thanks for your help. Firstly I like to mention I, as one of the users of Zeep, certainly appreciate your work, and I stated that Zeep does work like a charm. This is indeed a small issue for you as the developer, for me as the user, it brings my work to a complete stop when my entire backend is developed based on Zeep. so I hope there is no misunderstanding here, we appreciate your free help and having Zeep

**Comment by mvantellingen** [comment]
FYI: Caching is now disable in master and needs to be explicitly enabled
