### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by grguthrie** [mvantellingen/python-zeep#295]
I tried to install zeep, and followed instructions to install required tools tools ( pip install --upgrade setuptools; and https://wiki.python.org/moin/WindowsCompilers ), but trying

>  "pip install zeep"

still fails with "_Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?_," which pip cannot find.

> Collecting libxml2
>   Could not find a version that satisfies the requirement libxml2 (from versions: )
> No matching distribution found for libxml2

Is there a simple procedure to install ZEEP for Python-3?

**Comment by RichardRirie** [comment]
This might help https://github.com/mvantellingen/python-zeep/issues/201

**Comment by grguthrie** [comment]
Thank you - but it didn't work for me;
I downloaded:

>  (Libxml-python are bindings for the libxml2 and libxslt libraries.
>     libxml2_python‑2.9.3‑cp27‑none‑win32.whl)

and ran:
> pip install libxml2_python-2.9.3-cp27-none-win_amd64.whl
> libxml2_python-2.9.3-cp27-none-win_amd64.whl is not a supported wheel on this platform.

**Comment by grguthrie** [comment]
Hmm, not sure why this became closed - it was not resolved.

**Comment by mvantellingen** [comment]
See updated docs: http://docs.python-zeep.org/en/master/#installation

**Comment by grguthrie** [comment]
Thank you – but it still fails.

Trying simplest approach:

    pip install zeep

It finally fails with:
     …
       C:\Users\guthrie\AppData\Local\Temp\xmlXPathInitysnbhf_v.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

So then trying:

   pip install lxml==3.7.1 zeep

it fails with:
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for lxml

Trying to remedy this:
>pip install libxslt
Collecting libxslt
  Could not find a version that satisfies the requirement libxslt (from versions: )
No matching distribution found for libxslt

>pip install libxml2
Collecting libxml2
  Could not find a version that satisfies the requirement libxml2 (from versions: )
No matching distribution found for libxml2

So I tried to download the lxml package, but the most recent seems to be for Python 3.5, but I am running (the default current version) 3.6,
>pip install lxml-3.7.1-cp35-cp35m-win_amd64.whl
lxml-3.7.1-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

>python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32

Maybe I need to build from source, I’ll have to check into how to do this if necessary, but I was hoping for a simple “pip install” with the current python version, and have gotten into a bit more than familiar territory for me!

Thanks for the help, sorry if I am missing somethgn simple here!

**Comment by grguthrie** [comment]
Ah!
I found a 3.6 version of (lxml-3.7.1-cp36-cp36m-win_amd64.whl), and it installed easily, and then zeep also installed easily - Yeah! 
My problems were just in finding compatible versions of the libraries (pip couldn't find them apparently.)
Now to try to use it!  :-)
