### ISSUE TITLE
Simple WSDL query?

### ISSUE THREAD

**Issue by grguthrie** [mvantellingen/python-zeep#297]
I want to do a simple thing;
what is the python version of the command line:
     user>  python -mzeep http://www.soapclient.com/xml/soapresponder.wsdl

> # Try the Demo web service
> wsdl = 'http://www.soapclient.com/xml/soapresponder.wsdl'
> client = zeep.Client(wsdl=wsdl)
> print(client.service.???())

And is this a standard SOAP service for any server to query its WSDL?

**Comment by mvantellingen** [comment]
Sorry, I have no idea what you mean

**Comment by grguthrie** [comment]
Thanks. I had only meant - is there a way programmatically (e.g. in Python) to list the wsdl in the same manner that the example command-line does.

**Comment by vstoykov** [comment]
@grguthrie  what I found is that you can do the following:
```
wsdl = 'http://www.soapclient.com/xml/soapresponder.wsdl'
client = zeep.Client(wsdl=wsdl)
client.wsdl.dump()
```
This will print the same info that is printed when you execute:
```
python -mzeep http://www.soapclient.com/xml/soapresponder.wsdl
```
You can reed the source to see how different parts of the information are taken
https://github.com/mvantellingen/python-zeep/blob/1668fe1b0a75a161b88421a52ad45a3e07db8aee/src/zeep/wsdl/wsdl.py#L73-L115

**Comment by grguthrie** [comment]
Thank you.

  ---------------------------------
|    Dr. Gregory Guthrie         |
  ---------------------------------

**Comment by singhrajkr** [comment]
@mvantellingen  @vstoykov 
Do we have any way to get the dump output to a variable?

**Comment by urosdigital** [comment]
@singhrajkr same here, looking for a way how to do it... 
@mvantellingen @vstoykov any feedback here maybe?
