### ISSUE TITLE
TypeError: 'long' object is not iterable

### ISSUE THREAD

**Issue by CrabbyPete** [mvantellingen/python-zeep#298]
I am using the helper.serialize_object and I get the exception above when I try and serialize what I am getting 

Its because I have an element that has a list
    'deliveryData': {
        'units': [
            0L,
            0L,
            0L,
            0L,
            0L,
            0L,
            0L
        ]
    },

**Comment by CrabbyPete** [comment]
This will fix it 

```
def serialize_object(obj):
    """Serialize zeep objects to native python data structures"""
    if obj is None:
        return obj

    if isinstance(obj, etree._Element):
        return obj

    if isinstance(obj, list):
        return [serialize_object(sub) for sub in obj]

    result = OrderedDict()
    try:
        for key in obj:
            value = obj[key]
            if isinstance(value, (list, CompoundValue)):
                value = serialize_object(value)
            result[key] = value
    except TypeError as e:
        pass
    
    return result

```

**Comment by mvantellingen** [comment]
Can you give master a try? Refactored the serialize_object() method

**Comment by CrabbyPete** [comment]
Sure. I will look at it shortly. 
Thanks

**Comment by mvantellingen** [comment]
I'm closing this ticket for now as it should be fixed. If there are still any issues then please let me know so that I can re-open the issue.
