### ISSUE TITLE
Error parsing SOAP response with Salesforce Enterprise WSDL

### ISSUE THREAD

**Issue by nrawling** [mvantellingen/python-zeep#303]
Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)

0.24.0

2. The WSDL you are using

**https://gist.github.com/nrawling/30f5f0b3318321628d34bf0f9b18290b**

3. An example script

**https://gist.github.com/nrawling/56d87fae8323edf44d92f9c08c46e984**

This gives me a traceback with this output:

zeep.exceptions.XMLParseError: Unexpected element u'{urn:enterprise.soap.sforce.com}metadataServerUrl', expected u'{urn:enterprise.soap.sforce.com}created'

This is different from the error I get when I run this in my regular script, but it is similar:

zeep.exceptions.XMLParseError: Unexpected element u'{urn:enterprise.soap.sforce.com}LimitInfoHeader', expected u'{urn:enterprise.soap.sforce.com}DebuggingInfo'

I've tried using the "Partner" Salesforce WSDL instead (which is much simpler), but I get similar problems parsing responses.

Thank you for all of your work on Zeep. It's working great for my Cvent integration, but the Salesforce WSDL seems to trip things up.

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by nrawling** [comment]
Sorry. I had embedded both the WSDL and script from gist, but it's my first time using it. I've updated the URLs in the original comment.

**Comment by mvantellingen** [comment]
The example script calls the 'upsert' operation but provides the response of a 'login' operation. That doesn't seem correct. If i change the operation in the script to 'login' everything works fine. Are you really receiving a login response from the server when you call upsert? That seems like a bug on the server end in that case ?

**Comment by nrawling** [comment]
Well, that explains why I wasn't getting the correct error. I pasted the wrong response into the example script. I apologize for wasting your time.

Here is a new example script, which has the correct response in it:

https://gist.github.com/nrawling/955d4cda8f4e6c54576bdeed59c5c85f

Thanks again for all of your hard work on this project.

**Comment by mvantellingen** [comment]
This seems to be fixed in the latest release, could you give that a try?

**Comment by nrawling** [comment]
I confirm, this is fixed. Thank you so much!

**Comment by mvantellingen** [comment]
Thanks for confirming :-)

**Comment by yhbk12** [comment]
@nrawling you mentioned you did a CVent integration with Zeep. I'm trying to do that exact thing right now and struggling...do you have any example code you might want to share? Thanks in advance.

**Comment by chiholee** [comment]
@yhbk12 
Here some sample code that i hav ehope this helps you.

wsdl = 'https://api.cvent.com/soap/V200611.ASMX?WSDL'
client = zeep.Client(wsdl=wsdl)
LoginResult = client.service.Login('ORGID', 'USERNAME', 'PASSWORD')
CventSessionValue = LoginResult.CventSessionHeader
sendSoap = client.set_default_soapheaders({'CventSessionHeader':CventSessionValue})
client.service.Retrieve(ObjectType='Event', Ids="XXXXXX")
