### ISSUE TITLE
Error: Input string was not in a correct format.

### ISSUE THREAD

**Issue by jmwoloso** [mvantellingen/python-zeep#309]
Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep : 0.23.0
2. The WSDL you are using: (`bookingwebservice.asmx.wsdl.txt`; see attached)
3. An example script: (see attached)
4. Also attached: envelope and error response
[soap_demo.py.txt](https://github.com/mvantellingen/python-zeep/files/712131/soap_demo.py.txt)
[last_envelope_sent.txt](https://github.com/mvantellingen/python-zeep/files/712132/last_envelope_sent.txt)
[error_response.txt](https://github.com/mvantellingen/python-zeep/files/712133/error_response.txt)
[bookingwebservice.asmx .wsdl.txt](https://github.com/mvantellingen/python-zeep/files/712117/bookingwebservice.asmx.wsdl.txt)

I believe the input should be sent as a string, but it appears that the value is actually sent as an Int when enclosed in the envelope. You can see on line 283 of the attached python script that I assign it as a string (assuming that is the problem).

In the docs for the WSDL it shows an examples and the value is a string instead of an Int. Thanks in advance for your help!

**Comment by mvantellingen** [comment]
Hi,

First of all thanks for taking the time to add all the information.

I tried to run the example script as provided but it seems to depend on environment variables. Could you add an example script as described in the documentation: http://docs.python-zeep.org/en/master/reporting_bugs.html

**Comment by jmwoloso** [comment]
Just sent you an email with a script that should work. Thank you!

**Comment by mvantellingen** [comment]
As mentioned per e-mail, please try master branch

**Comment by mvantellingen** [comment]
I'm closing this ticket for now as it should be fixed. If there are still any issues then please let me know so that I can re-open the issue.

**Comment by jmwoloso** [comment]
Using master worked for that part. Thanks!
