### ISSUE TITLE
Support for HTTP basic authentication

### ISSUE THREAD

**Issue by mcordes** [mvantellingen/python-zeep#31]
Hello, 

Is there a plan to support HTTP basic authentication when using the HTTP binding? 

The aging suds library provides this as optional parameters to the client class (https://fedorahosted.org/suds/wiki/Documentation#HTTPAUTHENTICATION).

Here's a stab at a solution I made. I decided to add an http_auth parameter to the transport and pass that straight through to request.get/post

https://github.com/mcordes/python-zeep/commit/a2b5d982a7ea1e8cef52738758a3f85898a2a92d

I hope that's useful (and I'm happy to send a PR if that's reasonable) and I've love to see this functionality get added in whatever capacity.

**Comment by mvantellingen** [comment]
Yep definitely useful! PR would be nice, could you pep8 it a bit (line length).

Thanks!

**Comment by mcordes** [comment]
Will do. That's funny we use 100 character lines at work so I didn't notice. :)
