### ISSUE TITLE
XMLParseError: Unexpected element

### ISSUE THREAD

**Issue by atomotic** [mvantellingen/python-zeep#310]
i'm having the 'Unexpected element' error (i've seen some similar tickets)
Python 3.5.2 + zeep (0.24.0)

here the wsdl, the request and the response (the wsdl server is not public, sorry)
https://gist.github.com/atomotic/36dc2e59f762e43ba5e5ed3eb22d286c

thanks

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by atomotic** [comment]
sorry, my mistake. here a simplified version of the script.
the endpoint is not public, and i'm not pasting user credentials here.

thanks

```from zeep import Client
from zeep.transports import Transport
transport = Transport(verify=False)

import logging.config

logging.config.dictConfig({
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(name)s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'zeep.transports': {
            'level': 'DEBUG',
            'propagate': True,
            'handlers': ['console'],
        },
    }
})

wsdl_software = "http://md-services.test.bncf.lan/MagazziniDigitaliServices/services/AuthenticationSoftwarePort?wsdl"
client = Client(wsdl_software, transport=transport)
result = client.service.AuthenticationSoftwareOperation(user, password)
print(result)
```

**Comment by mvantellingen** [comment]
I definitely understand that wsdl's can be private (and credentials also ofcourse). 

This however makes it impossible for me to offer any help. So I'm afraid you will have to generate a test case for it yourself and submit it via a PR. See https://github.com/mvantellingen/python-zeep/blob/master/tests/test_xsd_integration.py for a number of examples.
