### ISSUE TITLE
Problems with result parsing from call with Complex Types

### ISSUE THREAD

**Issue by adamlwatson** [mvantellingen/python-zeep#322]
Hi there,

I'm attempting to access a SOAP API of one of our partners, and I seem to be getting a response that is not being parsed properly. The response contains a ComplexType which consists of an array of "Transactions", which is also a complex type.

Here is the requested test script as per your reporting instructions. The wsdl is included in the script:

https://gist.github.com/adamlwatson/fbfdc439bb95120df7ba7786f903d97f

What's interesting to note is that if I enable debug logging, I can see the full XML response contains all of the expected nodes with values. It's only when the response is parsed that the objects in the array seem to be munged.

Any help or insight would be appreciated!

Thanks.
Adam

**Comment by mvantellingen** [comment]
should be fixed in master ;-)

**Comment by adamlwatson** [comment]
Excellent... thanks for the quick turnaround.

Great library, btw.
