### ISSUE TITLE
multipart/related test breaks when Content-Type header is missing

### ISSUE THREAD

**Issue by willhardy** [mvantellingen/python-zeep#327]
I've added an inline comment to the recent commit https://github.com/mvantellingen/python-zeep/commit/2a0415a87f0be17b136026680864a33d87ce23bf#commitcomment-20661928, which caused a `TypeError` to be raised in our unit tests (passes <= 0.26.0, fails against 0.27.0).

**Comment by mvantellingen** [comment]
thanks for the report, should be fixed in master
