### ISSUE TITLE
Empty element in response ignored

### ISSUE THREAD

**Issue by BillyR512** [mvantellingen/python-zeep#328]
zeep==0.26.0
WSDL - http://ws.satorisoftware.com/Architect/US/Move/MoveService.asmx?WSDL

Issue: 
Using the WSDL above, I post addresses for NCOA (national change of address) and everything works great. However, occasionally the service will return empty values for parts of the address and zeep seems to ignore them. An example response:

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body>
    <RetrieveResponse xmlns="WS-SatoriSoftware-US-MOVE">
        <RetrieveResult>
            <Addresses>
                <Address>
                    <AddressFields>
                        <string>2c96eb6d-5ca6-4de1-92c0-66da8219db48</string>
                        <string>John</string>
                        <string>Smith</string>
                        <string>123 Main St</string>
                        <string>APT 111</string>  <!-- Value present -->
                        <string>ATLANTA</string>
                        <string>GA</string>
                        <string>30318-4370</string>
                    </AddressFields>
                </Address>
                <Address>
                    <AddressFields>
                        <string>2c96eb6d-5ca6-4de1-92c0-66da8219db48</string>
                        <string>Jane</string>
                        <string>Smith</string>
                        <string>123 Main St</string>
                        <string />              <!-- Value missing -->
                        <string>ATLANTA</string>
                        <string>GA</string>
                        <string>30318-4370</string>
                    </AddressFields>
                </Address>
            </Addresses>
        </RetrieveResult>
    </RetrieveResponse>
</soap:Body>
</soap:Envelope>
```

When I call `zeep.helpers.serialize_object()` on the response object in the example above, I get the following:

John Smith (8 items) - `['2c96eb6d-5ca6-4de1-92c0-66da8219db48', 'John', 'Smith', '123 Main St', 'APT 1111', 'ATLANTA', 'GA', '30318-4370]`

Jane Smith (7 items) - `['2c96eb6d-5ca6-4de1-92c0-66da8219db48', 'Jane', 'Smith', '123 Main St', 'ATLANTA', 'GA', '30318-4370']`

Are empty elements like in the example above intentionally ignored or is this a bug? Unfortunately prior to posting addresses to the service, I have to specify a `field_list_in` and a `field_list_out`. So a missing element in the serialized response is tough to deal with programatically.

Thank you to all who have contributed to zeep, it makes working with soap APIs in python pretty manageable.

**Comment by mvantellingen** [comment]
thanks for the report, could you give master a try?

**Comment by BillyR512** [comment]
Working as intended on master. Thank you for the quick reply!
