### ISSUE TITLE
Option to remove WSA headers

### ISSUE THREAD

**Issue by xtrinch** [mvantellingen/python-zeep#330]
I've been trying to find a way to remove/manipulate the wsa action header.

I've tried adding this plugin:

```
from zeep import Client
from zeep.wsa import WsAddressingPlugin

client = Client(
    'http://examples.python-zeep.org/basic.wsdl',
    plugins=[WsAddressingPlugin()])
client.service.DoSomething()
```

And since the WSDL I am using specifies WSA addressing, I now have duplicate wsa headers.

But my objective is that I would like to remove/manipulate the wsa headers all together. The example does not tell me in any way how do I modify it via that plugin. So is it possible to modify/delete it?

**Comment by mvantellingen** [comment]
The wsa headers are inserted before the plugins are run. So a somewhat hacky solution is to create a custom plugin which deletes the header element again. See http://docs.python-zeep.org/en/master/plugins.html#plugins.

Something like:

```python
class RemoveWSA(Plugin):
  def egress(self, envelope, http_headers, operation, binding_options):
    envelope.find('soap:Header').clear()
```

**Comment by xtrinch** [comment]
Task orders.tasks.import_orders[38239be4-f8f8-43c9-bf39-bfe5c2638192] raised unexpected: SyntaxError("prefix u'soap' not found in prefix map",)

Neither can it find soap-env:Header or wsa:Action

**Comment by mvantellingen** [comment]
yeah it was an example; you will need to pass an nsmap atleast. But even then my example code won't really work i think :-)

Just showing what is possible

**Comment by chadgates** [comment]
Just an update for anyone else having the same question: the above example worked for me with following adjustment: 

`  
  def egress(self, envelope, http_headers, operation, binding_options):
      envelope.find('{http://schemas.xmlsoap.org/soap/envelope/}Header').clear()
      return envelope, http_headers
`

**Comment by Gdar1127** [comment]
hello @chadgates , would you please share the full implementation, I'm facing the same issue. 
and running your example I'm getting this TraceBack: 
TypeError: egress() missing 1 required positional argument: 'binding_options'
Thanks in advance

**Comment by chadgates** [comment]
@Gdar1127: Meanwhile the code looks a bit different, but don't recall exactly why that was. The implementation looks about as follows and is targeted at a Dynamics AX 2012 R2 SOAP endpoint: 

```python
from zeep import Client
from zeep import Plugin
from zeep.plugins import HistoryPlugin
from zeep.transports import Transport

...

class RemoveWSA(Plugin):
    def egress(self, envelope, http_headers, operation, binding_options):
        env = envelope.find('{http://schemas.xmlsoap.org/soap/envelope/}Header')  
        for child in env:
            if child.tag.startswith('{http://www.w3.org/2005/08/addressing}'):
                env.remove(child)
        return envelope, http_headers

....

user = ''
pw = ''
url = ''

self.session = Session()
self.session.auth = HttpNtlmAuth(username=user, password=pw)
self.historyplugin = HistoryPlugin()

self.client = Client(url, transport=Transport(session=self.session), plugins=[RemoveWSA(), self.historyplugin])
servicename = 'RoutingService'
portname = 'BasicHttpBinding_......'
self.service = self.client.bind(servicename, portname)
```

**Comment by umermughal** [comment]
> hello @chadgates , would you please share the full implementation, I'm facing the same issue.
> and running your example I'm getting this TraceBack:
> TypeError: egress() missing 1 required positional argument: 'binding_options'
> Thanks in advance

I was getting the same issue `'TypeError: egress() missing 1 required positional argument: 'binding_options'` because I just passed a class name in plugins array you need to pass the object of plugin 
`plugins=[YourPlugin()]` instead of `plugins=[YourPlugin])`

**Comment by jeroen7s** [comment]
Quite annoying that there's no proper way to remove namespaces without writing patches like this.
I need to remove the namespaces for 10 different elements for my implementation
Shouldn't this be re-opened?
Or is there a better way available now?
