### ISSUE TITLE
SSL verification option missing in Transport class

### ISSUE THREAD

**Issue by shanzhong** [mvantellingen/python-zeep#331]
I found zeep while I was searching for a Python SOAP client that can bypass SSL certificate verification, so that it can work with a server running on a local VM. It seems to be a great library with excellent documentation! However, while I was trying to follow the first example to disable SSL verification on http://docs.python-zeep.org/en/master/transport.html, I realized the Transport class doesn't accept the verify=False option in its initiator. I looked through the code history, and found that the option was there in 0.25.0 but is gone in 0.26.0 and later versions. Here's the initiator for the Transport class in the two versions(src/zeep/transports.py):

v0.25.0:
```python
class Transport(object):
    def __init__(self, cache=NotSet, timeout=300, operation_timeout=None,
                     verify=True, http_auth=None):
```

v0.26.0:
```python
class Transport(object):
    def __init__(self, cache=None, timeout=300, operation_timeout=None,
                 session=None):
```

Could you check if this is intended or a bug? Thanks!

**Comment by mvantellingen** [comment]
it's mentioned in the changelog: http://docs.python-zeep.org/en/master/changes.html#id3

Since 1.0 is now out I'm intending to follow semver.
