### ISSUE TITLE
Wrong http_auth documentation

### ISSUE THREAD

**Issue by hanshoi** [mvantellingen/python-zeep#333]
zeep == 1.0.0

documentation version "master"

When the way using http_auth changed when upgrading from 0.24.0 to 1.0.0 then there was an error in documentation of the new way of using http_auth.

http://docs.python-zeep.org/en/master/transport.html#http-authentication
In this documentation it gives a indication that you can give _auth_ as parameter to _Session_, this however is not true if you look at requests source code (https://github.com/kennethreitz/requests/blob/v2.13.0/requests/sessions.py#L308) or try it. 

It seems that this works though:
```
import requests
from requests.auth import HTTPBasicAuth

session = requests.Session()
session.auth = HTTPBasicAuth(user, password)
client = Client('http://my-endpoint.com/production.svc?wsdl',
    transport=Transport(session=session))
```

**Comment by mvantellingen** [comment]
Should be fixed, thanks!
