### ISSUE TITLE
AttributeError: '_StaticIdentity' object has no attribute 'items'

### ISSUE THREAD

**Issue by daniloardenghi** [mvantellingen/python-zeep#338]
First of all, very thanks by your efforts in the zeep @mvantellingen.

I don't know if what I'm trying to report is a bug or if I'm doing something wrong, so I'll detail all the problem here.

The version of zeep here is 1.0.0

First of all, I did the code run with the postman, as the procedures described here:
https://gist.github.com/daniloardenghi/40862e01e4efb94ff9d1b907ba0327de

Now, I need to make this code above to works with zeep, and what I tried is this:
https://gist.github.com/daniloardenghi/e491a12423c3cf613da9310b22482578

The output was:
https://gist.github.com/daniloardenghi/694a494ef087ac94585d11582261a576

Can someone please help me?
Thanks!

**Comment by mvantellingen** [comment]
Could you retry this with master? thanks

**Comment by daniloardenghi** [comment]
Hey @mvantellingen, very very thanks by your help, but the error persists.

Maybe is am I doing something wrong?
The set_default_soapheaders is able to set those data right after <soap:Header> in this xml sample?
https://gist.github.com/daniloardenghi/40862e01e4efb94ff9d1b907ba0327de

Thanks by your patience.

**Comment by daniloardenghi** [comment]
Only here to update the thread and inform that the error was the way I was trying to construct the header.
It needs to be only dict, and I was trying to do a dict and list of dict inside it.

The problem was solved.
Thanks @mvantellingen
