### ISSUE TITLE
TypeError: encode() argument 1 must be str, not None - if there is no charset in http-header

### ISSUE THREAD

**Issue by keepkg** [mvantellingen/python-zeep#346]
Hi, Michael.
Thank you for this great zeep module. It seems the best for Python 3 at the moment.
Probably I can help you to make it better with this issue.

The problem is that if no charset was set in response http-header, type error will be raised.

This is a response from server (example)

------------------------
```
HTTP/1.1 200 OK
Server: nginx/1.11.5
Date: Tue, 14 Feb 2017 13:47:40 GMT
Content-Type: multipart/related; boundary="MIMEBoundary_ac7ef06563d301021317f66dde25efbee5a4bd174ac8b5d4"; type="application/xop+xml"; start="<0.9c7ef06563d301021317f66dde25efbee5a4bd174ac8b5d4@apache.org>"; start-info="text/xml"
Transfer-Encoding: chunked
Connection: keep-alive

--MIMEBoundary_ac7ef06563d301021317f66dde25efbee5a4bd174ac8b5d4
Content-Type: application/xop+xml; charset=UTF-8; type="text/xml"
Content-Transfer-Encoding: binary
Content-ID: <0.9c7ef06563d301021317f66dde25efbee5a4bd174ac8b5d4@apache.org>

<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:getFolderPathResponse xmlns:ns="http://somehost.org/xsd"><ns:return>/Folder</ns:return></ns:getFolderPathResponse></soapenv:Body></soapenv:Envelope>
--MIMEBoundary_ac7ef06563d301021317f66dde25efbee5a4bd174ac8b5d4--
```
------------------------

We see NO  charset=utf-8  here in header. W3c says that is normal (specs).
[trace.txt](https://github.com/mvantellingen/python-zeep/files/774814/trace.txt)

Because of that we have this error - 

```
/path/to/anaconda3/lib/python3.5/site-packages/requests_toolbelt/multipart/encoder.py in encode_with(string, encoding)
    408     """
    409     if not (string is None or isinstance(string, bytes)):
--> 410         return string.encode(encoding)
    411     return string
    412 
```

TypeError: encode() argument 1 must be str, not None 

It comes from transport object which use requests.response object filled with values from header.
response.encoding is None  when charset is omitted in http-header of response.

I went deep (using debugger) and then explored 'requests' module. It tries to guess in case charset is omitted in header but 'requests' module documentation says that we should set charset (encoding) directly (explicit) if we know it and utf-8 is a default for http/web.

Please let me know how I can set charset/encoding in transport object directly.

I'm not a python professional like you, I'm quite young in python so I apologise if this issue is not a problem at all.
Hopefully the problem not in my head. )))

With warm regards and respect to you as an author of this great zeep module.

1.
```
>>> zeep.__version__
'1.0.0'
```
2. As I see the problem is not in wsdl but I'm ready to provide it if you need.
3. An example script as well.
[Uploading trace.txt…]()

**Comment by mvantellingen** [comment]
Should be fixed in master / 1.1.0
