### ISSUE TITLE
Using Plugin:  empty enveloppe parameter

### ISSUE THREAD

**Issue by LensHunnel** [mvantellingen/python-zeep#354]
zeep==1.0.0
sample of code: https://gist.github.com/LensHunnel/07a42bb09ccb7dcdf11e498caa02cedb
I'm using the Plugin example (in the gist above) in my project and  I get an empty "enveloppe" parameter but only in apache 2.2 wsgi config for a django project. When I'm using the django integrated web server  It works fine.

**Comment by mvantellingen** [comment]
This really needs some more information 😄
