### ISSUE TITLE
Error parsing WSDL

### ISSUE THREAD

**Issue by david-house** [mvantellingen/python-zeep#355]
Parsing WSDL on the command line is not showing bindings, or port, or operations:

python3 -m zeep "https://integration2.legal-x.com/ws/5.8.1/review/PaymentService?wsdl"

From the same provider, a different WSDL works fine:

python3 -m zeep "https://integration2.legal-x.com/ws/reporting/ReportingService?wsdl"

I encountered the error in a Python script with an index error, it found no default binding on the first one.

1. The version of zeep (or if you are running master the commit hash/date) **1.1.0 (also 1.0.0 had the issue)**
2. The WSDL you are using **See above**
3. An example script **See above**

Note: I tried this on Win 10 and Ubu 16.04 systems with the same result. I was able to use .Net Framework 4.5.X & WCF to perform operations using both WSDLs in a different app.

**Comment by mvantellingen** [comment]
Should be fixed in master, could you give that a try?  (``pip install https://github.com/mvantellingen/python-zeep/archive/master.zip``)

**Comment by david-house** [comment]
The command line script:

python3 -m zeep "https://integration2.legal-x.com/ws/5.8.1/review/PaymentService?wsdl"

 **works now**. Thanks, I will try in my code later today.

I had to modify the pip install to get it to upgrade the existing install though::

sudo pip3 install --upgrade https://github.com/mvantellingen/python-zeep/archive/master.zip

**Comment by david-house** [comment]
Confirming that the Client works in Python3 for both WSDLs now.
