### ISSUE TITLE
Failure parsing wonky WSDL with tempuri.org

### ISSUE THREAD

**Issue by inchoate** [mvantellingen/python-zeep#356]
Howdy,

I just got started with zeep and am trying to parse a client's WSDLs. All their WSDLs have `tempuris` in them which zeep refuses to parse. Any help is greatly appreciated.

Details:
 - `zeep==1.1.0`
 - [WSDL](https://listings.colliershub.com/Services/API/Currencies.svc?wsdl)
 - [Full Sample Script and Output](https://gist.github.com/inchoate/d8c57d96c0a2d59f34caa0b3ffdcea03), summarized here:
```bash
17:09 $ python -mzeep 'https://listings.colliershub.com/Services/API/Currencies.svc?wsdl'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

[...snip...]

  File "/Users/vertrees/.virtualenvs/colliers_testing/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 181, in get
    raise IndexError("No definition %r in %r found" % (key, name))
IndexError: No definition u'{http://tempuri.org/}Currencies' in 'port_types' found
```

**Comment by mvantellingen** [comment]
Hi, Could you give the master branch a try?

The issue is actually that the wsdl's are invalid since the main wsdl references a port via tns:BasicHttpBinding_Currencies but there is no such binding defined since the target namespace of the wsdl include is an empty string. 

I've added a silly workaround for this ;-)

**Comment by inchoate** [comment]
@mvantellingen that worked! Thanks for your quick response & fix.
