### ISSUE TITLE
Parse Error Response Zeep Master release

### ISSUE THREAD

**Issue by lab1Vigeura** [mvantellingen/python-zeep#357]
Hello, thanks for your wonderful module. I love it. I have a problem when zeep parse the response. My problem is that I can't give you the wsdl url because it is accessible only via VPN. I will send only the content of that wsdl, the response and the error log obviously.

[dettaglioAutoveicoloComproprietari.wsdl.txt](https://github.com/mvantellingen/python-zeep/files/796341/dettaglioAutoveicoloComproprietari.wsdl.txt)
[response.txt](https://github.com/mvantellingen/python-zeep/files/796342/response.txt)

[error log.txt](https://github.com/mvantellingen/python-zeep/files/796343/error.log.txt)

I think the problem is when it parse luogoNascita and annoNascita. It is in a choice element, so maybe zeep make confusion for this.

Onestly I don't have any ideas, and this is a big problem for me to parse this xml.

Can you check please?

Thanks a lot.

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by lab1Vigeura** [comment]
Hello,

unfortunately I can’t give you a script, because you can’t test it. The url where you can find the wsdl is unreachable for you, because it is in a VPN, and I can’t give you the access to it.

If you can’t help me, don’t worry. I will resolve the problem by myself.

Thanks, and best regards.
