### ISSUE TITLE
absolute_location does not support base urls with file as scheme

### ISSUE THREAD

**Issue by aerandir92** [mvantellingen/python-zeep#358]
Version 1.1.0

When you send a location, say 'TestWSDL.xsd', with base 'file:///tmp/scheme', the result ends up being something like /home/usr/file:/tmp/scheme/testWSDL.xsd
Simply adding file to the schemes in absolute_location should fix this. 
I can create a pull-request when I get home

Console output showing issue:
https://gist.github.com/aerandir92/e62d4bc51d75c6444edf53c01b902824

**Comment by mvantellingen** [comment]
Merged your pr, thanks
