### ISSUE TITLE
Unable to find any way to customize handling of responses

### ISSUE THREAD

**Issue by aerandir92** [mvantellingen/python-zeep#362]
I am working on porting some existing old code from using subs to using zeep, I've gotten it to run and work now, but we need have some custom processing of http responses in certain cases, this goes for HTTP 500 and 503. 

I've been looking around the code a lot and red the docs, but I am unable to figure out anyway that I can 'hook' myself into the response processing and take control when the status code is 500 or 503, is there any way to do this?

The only thing that happens now is that zeep raises "Fault" with "Unknown fault ocured" with no errorcode, and that's not helpful at all. With just something more sane, I could've done a try/except and worked myself from, maybe.

**Comment by aerandir92** [comment]
Finally figured out what I was doing wrong, using requests "Hooks" worked for me

**Comment by soterocra** [comment]
@ThreePinkApples i have the same problem, can you explain better?
