### ISSUE TITLE
Schema.py log level INFO fills up logs

### ISSUE THREAD

**Issue by pringlewood** [mvantellingen/python-zeep#369]
Hello,

In https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/xsd/schema.py, 

```python 
def _add_schema_document(self, document):
```

and 

```python
def resolve(self):
         Implement logger.info() 
```

If zeep is used in a Django or celery project and default logging configured as below, and logging is not explicitly configured for zeep as per the docs.

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': env.int('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}
```

Every time the zeep client is initialised the log files fill up quickly with entries such as:

```Resolving in schema <SchemaDocument(location='<wsdl_location>', tns='http://tempuri.org/', is_empty=False)>```

and

```Add document with tns http://www.w3.org/2001/XMLSchema to schema 140240616243720```

Maybe the log level should be debug? As it does not add any information at the info level to production.

**Comment by mvantellingen** [comment]
Should be using logger.debug() now. Thanks :-)
