### ISSUE TITLE
Nested xsd:choice element do not work

### ISSUE THREAD

**Issue by arjenjb** [mvantellingen/python-zeep#370]
I'm using the latest version of Zeep and encountered the following issue. See the testcase in the following gist.

https://gist.github.com/arjenjb/76f8a96a158d9ec27e288e91ea88b9d9

Probably a rare scenario where `choice`s are nested in an XSD, but supposedly it's valid XSD. I encountered this in the XSD of a third party, so I cannot work around it.

**Comment by mvantellingen** [comment]
Should work in master/1.3.0
