### ISSUE TITLE
Incorrect parsing of response

### ISSUE THREAD

**Issue by molszowy** [mvantellingen/python-zeep#371]
Hi!

First of all, big thanks for writing this library. I've implemented it in my project and rely on it :)
I am having troubles getting correct responses for one query with the latest zeep 1.1.0 :

#Raw response from the server
`<?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><ns:executeSQLQueryResponse xmlns:ns="http://www.cisco.com/AXL/API/10.5"><return><row><name>10.48.46.175</name></row><row><name>10.48.46.171</name></row></return></ns:executeSQLQueryResponse></soapenv:Body></soapenv:Envelope>`

#response that I got from zeep
```
{
'return':
{ 'row': [ [ <Element name at 0x107d7e588> ], [ <Element name at 0x107d7e508>] ] }
,
'sequence': None
}
```

WSDL and the script to reproduce is attached.
[incorrect_parsing.zip](https://github.com/mvantellingen/python-zeep/files/814949/incorrect_parsing.zip)

**Comment by mvantellingen** [comment]
This seems to work fine I think? The result contains an anyType and since zeep is not able to reliably decide what should happen with it it will return the lxml node.

**Comment by molszowy** [comment]
Good catch. I didn't notice that this is anyType. Can we have a parameter to still decode Elements even if anyType or I have to do it outside of zeep?

**Comment by mvantellingen** [comment]
I'll look into that. It's a common request and I might be able to do something better

**Comment by mvantellingen** [comment]
This should be possible with http://docs.python-zeep.org/en/master/helpers.html#zeep.helpers.serialize_object
