### ISSUE TITLE
How to apply namespace prefix to all elements in request

### ISSUE THREAD

**Issue by Sallist** [mvantellingen/python-zeep#376]
Hello,

Is there a way to ensure the namespace prefix is applied to all elements within my SOAP request?
I am consuming a SOAP service from a 3rd party and thus don't "own" the WSDL or XSD files provided by the service.

My SOAP/XML knowledge is not too great, so I'm unsure if this is a problem with my code, the WSDL/XSD files provided by the 3rd party or Zeep itself.

When I use Zeep (version 1.1.0) to send my request it serialises the data as follows, which the remote service errors upon:
```xml
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:ServiceRequest xmlns:ns0="http://www.example.com/SoapService/xsd">
      <ns0:WholesaleServiceRequest>
        <serviceId>123456789</serviceId>
        <returnExtendedData>true</returnExtendedData>
      </ns0:WholesaleServiceRequest>
    </ns0:ServiceRequest>
  </soap-env:Body>
</soap-env:Envelope>
```

When I checked with the service admins they told me that the error is because my `serviceId` and `returnExtendedData` elements do not have the `ns0` namespace prefix applied.
They gave me an example on how my request should be formed which is as follows.
```xml
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:ServiceRequest xmlns:ns0="http://www.example.com/SoapService/xsd">
      <ns0:WholesaleServiceRequest>
        <ns0:serviceId>123456789</ns0:serviceId>
        <ns0:returnExtendedData>true</ns0:returnExtendedData>
      </ns0:WholesaleServiceRequest>
    </ns0:ServiceRequest>
  </soap-env:Body>
</soap-env:Envelope>
```

I would be very grateful for any assistance.

A cut down version of my python code is here:
https://gist.github.com/Sallist/4d3ba0541b96a4210108ed2618598e21

The XSD for the serviceRequest is here:
https://gist.github.com/Sallist/c074537350a2a97ac37dd351740f7170

The XSD for the WholesaleServiceRequest is here:
https://gist.github.com/Sallist/ef9a9fce88f0a0933f8c41e37ccf1edc

The XSD for the ServiceNumber is here:
https://gist.github.com/Sallist/df1b0371ff2b49cef12fefbf1c1b2889

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
