### ISSUE TITLE
App Engine Support for lxml version 2.3 only causing an error

### ISSUE THREAD

**Issue by shaunc869** [mvantellingen/python-zeep#379]
When using Zeep on app engine I am getting the following error:

File "lxml.etree.pyx", line 2139, in lxml.etree._Attrib.__cinit__ (third_party/apphosting/python/lxml/v2_3/src/lxml/lxml.etree.c:46754)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)

from /zeep/xsd/types/complex.py", line 165.

Obviously this isn't Zeep's fault that app engine won't support higher than 2.3 or 2.3.5, but can you recommend a work around for this issue? When I use 3.7.3 on my local machine it works fine.

**Comment by mvantellingen** [comment]
Not sure if this is something that is easy to fix. Do you have a complete traceback?

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue

**Comment by gcbirzan** [comment]
A workaround is suggested here: https://bugs.launchpad.net/lxml/+bug/1104370

Rather than use copy.copy(), use dict(). This seemed to work for me, maybe it should be put as some compat fix for old lxmls.
