### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by pmesgari** [mvantellingen/python-zeep#38]
Hello, 

I am getting an error when trying to run the command:
- from zeep import Client
The error is:
ImportError: cannot import name 'python_2_unicode_compatible'

I have tried the installation with both pip and pip3.

Regards,
Payam

**Comment by mvantellingen** [comment]
Do you have six installed? Check the output of `pip freeze`

**Comment by pmesgari** [comment]
Wow you replied so quick!
pip and pip3 freeze both says:
siz==1.5.2

**Comment by mvantellingen** [comment]
Oke, seems we require atleast six 1.9.0. Try installing the master branch or just `pip install six==1.9.0`

**Comment by pmesgari** [comment]
Thank you it worked!

**Comment by mvantellingen** [comment]
Cool :)

**Comment by SushilShrestha** [comment]
I am having same problem here. I am trying to run zeep via python 2.7.6
```python
import zeep
ImportError: cannot import name python_2_unicode_compatible
```
```
pip freeze | grep six
six==1.10.0

pip freeze | grep zeep
zeep==1.0.0
```
