### ISSUE TITLE
Zeep 1.2.0 assert name AssertionError at indicators.py line 116

### ISSUE THREAD

**Issue by RokoMijic** [mvantellingen/python-zeep#380]
Full stack trace of the error: [https://gist.github.com/RokoMijic/8411c4a8ccc1356199b6cf3f68f5bb86](https://gist.github.com/RokoMijic/8411c4a8ccc1356199b6cf3f68f5bb86)

1. zeep version = 1.2.0
2. WSDL is at [http://eur-lex.europa.eu/eurlex-ws?wsdl](http://eur-lex.europa.eu/eurlex-ws?wsdl)
3. Example script: https://gist.github.com/RokoMijic/63f659f00c658ddee3cb53cc8602fd24

Zeep is having trouble parsing the XML that is returned:

```
<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:S="http://www.w3.org/2003/05/soap-envelope"><env:Header/><S:Body><searchResults xmlns="http://eur-lex.europa.eu/search" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:searchLayerHelper="xalan//eu.europa.ec.op.searchlayer.domain.util.SearchLayerHelper" xsi:schemaLocation="http://eur-lex.europa.eu/search http://eur-lex.europa.eu/eurlex-ws?xsd=3">
   <numhits>1</numhits>
   <totalhits>75412</totalhits>
   <page>1</page>
   <language>en</language>
   <result>
      <reference>eng_cellar:feb8db71-f0eb-4ad6-8621-194a6b8a4c5c_en</reference>
      <rank>1</rank>
      <content>
         <NOTICE>
            <WORK>
               <ID_CELEX>
                  <VALUE>61994CJ0286</VALUE>
               </ID_CELEX>
            </WORK>
         </NOTICE>
      </content>
   </result>
</searchResults></S:Body></S:Envelope>
```

I have worked around this by editing soap.py so that it doesn't try to parse the XML body (I inserted `return body` into `deserialize(self, envelope)` )

It would be great if zeep offered an easy (e.g. a parameter) option to not try to parse the returned XML, since the parsing can be done with dedicated XML parsers if zeep has trouble parsing. 

Thanks -

**Comment by mvantellingen** [comment]
Should be fixed in master
