### ISSUE TITLE
Problem to read the WSDL cause the schema is not available

### ISSUE THREAD

**Issue by renatomattos2912** [mvantellingen/python-zeep#387]
Hi, i'm having a problem to read the wsdl operations and i`m getting the error:

> _NamespaceError: Unable to resolve type {https://devsistema.nfeplace.com.br/services/emissor}PDF. No schema available for the namespace u'https://devsistema.nfeplace.com.br/services/emissor'_

My code is:

```
import cherrypy
from requests import Session
from zeep import Client
from zeep.transports import Transport
from cert_module import pfx_to_pem


class PlaceEmissor(object):
    @cherrypy.expose
    def index(self):
        url = "https://<my-url>?wsdl"
        body = ""
        encoded_request = body.encode('utf-8')
        headers = {"Content-Type": "text/xml; charset=UTF-8", "SOAPAction": ""}
        pfx_path = "<my-cert>"
        pfx_password = "<my-pass>"

        session = Session()
        session.headers = headers
        session.data = encoded_request
        session.cert = pfx_to_pem(pfx_path, pfx_password)
        session.verify = False

        transport = Transport(session=session)

        client = Client(
            wsdl=url,
            transport=transport,
            strict=True)

        # pprint(vars(client))

        return client


if __name__ == '__main__':
    cherrypy.server.socket_host = '0.0.0.0'
    cherrypy.quickstart(PlaceEmissor())

```

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by renatomattos2912** [comment]
@mvantellingen thanks for your reply. So, i try to debug like you said but nothing happens, cause the error occurs on the creation of the Client, all the lines bellow don't execute. So i think that the only way that i can help you to help me is send you the XML of the WSDL, that follows bellow:


[wsdl.xml.zip](https://github.com/mvantellingen/python-zeep/files/854947/wsdl.xml.zip)

**Comment by renatomattos2912** [comment]
The version of the zeep module that i installed is the 1.3.0 from master branch.

**Comment by mvantellingen** [comment]
The wsdl references a non-existing type (PDF). I've made some changes so that only the impacted operations are removed
