### ISSUE TITLE
XMLSyntaxError

### ISSUE THREAD

**Issue by pmesgari** [mvantellingen/python-zeep#39]
Hi Michael,

Another issue. I am running:
python -mzeep http://www.webservicex.net/ConvertSpeed.asmx?WSDL
And I get lxml.etree.XMLSyntaxError: AttValue: " or ' expected, line 28, column 64
![michael](https://cloud.githubusercontent.com/assets/14719521/15645475/f3178b58-2658-11e6-9772-43da38afef5d.PNG)

**Comment by mvantellingen** [comment]
Yeah noticed this myself this morning, seems that the webservice endpoint is down so it doesn't return valid xml. But it should raise a clean error instead of this

**Comment by mvantellingen** [comment]
Just commited a fix to better report the error to the user. Thanks
