### ISSUE TITLE
Allow WSSE signature to use in-memory keys and certificates

### ISSUE THREAD

**Issue by eagle-r** [mvantellingen/python-zeep#400]
I just have a feature request that you modify the wsse.Signature() plugin to be able to use in-memory keys and/or certs rather than being a file. I've checked and the xmlsec module does provide methods for this.

My use case is that the Australian government uses WSSE for all web service requests. The keys and certs for this are provided in a very specific format and they have very specific guidelines about what can be stored and where. So, essentially, to keep all of the data according to their requirements, I can't actually save the keys or certs to a file just to be able to sign the requests.

For now, my workaround is to literally copy and paste the signature plugin and change it to use the appropriate xmlsec methods for in-memory rather than from-file.

**Comment by nanonyme** [comment]
I'd personally suggest some refactoring so sign_envelope and verify_envelope to take Key objects instead of filenames and having the current stuff as helpers. Seems easy to do to me @mvantellingen how important do you consider API compatibility to be?

**Comment by mvantellingen** [comment]
@nanonyme I think we can easily detect if filenames are passed instead of key files right? So it can stay backwards compatible. Do you want to submit a PR for this?

**Comment by nanonyme** [comment]
@mvantellingen Hmm, maybe. Although I'd personally prefer it to be more explicit so that you pass instead of Signature a MemorySignature (or something) and there's no checks anywhere in code for whether it's a file or data. I'll cook up a PR at some point, it's probably better to discuss over code. I think we can retain entirety of original API anyhow

**Comment by rouge8** [comment]
is there anything that can be done to help #411? I came here expecting to implement this myself and was pleasantly surprised to see there's already an issue and PR 😄

**Comment by nanonyme** [comment]
I haven't had time to look into those codecov failure as they weren't really obvious. Also not sure if maintainer approves my idea at all

**Comment by mvantellingen** [comment]
I still have some doubts relating to the API. Isn't providing a MemorySignature and a Signature confusing?  It is common in the python world to have functions which either accept a file handle or a file name. So we could also let them use signature like this:

```python
from io import StringIO

key_fh = StringIO("<key data>")
cert_fh = StringIO("<cert data>")
Signature(key_fh, cert_fh)
```
or as previous

```python
from io import StringIO

Signature("filename_1.key", "filename_2.key")
```

Now we could also do both changes :-). I'll try to review asap

**Comment by nanonyme** [comment]
@mvantellingen Hmm,  sure if you don't consider it awkward you need to wrap your data inside a StringIO container to deal with in-memory keys. I think that's duck-typable

**Comment by nanonyme** [comment]
Extra care needs to be had though to make sure only io.BytesIO or file opened in binary mode is used. The API takes a byte buffer

**Comment by mvantellingen** [comment]
Ok merged it, I'll add the file object support in later. Thanks for the work btw! Really appreciated
