### ISSUE TITLE
Create elements not in the WSDL

### ISSUE THREAD

**Issue by eagle-r** [mvantellingen/python-zeep#401]
I'm using the current version of zeep (1.3.0) and my WSDL is https://thirdparty.authentication.business.gov.au/R3.0/vanguard/S007v1.2/service.svc

Running this with the CLI tool shows only the following for global elements for that namespace,
```
ns2:RequestSecurityToken(ns2:RequestSecurityTokenType)
ns2:RequestSecurityTokenResponse(ns2:RequestSecurityTokenResponseType)
ns2:RequestSecurityTokenResponseCollection(ns2:RequestSecurityTokenResponseCollectionType)
```
where ns2 is `http://docs.oasis-open.org/ws-sx/ws-trust/200512`

However, when I go to the ws-trust namespace (http://docs.oasis-open.org/ws-sx/ws-trust/200512/ws-trust-1.3.xsd) there are all of the child elements of the above 3 and I need to create them in my request e.g. `RequestType`. Trying to create one of these child elements results in a LookupError since they are not in the original WSDL.

A cut-down example script of what I'm trying to run is below,
```
client = zeep.Client(wsdl='https://thirdparty.authentication.business.gov.au/R3.0/vanguard/S007v1.2/service.svc')

RequestType = client.get_element('ns2:RequestType')
request_type = xsd.AnyObject(RequestType, RequestType('http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue'))
response = client.service.Trust13Issue([request_type])
```

**Comment by mvantellingen** [comment]
Can you provide a runnable example script as described in the documentation?

**Comment by eagle-r** [comment]
Due to time and budget constraints for our client, we ended up coding our
own basic solution specific to them but I will try to supply an example
script in my own time as I would like to see this library developed to its
full potential.

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
