### ISSUE TITLE
Fix docs regarding backwards-compatibility

### ISSUE THREAD

**Issue by nanonyme** [mvantellingen/python-zeep#405]
Docs say
"""Note
Since this module hasn’t reached 1.0.0 yet their might be minor releases which introduce backwards compatible changes. While I try to keep this to a minimum it can still happen. So as always pin the version of zeep you used (e.g. zeep==0.24.0‘)."""
However, zeep is already at 1.3.0+. Either needs to be removed or changed if backwards-compatibility is still not guaranteed

**Comment by nanonyme** [comment]
The relevant file is https://github.com/mvantellingen/python-zeep/blob/master/docs/index.rst

**Comment by mvantellingen** [comment]
Thanks, fixed
