### ISSUE TITLE
LookupError: No type 'ArrayOfString' in namespace

### ISSUE THREAD

**Issue by marcokorb** [mvantellingen/python-zeep#407]
**1. The version of zeep:** zeep==1.3.0

**2. The WSDL you are using:** http://vinomundi.dev.bizcommerce.com.br/api/v2_soap?wsdl=1

**3. An example script:**  Just using command line to inspect a WSDL as below.

    python -m zeep http://vinomundi.dev.bizcommerce.com.br/api/v2_soap?wsdl=1
    
Hi,

When I'm trying to inspect a WSDL the following error occurs: **No type 'ArrayOfString' in namespace**.
I don't exactly know if this is a bug but I solved adding a new complex type to xsd/types/builtins.py 

Here you can check my fix: https://github.com/marcokorb/python-zeep/commit/809e5e1b0640120fbe6830a6337d43d919760328#diff-0ceb862431027f98230eac8ea650c9ba

I don't know if this a real fix, just a workaround or a bad practice to solve the problem,  so I was hoping that someone could help me.

Thanks.

**Comment by mvantellingen** [comment]
So the wsdl is referencing xsd:ArrayOfString which doesn't exist. Seems like a faulty XSD to me :-)

I don't really have a solution for now except monkeypatch zeep by injecting the value. Will think about this later (perhaps we need an official type/element injection mechanism)

**Comment by mvantellingen** [comment]
I've added some changes so that only the impacted operations are disabled, will be in 1.5
