### ISSUE TITLE
No Visitor Defined '{http://www.w3.org/2001/XMLSchema}attributeGroup'

### ISSUE THREAD

**Issue by nikeighley** [mvantellingen/python-zeep#41]
I get this error 
ValueError: No visitor defined for '{http://www.w3.org/2001/XMLSchema}attributeGroup'

when I try to read my WSDL file. I've included the file (changing the file extension to .txt)

[ProgramManager-wsdl.txt](https://github.com/mvantellingen/python-zeep/files/291280/ProgramManager-wsdl.txt)

**Comment by mvantellingen** [comment]
Should already be fixed on the master branch, could you give that a try?

``pip install https://github.com/mvantellingen/python-zeep/archive/master.zip#egg=zeep``

**Comment by nikeighley** [comment]
failed to install

$ pip install https://github.com/mvantellingen/python-zeep/archive/master.zip#egg=zeepDownloading/unpacking https://github.com/mvantellingen/python-zeep/archive/master.zip#egg=zeep
  Downloading master.zip (unknown size): 98Kb downloaded
  Running setup.py egg_info for package from https://github.com/mvantellingen/python-zeep/archive/master.zip#egg=zeep
    
Requirement already satisfied (use --upgrade to upgrade): defusedxml>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from zeep==0.8.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): isodate>=0.5.4 in /usr/local/lib/python2.7/dist-packages (from zeep==0.8.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from zeep==0.8.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from zeep==0.8.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from zeep==0.8.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python2.7/dist-packages/pytz-2016.4-py2.7.egg (from zeep==0.8.0.dev0)
Installing collected packages: zeep
  Found existing installation: zeep 0.6.0
    Uninstalling zeep:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1089, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 476, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1391, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 248, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 297, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 248, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/zeep/xsd/types.py'

Storing complete log in /home/developer/.pip/pip.log

**Comment by mvantellingen** [comment]
You might need to do `sudo pip install ..` or create a virtualenv. This is unrelated to zeep/

**Comment by nikeighley** [comment]
duh. Yes it installs and appears to work. Thanks!
