### ISSUE TITLE
Only first array element is processed

### ISSUE THREAD

**Issue by chemelson** [mvantellingen/python-zeep#410]
Hi,
I'm experiencing the following problem with Zeep 1.3.0.
1. Here's SOAP envelope I send - https://gist.github.com/chemelson/14950077a4c7d91fbb1825348bae92db
2. Here's the code
client.service.doSelect(sid = sid, objectType = 'cr', whereClause=cfg.sdm_whereClause, maxRows = cfg.sdm_maxRows, attributes = ["type", "summary"])
3. The problem, that  I get value only for the first item in 'attributes' list, in this code - "type", following are ignored.
For example: https://gist.github.com/6e1825e81302f9df27a30042f62de03d.git

I've looked through zeep docs, but found nothing. 
Is it bug or I'm doing smth wrong?
Thanks!

**Comment by chemelson** [comment]
It seems to me that issue #374 is about the same issue.

**Comment by mvantellingen** [comment]
Should be fixed now, will be in 1.4 release

**Comment by chemelson** [comment]
1.4.1 didn't help, situation is the same.

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by karlbe** [comment]
I think I also had this issue, fixed it by creating a dict with the element name as key and the list of values as value. Don't know if that's the way it's supposed to be done, but seems a bit unintuitive to me.

For example: (assuming the elements in the attributes have the name attribute):

`attributes = {'attribute':["type", "summary"])`

resulted in

```
<ns0:attributes>
<ns0:attribute>type<ns0:attribute>
<ns0:attribute>summary<ns0:attribute>
<ns0:attributes>
```

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
