### ISSUE TITLE
Support passing in str types to soapenc:string

### ISSUE THREAD

**Issue by wenwei63029869** [mvantellingen/python-zeep#416]
I am using `1.4.1` version
[The WSDL I am using](https://gist.github.com/wenwei63029869/65bb4c1e0e72bebb8ac697dac54b7b6a)
[Example script that I used](https://gist.github.com/wenwei63029869/879b4f4c134f7e8763cf6aad1661a9b0)
[Error](https://gist.github.com/wenwei63029869/0386a6180327849e172faec3a075fa49)

As you can see in the script, I set some of the attributes to be `None` and `Error while create XML for complexType '{http://schemas.xmlsoap.org/soap/encoding/}string': Expected instance of type <class 'zeep.objects.string'>, received <type 'str'>` instead. is raised. Also, I tried replacing `None` with `zeep.xsd.SkipValue` or convert the string into `AnyObject`, but the same error still occurred. I can't give you the credentials to actually test the response, but I think they are not needed for this specific problem. Could you please help me figure out if I did something wrong? Please do let me know if you need anything else from me. Thank you so much.

**Comment by mvantellingen** [comment]
Should be fixed, Could you give master a try?

**Comment by rodorgas** [comment]
Worked for me.
