### ISSUE TITLE
Add support for pickle to the value objects

### ISSUE THREAD

**Issue by Flauschbaellchen** [mvantellingen/python-zeep#417]
Zeep-Version: 1.1.0

When trying to pickle responses gotten from a soap-call I get the following error:
```
_pickle.PicklingError: Can't pickle <class 'zeep.objects.LoginResponse'>: import of module 'zeep.objects' failed
```

As it seems that the reason lies in the nature of zeep and how the objects are dynamically generated I tried myself to transform them back into "normal" Python objects which are used within my application.

Example:
```python
class LoginResponse(object):
  def __init_(self, username, authToken):
    self.username = username
    self.authToken = authToken

  @staticmethod
  def from_transfer_object(data):
    return LoginResponse(username=data.username, authToken=data.authToken)
```

Usage:
```python
login_reponse = LoginResponse.from_transfer_object(my_zeep_client.service.login(username="foo", password="bar"))
```

Currently my application contains 63 classes and many of them with more than 10 attributes.

Is there an easy way to *de*serialize the soap-responses back into other python objects (recursively)?
Something like:

```python
login_response = my_zeep_client.service.login(username="foo", password="bar").cast_to(LoginResponse)
```
Adding additional logic into such objects would be much easier without writing the whole `from_transfer_object` stuff over and over...

Any ideas - or is there any other best practice I am missing?

**Comment by mvantellingen** [comment]
We will need to add pickle support (`__setstate__` and `__getstate__``) to https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/xsd/valueobjects.py#L36

**Comment by mvantellingen** [comment]
Could you give master branch a try?

**Comment by Flauschbaellchen** [comment]
Hi @mvantellingen 
Thanks for your very fast response.
I tried the master branch and it works now.

**Comment by gasparbrogueira** [comment]
Hi @mvantellingen

I still have the same problem (Python 2.7, zeep 3.2.0)

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <class 'zeep.xsd.dynamic_types.SetUserContactPhone'>: import of module zeep.xsd.dynamic_types failed

Could you help?

Many thanks!
