### ISSUE TITLE
Handling of arrays with complex types

### ISSUE THREAD

**Issue by EmPath86** [mvantellingen/python-zeep#424]
Hello!

Zeep-Version: 1.4.1

I encounter a problem when trying to create a SOAP-Request to access a web service, where the input parameter is an array with the elements being comprised of complex data types. 

Please see the WSDL: [https://gist.github.com/EmPath86/b0d6c4a82e35122791f19028067da015](https://gist.github.com/EmPath86/b0d6c4a82e35122791f19028067da015)
and example script: [https://gist.github.com/EmPath86/a6c868468149d4a273a9cda4763a63ac](https://gist.github.com/EmPath86/a6c868468149d4a273a9cda4763a63ac)
for further details.

When the data is parsed to create the message, Zeep looks for every attribute of the elements of the array, which behaves as expected.
However, when an empty array serves as input (e.g. `test_array_of_complexData = []`), this results in missing tags for the elements (again, as expected) but also leading to a missing tag for the the overall array (`test_array_of_complexData`), since `body.render()` in `wsdl/messages/soap.py` omits creating the tags for the elements. 
The server-side relies on all tags being present in order to handle data management.

I appreciate any help and look forward to your response. Maybe there is also something I am missing when creating the request?
 
If there is any information missing, please let me know.

**Comment by mvantellingen** [comment]
Hi,

test_array_of_complexData is specified as min_occurs=0, max_occurs=unbounded. So it is an optional element according to the xsd. Can you give master a try and set 

```python
from zeep.xsd import Nil
test_data = {
    'test_array_of_complexData': Nil
}
```

**Comment by EmPath86** [comment]
Hi,
thanks very much this works! :)

One thing I had to change in order to work was setting the attributes (`id` and `timestamp`) of the elements of the array (`objectShortData`) to `nillable=true`:

```
<xs:complexType name="objectShortData">
    <xs:sequence>
        <xs:element name="id" nillable="true" type="xs:long"/>
    <xs:element name="timestamp" nillable="true" type="xs:long"/>
</xs:sequence>
```

When I use
`subscribe_data = client.factory.complexTestData(test_data)`
to prepare the data, `subscribe_data` looks as follows:

```
subscribe_data = {
    'test_array_of_complexData': {
        'id': Nil,
        'timestamp': None
    }
}
```

This raises the ValidationError for the attribute `timestamp` in `zeep/xsd/elements/element.py, line 218`:

```
if not self.is_optional and not self.nillable and value in (None, NotSet):
    raise exceptions.ValidationError(
        "Missing element %s" % (self.name), path=render_path)
```

I think this could either be solved by setting all attributes of the element to Nil or by the workaround I used, since there might be cases where this behavior could be helpful in order to force the developer to consider this when creating the WSDL. 

Thanks again for your help! :)
