### ISSUE TITLE
When maxOccurs is > 1, the array assigned to the value ends up being a reference

### ISSUE THREAD

**Issue by aerandir92** [mvantellingen/python-zeep#425]
Zeep version: 1.4.1

Gist: https://gist.github.com/aerandir92/7a2310872fd95c4613e5819d881a22b7

When instantiating something through factory, it only returns a reference, resulting in broken experience when trying to create a the same type repeatedly. 

In the gist you see I use factory to create a new ArrayOfParticipant. I manipulate that object, then I try to create a second ArrayOfParticipant, but the resulting object is equal to the first one.

**Comment by aerandir92** [comment]
This only happens when I call ArrayOfParticipant() with no params

**Comment by aerandir92** [comment]
Outtake from WSDL showing ArrayOfParticipant and what it can contain
https://gist.github.com/aerandir92/cb96276eb7d1a94de1438a5f9eac449f

**Comment by aerandir92** [comment]
I tried to reproduce it with Participant (also part of the previous gist), and there it returned a clean, new Participant object each time. Could it have something to do with ArrayOfParticipant having maxOccurs="unbounded" ?

**Comment by aerandir92** [comment]
I'm trying to do some comparison between Participant and ArrayOfParticipant to try to understand why they behave differently.
Gist: https://gist.github.com/aerandir92/54614afc2a00fd4536ef5d818c5a5b3f

So from what I can see, both of them are zeep.xsd.dynamic_types and I can find no reason why they should be any different in behaviour.

**Comment by aerandir92** [comment]
Alright, dug even deeper. The issue appears for all values that have maxOccurs > 1, or in general, just not 1 (0, and -1 even works). So it's the array that is added when maxOccurs != 1 that ends up being a reference.

**Comment by mvantellingen** [comment]
Thanks for the excellent report, should be fixed now 🙈

**Comment by aerandir92** [comment]
Great! Got far enough today to medle with the cache, but didn't realise that I should've just made it a property
