### ISSUE TITLE
Not finding (prefixing) element

### ISSUE THREAD

**Issue by mattharrison** [mvantellingen/python-zeep#426]
Running on zeep 1.5. I'm not able to make a call because my request is not properly namespaced. The script below errors out connecting, but if you inspect the logged request, you will see that ``VehicleRulesLookup`` is not namespaced with ``ns0``.

The zip file with the schema is sadly missing a file, so here are instructions to get the wsdls/xsd's

* Get schema from https://support.travelport.com/webhelp/uapi/Content/Resources/uAPI_WSDLschema_Release-V17.2.0.67.zip

* Schema page - https://support.travelport.com/webhelp/uapi/Content/Getting_Started/Universal_API_Schemas_and_WSDLs.htm

* The zip is missing a schema. Create a directory ``SessionContext_v1`` and put the contents of this file in it
https://github.com/Travelport/travelport-uapi-tutorial-c-sharp/blob/master/ConsoleApplication1/ConsoleApplication1/Service%20References/UniversalService/SessionContext_v1.xsd

The script assumes that these are unzipped in the ``/tmp`` directory

    import zeep
    from zeep.transports import Transport
    
    import logging.config
    
    logging.config.dictConfig({
        'version': 1,
        'formatters': {
            'verbose': {
                'format': '%(name)s: %(message)s'
            }
        },
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'zeep.transports': {
                'level': 'DEBUG',
                'propagate': True,
                'handlers': ['console'],
            },
        }
    })
    
    fullpath = '/tmp/uAPI_WSDLschema_Release-V17.2.0.67/vehicle_v41_0/Vehicle.wsdl'
    service = 'VehicleService'
    port_name = 'VehicleRulesServicePort'
    t = Transport()
    c = zeep.Client(wsdl=fullpath, transport=t)
    port = c.bind(service, port_name)
    
    authorized_by = 'foo'
    target_branch = 'foo'
    origin_application = 'foo'
    
    req = {
            'AuthorizedBy': authorized_by,
            'TargetBranch': target_branch,
            'BillingPointOfSaleInfo': {
                'OriginApplication': origin_application
            },
            #'{http://www.travelport.com/schema/vehicle_v39_0}VehicleRulesLookup':{
            'VehicleRulesLookup':{
                'VehicleDateLocation': {
                    'PickupDateTime': '2017-03-20T22:50:00.000-04:00',
                    'PickupLocation': 'LAX',
                    'ReturnDateTime': '2017-03-24T22:50:00.000-04:00',
                    'ReturnLocation': 'LAX'
                },
                'VehicleSearchModifiers': {
                    'VehicleModifier': {'AirConditioning': "true",
                                        'TransmissionType': "Automatic",
                                        'VehicleClass': "Economy",
                                        'Category':"Car",
                                        'DoorCount': "FourToFiveDoors"
                    },
                    'RateModifiers': {'RateCode': '1234',
                                  'VendorCode': '234'}
                }
            }
        }
    
    res = port.service(**req)

**Comment by mattharrison** [comment]
I have hacked around this by changing the definition in `VehicleReqRsp.xsd` from:

    <xs:element name="VehicleRulesLookup">

to:

     <xs:element name="VehicleRulesLookup" form='qualified'>

This adds the namespace. From my understanding, any element in a schema should have the targetNamespace, but the code in `Visitor.visit_element` only does this for elements that are children of `schema`.

I would prefer not to have to edit schemas. Ideas? Bug?

**Comment by mvantellingen** [comment]
Might have fixed the issue, can you try master?

**Comment by mattharrison** [comment]
Works for me! Thank you!
