### ISSUE TITLE
Zeep not importing mutliple WSDL files?

### ISSUE THREAD

**Issue by RabbitBionic** [mvantellingen/python-zeep#428]
Hello,

First off, my apologies if this is not something that I understand. I read the docs and even tried to search for code examples in the past issues.

I'm using zeep 1.6.0 (installed through pip) and I'm facing a WSDL parsing error. The WSDL is part of a proprietary system, so I can't paste it here (however, I could email to the developer if required).

Basically, there's a main WSDL file that imports more files. If I use the main file, I get the following error in Zeep:

> "ValueError: There is no default service defined. This is usually due to missing wsdl:service definitions in the WSDL"

Here is how the main WSDL file defines the other files (hostname changed for privacy):
```
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:report="http://example.com/Report/3.5.0" xmlns:account="http://example.com/Account/3.5.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="exampleservices" targetNamespace="http://example.com/exampleservices/3.5.0">
<documentation xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></documentation>
<import namespace="http://example.com/Account/3.5.0" location="Account/Account.wsdl"/>
<import namespace="http://example.com/Report/3.5.0" location="Report/Report.wsdl"/>
<types/>
</definitions>
```

Here is how I invoked a command:
```
from zeep import Client
from zeep import xsd

wsdl_url = 'https://example.com/soap2/schema/latest/services.wsdl'
client = Client(wsdl_url, strict=False)
rawxml = client.service.GetAccounts()
```

And then I would get:

> ValueError: There is no default service defined. This is usually due to missing wsdl:service definitions in the WSDL

This command should normally work, because the GetAccounts function is defined within the https://example.com/soap2/schema/latest/Account/Account.wsdl file.

If I replace wsdl_url by the URL directly to 'https://example.com/soap2/schema/latest/Account/Account.wsdl', the function then works.

Alternatively, would it be possible to use multiple WSDL URLs directly into Zeep if tis bug can't be solved? 

Many thanks!

**Comment by mvantellingen** [comment]
Sorry, I'm not really able to provide proper help without access to the wsdl. But did you try http://docs.python-zeep.org/en/master/client.html#creating-new-serviceproxy-objects ?
