### ISSUE TITLE
raw soap call

### ISSUE THREAD

**Issue by malemodel** [mvantellingen/python-zeep#43]
hi...  how can i dump the raw soap call in zeep to see what the actual xml looks like?

thanks...

**Comment by mvantellingen** [comment]
``client.service._binding.create_message('OperationName', *args, **kwargs)``

**Comment by malemodel** [comment]
>>> c.service._binding.create_message('ProcessRequest', *args, **kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'args' is not defined

**Comment by mvantellingen** [comment]
Yeah so, that was an example. ``client.service._binding.create_message('OperationName', Arg1,Arg2)`` etc
