### ISSUE TITLE
Lists with xs:anyType are not parsed to given dynamic type

### ISSUE THREAD

**Issue by Flauschbaellchen** [mvantellingen/python-zeep#431]
Zeep-Version: 1.6.0

I'm currently running a server with Tomcat+JAXB/CXF to send data to the client.
As JAXB has a hard time handling HashMaps as a top-level object, I created a Wrapper-Class `JAXBWrapperList` to workaround this problem.

Some sources discussing this "specification"-bug:
 * https://jaxb.java.net/nonav/2.2.5-5/docs/ch03.html#annotating-your-classes
 * https://java.net/jira/browse/JAXB-223?jql=project%20%3D%20JAXB%20AND%20status%20%3D%20Open
* https://java.net/jira/browse/JAX_WS-320

My `JAXBWrapper` Class:
```java
@XmlRootElement
public class JAXBListWrapper<T> implements Iterable {

    @XmlElement(name="list")
    private List<T> wrappedList = new ArrayList<>();

    public JAXBListWrapper() {}

    public JAXBListWrapper(List<T> list) {
        this.wrappedList = list;
    }
[...]
```
As `T` is generic and can be any given class, the auto-generated WSDL contains `anyType` as the class-specification - which is as far as I can tell correct.
```xml
<xs:complexType name="jaxbListWrapper">
  <xs:sequence>
    <xs:element maxOccurs="unbounded" minOccurs="0" name="list" type="xs:anyType"/>
  </xs:sequence>
</xs:complexType>
```

When the client receives such a list, the following is transmitted (`masterObjectData` is my object used for `T` consisting of attributes `id`, `name`, `alive` and `custom`):
```xml
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="masterObjectData">
  <id>5</id>
  <name>Barcelona (Spanien)</name>
  <alive>true</alive>
  <custom>{ "color": "#d7d7d7"}</custom>
</list>
```

As the schema `http://www.w3.org/2001/XMLSchema-instance` is unknown to Zeep, I get the following warning:
```
Unable to resolve type masterObjectData. No schema available for the namespace None.
```
Just to try things out I removed the schema and set the correct namespace.
The message reads now:
```xml
<list ns0:type="masterObjectData">
  <id>5</id>
  <name>Barcelona (Spanien)</name>
  <alive>true</alive>
  <custom>{ "color": "#d7d7d7"}</custom>
</list>
```
The warnings disappeard.

However, the objects are not parsed to the corresponding dynamic types but are parsed as simple `Element`s:
```python
[
    <Element id at 0x6b069b8>,
    <Element name at 0x6b0b670>,
    <Element alive at 0x6b0b6c0>,
    <Element custom at 0x6b0b648>
]
```

Accessing them using `list[0].id` gives an `AttributeError`.
It is only possible to access the data using `list[0][0]` (id), `list[0][1]` (name) and so on.

Now the question is, would it be possible to parse them to the correct dynamic types as the type specification is given within the recieved XML?
Or would this clash with other SOAP/XML specifications I'm not aware of?

Is the additional namespace sent by CXF/JAXB `http://www.w3.org/2001/XMLSchema-instance` correct (thus zeep need to be improved to handle it) - or is this something I need to fix within my server?

Thanks for your hard work already done so far.

**Comment by mvantellingen** [comment]
So the issue seems to be that zeep can't detect which type it should use to translate to (since it is defined in the wsdl as anyType). Do you have a complete wsdl/xsd + example script for me?

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
