### ISSUE TITLE
http auth issue

### ISSUE THREAD

**Issue by vishnusomasekhar007** [mvantellingen/python-zeep#436]
I am getting an issue 
transport_with_basic_auth = Transport(http_auth=('username', 'password'))
as TypeError: __init__() got an unexpected keyword argument 'http_auth'.

please help to resolve this issue

**Comment by Devligue** [comment]
I had the same problem. Not resolved

**Comment by mvantellingen** [comment]
Please see http://docs.python-zeep.org/en/master/transport.html#http-authentication
