### ISSUE TITLE
Factories for complex type using a dot in theirs names

### ISSUE THREAD

**Issue by LensHunnel** [mvantellingen/python-zeep#438]
Hi Michael. Thank you for this excellent library.
One question:
I'm using zeep version 1.6 
I've this complex type define :

```xml
<xs:complexType name="Case.UserInformation">
<xs:sequence>
<xs:element minOccurs="0" name="id" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="name" nillable="true" type="xs:string"/>
</xs:sequence>
<xs:attribute ref="ser:Id"/>
<xs:attribute ref="ser:Ref"/>
</xs:complexType>
```

I'd like to know whether there is a better way to access that kind of type using factories : 
`factory = client.type_factory('ns0')`
The thing is that the code below is not working :
```python
user = factory.Case.UserInformation(id=1, name='John')
```
I'm using the function get_type to have it working.
```python
user_type = client.get_type('ns0:Case.UserInformation')
```
Thanks

**Comment by mvantellingen** [comment]
Try factory['Case.UserInformation'](id=1, name='john')

**Comment by LensHunnel** [comment]
thanks. That's working
