### ISSUE TITLE
Error: 'str' object has no attribute 'apply'

### ISSUE THREAD

**Issue by wenwei1030** [mvantellingen/python-zeep#441]
I am using 1.6.0 version
[The WSDL I am using](https://gist.github.com/wenwei63029869/65bb4c1e0e72bebb8ac697dac54b7b6a)
[Inspect WSDL file](https://gist.github.com/wenwei1030/3cda99d2145096a60fcc92239e92972b)
[Example script that I used](https://gist.github.com/wenwei1030/07f84426fbba3985a48fc7c6fbd5a0ae)
[Payload generated by zeep](https://gist.github.com/wenwei1030/0fc14c9aedfb935a60a8b1a3bfd46129)
[Payload generated by suds](https://gist.github.com/wenwei1030/6dd91be185bc9c59f4773ec71dd19a97)

Hi, this is a follow up on this closed [issue](https://github.com/mvantellingen/python-zeep/issues/416). The original issue has been solved. I am able to create the payload and send request. However, it seems like the payload is not created correctly. For example, there is no prefix for a lot of tags. I wonder if I use factory wrong. Would really appreciate your answer.

**Comment by mvantellingen** [comment]
Can you give the following a try:

```python
data = factory.trackingRequest(barcode="0306665955011139",
         clientGroupId=<???>,
         clientLicence=<???>,
         custRef1=None,
         custRef2=None,
         fromDate=None,
         maxRows=None,
         parcelId=None,
         toDate=None)
```

This is because zeep maps None to xsi:nil=true when a field is nillable.

**Comment by wenwei1030** [comment]
Thanks. That works. Now I am getting the correct response back. However, it seems like the response is not parsed correctly. Here is the new [script](https://gist.github.com/wenwei1030/72599a33e8086c9ab8f7a73ebec4a232). Please see result gist below:

[history.last_received](https://gist.github.com/wenwei1030/f3bd17343bcac6ff131806f727d18f3d)
[Result](https://gist.github.com/wenwei1030/b3f107a3c48ff35878216268dc12e1e6)

I am expecting something like [this](https://gist.github.com/wenwei1030/3060db873f4662857e13ccca78ad2bf5)

**Comment by mvantellingen** [comment]
That is almost certainly related to #326

**Comment by wenwei1030** [comment]
Thanks for the link. I wonder when you plan on working on this issue. My team is really excited about Zeep because it is based on requests and we hope can start implementing it as soon as possible.

**Comment by wenwei1030** [comment]
Yes, it works! Thank you so much.

**Comment by wenwei1030** [comment]
Follow up question: Therefore a lot of extra values in the zeep response. Are they necessary? Please see the responses from zeep and suds for comparison:
[Zeep response](https://gist.github.com/wenwei1030/feca65e012a94c4fffa78d4b776da0ca)
[Suds response](https://gist.github.com/wenwei1030/339e219690090aa672577cbb8aa95aa5)

**Comment by mvantellingen** [comment]
Regarding the extra fields, these fields are actually all defined in the xsd. Suds behaviour may seems nicer but it isn't consistent for all responses. If suds receives the other attributes then it will suddenly use another data structure. That requires a lot of ``hasattr()`` calls to properly read out suds responses.

Regarding the L, that is probably the Long indicator in Python, see https://docs.python.org/2/library/functions.html#long
