### ISSUE TITLE
Exception on empty response from SOAP server

### ISSUE THREAD

**Issue by 0nkery** [mvantellingen/python-zeep#442]
1. The version of zeep 
```
zeep==1.6.0
```

2. The WSDL you are using
```
https://api-beta.reformagkh.ru/api/wsdl
```
3. An example script

[Here it is](https://gist.github.com/0nkery/6096bb5ffd9358566b8aa66a58cbd2b0#file-test-py).

As you can see, `Logout` method is not returning anything and `zeep` crashes trying to process an empty response.

Proposed solution:

``` python
def process_reply(self, envelope):
...
    if self.output:
        return self.output.deserialize(envelope)
```

**Comment by 0nkery** [comment]
What does it mean?

**Comment by mvantellingen** [comment]
Should be fixed, thanks!
