### ISSUE TITLE
How to create client with specific endpoints?

### ISSUE THREAD

**Issue by wenwei1030** [mvantellingen/python-zeep#444]
I am using zeep 2.0.0
[Suds client instantiation](https://gist.github.com/wenwei1030/0e3e4383072136729e8e1cc2e9797f39)
In the example, I was trying to create a suds client with the wsdl file path, authentication url, username, and password. I wonder how I can do the same thing with Zeep since Zeep doesn't have location optioin.

**Comment by mvantellingen** [comment]
See http://docs.python-zeep.org/en/master/client.html#creating-new-serviceproxy-objects

**Comment by wenwei1030** [comment]
I think I was asking the wrong question. 
[The WSDL I am using](https://gist.github.com/wenwei63029869/65bb4c1e0e72bebb8ac697dac54b7b6a)
[Suds request payload](https://gist.github.com/wenwei1030/83919032f914f10971ee174dbd57badf)
I have tried to use the basic auth referring [python-zeep/examples/http_basic_auth.py](https://github.com/mvantellingen/python-zeep/blob/master/examples/http_basic_auth.py), but I keep getting `TypeError: __init__() got an unexpected keyword argument 'http_auth'`. Am I doing it the wrong way?

**Comment by mvantellingen** [comment]
Ah that example was out of date, see 7b1b47af6f07bdb321f8fca32c1b7e8bdfd154dc
