### ISSUE TITLE
Using zeep without lxml

### ISSUE THREAD

**Issue by alexjurkiewicz** [mvantellingen/python-zeep#445]
Hi, I'm looking to build a few AWS Lambda functions that use zeep and act as a sort of REST<->SOAP gateway.

Zeep relies on lxml, which requires native code extensions, which are troublesome to use with Lambda. Is it possible to use Zeep without lxml?

**Comment by mvantellingen** [comment]
Not really, the etree module in the stdlib doesn't really support namespaces afaik. A quick Google reveals that there are solutions to un lxml on lambda though

**Comment by mrayco** [comment]
Is there a work around to make zeep work on aws lambda?

**Comment by alexjurkiewicz** [comment]
@mrayco Theoretically, you can take the python-lxml native library from building python-lxml on amazon linux (the same version as Lambda uses) and include them in your base directory of your lambda function package. I didn't manage to get this working though. :(

You can find tutorials giving advice on how to do this for Python, Javascript and Ruby on Lambda -- the process is the same for native extensions in any non-native language on Lambda.

**Comment by michaelangelorayco** [comment]
@alexjurkiewicz After spending a day, I got it to work. I followed this [post](https://www.azavea.com/blog/2016/06/27/using-python-lxml-amazon-lambda/).
but instead of using python 2.7, I used python 3.5 because that's the latest version you can get on amazon-inux right now.

**Comment by lucascosta** [comment]
This worked for me: https://github.com/JFox/aws-lambda-lxml
