### ISSUE TITLE
Implement Mapping for zeep.xsd.valueobjects.CompoundValue

### ISSUE THREAD

**Issue by justanr** [mvantellingen/python-zeep#446]
Right now CompoundValue mostly behaves like a Mapping -- we can do `CV['...']` to retrieve a value, `'thing' in CV` to see if a key exists, it's even backed by an OrderedDict (though that's an implementation detail for sure).

Currently, translating a CompoundValue into a true dictionary requires either using the `__json__` or `__values__` hook (which is odd to see in high level code) or to manually pluck key value pairs out (tedious).

By implementing the Mapping interface, it can be done with `dict(CV)` or with the `**` unpacking.

Looks like the only missing methods are `keys`, `items`, `values`, and `get`.

**Comment by mvantellingen** [comment]
The proper way now to convert a CompoundValue is to use the serialize_object call (see http://docs.python-zeep.org/en/master/helpers.html#zeep.helpers.serialize_object).

I do understand your request however, but it also has some downsides. What if the returned object has a key 'items' (which is actually fairly common) ? It will require various special cases for these keys then.

**Comment by justanr** [comment]
Ah, I didn't know that was there. I'll use that and see if it fits my needs. Thanks. 

I'll close this and refile if I feel it's still needed.

**Comment by jonathanelscpt** [comment]
Any way to document this better?  I also hit this and don't think this is the ideal place to have to come looking for it...
