### ISSUE TITLE
Only the first choice in the Response is picked up

### ISSUE THREAD

**Issue by mjahanbin** [mvantellingen/python-zeep#448]
Hello Michael,
What an amazing module you've created! Lifesaver. Seriously. Thank you.

I am have some issues using with methods that have a choice in their response. 
Basically if anything other than the first choice is returned zeep complains with a message like this:

XMLParseError: Unexpected element '{http://Path/To/1.0/wsdl}returnArg2', expected u'{http://Path/To/1.0/wsdl}returnArg1'

I was experiencing this issue with zeep 1.1.0 so I decided to upgrade to the latest, but get the same thing with zeep 2.0.0

Attached is a zip file that contains the relevant parts of the WSDL and the request/response xsd's.

Your help will be very much appreciated.

Live Long.

[test.zip](https://github.com/mvantellingen/python-zeep/files/1030020/test.zip)

**Comment by mvantellingen** [comment]
It seems that the one of the choices uses XOP, which isn't supported yet. See #194

**Comment by mjahanbin** [comment]
Yes you're right, there is an xop as part of the attachment even though the attachment is not binary, its just some xml. I may be wrong, but I dont believe xop is the issue for several reasons. 

First I use zeep successfully to make a similar call that does not have a choice but does have an xop:include and zeep has no issues with that. May be the server is being a little  liberal with the use of xop!

In addition in the working example, Response2, zeep returns both variables in the choice setting the second one, the URI, to None. 

And finally the XMLParseError produced by zeep points towards a choice issue.

What do you think?

**Comment by mjahanbin** [comment]
My band-aid hack for this has been to change line 89 in zeep/xsd/elements/indicators.py (property elements_nested) from:
     "if elm.accepts_multiple: "
to
     "if elm.accepts_multiple or isinstance(elm, Choice): "

as Choice object appears to return False for accepts_multiple

Thanks.

**Comment by mvantellingen** [comment]
@mjahanbin are you able to provide a PR + unittest for this? That way it might be included for the next release

**Comment by mjahanbin** [comment]
Please point me where I can see how to put together a PR and unit tests for zeep. I found a couple of other little things which may be worth fixing. I'll open new issues for those.

Thank you for all your hard work.

/m

**Comment by mvantellingen** [comment]
Can you give the latest release a try? It fixed a lot of bugs in the mean time,

**Comment by oeMoe** [comment]
Hi,

I have the same issue.
The response from the Soap service is defined as this in the wsdl/xsd:
<element name="Response">
    <complexType>
      <sequence>
        <element ref="Status" />
        <choice>
          <element ref="ErrorMessage" />
          <element ref="Id" />
        </choice>
      </sequence>
    </complexType>
</element>

When the service returns 
<Response>
 <Status>OK</Status>
 <Id>860607757</Id>
</Response>

I get an error:
E                   zeep.exceptions.XMLParseError: Unexpected element 'Id', expected 'ErrorMessage'

...\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\types\complex.py:173: XMLParseError

(I have left out the namespace references above)
I'm using version 2.5.0 of zeep.
