### ISSUE TITLE
Zeep is Returning Unrequested Fields in API Response

### ISSUE THREAD

**Issue by jonathanelscpt** [mvantellingen/python-zeep#449]
Question/Confusion on zeep behaviour...

I'm having an issue in that my zeep client is returning fields that I have not requested.

1. zeep version - **2.0.0**
2. Cisco CUCM AXL WSDL - https://developer.cisco.com/site/axl/learn/how-to/get-wsdl.gsp

```
from requests import Session
from requests.auth import HTTPBasicAuth

from zeep import Client
from zeep.transports import Transport
from zeep.cache import SqliteCache

WSDL_URL = 'file:///path/to/axl/current/AXLAPI.wsdl'
CUCM_URL = 'https://cucm01:8443/axl/'
USERNAME = 'axl'
PASSWD = 'axl'

session = Session()
session.verify = False
session.auth = HTTPBasicAuth(USERNAME, PASSWD)
transport = Transport(session=session, timeout=10, cache=SqliteCache())

client = Client(WSDL_URL, transport=transport)
service = client.create_service("{http://www.cisco.com/AXLAPIService/}AXLAPIBinding", CUCM_URL)

aarg_data = {
    'searchCriteria': {
        'name':'%'
    },
    'returnedTags': {
        'uuid': ''
    }
}

aarg_resp = service.listAarGroup(**aarg_data)
print(aarg_resp)
```

The XML from SoapUI for this method is:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/11.5">
   <soapenv:Header/>
   <soapenv:Body>
      <ns:listAarGroup sequence="1">
         <searchCriteria>
            <!--Optional:-->
            <name>?</name>
         </searchCriteria>
         <returnedTags uuid="?">
            <!--Optional:-->
            <name>?</name>
         </returnedTags>
         <!--Optional:-->
         <skip>?</skip>
         <!--Optional:-->
         <first>?</first>
      </ns:listAarGroup>
   </soapenv:Body>
</soapenv:Envelope>
```

zeep returns the following:

```
{
    'return': {
        'aarGroup': [
            {
                'name': None,
                'uuid': '{EC773CBE-EFE0-8565-A048-DA864B7542D4}'
            },
            {
                'name': None,
                'uuid': '{7E8C5CE6-BDB2-C827-8030-08D9DDBB0AB3}'
            },
            {
                'name': None,
                'uuid': '{FD4DAAD3-C0A4-434A-5395-4998AB14B79C}'
            }
        ]
    },
    'sequence': None
}
```

Values that were not requested do appear in the object, and are marked as None, which creates huge blobs for larger API objects.

In comparison, if I use suds, it does not return unrequested response fields:
```
(reply){
   return = 
      (return){
         aarGroup[] = 
            (LAarGroup){
               _uuid = "{EC773CBE-EFE0-8565-A048-DA864B7542D4}"
            },
            (LAarGroup){
               _uuid = "{7E8C5CE6-BDB2-C827-8030-08D9DDBB0AB3}"
            },
            (LAarGroup){
               _uuid = "{FD4DAAD3-C0A4-434A-5395-4998AB14B79C}"
            },
      }
 }
```

I'm confused by the behaviour?  Is this expected, and is there a way not to return the unrequested data?  I only want to work the with data that I'm expecting to see.

Thanks for all the work that you're doing here.  It's excellent.

**Comment by mvantellingen** [comment]
Zeep will always create objects as defined in the WSDL. Suds will return objects based on the response, which sucks because it requires you to do a lot if ``if hasattr()`` etc statements.

**Comment by RKWesdijk** [comment]
I'm all new to this, so forgive me if it's a 'dumb' question, but why would you want to specify 'returnedTags' if all the tags are always returned? If not specified the content of a tag is None? Than instead of a alot of hasattr() statements you would have to check the contents? I don't see the advantage.

Again, I'm all new to this so perhaps I'm missing something obvious :)

**Comment by jonathanelscpt** [comment]
Agreed.  The wsdl i'm using sometimes returns many attrs.  This gives me a lot to choose from in `returnedTags`.  Typically, I don't want all data - such a pain then to clean up everything that I didn't ask for all the time.  I really don't see the advantage.

@mvantellingen, can you give a more concrete example where your chosen behaviour is more valuable than returning the specified filtered attrs?  Also new to this, so keen to understand this more.

**Comment by jonathanelscpt** [comment]
I take this back....  I get it now...
