### ISSUE TITLE
wsdl file throw error No connection adapters were found

### ISSUE THREAD

**Issue by ayoubolk** [mvantellingen/python-zeep#45]
I'm tryin to use Zeep library with wsdl file instead of url but it doesn't work for me
here is my code:
```
import zeep
import os

try:
    wsdl_file = 'test.wsdl'
    base_dir = os.path.dirname(__file__)
    wsdl = 'file://%s' % os.path.abspath(base_dir + "/" + wsdl_file)
    client = zeep.Client(wsdl=wsdl)
except Exception as e:
    print e
```

**Comment by mvantellingen** [comment]
Yeah 'file://' isn't supported yet. You can just pass in a relative/absolute path to the file. In the future the scheme will be required (didnt have any time yet )
