### ISSUE TITLE
zeep 2.0.0 with issue RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by xudesheng** [mvantellingen/python-zeep#451]
1) Zeep version: 2.0.0
2) WSDL: https://gist.github.com/xudesheng/891eab5324135aeb00b86bd72d7ef343
3) Example Script:

from zeep import Client
client = Client('http://demo:6666/ProcessDefinitions/DataProcessing/SOAPServer?wsdl')
client.wsdl.dump()

RuntimeError: maximum recursion depth exceeded

Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
2. The WSDL you are using
3. An example script

Also please don't paste WSDL/XSD file contents directly into the issue since 
that makes it hard to read, instead please create a gist at 
https://gist.github.com and link that here.

Please see http://docs.python-zeep.org/en/master/reporting_bugs.html for 
more information.

**Comment by mvantellingen** [comment]
Hi, thanks for the info, can you give master a try? It should work there
