### ISSUE TITLE
Setting value for an element 

### ISSUE THREAD

**Issue by madjokr** [mvantellingen/python-zeep#452]
I am trying to set a value for an element which cannot be retrieved through `get_type` or `get_element` methods.

This is the xml that needs to be created 

```xml
<ns1:Party xmlns:ns3="urn:oasis:names:tc:ciq:xpil:3" ns3:PartyType="Individual">
<PersonName  xmlns="urn:oasis:names:tc:ciq:xnl:3">
       <NameElement  d10p1:ElementType="FirstName" xmlns:d10p1="urn:oasis:names:tc:ciq:xnl:3">
                                            My name
        </NameElement>
         <NameElement  d10p1:ElementType="LastName" xmlns:d10p1="urn:oasis:names:tc:ciq:xnl:3">
                                            Wyatt
        </NameElement>
</PersonName>
</Party>
```

I am able to get the type of `PersonName`. I tried finding all  types and elements using 
`python -mzepp myfile.wsdl` . I can't find the `NameElement` type  using this command. 

```NameElement: {xsd:normalizedString, ElementType: ns6:PersonNameElementList, Abbreviation: xsd:boolean, _attr_1: {}}[]```

How do I set the normalizedString for the above case? 

However, I somehow managed to get the xml to an extent using the following code.
```python
name_elements ={'NameElement':[{'ElementType':'LastName'},{'ElementType':'LastName'}]}
party_name_type = reg_client.get_type('ns6:PartyNameType')
party_name_type = party_name_type(PersonName=[name_elements])


party_type = reg_client.get_type('ns4:PartyType')
party_type = party_type(PartyName=party_name_type, PartyType="Individual")

```
I don't know how to set the value for the element `NameElement` . I always get this output 

```xml
 <ns3:PartyName>
                <ns4:PersonName xmlns:ns4="urn:oasis:names:tc:ciq:xnl:3">
                  <ns4:NameElement ns4:ElementType=FirstName'">NotSet</ns4:NameElement>
                  <ns4:NameElement ns4:ElementType="LastName">NotSet</ns4:NameElement>
                </ns4:PersonName>
   </ns3:PartyName>
```
It would be great if you guys can help me figure this out. I am stuck with this for almost a day.

**Comment by mvantellingen** [comment]
I can't really help you without more info (like for example the wsdl)

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
