### ISSUE TITLE
Request from json

### ISSUE THREAD

**Issue by Kappasama** [mvantellingen/python-zeep#453]
Hi! 
I have data structure as:
{"key": "value", "items": [{"name": "value_name", "parameter": "parameter_value"}, {"name": "value_name", "parameter": "parameter_value"}]}

and i need to request to soap servise. Is passible convert and send request by zeep? 
I found only "key=value" param.  I did not find any information in the examples and documentation

**Comment by willibix** [comment]
Try using this to serialize your json message:
```
import json
D1 = json.dumps({"key": "value", "items": [{"name": "value_name", "parameter": "parameter_value"}, {"name": "value_name", "parameter": "parameter_value"}]})
```
Then use the result as the value for the parameter in your soap request that need the json message.

**Comment by mvantellingen** [comment]
Sorry, i'm going to close this issue, please use for example stackoverflow for generic python questions
