### ISSUE TITLE
GUID not parsed from XML to JSON in SOAP response

### ISSUE THREAD

**Issue by bsteverink** [mvantellingen/python-zeep#455]
I am connecting to a SOAP web service and found that one of the fields that is returned in the XML is not parsed correctly. I have copied the fragment from the XML response below, as well as the parsed JSON. 

Also refer to https://gist.github.com/bsteverink/dede1f3341828d069a502f16ccc5da0b for the full demonstration as per instruction in the documentation.

I am using Zeep 2.0.0.

The fragment that is returned from the SOAP service:

    <GetDataExchangeQueryResultRow>
        <DataType>System.Guid</DataType>
        <ReturnObject xmlns:q1="http://microsoft.com/wsdl/types/" xsi:type="q1:guid">16fed64c-9b6d-4383-bdd1-fd5cde084afe</ReturnObject>
        <DisplayName>Auto_ID</DisplayName>
    </GetDataExchangeQueryResultRow>

The JSON result from the client:

    {
        'DataType': 'System.Guid',
        'ReturnObject': [],
        'DisplayName': 'Auto_ID'
    }

Hope this information is sufficient. Thanks in advance for your time :)

**Comment by mvantellingen** [comment]
Should be fixed in master (the q1 namespace is unknown so it now returns the raw data)
