### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by dmollerm** [mvantellingen/python-zeep#456]
Description: on failed authorization, the webservice we are trying to use will return a 200 OK http code and an html page with non unicode characters as content, which causes zeep to raise an UnicodeDecodeError instead of a TransportError due to handling an XMLSyntaxError

1. zeep version 1.6
2. wsdl: https://gist.github.com/dmollerm/1d7abd8a71bdef8e3159b70ca9366cdb
3. Yet the bug can be reproduced with the wsdls in the tests folder:

```
# -*- coding: utf-8 -*-

from pretend import stub
from zeep import Client
from zeep.exceptions import TransportError

if __name__ == "__main__":
    data = "òñÇÿ"

    client = Client('tests/wsdl_files/soap.wsdl')
    binding = client.service._binding

    response = stub(
        status_code=200,
        content=data,
        encoding='utf-8',
        headers={}
    )

    try:
        binding.process_reply(
            client, binding.get('GetLastTradePrice'), response)
    except TransportError as e:
        print(e)
    except Exception as e:
        print(e)

```
One would expect the answer to be
`Server returned HTTP status 200 (òñÇÿ)`
yet it is
`'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)`

**Comment by dmollerm** [comment]
I made a pull request to solve this, yet I don't know how to link it to this issue, sorry.
https://github.com/mvantellingen/python-zeep/pull/457

**Comment by mvantellingen** [comment]
Thanks, merged it. GitHub automatically creates a link between issues (and pull requests) when you use the id in the comment like you did. So you have 'linked' it perfectly :-)
