### ISSUE TITLE
Explicit documentation about single service with multiple operations

### ISSUE THREAD

**Issue by GermanMtzmx** [mvantellingen/python-zeep#458]
I have a wsdl that contains getLanguage Operation, by default takes a token param and languageId,`it has two posible soap body

```xml
     <soapenv:Body>
      <cat:UniqueLanguage>
         <!--Optional:-->
         <cat:token>?</cat:token>
         <cat:languageId>?</cat:languageId>
      </cat:UniqueLanguage>
   </soapenv:Body>
```

his description is 

MessageName="UniqueLanguage" 
Returns a register in the language catalog table

but this service also is used to get a list  of languages passing only token  like this way 

```xml
   <soapenv:Body>
      <cat:ListLanguage>
         <!--Optional:-->
         <cat:token>e0b1e3c1305d4049b0ba7fe9fd02f70f_636322607699444720</cat:token>
      </cat:ListLanguage>
   </soapenv:Body>
```

MessageName="ListLanguage" 
Return a list of registers of the language catalog table

ListLanguage is aviable on Global elements but not in operations `ns0:ListLanguage(token: xsd:string)`

doing  `python -mzeep mywsdl.com/catalogs.asmx?WSDL`  i get this description of operation

`getLanguage(token: xsd:string, languageId: xsd:int) -> UniqueLanguageResult: ns0:LANGUAGE`

My question is how can i tell to zeep client use this MessageName to get the list instead only one element,

**Comment by mvantellingen** [comment]
Could you please add the information which was requested from you when you created the issue?
