### ISSUE TITLE
Transport Session with HTTPBasicAuth

### ISSUE THREAD

**Issue by tanuki505** [mvantellingen/python-zeep#460]
I am new to soap and zeep and I'm not sure this is really a bug but I am having an issue with the following script.  It loads the wsdl file but gives me an sessionid error when I call a method.  It never seems to open a connection to the soap server and I get false when I try to verify.

Any help would be greatly appreciated,
 

Zeep version is 2.0.0
WSDL file is at https://gist.github.com/tanuki505/8c27252d66b78b174af00a4d6fcd1be0

************My script**********
```python
from requests import Session
from requests.auth import HTTPBasicAuth  # or HTTPDigestAuth, or OAuth1, etc.
from zeep import Client, loader
from zeep.transports import Transport

session = Session()
session.verify = False
session.auth = HTTPBasicAuth('hpna', 'password)

myload = loader.absolute_location(r'hpna_soap', r'c:/temp/')
client = Client(myload, transport=Transport(session=session))
```
************End my script*******
```python
client.service.show_memory('')
zeep.exceptions.ValidationError: Missing element sessionid

client.transport.session.verify
False
```

**Comment by tanuki505** [comment]
Is there a more appropriate forum that I should use to ask for help?

**Comment by mvantellingen** [comment]
Bit late; you need to pass a sessionid variable as reported. Perhaps this is a soapheader. See ```python -mzeep <url>```
