### ISSUE TITLE
Error runing basic example on GAE with flask

### ISSUE THREAD

**Issue by lgalant** [mvantellingen/python-zeep#461]
I'm evaluating using Zeep to send SOAP messages to Netsuite from Google App Engine.
I'm testing the basic example provided in the docs but getting the following error:

> TypeError: expected httplib.Message, got <type 'instance'>.

It happens in the following line of code:

`client = Client('http://www.webservicex.net/ConvertSpeed.asmx?WSDL')`

First of all I would like to know if Zeep works well with GAE and Flask.
Based on this issue (closed), it is supposed to work:

https://github.com/mvantellingen/python-zeep/issues/243

However this StackOverflow posting says GAE does not work well with "requests" library
https://stackoverflow.com/questions/34683437/typeerror-expected-httplib-message-got-type-instance-when-using-requests

I've tested with the following Zeep versions and getting always the same issue:
0.19, 0.21, 1.6, 2.0

Here's the full code snippet

```
from flask import Blueprint, jsonify, request
import logging
from zeep import Client

customer = Blueprint('customer', __name__)

@customer.route('/api/customers/',methods=['GET','PUT'])
def customerListHandler():


    client = Client('http://www.webservicex.net/ConvertSpeed.asmx?WSDL')
    result = client.service.ConvertSpeed( 100, 'kilometersPerhour', 'milesPerhour')
```

Please let me know if I'm doing something wrong or just Zeep doesn't work in this context

Thanks

**Comment by mvantellingen** [comment]
I've never tested zeep on GAE myself. It should work with Flask though
