### ISSUE TITLE
Cache attempts to use $HOME rather than $TMP

### ISSUE THREAD

**Issue by hobarrera** [mvantellingen/python-zeep#464]
By default, `SqliteCache` attempts to save the the cache file into the running user's home.

Given that `zeep` isn't always used by an interactive user (eg: it's pretty common to use in on servers), this default fails if the user doesn't have a home directory.

It makes a lot more sense to use $TMP (generally `/tmp`) by default, rather than the user's home, which is always guaranteed to exist.

This behaviour is defined in [`_get_default_cache_path`](https://github.com/mvantellingen/python-zeep/blob/da95cbbb61ba8bb5630e7ea51ea8b5c61556a3c4/src/zeep/cache.py#L149).

Would it be acceptable to change that default to use [`tempfile`](https://docs.python.org/3.6/library/tempfile.html) or `$TMP` instead?

**Comment by mvantellingen** [comment]
Zeep actually uses the appdirs module (https://pypi.python.org/pypi/appdirs/) to find the platform specific cache directory. You can alter the cache dir via the XDG_CACHE_HOME env var or initialize the cache with a path of your choosing

**Comment by hobarrera** [comment]
Yeah, I guess it makes sense -- although services (eg: webapps) aren't usually run by an actual user with a home directory.

How would if feel about using `$TMP` as a fallback only if the cache dir does not exist and is not creatable?

**Comment by WhyNotHugo** [comment]
I've been hit again by this with an environment where `$HOME` is read-only. Using `$TMP` as a fallback is not okay?
