### ISSUE TITLE
Public signing key not available

### ISSUE THREAD

**Issue by mbehrle** [mvantellingen/python-zeep#466]
$ gpg --verify zeep-2.1.1.tar.gz.pgp zeep-2.1.1.tar.gz
gpg: Signature made So 11 Jun 2017 19:34:29 CEST
gpg:                using RSA key 58B1E1B46CF0C00A1C2783F1E5A8120B3DEF67BF
gpg: Can't check signature: Kein öffentlicher Schlüssel

Couldn't find the signing key on any public keyserver.  Could you please upload?

Thanks,
Mathias

**Comment by mvantellingen** [comment]
Should be fixed (uploaded to pgp.mit.edu)

**Comment by mbehrle** [comment]
Are you sure you uploaded the correct key?

http://pgp.mit.edu/pks/lookup?search=58B1E1B46CF0C00A1C2783F1E5A8120B3DEF67BF&op=index
No results found: No keys found

**Comment by mvantellingen** [comment]
I might have uploaded it the wrong way: ``http://pgp.mit.edu/pks/lookup?search=michaelvantellingen@gmail.com&op=index``
I'll look into it later (I don't use PGP much)

**Comment by mbehrle** [comment]
The key is now available, thanks!

**Comment by mbehrle** [comment]
Problem appears again with zeep-3.1.0.tar.gz:

$ gpg --verify zeep-3.1.0.tar.gz.asc zeep-3.1.0.tar.gz
gpg: Signatur vom Sa 28 Jul 2018 09:50:48 CEST
gpg:                mittels RSA-Schlüssel B58A7FFB4E04A54B4EBF01C7B25EF97F6B8CF4C2
gpg: Signatur kann nicht geprüft werden: No public key

Could you please publish the new key?

Thanks!

**Comment by mbehrle** [comment]
May I remind this issue? Standard importing procedures into Debian fail because of the missing key. 

Publicly available is 96B67042ABC44F77, could you please sign in future with this key or publish the real signing key?

Thanks,
Mathias

**Comment by mvantellingen** [comment]
I've read somewhere that pypi is going to drop support for gpg singing packages (i think https://github.com/pypa/warehouse/issues/3356). And since I had a new laptop I didn't bother with it.

**Comment by mbehrle** [comment]
> I've read somewhere that pypi is going to drop support for gpg singing packages (i think [pypa/warehouse#3356](https://github.com/pypa/warehouse/issues/3356)). And since I had a new laptop I didn't bother with it.

Alright, I am aware of the discussion about the topic, but please have a look at the comments on the issue. It think the change is widely perceived as a mis-feature. Also, the change on pypi is just about not showing the signature.
Finally: at least it doesn't make any sense to sign a release with an unpublished key. So very please either publish the signing key (very much prefered) or do not sign at all. Signatures with an unpublished key will trigger annoying errors on distribution infrastructures.

Thanks
