### ISSUE TITLE
Question about retry logic

### ISSUE THREAD

**Issue by ledohoanglong** [mvantellingen/python-zeep#467]
Hi Mvantellingen,

I'm using Zeep 1.6.0. I have a question regarding the retry logic.

Is it possible to customize the request retries number in Zeep?

I understand that Zeep is using requests underneath. In Requests, you can customize the Retry number by Adapter. Is there any way I can change this number when calling Zeep? Or I have to roll my own version of retry logic?

My requests version is 2.14.2

**Comment by mvantellingen** [comment]
You can pass a request session to zeep which is already configured with retries.

See http://docs.python-zeep.org/en/master/transport.html#transports

**Comment by ledohoanglong** [comment]
In the end, I rolled out my own logic, but thanks!
