### ISSUE TITLE
zeep.exceptions.Fault: Multiple headers with name 'To' and namespace 'http://www.w3.org/2005/08/addressing'

### ISSUE THREAD

**Issue by njuki** [mvantellingen/python-zeep#471]
1. The version of zeep : 2.1.1

```
import zeep
from lxml.builder import ElementMaker
import uuid

from zeep.wsa import WsAddressingPlugin
import datetime
import Configs  #import configs

payload = { 
    'ActisureEntity':1178314
}

WSA = ElementMaker(namespace='http://www.w3.org/2005/08/addressing')

wsa_els = [
    WSA.Action(<url>),
    WSA.To(<url>),
]

client = zeep.Client(wsdl=Configs.COLWSDL, plugins=[WsAddressingPlugin()])
client.service.Act_GetEntityPolicyList(payload)

```
When I omit WSA settings, I get a different error as below:

**zeep.exceptions.Fault: The SOAP action specified on the message <url1>, does not match the HTTP SOAP Action, <url2>.**

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
