### ISSUE TITLE
Question about SalesForce API login route

### ISSUE THREAD

**Issue by JuanMartin93** [mvantellingen/python-zeep#472]
Let's start by saying that I'm new to Zeed and SOAP. Thus, I'm guessing this will be kind of a basic step instead of an issue. 
```
1.Sets the session ID in the SOAP header so that the API can validate subsequent requests for this session.
2.Specifies the server URL as the target for subsequent service requests. The login server supports only login calls
```
I'm following the steps to use the Salesforce SOAP API, and after logging I'm asked to set the
```
>>> import zeep
>>> wsdl = 'wsdl.xml'
>>> client = zeep.Client(wsdl=wsdl)
>>> LoginResult = client.service.login(username=myusername,password='mypassword+token')
```

I've seen example for suds, but nothing for zeep. Please any help will be appreciated

**Comment by mvantellingen** [comment]
I'm sorry but I'm not really sure what you want to achieve (and i'm not familiar with the salesforce soap api) Do you get an error when you execute the login call().

**Comment by mvantellingen** [comment]
PS. There seems to be an API using zeep for Salesforce: https://github.com/gbarger/PySalesforce
