### ISSUE TITLE
Problem parsing wsdl

### ISSUE THREAD

**Issue by RafaelHarispe** [mvantellingen/python-zeep#473]
Hi
I'm trying to interact with following service, and it is getting some errors, and finally, zeep doesn't discover any ws operation.
http://190.104.208.36/ws/services/AssistCardService?wsdl
First time I thought there was some mistake at WS, but SOAPUI is able to work with it, so I'm posting this issue.  May be it is posible to solve.

Best Regards,

**Comment by mvantellingen** [comment]
The wsdl used the soapenc namespace which was never imported. I think Axis (again...) assumed that this was a default namespace
