### ISSUE TITLE
Convert Zeep object to XML representation

### ISSUE THREAD

**Issue by majackson** [mvantellingen/python-zeep#478]
Hi there, Zeep is a great project! Many thanks for building it.

Is it possible to inspect the XML that will be produced by a Zeep object without actually sending it off to an operation endpoint? This would be a useful tool for debugging.

If this is not already possible, this would make for a useful helper function.

**Comment by andreixk** [comment]
It is possible. Instead of doing this:

```python
client.service.MyService(params,_soapheaders=headers)
```

do this:

```python
from lxml import etree as ET
#
#<your setup code for zeep here>
#
node = client.create_message(client.service, 'MyService', params = params, _soapheaders=headers)
tree = ET.ElementTree(node)
tree.write('test.xml',pretty_print=True)
```

**Comment by mvantellingen** [comment]
Please see http://docs.python-zeep.org/en/master/client.html#creating-the-raw-xml-documents

**Comment by prasanth-varikallu** [comment]
Hello I followed the example from the above link to create a raw xml for my wsdl. I couldn't generate any raw xml. I modified the request slightly to have None as the 3rd argument. 

from zeep import Client

client = Client('http://my-endpoint.com/production.svc?wsdl')
node = client.create_message(client.service, 'myOperation', None)
print(node)

The response is as follows:
<Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x279506089c8>

Can you please tell what's my mistake?

**Comment by ewh** [comment]
@prasanth-varikallu I'm _very_ new to zeep, so I may not be recommending the best practice, but you can try a couple approaches:
* Simple: 
`from zeep.wsdl.utils import etree_to_string`
`etree_to_string(soap_message).decode()`

* Approach which gives a bit more control over the formatting: 
`from lxml import etree`
`etree.tostring(soap_message, pretty_print=True, xml_declaration=True, encoding='utf-8').decode()`

(I learned the second approach by looking at the implementation of helper function `etree_to_string`.)

Hope this helps.

**Comment by sunil2985** [comment]
@andreixk I need help how to save output of zip client service into xml right now its in json formate.
below is the command I am using, also attached snapshot of output I am getting
client.service.Ib440ConfigGet()
![Snip20200921_111](https://user-images.githubusercontent.com/29259787/93753445-c950fa80-fc1d-11ea-95bd-55842034808b.png)

**Comment by ccurvey** [comment]
to get the values dumped to stdout...

```
import zeep

wsdl = 'http://www.soapclient.com/xml/soapresponder.wsdl'
client = zeep.Client(wsdl=wsdl)
print(client.service.Method1('Zeep', 'is cool'))

node = client.create_message(
    client.service, 'Method1', bstrParam1='hello', bstrParam2='world')

from lxml import etree as ET
tree = ET.ElementTree(node)
print(ET.tostring(tree))
```

**Comment by airatbakiev** [comment]
I need the hash of the xml being sent in order to insert that hash into the header. To do this, before sending the request, I wanted to receive the generated xml request using create_message. But create_message sends a request. You can see it in wireshark. I need to avoid sending request when generating xml. How to do it?
