### ISSUE TITLE
Duplicate Body within SOAP request message

### ISSUE THREAD

**Issue by dacut** [mvantellingen/python-zeep#479]
This is happening on both Python 2.7 and Python 3.6. Zeep version is 2.2.0 (`zeep-2.2.0-py2.py3-none-any.whl`), installed via pip.

This is from a NOAA service whose WSDL lists an incorrect endpoint, so I've patched the WSDL here: https://tidal-harmonics.s3-us-west-2.amazonaws.com/ActiveStationsFixed.wsdl

Sample script that fails:

    import zeep
    active_stations = zeep.Client("https://tidal-harmonics.s3-us-west-2.amazonaws.com/ActiveStationsFixed.wsdl")
    active_stations.service.getActiveStationsV2()

Results in:

    zeep.exceptions.Fault: No such operation 'Body'

This is an issue when creating the request:

    >>> env = active_stations.create_message(active_stations.service, "getActiveStationsV2")
    <Element {http://schemas.xmlsoap.org/soap/envelope/}Envelope at 0x10a90de60>
    >>> env.getchildren()
    [<Element {http://schemas.xmlsoap.org/soap/envelope/}Body at 0x10a90d998>]
    >>> env.getchildren()[0].getchildren() # Should be empty here
    [<Element {http://schemas.xmlsoap.org/soap/envelope/}Body at 0x10a8bd0e0>]

As you can see, there's an extra body within the body. The resulting SOAP message looks like:

    DEBUG:zeep.transports:HTTP Post to https://opendap.co-ops.nos.noaa.gov/axis/services/ActiveStations:
    <?xml version='1.0' encoding='utf-8'?>
    <soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
      <soap-env:Body>
        <soap-env:Body/>
      </soap-env:Body>
    </soap-env:Envelope>

**Comment by mvantellingen** [comment]
Should be fixed! Thanks

**Comment by M1hacka** [comment]
Got the same error on 2.5.0 (current pypi version).
Sorry for no working example, I can't distribute it
Code:
```python
from zeep import Client
url = 'http://someurl'
client = Client(url)
auth_service = client.bind('SomeService')
# Expects xsd:string, xsd:string as AuthorisationRequest
auth_res = auth_service.AuthoriseUser('user', 'pwd')
```

Generated xml:
```xml
<?xml version='1.0' encoding='utf-8'?><br>
<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
   <soap-env:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
      <wsa:Action>http://someurl/AuthoriseUser</wsa:Action>
      <wsa:MessageID>urn:uuid:89de8c51-4966-4a06-b3f0-5d3c67858043</wsa:MessageID>
      <wsa:To>http://someurl.svc</wsa:To>
   </soap-env:Header>
   <soap-env:Body>
     <soap-env:Body>
         <ns0:User xmlns:ns0="http://tempuri.org/">user</ns0:User>
         <ns1:Password xmlns:ns1="http://tempuri.org/">pwd</ns1:Password>
      </soap-env:Body>
   </soap-env:Body>
</soap-env:Envelope>
```
