### ISSUE TITLE
No such operation:  (HTTP GET PATH_INFO: /kfe/services/energy-data)

### ISSUE THREAD

**Issue by boumboum** [mvantellingen/python-zeep#482]
I have this code:
```
from zeep import Client
client = Client("http://rpclient.oebb.at/kfe/services/energy-data?wsdl")
service = client.create_service("{http://kfe.oebb.at/kfe/energy-data-1.0}EnergyDataSoapBinding","0")
resp = service.ping()
```
If I run it I have this error message:
`Fault: No such operation:  (HTTP GET PATH_INFO: /kfe/services/energy-data)`

It I try to run it over Chrome'§s Boomerang extension I have the same error message if I run it with POST or GET but it works if I run it with OPTIONS.
Hot to change the http method to OPTIONS of the request is sent to the server?

**Comment by mvantellingen** [comment]
Please provide more info (way more)

**Comment by boumboum** [comment]
Well, I cannot.
I can consume other SOAP webservices, but that one does not work. And unfortunately I have to work with that one (obviously not with the ping service but the "real" ones).
Interesting thing is that a PHP program using SOAPClient (python equivalent is more or less pysimplesoap) works well but none of the python libs (zeep, pysimplesoap or suds) is working out of the box.
This is the code
```
from zeep import Client
client = Client("http://rpclient.oebb.at/kfe/services/energy-data?wsdl")
service = client.create_service("{http://kfe.oebb.at/kfe/energy-data-1.0}EnergyDataSoapBinding","http://rpclient.oebb.at/kfe/services/energy-data") ''' because the wsdl is erroneous'''
resp = service.ping()
```
An this is the error message:
```
Traceback (most recent call last):
  File "<ipython-input-7-f5de791a6f47>", line 1, in <module>
    runfile('C:/Temp/energydata.py', wdir='C:/Temp')
  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Temp/energydata.py", line 11, in <module>
    resp = service.ping()
  File "C:\Anaconda3\lib\site-packages\zeep\client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "C:\Anaconda3\lib\site-packages\zeep\wsdl\bindings\soap.py", line 121, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Anaconda3\lib\site-packages\zeep\wsdl\bindings\soap.py", line 178, in process_reply
    return self.process_error(doc, operation)
  File "C:\Anaconda3\lib\site-packages\zeep\wsdl\bindings\soap.py", line 280, in process_error
    detail=fault_node.find('detail'))
Fault: No such operation:  (HTTP GET PATH_INFO: /kfe/services/energy-data)
```
If I execute this with the Chrome extension Boomerang it works.
This is the request from Boomerang:
```
OPTIONS http://rpclient.oebb.at/kfe/services/energy-data HTTP/1.1

Content-Type: text/xml; charset=utf-8
SOAPAction: {N/A}

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ene="http://kfe.oebb.at/kfe/energy-data-1.0">
    <x:Header/>
    <x:Body>
        <ene:ping/>
    </x:Body>
</x:Envelope>
```

An this is the expected result:
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ed:pingResponse xmlns:ed="http://kfe.oebb.at/kfe/energy-data-1.0">
            <ed:return>
                <ed:code>0</ed:code>
                <ed:description>Everything ok</ed:description>
                <ed:name>OK</ed:name>
            </ed:return>
        </ed:pingResponse>
    </soap:Body>
</soap:Envelope>
```
But it only works if I change the request method to OPTIONS. If I leave it to POST, I have the same error message.
I know the issue is with the server, but I cannot change it. I have to use it.
And I don't understand why the PHP code is working without any magic.

So how can I get access to that SOAP service (changing the request method to OPTIONS or any other way)?

**Comment by boumboum** [comment]
coulc you maybe test if you have the same error? (If so, maybe you can solve it)

**Comment by mvantellingen** [comment]
I think this is some configuration error on the server side. It also doesn't seem to work with soap-ui
Your best bet is to check with the supplier of the service. It just isn't right that it only works with OPTIONS

**Comment by mvantellingen** [comment]
Also, perhaps you can workaround it by using a custom transport class in zeep. But really, the server should be fixed :-)

**Comment by boumboum** [comment]
As I told you, I cannot change the server side code.
And also. If we access to the same server/webservice with a PHP code (soapclient). it works out of the box.
I only have problem out of our python  code.
