### ISSUE TITLE
[Question & Issue] : Issue while Creating XML with WSDL

### ISSUE THREAD

**Issue by dhinchakdhoom** [mvantellingen/python-zeep#483]
Following is the XSD ,
```
<xs:complexType name="process">
	<xs:sequence>
		<xs:element minOccurs="0" maxOccurs="unbounded" name="Attribute">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string">
						<xs:attribute name="AttributeName" type="xs:NMTOKEN"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
		<xs:element minOccurs="0" maxOccurs="unbounded" name="Array">
			<xs:complexType>
				<xs:sequence>
					<xs:element minOccurs="0" maxOccurs="unbounded" name="ArrayAttribute">
						<xs:complexType>
							<xs:simpleContent>
								<xs:extension base="xs:string">
									<xs:attribute name="ArrayAttributeName" type="xs:NMTOKEN"/>
								</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="ArrayName" type="xs:NMTOKEN"/>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>
```

Following is the get_type Output
``` 
client.get_type("process")
process(Attribute: {xsd:string, AttributeName: xsd:NMTOKEN}[], Array: {ArrayAttribute: {xsd:string, ArrayAttributeName: xsd:NMTOKEN}[], ArrayName: xsd:NMTOKEN}[])
```

Which is programmatically never be possible!!
As Dictionary will not be able to take value with (,)

Expected Output XML : 
```
<Attribute AttributeName="text">text</Attribute>
<Array ArrayName="text">
<ArrayAttribute ArrayAttributeName="text">text</ArrayAttribute>
</Array>
```
```
#When I tried with something like this : 
process={
    'Attribute': (
        ['text',{"AttributeName": 'text'}]
    )
}

#I got below output : 
<process>
<Attribute>tex11<Attribute>
<Attribute AttributeName="text2"><Attribute>
<process>
```

If I use anything else I am getting exception as : 
`NMToken does not Accept pair value Signature: 'xsd:string, name: xsd:NMTOKEN'`

**Comment by dhinchakdhoom** [comment]
@mvantellingen : I pasted the XSD, code, expected XML, the script that I used to create the XML. I am not sure what anything you want. Can you help me to understand your question? What example Script you need? If you are asking for WSDL, then this is not possible as access to WSDL is only from Intranet.

**Comment by mvantellingen** [comment]
When you create the issue it states that you need to supply an example script as explained on http://docs.python-zeep.org/en/master/reporting_bugs.html

I'm sorry to be so 'aggressive' about this, but zeep is a volunteer project and I have limited time available for it. So the one thing I can ask of people who are freely using my code is to at least make it easy for me to solve potential bugs.

**Comment by dhinchakdhoom** [comment]
Ok  @mvantellingen .
I pasted a client.wsdl.dump() on gist [here](https://gist.github.com/dhinchakdhoom/d5bfe12eb8762718d35ba2773b7170fb).
Have a look on it.
 I am using zeep version 2.2.0
An example of script for creating request is given above.


You are not 'aggressive' at all this project is a great project believe me. :+1:
