### ISSUE TITLE
SqliteCache does not timeout

### ISSUE THREAD

**Issue by molszowy** [mvantellingen/python-zeep#485]
Hi!

I've recently implemented the cache to improve performance and noticed that the cache doesn't expire for some reason after timeout. Could you please help to validate if I use SqliteCache() correctly ?

In my implementation I use a class which keeps self.__client which is an instance of zeep.Client() so that I can reuse it for every query:
```python
cache = SqliteCache(path='soap_wsdl_cache.db', timeout=30)

transport = Transport(session=session, timeout=self.timeout,
                                  operation_timeout=self.timeout, cache=cache)
self.__client = zeep.Client(self.wsdl, transport=transport)
```

The first time, WSDL is cached which is fine:

2017-06-27 11:38:56,534 zeep.cache Module="cache" Level="DEBUG" Cache MISS for https://xxxx?wsdl
2017-06-27 11:38:56,920 zeep.cache Module="cache" Level="DEBUG" Caching contents of https://xxxx?wsdl

after 30 seconds I don't see any MISS/HIT debugs, we don't query for WSDL again and we reuse the cache.

It seems that I have to create zeep.Client() with every query and then I can see that the cache is expired but I guess this shouldn't be the way to go

**Comment by molszowy** [comment]
@mvantellingen I would appreciate if you can look into this issue once you have some time.

**Comment by mvantellingen** [comment]
Can you do a PR with a unittest to highlight the issue? That would be appreciated from my end :-)

**Comment by molszowy** [comment]
I believe I misunderstood how zeep.Client was implemented. It seems that the wsdl is loaded only once when you initialize zeep.Client. I thought that it reloaded with every service operation.
In this case the cache is actually checked only when I instantiate a new Client object.

Can you confirm ?

**Comment by mvantellingen** [comment]
Yeah correct, when you instantiate the client then the wsdl is parsed (and cache is used)
