### ISSUE TITLE
Error when parsing iso8601 from Transportation based SIRI webservice.

### ISSUE THREAD

**Issue by ekarlso** [mvantellingen/python-zeep#486]
Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
zeep==2.2.0

2. The WSDL you are using
http://sis.kolumbus.no:90/VMWS/VMService.svc?wsdl

3. An example script
```
import logging

import arrow
from zeep import Client

logging.basicConfig(level="DEBUG")
client = Client("http://sis.kolumbus.no:90/VMWS/VMService.svc?wsdl")

ts = arrow.utcnow()
request = {
    "ServiceRequestInfo": {
        "RequestTimestamp": ts,
        "RequestorRef": "evry_poc"
    },
    "Request": {
        "version": "1.4",
        "RequestTimestamp": ts
    },
    "RequestExtension": []
}

print request
info = client.service.GetVehicleMonitoring(**request)
```

**Comment by mvantellingen** [comment]
Seems like the isodate module which zeep uses doesn't like negative durations. I've added a workaround for this and opened an issue on the isodate issue tracker.
