### ISSUE TITLE
Is there a quickstart for how to call services and real with non-scalar responses?

### ISSUE THREAD

**Issue by Trii** [mvantellingen/python-zeep#488]
Hi, this library looks great but I can't seem to find out how to deal with the results from a .NET SOAP service.

Assuming fake service called `TheServiceCall`, this is what I get back.
```python
{
    'TheServiceCallResult': {
        'schema': <Schema(location=None, tns=None)>,
        '_value_1': <Element {urn:schemas-microsoft-com:xml-diffgram-v1}diffgram at 0x10623cfc8>
    },
    'ErrorCode': 0L,
    'Error': 'Successful login'
}
```

How do I use this? `result.TheServiceCallResult._value_1` doesn't seem right

**Comment by pierresigwalt** [comment]
Same here, It's look like it's not able to add a schema for microsoft services:

` DEBUG 2017-07-06 12:06:05+0800 schema(335): Init schema document for None
 DEBUG 2017-07-06 12:06:05+0800 schema(297): Add document with tns None to schema 4438162736
 DEBUG 2017-07-06 12:06:05+0800 schema(437): register_element('NewDataSet', <Element(name='NewDataSet', type=<zeep.xsd.dynamic_types.NewDataSet object at 0x1088a6eb8>)>)
 DEBUG 2017-07-06 12:06:05+0800 schema(383): Resolving in schema <SchemaDocument(location=None, tns=None, is_empty=False)>`

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by Trii** [comment]
I'll have to find a public .NET soap service to use. I can't exactly give out the details for the one I am using.
