### ISSUE TITLE
Namespace in own element not recognized

### ISSUE THREAD

**Issue by macrojames** [mvantellingen/python-zeep#489]
Me again.

The AXIS server sends the follwing response:
```xml
<securityQuestionsAnswers xmlns:ns5="http://webservice.rsa.com" xsi:type="ns5:ArrayOf_tns725_NameValuePair" xsi:nil="true"/>
```

Zeep fails on parsing that response:
```python
  File "/xxx/venv/local/lib/python2.7/site-packages/zeep/utils.py", line 32, in as_qname
    raise XMLParseError("No namespace defined for %r" % prefix)
zeep.exceptions.XMLParseError: No namespace defined for 'ns5'
```

Is that invalid xml again? Or is it the order in the parsing that should check for a namespace first?

**Comment by mvantellingen** [comment]
That seems valid. But I will need an example script to help you resolving the issue.

**Comment by macrojames** [comment]
Thanks for looking into it.

[test_rsa_api_zeep.py.zip](https://github.com/mvantellingen/python-zeep/files/1118553/test_rsa_api_zeep.py.zip)

**Comment by macrojames** [comment]
Rough guess after another day of debugging:
complex.py:159
```python
elements = deque(xmlelement.iterchildren())
```
should be a generator expression where single elements can get their own nsmap if xmlns: is in their attribute list?
From the other code parts I can only guess the etree functions don't do that on their own?

**Comment by macrojames** [comment]
That was wrong. nsmap is already faulty there.
Can you give me a hint where to search @mvantellingen ?
I am still kinda lost after days of searching for the code :(

**Comment by macrojames** [comment]
The correct .nsmap for the node gets lost during
```python
process_multiref(body_element)
``` in wsdl/messages/soap.py

**Comment by mvantellingen** [comment]
Hi @macrojames, due too a bit busy schedule i haven't been able to dive into this. I'm afraid the earliest i can look at this is this weekend. So If you are able to submit a PR before that would be wonderful. Even creating a PR with a unittest which fails allows me to look at the issue maybe a bit faster. Hope you understand

**Comment by macrojames** [comment]
Hi. I understand.
I am on a good way to get that resolved, I found the actual call removing the nsmap for the node.
At the moment I have no clue how to preceed on fixing it but will send a PR if I find a solution.

**Comment by mvantellingen** [comment]
When I edit the response and change ``ArrayOf_tns725_NameValuePair`` to ``ArrayOf_tns717_NameValuePair`` it seems to work now. Not sure why the response is wrong, perhaps it is dynamically created per wsdl

**Comment by macrojames** [comment]
It works with your fix against the backend server.

I don't know what was wrong with my PR?
I started reimplementing your code, ended up with the same logic, improved with xpath searches for the namespaces instead of reg regex.
Why are you cloning the elements instead of moving the nodes? 
For big responses this could have a serious performance impact.

**Comment by mvantellingen** [comment]
afaik multiple nodes can use the same reference, so moving is not an option. I'm really open to any improvements on this so if you want to submit a new PR to fix performance issues then please do.
