### ISSUE TITLE
Optional tags not displayed when printing nodes

### ISSUE THREAD

**Issue by andreasblomqvist** [mvantellingen/python-zeep#490]
Hi

Trying to print the request xml for operations in a WSDL. Seems the nodes which have  doesn't get printed?

Heres is the code:

```
from lxml import etree
from zeep import Client

client= Client('http://www.webservicex.com/globalweather.asmx?WSDL')



for service in client.wsdl.services.values():
    for port in service.ports.values():
        operations = sorted(
        port.binding._operations.values(),
        key=operator.attrgetter('name'))

        for operation in operations:
            print operation.name
            node = client.create_message(client.service, operation.name)
            print etree.tostring(node, method='xml', pretty_print=True)
```

Running on an example WSDL : http://www.webservicex.com/globalweather.asmx?WSDL

The output is from the zeep script:

```
GetWeather
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:GetWeather xmlns:ns0="http://www.webserviceX.NET"/>
  </soap-env:Body>
</soap-env:Envelope>
```

But the same WSDL in soapUi shows the missing tags:

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:web="http://www.webserviceX.NET">
   <soap:Header/>
   <soap:Body>
      <web:GetWeather>
         <!--Optional:-->
         <web:CityName>?</web:CityName>
         <!--Optional:-->
         <web:CountryName>?</web:CountryName>
      </web:GetWeather>
   </soap:Body>
</soap:Envelope>
```

**Comment by mvantellingen** [comment]
Not sure where you want to go with this. If optional elements have no value then the element is not rendered in the XML.  

If you want to use zeep to create documentation then please see #110

**Comment by andreasblomqvist** [comment]
Hi

I want to print the entire request xml (including optional tags) because I use it to generate REST services in an API Gateway. I generate REST services for every operation found in the WSDL. The request xml is used to create a SOAP call from REST. 

by adding '?' to the client.create_message the parameter gets printed. Like this:

`node = client.create_message(client.service, operation.name, ?, ?)`

But then I need to know how many parameters there are. 

Right now I did this using groovy instead by the python and Zeep is much more suitable since I run everything thru Ansible. 

Would it be hard to make the client.create_message to include all parameters? 

Thx for your work!

**Comment by VMahipalReddy** [comment]
Hi @andreasblomqvist, did you find out any solution?
