### ISSUE TITLE
Implement an IS_AXIS compability flag to work with broken AXIS soap servers

### ISSUE THREAD

**Issue by mvantellingen** [mvantellingen/python-zeep#493]
The AXIS soap server is broken and still seems to be used a lot. So we can now pass strict=false to zeep to workaround it somewhat by not parsing unexpected elements, an IS_AXIS flag might just process xsd:sequence as xsd:all when it is set

**Comment by macrojames** [comment]
While i considered to start working on this, I came to the conclusion `xsd:all` is not a correct solution.
AXIS requires all the elements, they are just in a different order.
They sort the elements after the inclusion of all extensions in their wsdl alphabetically.
That shouldn't change any requirements, just a sorting is applied before sending the response.

**Comment by Jitsusama** [comment]
FYI; I found this JIRA on AXIS; https://issues.apache.org/jira/browse/AXIS-2677

It looks like it's an issue with an application utilizing AXIS that doesn't properly implement the Java interface files from their built WSDL or some such.

**Comment by Jitsusama** [comment]
@mvantellingen; out of curiosity, are there any plans to take a look at this soon? I'd be willing to even take a look at doing it myself, but I would probably require some pointers around the parts of code that I should look at.
