### ISSUE TITLE
how to handle WSDL with no service defined ?

### ISSUE THREAD

**Issue by deronnax** [mvantellingen/python-zeep#496]
Some SOAP servers issue WSDL files with no service tag, hence triggering the `ValueError: There is no default service defined` error. For Example, Microsoft Exchange Server does such thing. What would be the recommended way to deal with those aliens ?

1. The version of zeep (or if you are running master the commit hash/date)
2.2.0
2. The WSDL you are using
https://gist.github.com/deronnax/080f4af9c55bea70d3bd98757f4df572
3. An example script
Any method call

**Comment by deronnax** [comment]
Okay:
http://docs.python-zeep.org/en/master/client.html#creating-new-serviceproxy-objects

**Comment by TaylorAnswrth** [comment]
What params did you give for create_service?

**Comment by deronnax** [comment]
Didn't use it finally, stuck to suds

**Comment by andreabisello** [comment]
@deronnax  same problem here,
with a wsdl without any binding tags. was you able to solve the problem? maybe with suds-py3 ? thanks

**Comment by deronnax** [comment]
As I said in the previous comment, I stuck with suds. Btw, I don't work with soap anymore, I can't help you (or anyone).

**Comment by andreabisello** [comment]
@deronnax  i hate soap.

**Comment by deronnax** [comment]
if your company force you to use SOAP, consider leaving :D

**Comment by andreabisello** [comment]
@deronnax  ha ha, i agree, but this is a old implementation :)
