### ISSUE TITLE
Zeep WSSE Utils should support Zulu timestamps

### ISSUE THREAD

**Issue by tseminivan** [mvantellingen/python-zeep#498]
In zeep (2.2.0)

Currently get_timestamp returns the pytz isoformat() with `+00:00` whereas the XML schema for timestamps also allows for the Zulu time `Z` (re: http://books.xmlschemata.org/relaxng/ch19-77049.html)

**Comment by JanCejka** [comment]
I get **OSB-386200: General web service security error** when format of Created timestamp in UsernameToken is in the 2019-12-16T08:27:20.299+00:00 format. If format is "2019-12-16T08:27:20.299Z", everything works as expected. I have provided pull request #1037 to solve this.

**Comment by mvantellingen** [comment]
Fixed in master
