### ISSUE TITLE
Better distinction between global elements and complex types

### ISSUE THREAD

**Issue by mvantellingen** [mvantellingen/python-zeep#5]
Take for example the following schema
```xml
<?xml version="1.0"?>
<schema>
  <element name="SomeRequest">
    <complexType>
      <all>
        <element ref="tns:account"/>
      </all>
    </complexType>
  </element>
  <complexType name="account">
    <sequence>
      <element name="balance" type="int"/>
    </sequence>
  </complexType>
  <element name="account">
    <complexType>
      <sequence>
        <element name="id" type="int"/>
        <element name="user" type="string"/>
      </sequence>
    </complexType>
  </element>
</schema>
```
The only way to create this request is by using:
```python
client.get_element('tns:account').type(id=1, user='foo')
client.service.SomeRequest(obj)
```
Using the following would cause an error in this case.
```python
client.get_type('tns:account')(id=1, user='foo')
client.service.SomeRequest(obj)
```
So this means the user needs to have an understanding of the xsd schema, which should not be the case.

**Comment by postfalk** [comment]
Thank you. I guess I am not too familiar with the SOAP specification and I think all these quirks are the reason why it fell out of favor. Nevertheless, there are a lot of legacy API's out there. Thank you for your work it helps me a lot. Maybe, I will have a look anyways.
