### ISSUE TITLE
Question: how to create empty element which is a choice with optional sequence

### ISSUE THREAD

**Issue by aviskase** [mvantellingen/python-zeep#503]
Hi, I'm not sure, it's a bug, or I'm just missing something.

zeep==2.2.0

This is a part of xsd:
![0720_003](https://user-images.githubusercontent.com/3819473/28391400-bdf39856-6cff-11e7-9cc1-cbe5834088f9.png)

Basically, there is choice between `Offer`/`ApartmentBuildingOwner`/`LivingHouseOwner`/`Organization`. For `LivingHouseOwner` there is a choice: `RegOrg` or `Ind` . And for `Ind` I have an option to make it empty element or complete with sequence.

It means, that I should be able to use (**option_1**):
```xml
<ns0:LivingHouseOwner>
    <ns0:Ind>
        <ns0:Surname>Pupkin</ns0:Surname>
    </ns0:Ind>
</ns0:LivingHouseOwner>
```
or this (**option_2**):
```xml
<ns0:LivingHouseOwner>
    <ns0:Ind/>
</ns0:LivingHouseOwner>
```

I have no problem with **option_1**:
```python
{'LivingHouseOwner': {'Ind': {'Surname': 'Pupkin'}}}
```

But cannot figure out, how to achieve **option_2**. I've tried this:
```python
{'LivingHouseOwner': {'Ind': {}}
```
but it ends with an error: `zeep.exceptions.ValidationError: Missing element Surname (importSupplyResourceContractRequest.Contract.Surname)`

These two are also no good:
```python
{'LivingHouseOwner': {'Ind': []}
{'LivingHouseOwner': {'Ind': None}
```
because they just end up with no `LivingHouseOwner` element in the message.

So, the question is, how can I achieve **option_2**?

**Comment by mvantellingen** [comment]
Can you try to use xsd.Nil

```
from zeep import xsd
{'LivingHouseOwner': {'Ind': xsd.Nil}}
```

**Comment by aviskase** [comment]
It raises exception:
```
.../venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 130, in parse_args
    raise TypeError("Choice elements only work with keyword arguments")
TypeError: Choice elements only work with keyword arguments
```

**Comment by mvantellingen** [comment]
Ok, if you can post an example script (which i can run locally) then i can see how we can solve this

**Comment by david9ppo** [comment]
Hi! I'm also getting this error: "TypeError: Choice elements only work with keyword arguments"
I have in my xsd a ID field and one choice between 2 elements where the minOccurs is zero at both of them. I think that zeep obliges me to have to invoke with one of the two elements of the choice.  It's a bug? Thanks you in advance ;)

**Comment by aviskase** [comment]
Hi.
I've managed to create a simple gist for that wsdl: https://gist.github.com/aviskase/0b0025dd6045c1bf0867c6491e887cfb

Working example:
```python
from zeep import Client
from zeep.plugins import HistoryPlugin
from zeep import xsd

history = HistoryPlugin()
client = Client('http://localhost:8088/mockAgreementServiceSoap?wsdl', plugins=[history])
a = client.service.CreateAgreement(Agreement={'Owner': {'Ind': {'Surname':'Pupkin', 'FirstName': 'Vasya'}}})
```

Not working example (but should be valid):
```python
from zeep import Client
from zeep.plugins import HistoryPlugin
from zeep import xsd

history = HistoryPlugin()
client = Client('http://localhost:8088/mockAgreementServiceSoap?wsdl', plugins=[history])
a = client.service.CreateAgreement(Agreement={'Owner': {'Ind': xsd.Nil}})
```

Error:
```
.../venv/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 236, in validate
    "Missing element %s" % (self.name), path=render_path)
zeep.exceptions.ValidationError: Missing element FirstName (CreateAgreementRequest.Agreement.FirstName)
```

Request for reference:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:agr="http://example.com/agreement">
   <soapenv:Header/>
   <soapenv:Body>
      <agr:CreateAgreementRequest>         
         <agr:Agreement>           
            <agr:Owner>
               <agr:Ind></agr:Ind>
            </agr:Owner>
         </agr:Agreement>
      </agr:CreateAgreementRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

zeep==2.4.0
