### ISSUE TITLE
WSSE (x509) documentation poor

### ISSUE THREAD

**Issue by nerdoc** [mvantellingen/python-zeep#506]
Using zeep 2.2.0, I am just testing the connection to my SOAP server, which is HTTPS, with a CA signed cert. I have the two certs (the root, signing CA, and the cert of the service) in my local directory and try to execute the following example script:

```
from zeep import Client
from zeep.wsse.signature import Signature

c = Client('https://192.168.0.50/servicemanager/1?wsdl', wsse=Signature(
    "private_key_filename.cer", "public_key_filename.cer"
    ))
```

But I always get the error:

    requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

No matter what I do. I suppose I don't use the certificate keys right - is there any more information on how I use that keys? Do they have to be in  `.cer` format, or in `.pem`? I only have a RootCA and a "Production CA" certificate file, so separate keys. They are used to be imported in the browser to see that server's pages - which works perfectly. But with zeep I can't access that service.

While my problem is not really a bug report, the "bug" is the lacking documentation - maybe you can add some lines explaing the usage of the keys?

**Comment by mvantellingen** [comment]
This error is on the transport layer and not a wsse error. 
See http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification for setting your cert. And http://docs.python-zeep.org/en/master/transport.html#transports for changing the request settings in zeep.

Also remember, it's an opensource project. Help to improve the documentation is really appreciated. So i'm open to pull requests with improvements

**Comment by nerdoc** [comment]
Ok, thanks. That't what I forgot to offer (and why I made a "bug" out of it): I'd love to improve the docs, If I find out how ;-)
So expect a PR here. Thanks again.

**Comment by aggsol** [comment]
@nerdoc  Did you find out how work it? I also have some PEM and JKS files and I am unsure how to use them. The docs does not mention JKS at all.

**Comment by nerdoc** [comment]
No, sorry.
