### ISSUE TITLE
Configurable service endpoint IP adress

### ISSUE THREAD

**Issue by nerdoc** [mvantellingen/python-zeep#511]
Using zeep 2.2.0. I happen to have to talk to a server which I can't control, so I have to take the WSDL files I get from it. At the bottom of the WSDL file (I get online):

```
<service name="ServiceManager">
  <port name="servicemanager_1" binding="tns:servicemanager_1Binding">
    <soap:address location="http://localhost/servicemanager/1"/>
  </port>
</service>
```

So, my dumb server *always* sends "localhost" as hostname. I can't change that. I've been told that SOAP clients "generally" should be able to change that IP address. Although I am not convinced if that makes sense, it could be helpful for complex situations where the server is connected to by a tunnel, so the hostname it provides in the WSDL file is not applicable.

I hereby ask, does it make sense to implement a `override_endpoint_hostname` attribute for the client that does exactly this?
Michael, please just tell me what you think here, and if yes, I could try and write some code.

**Comment by mvantellingen** [comment]
Please see http://docs.python-zeep.org/en/master/client.html#creating-new-serviceproxy-objects

The documentation might not be perfect but it does contain a lot of information.

**Comment by nerdoc** [comment]
Ah - completely missed this one. Thanks.

**Comment by nerdoc** [comment]
Ah - completely missed this one. Thanks.

**Comment by mvantellingen** [comment]
Yeah for each service. Most wsdl's only have one service defined though

**Comment by nerdoc** [comment]
OK, right. Thanks.
