### ISSUE TITLE
Zeep is returning Empty arrays

### ISSUE THREAD

**Issue by aius2** [mvantellingen/python-zeep#512]
Zeep Version: 2.2.0

WSDL : http://www.innovaphone.com/wsdl/pbx10_00.wsdl

Sent and Recived XML : https://gist.github.com/aius2/3d04855c932fc36877fb07f0168cb131

Code Example:
```python
session = Session()
session.auth = HTTPBasicAuth('admin', 'ip411')
transport_with_basic_auth = Transport(session=session)


client = zeep.Client(wsdl='C:/.../pbx10_00.wsdl',transport=transport_with_basic_auth,strict=False)
Inno_return = client.service.Initialize('soap','Python',True,True,True,True,True)

Inno_user = client.service.Poll(Inno_return['return'])
print (Inno_user)
```

Output:
{
    'user': [],
    'call': [],
    'reg': [],
    'info': []
}

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.
