### ISSUE TITLE
Issue with empty array

### ISSUE THREAD

**Issue by aficustree** [mvantellingen/python-zeep#516]
1. The version of zeep (or if you are running master the commit hash/date)
2.2

I have an object called WSContext that is provided a return to an SOAP call, in the WSDL it's noted as:

`ns2:WSContext(contextId: ns1:string, contextType: ns1:string, filter: ns1:string, firstResultPos: xsd:int, internalResultCount: xsd:int, maxResults: xsd:int, options: ns0:ArrayOf_xsd_string, query: ns1:string, resultCount: xsd:int)`

Within the context of the return, the server actual responses back with 

`<options xsi:type="soapenc:string" xsi:nil="true" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"/>`

When I go to pass the response as a parameter, the validation fails as option element has min_occurs set to '1'. I'm fairly new to python and can't figure out how to adjust the client to allow min_occurs to equal 0. Can you assist?

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.
