### ISSUE TITLE
Attribute Error Parsing WDSL from National Rail

### ISSUE THREAD

**Issue by edwinj85** [mvantellingen/python-zeep#523]
Hi there

I'm using Zeep 2.2.0 on Windows 10 (x64) running Python 3.6
The WDSL I am using is https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx
My example script is:

```
from zeep import Client
client = Client(wsdl="https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx")
```

This gives this error, every time:

**zeep\xsd\elements\indicators.py", line 632, in __init__
    self.name = name.localname
AttributeError: 'str' object has no attribute 'localname'**

This works fine when I use that WDSL with Suds, SoapUI or a .Net project as a service reference.

**Comment by mvantellingen** [comment]
Should be fixed on master!

**Comment by edwinj85** [comment]
I can confirm this fixes it. Thank you very much :)
