### ISSUE TITLE
Error parsing server response

### ISSUE THREAD

**Issue by Elektroi** [mvantellingen/python-zeep#525]
I am using zeep 2.2.0
This is the wsdl that I am using [link] (https://github.com/knutster/OCPP/blob/master/ocpp_centralsystemservice_1.5_final.wsdl) or [ocpp_centralsystemservice_1.5.txt](https://github.com/mvantellingen/python-zeep/files/1199824/ocpp_centralsystemservice_1.5.txt)

The raw response tell me that the server return ok code and the information is there but it have problems to parse the response.

`ERROR:root:Server returned HTTP status 200 (<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"  xmlns:tns="urn://Ocpp/Cs/2012/06/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa5="http://www.w3.org/2005/08/addressing"><soap:Header><tns:chargeBoxIdentity SOAP-ENV:mustUnderstand="true">id1234</tns:chargeBoxIdentity><wsa5:Action SOAP-ENV:mustUnderstand="true">/BootNotificationResponse</wsa5:Action></soap:Header><soap:Body><tns:bootNotificationResponse><tns:status>Accepted</tns:status><tns:currentTime>2013-02-01T15:09:18Z</tns:currentTime><tns:heartbeatInterval>1200</tns:heartbeatInterval></tns:bootNotificationResponse></soap:Body></soap:Envelope>)`

**Comment by krasswez** [comment]
Hey, I myself have only just started using zeep, so don't know how helpful I can be.
But have you tried passing  `strict=False` when instantiating the Client?. I guess when on strict, the parser will look for `<soap:Envelope ... >` to be the document root, if not, it might accept anoter document root.

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.
