### ISSUE TITLE
Having trouble with a Part response

### ISSUE THREAD

**Issue by krasswez** [mvantellingen/python-zeep#531]
I am having trouble with a response I receive. I receive this content (this is what zeep prints as response content for the `TransportError` it raises (i have left out some stuff that is just content, as I would say it is not relevant here):

`------=_Part_208_5901714.1502282321643`
`Content-Type: application/xop+xml; charset=utf-8; type="application/soap+xml"`

`<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/><env:Body><ect:getServiceNumberGroupRS xmlns:ect="http://www.ect-telecoms.de/"> ... </ect:getServiceNumberGroupRS></env:Body></env:Envelope>`
`------=_Part_208_5901714.1502282321643--`

1. I am running zeep version 2.2.0
2. The WSDL I am using is I cannot disclose here.
3. Don't know if an example script will help here, but:

`from zeep import Client, exceptions`
`from zeep.wsse.username import UsernameToken`

`wsdlEFF = 'proxy/test/effectiveService.wsdl'`
`clientEFF = Client(wsdl=wsdlEFF, wsse=UsernameToken('XXXXX', 'XXXXX')`

`print (clientEFF.service.getServiceNumberGroup("10293755"))`

My question is this: Is the service not implemented correctly when it is sending this part response? Or is zeep just not able to handle it correctly? soapUI does not show an error for the same request, so I guess zeep is simply having problems parsing this response. I have been looking for issues similar to mine but I could not find any, so I opened this one.

I would be very glad if someone could help out here.

Regards,
Felix

**Comment by mvantellingen** [comment]
To look at this I really need an example script including the wsdl and xml. Otherwise I can only guess what is going wrong :(
