### ISSUE TITLE
cisco AXL api executeSQLQuery return Element pkid at 0x1f4c56b88c8 but postman return the right value that i need

### ISSUE THREAD

**Issue by luosw0001** [mvantellingen/python-zeep#539]
when i call cisco AXL api executeSQLQuery with "select * from device", 
i get somthing like [[<Element pkid at 0x1f4c568f508>, <Element name at 0x1f4c568f548>, <Element description at 0x1f4c568f588>, <Element tkmodel at 0x1f4c568f5c8>]]

but i use postman, i get what i need:
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <ns:executeSQLQueryResponse xmlns:ns="http://www.cisco.com/AXL/API/11.5">
            <return>
                <row>
                    <pkid>36e94f58-8987-4514-9bf4-dfe43bddfc51</pkid>
                    <name>Sample Device Template with TAG usage examples</name>
                    <description>#FirstName# #LastName# (#Product# #Protocol#)</description>
                    <tkmodel>645</tkmodel>
                    <tkdeviceprotocol>11</tkdeviceprotocol>
                    <tkprotocolside>1</tkprotocolside>
                    <specialloadinformation/>
                    <fkdevicepool>1b1b9eb6-7803-11d3-bdf0-00108302ead1</fkdevicepool>
                    <fkphonetemplate>1f9180ed-d6f1-417d-96f0-a57c42f20665</fkphonetemplate>
                    <fkcallingsearchspace/>
                    <ctiid>1</ctiid>
                    <tkclass>1</tkclass>
                    <fkprocessnode/>
                    <defaultdtmfcapability>0</defaultdtmfcapability>
                    <fklocation>29c5c1c4-8871-4d1e-8394-0b9181e8c54d</fklocation>
                    <tkproduct>530</tkproduct>
                    <dialplanwizardgenid/>
                    <deviceleveltraceflag>f</deviceleveltraceflag>
                    <fkenduser>b073f5f5-8c5b-4e1a-8e2a-604953903655</fkenduser>
                    <allowhotelingflag>f</allowhotelingflag>
                    <tkdeviceprofile>0</tkdeviceprofile>
                    <ikdevice_defaultprofile/>
                    <fkmediaresourcelist/>
                    <userholdmohaudiosourceid/>
                    <networkholdmohaudiosourceid/>
                    <unit>0</unit>
                    <subunit>0</subunit>
                    <tkcountry/>
                    <tkuserlocale/>
                    <tkproduct_base/>
                    <fkcallingsearchspace_aar/>
                    <fkaarneighborhood/>
                    <fksoftkeytemplate/>
                    <retryvideocallasaudio>t</retryvideocallasaudio>
                    <routelistenabled>f</routelistenabled>
                    <fkcallmanagergroup/>
                    <tkstatus_mlppindicationstatus>2</tkstatus_mlppindicationstatus>
                    <tkpreemption>2</tkpreemption>
                    <tkstatus_builtinbridge>2</tkstatus_builtinbridge>
                    <mtprequired>f</mtprequired>
                    <tkqsig>4</tkqsig>
                    <tkpacketcapturemode>0</tkpacketcapturemode>
                    <packetcaptureduration>0</packetcaptureduration>
                    <authenticationstring/>
                    <tkcertificatestatus>1</tkcertificatestatus>
                    <upgradefinishtime/>
                    <fkmlppdomain/>
                    <transmitutf8>f</transmitutf8>
                    <ignorepi>f</ignorepi>
                    <tknetworklocation>2</tknetworklocation>
                    <v150modemrelaycapable>f</v150modemrelaycapable>
                    <tkcertificateoperation>1</tkcertificateoperation>
                    <fksecurityprofile>1cd2cb25-c9f6-4786-a38f-1cf02de290ee</fksecurityprofile>
                    <fkdialrules/>
                    <fkcallingsearchspace_reroute/>
                    <fkcallingsearchspace_refer/>
                    <unattended_port>f</unattended_port>
                    <tkdtmfsignaling>1</tkdtmfsignaling>
                    <requiredtmfreception>f</requiredtmfreception>
                    <publickey/>
                    <fksipprofile>fcbc7581-4d8d-48f3-917e-00b09fb39213</fksipprofile>
                    <rfc2833disabled>f</rfc2833disabled>
                    <allowcticontrolflag>t</allowcticontrolflag>
                    <datetimeinserted/>
                    <sshpassword/>
                    <sshuserid/>
                    <fkcallingsearchspace_restrict/>
                    <fkmatrix_presence>ad243d17-98b4-4118-8feb-5ff2e1b781ac</fkmatrix_presence>
                    <fkcommonphoneconfig>ac243d17-98b4-4118-8feb-5ff2e1b781ac</fkcommonphoneconfig>
                    <tkkeyauthority>0</tkkeyauthority>
                    <tksipcodec_mtppreferredorigcodec>1</tksipcodec_mtppreferredorigcodec>
                    <md5hash/>
                    <srtpallowed>f</srtpallowed>
                    <isstandard>f</isstandard>
                    <resettoggle>f</resettoggle>
                    <tkreset>2</tkreset>
                    <versionstamp>0000000000-c7a6c673-7479-46b0-839e-014d3d093963</versionstamp>
                    <fkcommondeviceconfig/>
                    <huntlistforvm>f</huntlistforvm>
                    <remotedevice>f</remotedevice>
                    <tkstatus_devicemobilitymode>2</tkstatus_devicemobilitymode>
                    <dndtimeout>0</dndtimeout>
                    <tkdndoption>2</tkdndoption>
                    <tkringsetting_dnd/>
                    <isdualmode>f</isdualmode>
                    <fkcallingsearchspace_cgpntransform/>
                    <fkenduser_mobility>b073f5f5-8c5b-4e1a-8e2a-604953903655</fkenduser_mobility>
                    <tkoutboundcallrollover>0</tkoutboundcallrollover>
                    <tkphonepersonalization>3</tkphonepersonalization>
                    <tkstatus_joinacrosslines>2</tkstatus_joinacrosslines>
                    <tkbarge>3</tkbarge>
                    <tkstatus_usetrustedrelaypoint>2</tkstatus_usetrustedrelaypoint>
                    <istrustedrelaypoint>f</istrustedrelaypoint>
                    <srtpfallbackallowed>f</srtpfallbackallowed>
                    <ispaienabled>t</ispaienabled>
                    <isrpidenabled>t</isrpidenabled>
                    <tksipprivacy>0</tksipprivacy>
                    <tksipassertedtype>0</tksipassertedtype>
                    <fkcallingsearchspace_cdpntransform/>
                    <usedevicepoolcdpntransformcss>t</usedevicepoolcdpntransformcss>
                    <nationalprefix>Default</nationalprefix>
                    <internationalprefix>Default</internationalprefix>
                    <unknownprefix>Default</unknownprefix>
                    <subscriberprefix>Default</subscriberprefix>
                    <usedevicepoolcgpntransformcss>t</usedevicepoolcgpntransformcss>
                    <ikdevice_primaryphone/>
                    <tkstatus_audiblealertingidle>2</tkstatus_audiblealertingidle>
                    <tkstatus_audiblealertingbusy>2</tkstatus_audiblealertingbusy>
                    <isactive>t</isactive>
                    <tkphoneservicedisplay>3</tkphoneservicedisplay>
                    <isprotected>f</isprotected>
                    <fkmobilesmartclientprofile/>
                    <tkstatus_alwaysuseprimeline>2</tkstatus_alwaysuseprimeline>
                    <tkstatus_alwaysuseprimelineforvm>2</tkstatus_alwaysuseprimelineforvm>
                    <callednationalprefix>Default</callednationalprefix>
                    <calledinternationalprefix>Default</calledinternationalprefix>
                    <calledunknownprefix>Default</calledunknownprefix>
                    <calledsubscriberprefix>Default</calledsubscriberprefix>
                    <callednationalstripdigits/>
                    <calledinternationalstripdigits/>
                    <calledunknownstripdigits/>
                    <calledsubscriberstripdigits/>
                    <fkcallingsearchspace_callednational/>
                    <fkcallingsearchspace_calledintl/>
                    <fkcallingsearchspace_calledunknown/>
                    <fkcallingsearchspace_calledsubscriber/>
                    <hotlinedevice>f</hotlinedevice>
                    <fkgeolocation/>
                    <fkgeolocationfilter_lp/>
                    <sendgeolocation>f</sendgeolocation>
                    <nationalstripdigits/>
                    <internationalstripdigits/>
                    <unknownstripdigits/>
                    <subscriberstripdigits/>
                    <fkcallingsearchspace_cgpnnational/>
                    <fkcallingsearchspace_cgpnintl/>
                    <fkcallingsearchspace_cgpnunknown/>
                    <fkcallingsearchspace_cgpnsubscriber/>
                    <usedevicepoolcalledcssnatl>t</usedevicepoolcalledcssnatl>
                    <usedevicepoolcalledcssintl>t</usedevicepoolcalledcssintl>
                    <usedevicepoolcalledcssunkn>t</usedevicepoolcalledcssunkn>
                    <usedevicepoolcalledcsssubs>t</usedevicepoolcalledcsssubs>
                    <pstnaccess>f</pstnaccess>
                    <fkvipre164transformation/>
                    <usedevicepoolcgpntransformcssnatl>t</usedevicepoolcgpntransformcssnatl>
                    <usedevicepoolcgpntransformcssintl>t</usedevicepoolcgpntransformcssintl>
                    <usedevicepoolcgpntransformcssunkn>t</usedevicepoolcgpntransformcssunkn>
                    <usedevicepoolcgpntransformcsssubs>t</usedevicepoolcgpntransformcsssubs>
                    <fkfeaturecontrolpolicy/>
                    <runonallnodes>f</runonallnodes>
                    <enableixchannel>f</enableixchannel>
                    <tkdevicetrustmode>0</tkdevicetrustmode>
                    <usedevicepoolrdntransformcss>t</usedevicepoolrdntransformcss>
                    <fkcallingsearchspace_rdntransform/>
                    <enablebfcp>f</enablebfcp>
                    <requirecerlocation>f</requirecerlocation>
                    <usedevicepoolcgpningressdn>t</usedevicepoolcgpningressdn>
                    <fkcallingsearchspace_cgpningressdn/>
                    <earlyoffersupportforvoicecall>f</earlyoffersupportforvoicecall>
                    <enablegatewayrecordingqsig>f</enablegatewayrecordingqsig>
                    <calreference>-1</calreference>
                    <tkcalmode/>
                    <ndescription>#FirstName# #LastName# (#Product# #Protocol#)</ndescription>
                    <msisdn/>
                    <fkwirelesslanprofilegroup/>
                    <enablecallroutingtordwhennoneisactive>f</enablecallroutingtordwhennoneisactive>
                    <fkwifihotspotprofile/>
                    <allowcfbcontrolofcallsecurityicon>f</allowcfbcontrolofcallsecurityicon>
                    <fkelingroup/>
                    <ecpublickeycurve/>
                    <lscvaliduntil>0</lscvaliduntil>
                    <lscissuername/>
                    <lscissuervaliduntil>0</lscissuervaliduntil>
                </row>

i want to know how to get the right result from zeep?

**Comment by mvantellingen** [comment]
Please format your issue and add an example script as requested. I can't do anything with this 😞

**Comment by jonathanelscpt** [comment]
This is not an issue.  You need to use the `serialize_object` method to extract the data.  I am doing the same with `executeSQLQuery ` and Thin AXL and have this working without issue.

**Comment by vaibhavsolanki1193** [comment]
Just to add what @jonathanelscpt  said, if you get response like `<Element pkid at 0x2469884c908>` you can always convert it to text format using `.text` if you extract relevant information and parse zeep output

**Comment by gjhinson** [comment]
I'm having the same issue as luosw0001. the output of my SQL Query via ciscoaxl in python is:


My code is as follows::
cmd = "select device.name AS DeviceName......" <== abbreviated
sql = ucm.sql_query(query=cmd)
print(sql)

Using the above 3 lines of code, my output is this:
'row': [
        [
            <Element devicename at 0x108403d88>,
            <Element extension at 0x1084030c8>,
            <Element linedescription at 0x1084031c8>,
            <Element linecss at 0x108403248>
....

How do I convert the 0x108... following the word "at" on each line to readable text? For example, what script commands would I add to convert the above data to the literal values below:

<Element devicename at XFER-to-VM2>,
<Element extension at **XXXX>,
<Element linedescription at XFER-to-VM>,
<Element linecss at css-device>

**Comment by gilmar-gms** [comment]
I'm using the example below:
https://afterthenumber.com/2018/04/27/serializing-thin-axl-sql-query-responses-with-python-zeep/comment-page-1/

I hope this helps you

**Comment by vanirtech** [comment]
> I'm using the example below:
> https://afterthenumber.com/2018/04/27/serializing-thin-axl-sql-query-responses-with-python-zeep/comment-page-1/
> 
> I hope this helps you

Yeah, that's my blog.  Glad others found it useful.

**Comment by jonathanelscpt** [comment]
> I'm using the example below:
> https://afterthenumber.com/2018/04/27/serializing-thin-axl-sql-query-responses-with-python-zeep/comment-page-1/
> 
> I hope this helps you

That's my blog.  Glad it helped you.
