### ISSUE TITLE
pip install error (python 2.7)

### ISSUE THREAD

**Issue by morocarlo** [mvantellingen/python-zeep#543]
Hi, i'm having some problems on debian with python 2.7.9. When i try to install the package i receive this errors:

```
pip install zeep

Compiling /tmp/pip-build-PTbceX/zeep/zeep/asyncio/bindings.py ...
  File "/tmp/pip-build-PTbceX/zeep/zeep/asyncio/bindings.py", line 8
    async def send(self, client, options, operation, args, kwargs):
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-PTbceX/zeep/zeep/asyncio/transport.py ...
  File "/tmp/pip-build-PTbceX/zeep/zeep/asyncio/transport.py", line 44
    async def _load_remote_data_async():
            ^
SyntaxError: invalid syntax
```

**Comment by mvantellingen** [comment]
Do you have a complete backtrace? This seems to be missing a number of lines

**Comment by morocarlo** [comment]
`user@Server:~# pip install zeep
Downloading/unpacking zeep
  Downloading zeep-2.3.0-py2.py3-none-any.whl (129kB): 129kB downloaded
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): defusedxml>=0.4.1 in /usr/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): isodate>=0.5.4 in /usr/local/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): requests-toolbelt>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.7.0 in /usr/local/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): cached-property>=1.3.0 in /usr/local/lib/python2.7/dist-packages (from zeep)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.0.0 in /usr/lib/python2.7/dist-packages (from zeep)
Installing collected packages: zeep
Compiling /tmp/pip-build-q1JWry/zeep/zeep/asyncio/bindings.py ...
  File "/tmp/pip-build-q1JWry/zeep/zeep/asyncio/bindings.py", line 8
    async def send(self, client, options, operation, args, kwargs):
            ^
SyntaxError: invalid syntax

Compiling /tmp/pip-build-q1JWry/zeep/zeep/asyncio/transport.py ...
  File "/tmp/pip-build-q1JWry/zeep/zeep/asyncio/transport.py", line 44
    async def _load_remote_data_async():
            ^
SyntaxError: invalid syntax

Successfully installed zeep
Cleaning up...
`

the strange thing is that it is working on my virtual machine and in other virtual machines, but not in one of our server

**Comment by arveitch** [comment]
The problem is that async is Python 3 and not present in Python 2.7

**Comment by morocarlo** [comment]
@arveitch ok.. but how can i make it working with python 2.7?

**Comment by arveitch** [comment]
@morocarlo I don't think it's a simple fix unfortunately. If you upgrade to Python 3 that will fix it.

Alternatively there are some old SOAP libraries that work with Python 2.7 but they are not as good as Zeep in my opinion.

@mvantellingen Do you plan to support Python 2.7 still with this library?

**Comment by mvantellingen** [comment]
Yeah Python 2.7 should still be supported. The issue seems that pip is compiling files it shouldn't compile since it is only for py3. 

This might have something do to with https://github.com/mvantellingen/python-zeep/commit/ebdbe1c3fcd20a73f355b4e27bfc4fa21240219b

Which pip version are you using? Since travis still runs py2 fine and locally it also still works

**Comment by morocarlo** [comment]
i have update the pip version, now it is working

**Comment by saper** [comment]
I have this issue again with 3.3.1 - not using pip, but simple `python2.7 setup.py install` fails with the same message. It tries to bytecompile 3.5+ files on 2.7.

More information:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229496

Complete build log from 3.0.0 (but I get the same with 3.3.1):

https://people.freebsd.org/~pi/logs/devel__py-zeep-cur-1530682232.txt

I think we should simply exclude those files on non-async pythons....

**Comment by saper** [comment]
Reverting https://github.com/mvantellingen/python-zeep/commit/ebdbe1c3fcd20a73f355b4e27bfc4fa21240219b does not help. I have also tried

````
+pkg = find_packages('src')
+pkg.remove('zeep.asyncio')

 setup(
     name='zeep',
@@ -77,7 +86,7 @@ setup(
     },
     entry_points={},
     package_dir={'': 'src'},
-    packages=['zeep'],
+    packages=pkg,
````

**Comment by saper** [comment]
Do we even try `python2.7 setup.py install` in the CI somewhere? Can't find it in https://dev.azure.com/mvantellingen/zeep/_build/results?buildId=85&view=logs
