### ISSUE TITLE
[question] Is it possible to validate a xml file against a wsdl?

### ISSUE THREAD

**Issue by skpilar** [mvantellingen/python-zeep#551]
Hi,

I do have the following scenario: I get 2 wsdl files and have to map the content
My steps:
 1. Generate request from wsdl1 via zeep 
 2. transform request via xslt (lxml)
 3. Validate transormed request xslt against wsdl2 (hopefully via zeep)

As this is currently in design time I cannot actually send the transformed xml to the server.

So my question is:
 Is it possible to validate a xml against a wsdl (with zeep)?

Kind Regards
 Simon

**Comment by mvantellingen** [comment]
That was initially the idea, to validate the generated xml against the lxml schemas. Unfortunately this turned out to be pretty much impossible due to the fact that lxml is too strict :-(
