### ISSUE TITLE
Question about client.set_address

### ISSUE THREAD

**Issue by catastrophe-brandon** [mvantellingen/python-zeep#554]
As I was trying to work with zeep for a work-related project, I noticed that the ancient SOAP service I'm trying to interact with provides a different endpoint URL than is specified in the WSDL. Some google searches turned up a means to override the one specified in the wsdl via client.set_address. However, as I was searching through release notes, it seems that this might have been removed?

```0.11.0 (2016-07-03)
-------------------
 - **backwards-incompatible**: The kwarg name for Any and Choice elements are
   renamed to generic ``_value_N`` names.
 - **backwards-incompatible**: Client.set_address() is replaced with the
   Client.create_service() call
```
If this was removed, how would you recommend connecting to this service?

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
Version 2.3.0
2. The WSDL you are using
The URL of the WSDL is https://aodws.attendanceondemand.com:8192/cc1.aew/wsdl/IAeXMLBridge
3. An example script
[Here you go](https://gist.github.com/catastrophe-brandon/7c4f7595a1ff6966f386872df2f6c6b4)

**Comment by catastrophe-brandon** [comment]
Basically - is the syntax for create_service() identical to set_address()? Is there any example code?

**Comment by catastrophe-brandon** [comment]
After crawling through documentation I *think* I may have found what I needed. Here is the example I came up with:

```
binding_qname = '{http://tempuri.org/}IAeXMLBridgebinding'
service = client.create_service(binding_qname
    , soap_endpoint)
```

**Comment by mvantellingen** [comment]
Yeah that is the correct usage indeed. This might need some clarification in the documentation. 

Are you able to help me with that?

**Comment by anaselli** [comment]
i seem i cannot be able to use client.create_service, i maybe missed something

**Comment by catastrophe-brandon** [comment]
Sorry for the delay responding, it seems this notification was buried in a mountain of others! I have some example code that's specific to my implementation, but I could take a stab at documenting it. Once I have something I'll put together a PR.

**Comment by catastrophe-brandon** [comment]
@anaselli You may want to take a look at "Creating new ServiceProxy Objects" in [this document](https://media.readthedocs.org/pdf/python-zeep/master/python-zeep.pdf). Here's the example that set me on the right path: 

```
from zeep import Client
from zeep import xsd
client = Client('http://my-endpoint.com/production.svc?wsdl')
service = client.create_service(
'{http://my-target-namespace-here}myBinding',
'http://my-endpoint.com/acceptance/')
service.submit('something')
```

I was a little rusty on my SOAP, so I didn't get this working until I figured out that I needed to explicitly provide the namespace for the binding, shown above as `{http://my-target-namespace-here}`. Once I figured that out everything started working nicely.

**Comment by catastrophe-brandon** [comment]
As this was really a failure on my part to understand the documentation, I think this issue can be closed.

**Comment by anaselli** [comment]
I followed that documentation :) Tomorrow i'll ask if i can publish our wsdl if needed, but my problem is that even if the service seems to be set when i call the service operation i get the URL http://www.example.org/ (url contained into my wsdl) content as response with a fault (i can't remember if with an exception or not)
So in my case, '{http://my-target-namespace-here}myBinding' seems to be correct while 'http://my-endpoint.com/acceptance/' does nothing or does not what i expect.
