### ISSUE TITLE
BST support not present

### ISSUE THREAD

**Issue by omgommt** [mvantellingen/python-zeep#561]
In this module, why BST support is not present as your py-soap-wsse module supports BST?
I have to use both py-soap-wsse and python-zeep in case of BST signing of xml request.

Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
2. The WSDL you are using
3. An example script

Also please don't paste WSDL/XSD file contents directly into the issue since 
that makes it hard to read, instead please create a gist at 
https://gist.github.com and link that here.

Please see http://docs.python-zeep.org/en/master/reporting_bugs.html for 
more information.

**Comment by mvantellingen** [comment]
It is supported, see http://docs.python-zeep.org/en/master/wsse.html#signature-x509

If there are issues with it can you then please open a detail issue description (and please put some effort into it)
