### ISSUE TITLE
How to set attribute and value to the same element?

### ISSUE THREAD

**Issue by harmonik001** [mvantellingen/python-zeep#564]
Hello,

I havent exactly bug, rather cant set dictinoary for specific instance. I try to search in your documentation or in the internet articles or discussion, but no success. Maybe, its a trifle and I'm a fool.

I would like to prepare the right dictionary in zepp, which describe element "SENDER". This element have a value and also the attribute, like this: <Sender CI_InstanceNumber="01">0080</Sender>

I found some examples, where are elements with attribute, but without value, like this: <element1 attr="01"><element2>0080</element2></element1>.

My script can assing the attribute to to element, but cant assing the value to the same element. Please, could you help me? 

The request, which is sent: <ns0:Sender ns0:CI_InstanceNumber="01">None</ns0:Sender> 

And I need: <ns0:Sender ns0:CI_InstanceNumber="01">0080</ns0:Sender> 

Thank you for any help or information about this. I'm sorry if the issue is stupid, and wasting your time.

Martin

----

1. zeep version: 2.3.0
2. provoz.szdc.cz/kadrws/taftsi2_1.asmx?WSDL
3. script:

client = Client('http://provoz.szdc.cz/kadrws/taftsi2_1.asmx?WSDL')
node = client.create_message(client.service, 'CZRequestOnAvailableIDMessage', 
message = 
	{
		'MessageHeader': {
		    'MessageReference': {
	            'MessageType': '1000',
	            'MessageTypeVersion': '2.1',
	            'MessageIdentifier' : 'kzc',	    
	            'MessageDateTime' : datetime.datetime.utcnow(),	    
	    	},
    	'Sender': {
        	'CI_InstanceNumber': '01'},  
	    },
    	'AllPathsOfTheCompany': "false",
    	'PathModificationDate': datetime.datetime.utcnow(),
	})           
  
return (etree.tostring(node, pretty_print=True))

**Comment by harmonik001** [comment]
The solution is simple as ussualy:)

    	'Sender': {
        	'CI_InstanceNumber': 'attribute_value',
            '_value_1': 'element_value'}, 

Martin

**Comment by mvantellingen** [comment]
Yeah the whole _value_x thing is still mwehhhhh :-)

**Comment by kiriharu** [comment]
Maybe add this example to docs? I wasted 6 hours to find this :(
