### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by orzilca** [mvantellingen/python-zeep#57]
Is it possible to create a "debug mode"?

I want to be able to see the XML request before it is sent.
It very hard to debug requests without actually seeing it..

**Comment by mvantellingen** [comment]
Currently not really. I agree that this might be something I want to add in the future.

You can for now subclass the Transport class and add logging in the post/get calls (https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/transports.py#L36)

**Comment by abhidotnet** [comment]
You could realize that objective by using a tool like Wireshark or Fiddler.

**Comment by YAmikep** [comment]
:+1: 
Being able to easily see the actual XML from the response would be nice as well.

**Comment by donaldharvey** [comment]
You could always use `requests`' HTTP and urllib3 logging to see the XML:
http://stackoverflow.com/a/16630836/70011

**Comment by mvantellingen** [comment]
http://docs.python-zeep.org/en/latest/transport.html#debugging should fix this now

**Comment by mvantellingen** [comment]
For reference: the HistoryPlugin offers better support for this
