### ISSUE TITLE
Zeep image problem

### ISSUE THREAD

**Issue by pashute** [mvantellingen/python-zeep#570]
Zeep image is reminiscent of a swastika. 

As someone who had 114 immediate family (up to first cousins) killed on my mothers side (including my grandmother's brother, my grandfather's twin sister, baby brother, parents and elderly grandparents) and more on my fathers side (my grandfather's brother and his family were murdered), I find the Zeep image disturbing.  So proposing the following fix...

![zeep](https://user-images.githubusercontent.com/1774131/30527572-245b393e-9c33-11e7-9780-51254138756d.png)

**Comment by mvantellingen** [comment]
Are you referring to the python logo? https://www.python.org/community/logos/

**Comment by pashute** [comment]
Sorry, I wasn't aware of the python logo. Although over 20 years developing had very little with python. 
Thank you for your great application.  And please disregard what I wrote.  The issue is with Python, and I don't think its something that can be easily changed.  :-S
