### ISSUE TITLE
Client Certificate authentication

### ISSUE THREAD

**Issue by vadivelkindhealth** [mvantellingen/python-zeep#573]
Hi,

Can I do a client certificate authentication with zeep? If so, can you provide an example of it?

Thanks!

**Comment by matthiask** [comment]
```
import requests
from zeep import Client
from zeep.transports import Transport

session = requests.Session()
session.cert = os.path.join(...., 'clientcert.pem')
transport = Transport(session=session)

....

client = Client(SERVICE_URL, transport=transport)
```

More: http://docs.python-requests.org/en/master/user/advanced/#client-side-certificates

**Comment by HotSwap** [comment]
I got it working as follows:

`#!/usr/bin/python

from requests import Session
from zeep import Client
from zeep.transports import Transport
#from zeep.wsse.username import UsernameToken

session = Session()
session.cert = './certs/your_client_cert.pem'
transport = Transport(session=session)
client = Client('SERVICE_URL',transport=transport)

with client.options(raw_response=True):
    response = client.service.sendSms(foo='bar', bar='foo')

    print response.content

    # response is now a regular requests.Response object
    #assert response.status_code == 200
    #assert response.content
`

Hope it helps....

**Comment by mvantellingen** [comment]
Thanks for answering @matthiask !

**Comment by canojim** [comment]
session.cert = (public_key_filename, private_key_filename)
