### ISSUE TITLE
Problem with missing files and wrong path

### ISSUE THREAD

**Issue by ogenstad** [mvantellingen/python-zeep#584]
I'm trying out zeep and want to access the soap-api for [BCC](https://www.incognito.com/products/broadband-command-center/). My problems started early on...

## Problem 1

```python
from zeep import Client
wsdl = 'http://[my_ip]:8998/axis2/services/IncSecurityService?wsdl'
client = Client(wsdl)
```

This failed with a 404 error to reach the xsd file. While the wsdl files it processed it points to the xsd file like this:

```xml
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://bcc.incognito.com/wsdl/IncSecurity" xmlns:ns="http://bcc.incognito.com/IncSecurity" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="IncSecurity" targetNamespace="http://bcc.incognito.com/wsdl/IncSecurity">
<types>
<xsd:schema targetNamespace="http://bcc.incognito.com/wsdl/IncSecurity">
<xsd:import namespace="http://bcc.incognito.com/IncSecurity" schemaLocation="IncSecurity.xsd"/>
</xsd:schema>
</types>
```

Since the `schemaLocation` is a relative path zeep tries to access it on this url where it isn't located:
http://[my_ip]:8998/axis2/services/IncSecurity.xsd

The vendor says that the server doesn't contain those files and that I have to bring my one ones from their sdk. I solved this by an ugly hack by just editing xsd/visitor.py (https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/xsd/visitor.py#L161-L162) like this:

```python
        if location:
            location = 'file:///Users/patrick/src/bcc-soap/local_xsd/' + location
            location = absolute_location(location, self.document._base_url)
```

What I would like is to be able to tell zeep that my schemaLocation's with a relativ path should be picked up from a location that I choose. It could be that this is possible and I just have to go through all the code? If not I could send in a PR to add this as an option. In that case it would be great if you could let me know where I can add this. Would it be acceptable to add a new keyword to the Client class? (https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/client.py#L116-L118)

## Problem 2
The second issue was that the wsdl files pointed to an incorrect url for the service and I got an error when I:

```python
creds = client.service.login(username, password)
```
There were two errors in the wsdl files.

Example 1:
```xml
<service name="IncSecurityService">
<port name="IncSecurityPort" binding="tns:IncSecurityBinding">
<soap:address location="http://localhost:8080/axis2/services/IncSecurityService"/>
</port>
</service>
````
Example 2:
```xml
<service name="DHCPServiceService">
<port name="DHCPServicePort" binding="tns:DHCPServiceBinding">
<soap:address location="http://localhost:8998/axis2/services/DHCPServiceService"/>
</port>
</service>
```
The problem here is that both of the services point to localhost instead of the actual ip I'm trying to reach, this is statically defined in the wsdl files. Also an additional problem is that one of the services even changes the port number, both should be `[my_ip]:8998`. This I solved with another ugly hack in wsdl/bindings/soap.py (https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/wsdl/bindings/soap.py#L112-L113)

```python
        real_address = options['address']
        real_address = real_address.replace('localhost:8080', '[my_ip]:8998')
        real_address = real_address.replace('localhost:8998', '[my_ip]:8998')
        response = client.transport.post_xml(
            real_address, envelope, http_headers)
```

While the above works I don't want to use a hacked version of Zeep instead I want to be able to solve this with a released version. Would the above be possible in the current version, or can you point me in the direction for where this should be solved?

Thanks!

**Comment by ogenstad** [comment]
I figured out how to solve this by passing in a custom Transport class.

**Comment by barbich** [comment]
hi
could ou explicit what you did for creating your custom Transport class?

tx

**Comment by ogenstad** [comment]
@barbich, it basically looked like this:

```python
class ChTransport(Transport):

    def __init__(self, wsdl):
        self.__base_target = wsdl
        super(ChTransport, self).__init__()

    def load(self, url):
        if 'axis2/services/' in url and '.xsd' in url:
            file_name = url.split('/')[-1]
            url = xsd_location + file_name
        return super(ChTransport, self).load(url)

    def post(self, address, message, headers):
        if 'localhost' in address:
            p = urlparse(self.__base_target)
            address = address.replace('localhost:8080', p.netloc)
            address = address.replace('localhost:8998', p.netloc)
        return super(ChTransport, self).post(address, message, headers)
```

Then I would call it like this:

```python
trans = ChTransport(wsdl)
client = Client(wsdl, transport=trans)
```
