### ISSUE TITLE
Error:zeep.exceptions.TransportError: Server returned HTTP status 415 (no content available)

### ISSUE THREAD

**Issue by jprobineau** [mvantellingen/python-zeep#589]
Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
==>2.4.0
2. The WSDL you are using
==>https://public-dis-stage.dpd.nl/Services/LoginService.svc?singlewsdl
3. An example script
from zeep import Client

wsdl_url = "https://public-dis-stage.dpd.nl/Services/LoginService.svc?singlewsdl"
client = Client(wsdl_url)
res = client.service.getAuth('login', 'pwd')

Also please don't paste WSDL/XSD file contents directly into the issue since 
that makes it hard to read, instead please create a gist at 
https://gist.github.com and link that here.

Please see http://docs.python-zeep.org/en/master/reporting_bugs.html for 
more information.

**Comment by mvantellingen** [comment]
Please create better issues. Zeep seems to do the correct thing here
