### ISSUE TITLE
Invalid tag name

### ISSUE THREAD

**Issue by Tharyrok** [mvantellingen/python-zeep#594]
Hello,
when a tag contains a final space there is an exception "Invalid tag name"

WSDL: http://api5.silverpop.com/SoapApi?wsdl
XSD: http://api5.silverpop.com/SoapApi/_resources_/xsd/Reporting1.xsd
SCRIPT: https://gist.github.com/Tharyrok/1e209441bde8122d525a331ed691a8eb

Error: 
```
ValueError: Invalid tag name 'AGGREGATE_SUPPRESSIONS '
```

**Comment by mvantellingen** [comment]
I'm afraid we can't fix that since this is an lxml issue. You might want to submit an issue there.

**Comment by jean152** [comment]
I stumbled accross the same issue and I was able to resolve it with a workaround (I strip the value to remove leading or trailing whitespaces):

Into '**zeep/utils.py**', I modified the "**as_qname**" method as follow:

`def as_qname(value, nsmap, target_namespace=None):`
    `"""Convert the given value to a QName"""`

    ## Workaround: if any leading and/or ending whitespaces are present, remove them
    ## strip whitespaces
    value = value.strip()
    ## End of workaround

    if ':' in value:
        prefix, local = value.split(':')

        # The xml: prefix is always bound to the XML namespace, see
        # https://www.w3.org/TR/xml-names/
        if prefix == 'xml':
            namespace = 'http://www.w3.org/XML/1998/namespace'
        else:
            namespace = nsmap.get(prefix)

        if not namespace:
            raise XMLParseError(
                "No namespace defined for %r (%r)" % (prefix, value))

        # Workaround for https://github.com/mvantellingen/python-zeep/issues/349
        if not local:
            return etree.QName(XSD, 'anyType')

        return etree.QName(namespace, local)

    if target_namespace:
        return etree.QName(target_namespace, value)

    if nsmap.get(None):
        return etree.QName(nsmap[None], value)
    return etree.QName(value)`
