### ISSUE TITLE
IndexError : No definition in 'messages' found while Parsing the WSDL

### ISSUE THREAD

**Issue by saurabhkr85** [mvantellingen/python-zeep#600]
1. zeep version = 2.4.0
2. wsdl = https://www.mbibeta.com/MBIWebServices/Employer/Services/EmployerService.svc?WSDL
3.  from zeep import CachingClient
     client = CachingClient(wsdl)

command to reproduce the error: `python -m zeep https://www.mbibeta.com/MBIWebServices/Employer/Services/EmployerService.svc?WSDL`

Alternatge WSDL URL = https://gist.github.com/saurabhkr85/308c262e5feb142859fcd446ee5e6f83#file-test-wsdl

stacktrace: https://gist.github.com/saurabhkr85/391ef553ad3fb7e783813cdd924a31aa

**Comment by saurabhkr85** [comment]
@mvantellingen

**Comment by mvantellingen** [comment]
You can see a lot of warnings when you execute the command that it can't find parts (mbiMessageIdHeader). I'm also unable to open the wsdl with soap-ui so my initial conclusion is that the wsdl is invalid
