### ISSUE TITLE
Add an option to disable HTTPS forcing

### ISSUE THREAD

**Issue by Julienh** [mvantellingen/python-zeep#605]
Hello,

I'm using the last version of zeep, for an API I can call a service in HTTPS but in internal some calls are in HTTP and zeep force to HTTPS, so I have a 404 error. If I'm using the HTTP service it's works.

Is it possible to add an option to disable the "force_https" please?

Thank you,
Julien

**Comment by mvantellingen** [comment]
Added

**Comment by Julienh** [comment]
Thank you Michael !
