### ISSUE TITLE
Use of xml_huge_tree

### ISSUE THREAD

**Issue by nathan30** [mvantellingen/python-zeep#606]
Hi,

I'm currently runnin Zeep 2.4.0 and I need some help with the xml_huge_tree param. 

The problem I have is when I have to send large pdf files using SOAP WebService, I have the following issue : 

>  XML error on line 2 col 10970669 byte 10970774 No memory

After some research, I found that the problem came from libxml in the newest version. Reading the Zeep doc, I found the xml_huge_tree param. So I try to use it like this, in my python script : 

```
def get_wsclient(url, host, port, username, password):
    client = None
    session = Session()
    session.auth = HTTPBasicAuth(username, password)
    try:
        client = Client(url, transport=Transport(session=session), strict=False, xml_huge_tree=True)
    except Exception as e:
        print(e)
    return client
```

But the problem remain, and I have the same error

Any ideas ?

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.
