### ISSUE TITLE
Double <soap:Body> elements written into SOAP Request?

### ISSUE THREAD

**Issue by jospradlin** [mvantellingen/python-zeep#608]
ZEEP VERSION:  2.4.0
WSDL Used:  https://gist.github.com/jospradlin/0d698dce469af5e9abdf15d1355bb8e3
EXAMPLE SCRIPT:

###########################################
from zeep import Client
from zeep import xsd
import logging.config

logging.config.dictConfig({
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(name)s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'zeep.transports': {
            'level': 'DEBUG',
            'propagate': True,
            'handlers': ['console'],
        },
    }
})

client = Client('https://cppm1055.ondemand.ca.com/niku/wsdl/Query/abc-cmdb-environmentnodes')
sessionId = client.service.Login("ServiceLoginXXXXXX","ServicePasswordYYYYY")
header_type = client.get_element("ns0:Auth")
header = header_type(SessionID=sessionId)
body_type = client.get_type('ns0:abc-cmdb-environmentnodesQuery')
body_data = body_type(Code="abc_cmdb_exp_envservers")

execute_and_get_results = client.service.Query(body=body_data,header=xsd.SkipValue,_soapheaders=[header])

###########################################

The main issue I'm having is that upon 'client.service.Query(...)' -- when the XML Request is sent to the  SOAP Service, there are two <soap:Body> elements that are being written into the Request.    (NOTE:  The Transport DEBUG elements show the XML sent to the server.)

<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
<soap-env:Header>
<ns0:Auth xmlns:ns0="http://www.niku.com/xog/Query">   
<ns0:SessionID>XXXXXXXXX__-YYYYYYYYYYYYYY</ns0:SessionID>
</ns0:Auth>
</soap-env:Header>
**<soap-env:Body>**_<soap-env:Body>_
<ns0:Query xmlns:ns0="http://www.niku.com/xog/Query"><ns0:Code>sprje02_cmdb_exp_envservers</ns0:Code></ns0:Query>
**</soap-env:Body>**_</soap-env:Body>_
</soap-env:Envelope>

Is this common to the Zeep library in 2.4.0?    Any ideas on resolving this, since it's likely being generated in the Transport?  

Would overriding 'post_xml(address, envelope, headers)' (in Transport) get around this?

Thanks!

**Comment by mvantellingen** [comment]
Could you please format your issue correctly?
