### ISSUE TITLE
method name or namespace not recognized

### ISSUE THREAD

**Issue by nikeighley** [mvantellingen/python-zeep#61]
This may be a faulty SOAP server but I'm seeing this stack dump

  File "./X.py", line 42, in getAlarms
    soap_response = client.service.GetCurrentState (sessionName)
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 23, in __call__
    self._proxy._client, self._op_name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/definitions.py", line 292, in send
    client, self.binding_options, operation, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/soap.py", line 94, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/soap.py", line 123, in process_reply
    return self.process_error(doc)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/soap.py", line 202, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: Method 'ns0:GetCurrentState' not implemented: method name or namespace not recognized

for this code fragment

```
def getAlarms ():
	wsdl = 'data/AlarmSoap.wsdl'
	sessionName = ""

	client = zeep.Client (wsdl=wsdl)
	client.set_address('AlarmSoap', 'AlarmSoap', url)

	# GetCurrentState(sessionName: xsd:string) -> GetCurrentStateResponse
	soap_response = client.service.GetCurrentState (sessionName)
	print (soap_response)
```

WSDL attached
[AlarmSoap.txt](https://github.com/mvantellingen/python-zeep/files/306365/AlarmSoap.txt)

**Comment by mvantellingen** [comment]
Hi,

It works in soap-ui, so it's a bug in zeep. I'll take a better look at it later.

Thanks

**Comment by mvantellingen** [comment]
Ignore my last comment; it seems that the xml generated by zeep is identical to soap-ui. So it might be a server issue. Do you have a working xml example request?

**Comment by nikeighley** [comment]
If I've copied the correct bit out of a tcpdump

<soap-env:Envelope.xmlns:ns0="http://wsdl/AlarmSoap.wsdl".xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
    <soap-env:Body>
        <ns0:GetCurrentState>
             <sessionName></sessionName>
        </ns0:GetCurrentState>
    </soap-env:Body>
</soap-env:Envelope>

**Comment by nikeighley** [comment]
Extracted from a tcpdump
`
<soap-env:Envelope.xmlns:ns0="http://wsdl/AlarmSoap.wsdl".xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
    <soap-env:Body>
        <ns0:GetCurrentState>
             <sessionName></sessionName>
        </ns0:GetCurrentState>
    </soap-env:Body>
</soap-env:Envelope>
`

**Comment by nikeighley** [comment]
The error was in my driver library there is no problem with zeep. Thanks for your assistance

**Comment by mvantellingen** [comment]
Cool, thanks for letting me know 👍
