### ISSUE TITLE
problem installin pip zeep[xmlsec]

### ISSUE THREAD

**Issue by lopow** [mvantellingen/python-zeep#610]
Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
2. The WSDL you are using
3. An example script

Also please don't paste WSDL/XSD file contents directly into the issue since 
that makes it hard to read, instead please create a gist at 
https://gist.github.com and link that here.

Please see http://docs.python-zeep.org/en/master/reporting_bugs.html for 
more information.

**Comment by lopow** [comment]
I need zeep and xmlsec to accsec soap protocol with cetrificate. But I can not install xmlsec.
I got this error when installin: pip zeep[xmlsec]

fatal error C1047: The object or library file 'build\extra\iconv-1.14.win64\lib\iconv_a.lib' was created with an older compiler than other objects; rebuild old objects and libraries
    LINK : fatal error LNK1257: code generation failed
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX64\\x64\\link.exe' failed with exit status 1257

**Comment by Dedalios** [comment]
**pip install zeep[xmlsec]**

  error: HTTP Error 404: The specified blob does not exist.
    Retrieving "https://ci.appveyor.com/api/buildjobs/hij3a6776pdv2007/artifacts/libxml2-2.9.4.win64.zip" to "build




Requirement already satisfied: zeep[xmlsec] in c:\python37\lib\site-packages (3.2.0)
Requirement already satisfied: pytz in c:\python37\lib\site-packages (from zeep[xmlsec]) (2018.9)
Requirement already satisfied: requests-toolbelt>=0.7.1 in c:\python37\lib\site-packages (from zeep[xmlsec]) (0.8.0)
Requirement already satisfied: lxml>=3.1.0 in c:\python37\lib\site-packages (from zeep[xmlsec]) (4.3.0)
Requirement already satisfied: requests>=2.7.0 in c:\python37\lib\site-packages (from zeep[xmlsec]) (2.21.0)
Requirement already satisfied: attrs>=17.2.0 in c:\python37\lib\site-packages (from zeep[xmlsec]) (18.2.0)
Requirement already satisfied: appdirs>=1.4.0 in c:\python37\lib\site-packages (from zeep[xmlsec]) (1.4.3)
Requirement already satisfied: six>=1.9.0 in c:\python37\lib\site-packages (from zeep[xmlsec]) (1.12.0)
Requirement already satisfied: defusedxml>=0.4.1 in c:\python37\lib\site-packages (from zeep[xmlsec]) (0.5.0)
Requirement already satisfied: cached-property>=1.3.0 in c:\python37\lib\site-packages (from zeep[xmlsec]) (1.5.1)
Requirement already satisfied: isodate>=0.5.4 in c:\python37\lib\site-packages (from zeep[xmlsec]) (0.6.0)
Collecting xmlsec>=0.6.1; extra == "xmlsec" (from zeep[xmlsec])
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
Requirement already satisfied: idna<2.9,>=2.5 in c:\python37\lib\site-packages (from requests>=2.7.0->zeep[xmlsec]) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\python37\lib\site-packages (from requests>=2.7.0->zeep[xmlsec]) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python37\lib\site-packages (from requests>=2.7.0->zeep[xmlsec]) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python37\lib\site-packages (from requests>=2.7.0->zeep[xmlsec]) (1.24.1)
Requirement already satisfied: pkgconfig in c:\python37\lib\site-packages (from xmlsec>=0.6.1; extra == "xmlsec"->zeep[xmlsec]) (1.4.0)
Installing collected packages: xmlsec
  Running setup.py install for xmlsec ... error
    Complete output from command c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mistertoto\\AppData\\Local\\Temp\\pip-install-ut0szoa7\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mistertoto\AppData\Local\Temp\pip-record-3wxyx5gw\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    error: HTTP Error 404: The specified blob does not exist.
    Retrieving "https://ci.appveyor.com/api/buildjobs/hij3a6776pdv2007/artifacts/libxml2-2.9.4.win64.zip" to "build/extra\libxml2-2.9.4.win64.zip"

    ----------------------------------------
Command "c:\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mistertoto\\AppData\\Local\\Temp\\pip-install-ut0szoa7\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mistertoto\AppData\Local\Temp\pip-record-3wxyx5gw\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\mistertoto\AppData\Local\Temp\pip-install-ut0szoa7\xmlsec\
