### ISSUE TITLE
(SSLError("bad handshake....

### ISSUE THREAD

**Issue by lopow** [mvantellingen/python-zeep#614]
<code>
from requests import Session

from zeep import Client

from zeep.transports import Transport
 
session = Session()

session.verify = '....../files/key1.pem'

transport = Transport(session=session)

client = Client(
    'https://......./ws/test/PingWs?wsdl',
    transport=transport) 
</code>

This is my code. I try to connect to webservices with my certificate. web servisec are in SOAP protocol.

but I get this erorr:
`
 raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='evidim-test.gov.si', port=443): Max retries exceeded with url: /ws/test/PingWs?wsdl (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

`

**Comment by MiquelIR** [comment]
Since you don't explain what's your goal i'm not sure what you're trying to do but, shouldn't you use the "session.cert" param instead of the "session.verify"?
Verify is used to check the ssl handshake.
Cert is used to sign the message with a certificate. (i guess that's your goal)

Once your message is signed you can proceed to verify it with a CA bundle...

**Comment by lopow** [comment]
My goul is to send and get some data from server, with web servisec. Protocol for sending and recivieng is SOAP. I get all wsdl files, all xsd files. To the server I can only accssed with my certificate. I got *.pfx certificat, but with openssl I convert it to the one file .pem.

**Comment by MiquelIR** [comment]
Use this then:

session = Session()
**session.cert = '....../files/key1.pem'**
transport = Transport(session=session)
client = Client( 'https://......./ws/test/PingWs?wsdl', transport=transport)

**Comment by lopow** [comment]
ok, i have done, like you sugdest. When I run my code, I don't get any error. I get nothing. Nothing hapen, And when I add somthing to the got a get nothing.

**Comment by lopow** [comment]
can anyone help please?

**Comment by lopow** [comment]
previous i've got the wrong pem certificate, therefore nothing hapend. Now I tested my certificat with SoapUi and wokrs, 

But with zeep I got bad handshacke.

**Comment by mvantellingen** [comment]
See http://docs.python-zeep.org/en/master/transport.html#ssl-verification

**Comment by kaushikdr** [comment]
> previous i've got the wrong pem certificate, therefore nothing hapend. Now I tested my certificat with SoapUi and wokrs,
> 
> But with zeep I got bad handshacke.

@lopow The issue is from 2 years ago but I am facing the same thing now, can you please tell me how did you solve it? I've been trying to reach you over StackOverflow but unable to do so.

If anyone else faced a similar issue, please respond if you can help me figure out a solution.

**Comment by lopow** [comment]
I did not solve it. I was working on other project and this is current
frozen.
But i plan to resolve it if you manage it to do it will be glad to know how.

V sre., 23. okt. 2019 10:16 je oseba Swarna Koushik Debroy <
notifications@github.com> napisala:

**Comment by cjparisi** [comment]
I don't know if this will work for you, but I finally got it to work after seeing similar problems. I had to concatenate both the cert file and the key file together.  And set:

session.cert = 'path/to/concatenated_file/both.pem' and now it works great.
