### ISSUE TITLE
sha256 instead of sha1

### ISSUE THREAD

**Issue by shravanthium** [mvantellingen/python-zeep#616]
Hi,

Is is possible to use sha256 for WSSE XML Request instead of sha1?
1. The version of zeep - 2.4

**Comment by mvantellingen** [comment]
You mean for the binary security token part right? https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/wsse/signature.py#L183 ?

That seems like a good suggestion

**Comment by matrixl** [comment]
@shravanthium Do you have a solution for this? Our system also need to use SHA256 instead of SHA1.

**Comment by zbynekdrlik** [comment]
+1

**Comment by ylnunez84** [comment]
Hi, i have a similar problem, i have to use xmlsec.Transform.RSA_SHA256 instead of xmlsec.Transform.RSA_SHA1

**Comment by apollo13** [comment]
@mvantellingen I've attached a patch in #957 which allows specifying signature as well as digest methods. Please let me know what you think and were I should adjust :)

**Comment by ylnunez84** [comment]
Great! +1 . When this change is going to be available y pypi?

**Comment by apollo13** [comment]
When it's done. If you want to have it there faster you can always write docs, changelog etc for it. This is most likely not even merge ready yet
