### ISSUE TITLE
how to build restframework serializer from wsdl

### ISSUE THREAD

**Issue by backbohne** [mvantellingen/python-zeep#618]
Hi,

Would it (if yes how) be possible to create a django restframework serializer based on the WSDL with zeep?

Regards
Frank

**Comment by ovnicraft** [comment]
Hi, considering SOA term, REsT and SOAP are different protocols and will works with different clients.
Its better for your review your services.

**Comment by backbohne** [comment]
Sure, but there are a lot of similarities and it is possible to create a kind of ResT to SOAP Proxy. Anyway I found a solution which is working for me. Will provide a DRF-SOAP (or DRF-Zeep) module if I'm done here ...
Issue can be closed.
