### ISSUE TITLE
ImportError: cannot import name parse_qname

### ISSUE THREAD

**Issue by bingtel** [mvantellingen/python-zeep#622]
zeep==2.4.0  
`    
from zeep.utils import parse_qname
ImportError: cannot import name parse_qname
`
zeep/utils.py has no `parse_qname` function

**Comment by jean152** [comment]
Why is this a bug ? You try to import something that does not exist and so you receive an ImportError

If you check the source code of the zeep.utils file (https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/utils.py) you will see that the 'parse_qname' function does not exist.
