### ISSUE TITLE
Problem with py2exe

### ISSUE THREAD

**Issue by serure** [mvantellingen/python-zeep#636]
Hi. I´m using zeep 2.4.0 with Python 2.7.13 under Windows 7. When I execute the python script, everything works pefectly fine. But when I create a distributable version with an .exe file using py2exe, running the resulting application's .exe file terminates immediately creating a python error logfile with the message "cannot import name builtins".

I've tried explicitly including the zeep modules in the py2exe setup.py file, but whenever I analize py2exe's output it invariably sends a message about "the following modules appear to be missing" and it lists a lot of modules:
'packages.six.moves', 'packages.six.moves.http_client', 'packages.six.moves.urllib.parse', 
'packages.ssl_match_hostname.CertificateError', 'packages.ssl_match_hostname.match_hostname',
'packages.urllib3.contrib', 'pkg_resources.extern.appdirs', 'pkg_resources.extern.packaging',
'pkg_resources.extern.six', 'pkg_resources.extern.six.moves', 'queue', 'requests.packages.urllib3',
'requests.packages.urllib3.connection', 'requests.packages.urllib3.contrib',
'requests.packages.urllib3.util', 'simplejson', 'six.moves.urllib.parse', 'socks', 'urllib.parse',
'urllib.request', 'xmlrpc', 'xmlrpc.client', 'zeep.wsdl.messages.DocumentMessage', 
'zeep.wsdl.messages.RpcMessage', 'zeep.xsd.ComplexType', 'zeep.xsd.elements.Any', 
'zeep.xsd.elements.AnyAttribute', 'zeep.xsd.elements.AttributeGroup', 
'zeep.xsd.elements.Choice', 'zeep.xsd.elements.Element', 'zeep.xsd.elements.Group', 
'zeep.xsd.elements.Sequence'
I've tried including several zeep modules in the "packages" section of setup.py but it always ends up stating that such modules are missing. Are there any circular import references in your code? Have you had any other report with issues when freezing the code with py2exe?
Thanks for your help.

**Comment by mvantellingen** [comment]
Sorry, not planning to support this for now
