### ISSUE TITLE
Using ComplexType as dict

### ISSUE THREAD

**Issue by GreenSmile** [mvantellingen/python-zeep#643]
zeep==2.4.0

Hi,

I tried to use `zeep.objects.ComplexType` to update existing dict and it was treated as iterable of iterables as it doesn't have `keys` method.

Please considers the following small example:
```    
    xsd_type = xsd.ComplexType(
        xsd.Sequence([
            xsd.Element('en', xsd.String()),
            xsd.Element('fr', xsd.String())
        ]))

    obj = xsd_type(en='test', fr='test')

    print(obj)
    # {
    #    'en': 'test',
    #    'fr': 'test'
    # }

    print(type(obj))
    # <class 'zeep.objects.ComplexType'>

    result = {}
    result.update(obj)
    print(result)
    # {'e': 'n', 'f': 'r'}  Oops
````

Adding `keys` method solved the issue:
```
    obj.keys = lambda: ['en', 'fr']
    result = {}
    result.update(obj)
    print(result)
    # {'en': 'test', 'fr': 'test'}
```

Is it possible to add `keys` method to ComplexType, so it would be treated as dict?

Thanks for taking the time to look into this issue!

**Comment by mvantellingen** [comment]
The issue with adding methods to the CompoundValue object is that when an attribute 'keys' exists that it will then conflict. 

You can do ``result.update({key: obj[key] for key in obj})``

**Comment by GreenSmile** [comment]
Thank you for response. My data structure is rather big, so I wonder if there already is any function to convert zeep objects to multilevel dicts.

**Comment by GreenSmile** [comment]
Nevermind, found `zeep.helpers.serialize_object`.

http://docs.python-zeep.org/en/master/helpers.html
