### ISSUE TITLE
 "NotImplementedError: AnySimpleType.xmlvalue() not implemented"

### ISSUE THREAD

**Issue by fernandomv3** [mvantellingen/python-zeep#644]
Hi! I'm having trouble creating a request I'm attaching the wsdl dump since it's not public, I'm also attaching a sample xml request I'm trying to send

I believe the problem lies here

`ns5:ViewCriteriaItem(conjunction: ns5:Conjunction, upperCaseCompare: xsd:boolean, attribute: xsd:string, operator: xsd:string, ({value: xsd:anySimpleType[]} | {nested: ns5:ViewCriteria}))`

I'm using a factory to create this element I need to send

`crm = client.type_factory('ns5')

vci_n = crm.ViewCriteriaItem(
    conjunction='And',
    upperCaseCompare=False,
    attribute='PersonDEO_CTRNrodedocumento_c',
    operator='=',
    value= '43692004'
)

vci_t = crm.ViewCriteriaItem(
    conjunction='And',
    upperCaseCompare=False,
    attribute='PersonDEO_CTRTipodedocumento_c',
    operator='=',
    value= 'DNI'
)

vcr = crm.ViewCriteriaRow(item=[vci_n,vci_t])
vc = crm.ViewCriteria(conjunction = 'And',group=[vcr])
fc = crm.FindCriteria(filter = vc)

client.service.findContact(findCriteria=fc, findControl = {'retrieveAllTranslations':False})`

So the last line executes I get an error saying "NotImplementedError: AnySimpleType.xmlvalue() not implemented"

Is there something special I should do on the "value" field of ViewCriteriaItem since i'ts defined as AnySimpleType in the wsdl? or am I taking the wrong aproach here?

I'm using zeep 2.4.0

Thanks in advance

[xml_example.txt](https://github.com/mvantellingen/python-zeep/files/1570669/xml_example.txt)
[wsdl_dump.txt](https://github.com/mvantellingen/python-zeep/files/1570673/wsdl_dump.txt)

**Comment by jean152** [comment]
I believe this can help you:
https://github.com/mvantellingen/python-zeep/issues/418

**Comment by mvantellingen** [comment]
Should be fixed with c035390307fc0af119eae4c0a6d0d5550e4cd211
