### ISSUE TITLE
escape charater question

### ISSUE THREAD

**Issue by rainmanwy** [mvantellingen/python-zeep#645]
1. zeep version: 2.4.0

example script:
`content = '''
<?xml version="1.0" encoding="UTF-8"?>
        <REALTIMEPAY_REQ>
       
      </REALTIMEPAY_REQ>
'''
logging.config.dictConfig({
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(name)s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'zeep.transports': {
            'level': 'DEBUG',
            'propagate': True,
            'handlers': ['console'],
        },
    }
})
client = Client('http://10.8.200.28:8080/slfs/services/TransPayMentServiceImpl?WSDL')
header = xsd.ComplexType([xsd.Element('{Authorization}REALTIMEPAY_REQ', xsd.String())])
h = header(REALTIMEPAY_REQ='test')
r = client.service.transPayMentRequest(content, _soapheaders=[h])
`

soap message:

> zeep.transports: HTTP Post to http://10.8.200.28:8080/slfs/services/TransPayMentServiceImpl:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Header><ns0:REALTIMEPAY_REQ xmlns:ns0="Authorization">test</ns0:REALTIMEPAY_REQ></soap-env:Header><soap-env:Body><ns0:transPayMentRequest xmlns:ns0="http://10.8.200.28:8080/slfs/services/TransPayMentServiceImpl"><bean>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
        &lt;REALTIMEPAY_REQ&gt;

when using the script, server report format problem.
After remove "<?xml version "1.0" encoding="utf-8">" part, server could response correctly.

I use java to send above message, and get correct response. After compare the message between jave version and zeep version. i found java will escape quote as &quot;

Thank you very much!

**Comment by rainmanwy** [comment]
I have checked the implementation.
Seems the problem is realted with lxml

`>>> s='''<bean><![CDATA[
...                     <?xml version="1.0" encoding="UTF-8"?>]]>
...          </bean>'''
>>> e = etree.parse(StringIO(s))
>>> etree.tostring(e)
b'<bean>\n                    &lt;?xml version="1.0" encoding="UTF-8"?&gt;\n\t     </bean>'
>>>`

zeep will use etree.tostring when creating soap message.

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
