### ISSUE TITLE
RecursionError: maximum recursion depth exceeded. Problem to parse WSDL file.

### ISSUE THREAD

**Issue by samuel1992** [mvantellingen/python-zeep#648]
Hello I have a problem to parse a wsdl file.
- Zeep 2.4.0
- Python 3.5

My wsdl/xsd files https://gist.github.com/samuel1992/04b43245118822f1f43411c13218b44a 

Thats what I'm trying to do:
`import zeep`
`client = zeep.Client("file:///home/samuel/Downloads/schemas.navitaire.com.ClientServices.SessionManager.SessionManagerClient.wsdl")`

Then it returns an error:
**RecursionError: maximum recursion depth exceeded in comparison**

- Complete output: https://gist.github.com/samuel1992/499d3f04538dc7ce9bed685932cacaa4

PS: If I dont let explicit the "file://" at the URL, then It returns to me: 
**IsADirectoryError** : [Errno 21] Is a directory: '/home/samuel/Downloads'

Thanks.

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by samuel1992** [comment]
@mvantellingen Sorry. I'm a little confuse how to post my code, then I did it on gist, is that ok?
https://gist.github.com/samuel1992/4e3061c9fb5667be5f2f56962d1fe25f

My WSDL files are not online so I post it on gist too:
https://gist.github.com/samuel1992/04b43245118822f1f43411c13218b44a

Thanks for your atention.
