### ISSUE TITLE
Usage of _soapheader for adding sessionId in SOAP header

### ISSUE THREAD

**Issue by dddtc2005** [mvantellingen/python-zeep#65]
I was trying to perform a simple login and logout with Zeep, the login is successful but the logout is not. I think I got a problem with the SOAP header. When login, I don't need to include a header with SessionId, but for logout I will need to provide the sessionid for the logout, where I have to include SessionId in my SOAP header.

I've read the [issue 33](https://github.com/mvantellingen/python-zeep/issues/33) and tried to use _soapheader to include my header. However I can't set value for the SessionId.

```
response = client.service.Login(username, password)
sid = response.sessionId
request = client.service._binding.create_message('Logout', sid, _soapheader={'SessionId':'123'})
print 'Request is: '
print(etree.tostring(request, pretty_print=True))
```

The above code gives a header with empty SessionId: (pieces of the response )
```
...
  <soap-env:Header>
    <ns0:SessionId></ns0:SessionId>
  </sopa-env:Header>
  <soap-env:Body>
    <ns0:Logout>
      <ns0:sessionId>f8836958a9724e1a8da19439d94a428f</ns0:sessionId>
    </ns:0:Logout>
  </soap-env:Body>
...
```
The soap body part are correct, but the header missing the SessionId value

A correct one should look like:

```
...
  <soap-env:Header>
    <ns0:SessionId>f8836958a9724e1a8da19439d94a428f</ns0:SessionId>
  </sopa-env:Header>
  <soap-env:Body>
    <ns0:Logout>
      <ns0:sessionId>f8836958a9724e1a8da19439d94a428f</ns0:sessionId>
    </ns:0:Logout>
  </soap-env:Body>
...
```

Am I not using "_soapheader in a correct way"? Thanks in advance.

Attached wsdl & xsd for reference
[wsdl_xsd.zip](https://github.com/mvantellingen/python-zeep/files/309086/wsdl_xsd.zip)

**Comment by mvantellingen** [comment]
Thanks for the clear issue description 👍 

The documentation for using soapheaders is still missing it seems. I've just fixed an issue so that you can now pass simple types to the _soapheader kwarg. Working code is now


```python
import zeep
from lxml import etree

client = zeep.Client('SessionControl.wsdl')
request = client.service._binding.create_message('Logout', '123', _soapheader='123')
print 'Request is: '
print(etree.tostring(request, pretty_print=True))
```

I've also updated the output of `python -mzeep <wsdl>` (which uses `client.wsdl.dump()`) to include the _soapheader information. I'll leave this issue open as a reminder that I need to add better docs for soap headers.

Thanks

**Comment by mvantellingen** [comment]
Updated the docs: http://docs.python-zeep.org/en/latest/in-depth.html#using-soap-headers

**Comment by dddtc2005** [comment]
Thanks for the quick feedback!

I tried to modified the code and run again following your suggestion:
```
wsdl_session = 'wsdl/EMAinterfaces/webservice_provisioning_cai3g1.2/wsdl/cai3g_1.2/Cai3g1.2_SessionControl.wsdl'

client = zeep.Client(wsdl=wsdl_session)
client.set_address('SessionControl',
                   'SessionControl',
                   'http://127.0.0.1:20081/CAI3G1.2/services/CAI3G1.2')

response = client.service.Login(username, password)
print 'Login SOAP response: ', response
sid = response.sessionId
print 'SessionId is: ', sid
request = client.service._binding.create_message('Logout', sid, _soapheader={sid})
print 'Request is: '
print(etree.tostring(request, pretty_print=True))
```

However I got:

```
None
Login SOAP response:  {   'baseSequenceId': 1108027479, 'sessionId': '6c346d0ab047403f9756dc48cd171460'}
SessionId is:  6c346d0ab047403f9756dc48cd171460
6c346d0ab047403f9756dc48cd171460
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    request = client.service._binding.create_message('Logout', sid, _soapheader=sid)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 56, in create_message
    serialized = operation.create(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 245, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 88, in serialize
    raise ValueError("Invalid value given to _soapheader")
ValueError: Invalid value given to _soapheader

```

Any idea why?

**Comment by mvantellingen** [comment]
It seems you are passing a set to the soapheader. Just pass the ''sid'' car directly.

**Comment by dddtc2005** [comment]
Sorry my typos. Actually I tried both with _sopaheader=sid, and _soapheader={sid}

And here is the result for setting _soapheader=sid:
```
None
Login SOAP response:  {   'baseSequenceId': 755231838, 'sessionId': '94474e9d364e4151ab309b8479b6c9d1'}
SessionId is:  94474e9d364e4151ab309b8479b6c9d1
94474e9d364e4151ab309b8479b6c9d1
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    request = client.service._binding.create_message('Logout', sid, _soapheader=sid)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 56, in create_message
    serialized = operation.create(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 245, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 88, in serialize
    raise ValueError("Invalid value given to _soapheader")
ValueError: Invalid value given to _soapheader

```

**Comment by dddtc2005** [comment]
Hi, sorry I was missing one line in the source code. Now it works, thanks!

**Comment by lmanning1022** [comment]
I am trying to debug my issue using soap headers as well. I'm confused by the code above. It looks as though you are just creating the request message. What is the syntax to actually send that request? I am still trying to wrap my head around how zeep works but it looks like the message isn't actually sent yet, only created.

**Comment by dddtc2005** [comment]
Hi @lmanning1022 

You are right that I'm just printing the message. This is for troubleshooting purpose. When I send the request, I use the following:
response = soapclient.service.Set(motype, moid, moattr, _soapheader = sessionid)

here the "Set" is one of the supported operation defined in wsdl/xsd.
