### ISSUE TITLE
How to extract SessionID from a SOAP header part of a response?

### ISSUE THREAD

**Issue by gignacz** [mvantellingen/python-zeep#654]
Hello,

(Disclaimer: I am a SOAP / WSDL newbie. I found zeep as a good and elegant alternative to suds, etc. So my question may be trivial.)

For the first (a login) operation call I get a response containing a sessionID, which I have to use in the subsequent operation calls. So I need to extract the sessionID from the first response, and use it in the subsequent messages sent. I think this is a fairly typical case.

The problems come with the details:

1. The WSDL file of the services does not mention sessionID at all. Nowhere. No other xml file is imported. The 'response' is therefore empty (but no failure occurred) when executing
`response = self.sessionClient.service.logIn( username, password)`
"response" seems to contain the body part only of the SOAP envelope; while debugging, I found the sessionID in the SOAP header part of the response like this:

```
<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Header>
	<ns1:sessionID soapenv:actor="http://schemas.xmlsoap.org/soap/actor/next" soapenv:mustUnderstand="0" xmlns:ns1="http://ws.polarion.com/session">
		1130201734193922495
	</ns1:sessionID>
</soapenv:Header>
...
</soapenv:Envelope>
```

2. I tried to access sessionID by calling get_element() like this:

`sessionID = self.sessionClient.get_element( '{http://ws.polarion.com/session}sessionID' )`

But I received the error message:

`zeep.exceptions.NamespaceError: Unable to resolve element {http://ws.polarion.com/session}sessionID. No schema available for the namespace u'http://ws.polarion.com/session'.`

Therefore my questions:
1. How can I access the *entire* last response of the client (including SOAP header)?
2. How can access the contents of SOAP header of the response?
3. How can I extract the sessionID value from SOAP header?
4. How can I set up a SOAP header with a specific sessionID?
   I think, once I have it built, I can use the Method2 described on [http://docs.python-zeep.org/en/master/headers.html].
   
Thank you very much,
Greg.

**Comment by schlamar** [comment]
Here is a working example by subclassing `Transport` to catch the response.

There might be a better solution, though. @mvantellingen Any idea?

    import requests
    import zeep
    from zeep import transports
    from lxml import etree


    class _Transport(transports.Transport):
        def __init__(self, *args, **kwargs):
            super(_Transport, self).__init__(*args, **kwargs)
            self.last_response = None

        def post(self, *args, **kwargs):
            self.last_response = super(_Transport, self).post(*args, **kwargs)
            return self.last_response


    def main():
        session = requests.Session()
        transport = _Transport(session=session)
        wdsl = 'http://POLARIONHOST/polarion/ws/services/SessionWebService?wsdl'
        client = zeep.Client(wdsl, transport=transport)
        client.service.logIn('user', 'password')

        root = etree.XML(transport.last_response.content)
        sessions = root.xpath('//ns1:sessionID', namespaces={
            'ns1': 'http://ws.polarion.com/session'})
        session_id = sessions[0]

        transport = transports.Transport(session=session)
        wdsl = 'http://POLARIONHOST/polarion/ws/services/TrackerWebService?wsdl'
        client = zeep.Client(wdsl, transport=transport)
        client._default_soapheaders = [session_id]
        item = client.service.getWorkItemById(
            'project', 'item_id')

        print(item.title)


    if __name__ == '__main__':
        main()
