### ISSUE TITLE
20mb XML data getting cut off

### ISSUE THREAD

**Issue by kororo** [mvantellingen/python-zeep#665]
Hi all,

For loading big XML using this project, you will need to get some workaround. Especially if you have big text node inside your XML (if you do it manually using parser, you will receive error **xmlSAX2Characters: huge text node**). In my case, we have 20mb worth of XML. Here is the work around.

I added timeout, this is optional but since you will need to load 20mb sometime the network will be very slow to get all of them.

```
# this is suppose to be your original code
client = Client(wsdl_url)
xml_data = client.service.method123(args1, args2, args3)

# change it to this way
transport = Transport(timeout=60, operation_timeout=60)
client = Client(wsdl_url, transport=transport)
with client.options(raw_response=True, timeout=60):
    response = client.service.method123(args1, args2, args3)
    # noinspection PyArgumentList
    parser = etree.XMLParser(huge_tree=True)
    xml_response = objectify.fromstring(response.content.decode(), parser=parser)
    xml_data = xml_response.xpath('//method123')[0]
```

For maintainer, it would be great to have huge_tree option to be passed into your internal parser. I am quite sure the parser is disabled once options raw_response set to True. Apologies, I dont have sample WSDL or XML for quick code issue replication.

Thanks

**Comment by matecsaj** [comment]
In http://docs.python-zeep.org/en/master/api.html note xml_huge_tree.

**Comment by kororo** [comment]
Hi there,

thanks!! that will do. I will wait until it is in the version tagged, since the code in master currently.
