### ISSUE TITLE
Wrong parsing of uri to local file on windows

### ISSUE THREAD

**Issue by pkaczynski** [mvantellingen/python-zeep#666]
1. Zeep version: 2.4.0
2. WSDL irrelevant

```python
import zeep
import pathlib
with tempfile.NamedTemporaryFile('wb') as f:
    zeep.Client(pathlib.Path(f.name).as_uri())
```
Gives an error

**Comment by sulbig** [comment]
I recently came across a similar problem on the Windows platform. Was getting an OSError about an invalid WSDL file location. I found the WSDL URI was being parsed in the Zeep library to include a leading slash (i.e., "file:///C:" becomes "/C:") in the url variable.

https://github.com/mvantellingen/python-zeep/blob/4df383021e31372c111bc26cbf2e4535deaee04e/src/zeep/transports.py#L117-L119

I am creating an absolute file URI using pathlib.Path() from a relative file location. The created path correctly begins with file:/// (3 slashes). In my local copy of Zeep, I changed the above code to work around this error as below:

```
        elif scheme == 'file':
            if url.startswith('file:///'):
                url = url[8:]
            if url.startswith('file://'):
                url = url[7:]
```

I am not sure if this is the best approach (i.e., how this will behave on other platforms). Thoughts?

Python: 3.7.2
Platform: Windows
Zeep: 3.3.1
