### ISSUE TITLE
Cannot process Axis2-generated WSDL

### ISSUE THREAD

**Issue by dstewart** [mvantellingen/python-zeep#671]
Zeep Version: 2.5.0

[WSDL](https://gist.github.com/dstewart/1dfdd14ccb744d8454b8760dd17889a4)

Example Script: `python -mzeep axis2.wsdl`

Exception: `zeep.exceptions.LookupError: Unable to resolve type {http://www.w3.org/2001/XMLSchema}RuntimeException in None. 
(via {http://core.springframework.org/xsd}NestedRuntimeException)`

**Comment by mvantellingen** [comment]
See https://stackoverflow.com/questions/2465081/wsdls-generated-by-axis2-services-cant-be-read-by-soapui-or-wsdl2java ?
