### ISSUE TITLE
HTTP status 415 (no content available)

### ISSUE THREAD

**Issue by michaelangelorayco** [mvantellingen/python-zeep#673]
Hi Michael,

I'm using zeep version 2.4.0 and 2.5.0 and I mostly get intermittent successful
connection to an enterprise WSDL which I cannot mention using zeep.

I used PyCharm's debugger to know the cause of error and it say's something like:

> Cannot process the message because the content type \'text/xml; charset=utf-8 XaSOfalw: rtt; ___utmvmBfuwVEwB=yEnqIuCmRhw\' was not the expected type \'text/xml; charset=utf-8\'.

I was able to fix it using the zeep Plugins and explicitly set the content type
to something like this:

> class MyLoggingPlugin(Plugin):
> 
>     def ingress(self, envelope, http_headers, operation):
>         return envelope, http_headers
> 
>     def egress(self, envelope, http_headers, operation, binding_options):
>         http_headers['Content-Type'] = 'text/xml; charset=utf-8;'
>         return envelope, http_headers

Although I know that the default content type of zeep is text/xml. Explicitly setting it in the Plugin solved my problem. Any thoughts?

**Comment by mvantellingen** [comment]
Seems like you need to work around a buggy soap server. If this works for you then that seems the way to go for now. There are so many incompatible soap servers that this might sometimes be the best solution
