### ISSUE TITLE
Is possible to make mtom request using zeep?

### ISSUE THREAD

**Issue by Urahara** [mvantellingen/python-zeep#674]
I see [SOAP Attachments (multipart)](http://docs.python-zeep.org/en/master/attachments.html), but its look that is only to get content from a request.

I want to make a request that contains XML + Binary file, its this possible?

**Comment by mrcoolhp** [comment]
@Urahara Did you resolve this issue, I have same kind of issue with my webservice ?

**Comment by Urahara** [comment]
@mrcoolhp I found another endpoint that don't use mtom, but i really interested in this functionality yet.. :/
