### ISSUE TITLE
Even with a strict mode i'm can't import a WSDL

### ISSUE THREAD

**Issue by Urahara** [mvantellingen/python-zeep#675]
So i have a WSDL that have this problem [How to import TStringList and TStrings type to WSDL](https://stackoverflow.com/questions/48530401/how-to-import-tstringlist-and-tstrings-type-to-wsdl), i try using `strict=False` but without success. I know that WSDL is wrong, but since i cannot change it, its there workaround to work with? (Since the WS works!)

> zeep.exceptions.LookupError: Unable to resolve type {urn:Custom}TStrings in (WebService URL removed) . (via {urn:CapsuleWSInf}TDetails)

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.
