### ISSUE TITLE
Issues parsing results from HP Network Automation 10.10

### ISSUE THREAD

**Issue by netdiag** [mvantellingen/python-zeep#677]
Thanks for taking the time to report an issue!

Unfortunately I cannot upload to gist, however, I have compressed the files and attached here - hope this is OK. The parser script has been modified slightly to remove some information - IP addresses and software details.

Zeep v2.5.0
[parser.zip](https://github.com/mvantellingen/python-zeep/files/1696117/parser.zip)
[wsdl.zip](https://github.com/mvantellingen/python-zeep/files/1696118/wsdl.zip)

As you can see, the Python variables are not being populated with the values that are being returned in the XML. 

Hope this provides sufficient information for you to review this.

**Comment by lacrosse1991** [comment]
Hello Netdiag,

Would you care to give my modified WSDL a try? I ran into the same issue with list_device and was able to get it working in the end by adding the following elements to the WSDL:
```

<element name="_newDeviceInImport" type="xsd:string" minOccurs="0" maxOccurs="1" nillable="true" /> <!--new-->
<element name="changedInCache" type="xsd:string" minOccurs="0" maxOccurs="1" nillable="true" /> <!--new-->
<element name="columnUpdateMap" type="xsd:string" minOccurs="0" maxOccurs="1" nillable="true" /> <!--new-->
<element name="loadedSecondaryIPs" type="xsd:string" minOccurs="0" maxOccurs="1" nillable="true" /> <!--new-->
```

The modified WSDL can be found here: https://drive.google.com/file/d/1Zk7K87aqgZ3jrnkmY8XTJyiJCt9sAPjq/view?usp=sharing

Let me know if you have any trouble accessing it.

**Comment by mvantellingen** [comment]
Thanks @lacrosse1991 for the help. Seeing there is no reply i'm closing this
