### ISSUE TITLE
asyncio and Tornado support is undocumented

### ISSUE THREAD

**Issue by schlamar** [mvantellingen/python-zeep#679]
There is not a single line in the documentation covering the support of asyncio / Tornado.

**Comment by mvantellingen** [comment]
Tornado was added via #530, I'm not really able to support that part since i'm not using it myself.

PR's really welcome

**Comment by agronholm** [comment]
The asyncio support is completely useless anyway. Zeep needs to be refactored to support async first, then the asyncio/tornado support can be documented.

**Comment by k4ppa** [comment]
Any news about asyncio support?

**Comment by denopa** [comment]
Is the async_client example supposed to work? In python 3.7 with zeep 3.4 I'm getting ` WSDL loading is not asynchronous yet. Instantiate the zeep client outside the asyncio event loop.` at the `client = zeep.Client(url, transport=transport)` line.

**Comment by mvantellingen** [comment]
The next version (4.0) drops support for aiohttp altogether. One of the reasons development of zeep stagnated was the addition of all the async transports which made it a maintenance hell.

From zeep 4.0 and onwards only httpx will be supported for async operations (wsdl loading will be kept sync)

**Comment by agronholm** [comment]
Couldn't WSDL loading be made async too?
