### ISSUE TITLE
ideally, should not be using the deprecated function getchildren()

### ISSUE THREAD

**Issue by matecsaj** [mvantellingen/python-zeep#684]
1. The version of zeep
2.5.0

2. The WSDL you are using
irrelevant

3. An example script
Line 333 of visitor.py is as follows
children = node.getchildren()

4. citing https://docs.python.org/3.4/library/xml.etree.elementtree.html
getchildren()
Deprecated since version 3.2: Use list(elem) or iteration.

**Comment by mvantellingen** [comment]
thanks
