### ISSUE TITLE
documentation nits

### ISSUE THREAD

**Issue by matecsaj** [mvantellingen/python-zeep#687]
http://docs.python-zeep.org/en/master/in_depth.html
webservice -> web service
Datastructures -> Data Structures  (found in left hand menu) 

http://docs.python-zeep.org/en/master/client.html
initating -> initiating
initialised -> initialized
automaticaly -> automatically
wsdl -> WSDL
xsd -> XSD
behaviour -> bahavior
non optional -> nonoptional
usefull -> useful
availble -> available

http://docs.python-zeep.org/en/master/transport.html.
verficate -> verify
self sign -> self-sign
crt -> .crt

http://docs.python-zeep.org/en/master/headers.html
soapheader -> SOAP header (when used in a sentence)

http://docs.python-zeep.org/en/master/attachments.html
a number of -> some

http://docs.python-zeep.org/en/master/wsa.html
a number of -> some
documnt -> document
hesistate -> hesitate
github -> GitHub

http://docs.python-zeep.org/en/master/plugins.html
is send -> is sent

http://docs.python-zeep.org/en/master/helpers.html
helpers functions -> helper functions

http://docs.python-zeep.org/en/master/changes.html
a number of -> some
properlhy -> properly
non standard -> nonstandard 
incompatibilties -> incompatibilities
semver -> ???
tns -> ???
serializing -> to serialize
complexType’s -> complex types
soapheaders -> SOAP headers (when used in a sentance)
multple -> multiple
deepcopy -> deep copy
ofers -> offers
ssl -> SSL

**Comment by mvantellingen** [comment]
Thanks, are you willing to open a PR for this?

**Comment by matecsaj** [comment]
I am willing, but have never done so before. Can you point me to a genuinely helpful how-to guide?

**Comment by Urahara** [comment]
I make a PR to solve this issue, i hope it helps!

**Comment by matecsaj** [comment]
Urahara, is learned from your PR, thank you.

**Comment by Urahara** [comment]
@matecsaj You are welcome. Basically is just create a "fork", edit what you need and them make a PR.

**Comment by uttamo** [comment]
How are 'initialised' and 'behaviour' typos?
