### ISSUE TITLE
Cisco CallManager Risport70 dictionary issue

### ISSUE THREAD

**Issue by gpaxsonjr** [mvantellingen/python-zeep#692]
Not a programming nor XML expert.  Cisco CUCM Risport70 accepts XML in the following form that does not make sense as a Python dictionary.  Successive item's would clobber the prior item.  Is there a way to make the items unique and acceptable for the XML message?  The dictionary is otherwise valid and provides the correct result for the last item.  Is there a attribute that can be made up to make this work?

https://gist.github.com/gpaxsonjr/6e7e39a62731c5dee87aee83e58dc121
https://gist.github.com/gpaxsonjr/bab5f7be15b8bb1c37ef706f93f45200

**Comment by mvantellingen** [comment]
You need to wrap the DevNames in a list, then it should work
