### ISSUE TITLE
Improve examples and documentation

### ISSUE THREAD

**Issue by lorenzog** [mvantellingen/python-zeep#7]
At the moment the documentation is quite limited to trivial cases. It would be nice to see more examples, such as: 

 * If a complex element contains a sequence of elements, how can I add elements 'by hand'?
 * Manually generating XML: [as shown in this StackOverflow example](http://stackoverflow.com/a/36892846/204634)

WSDL snippet:

    <xsd:compexType name="foo">
        <xsd:sequence>
            <xsd:element name="bar"/>

    <xsd:element name="element1">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name1" type="tns:foo" minOccurs="0" maxOccurs="unbounded"/>

How I'm trying to use it with the library:

    foo1 = client.get_type('ns1:foo')
    foo1.bar = "this is an attribute"
    element1 = client.get_element('ns1:element')
    # now the fields() method shows there's a list in element1, also invoking element1() prints
    # {    'item':  [] }
    # but, how do I add 'foo1' to 'element1'?
    element1.properties().append(foo1)  # no error, but doesn't show

Perhaps activate the wiki and let users contribute? I'd be happy to help.

**Comment by mvantellingen** [comment]
Hi @lorenzog,

I prefer to extend the documentation instead of a separate wiki. Perhaps creating a recipe page in the documentation will do?

Thanks for the feedback btw :)

**Comment by mvantellingen** [comment]
I've decided to create a wiki and perhaps we can then sometimes merge this with the docs
