### ISSUE TITLE
Cannot work with multiple WSDLs in one script

### ISSUE THREAD

**Issue by muhammaddagestani** [mvantellingen/python-zeep#702]
Hi everyone
I suppose there is a bug when working with multiple WSDL URLs

**1. zeep version:** 2.5.0
 **2. WSDL that I use:**
First link for `client1`: 
https://gist.github.com/muhammaddagestani/82d151b11d927cb9450469a3fa2ae04c
Second link for `client2`: https://gist.github.com/muhammaddagestani/7fe1de6a7e1f74529df817fed668e176
**3. Example of script:**
Here the methods `Initialize` and `LoadViewInvoke` are required for interaction with WSDL interface. 

    import zeep
    
    
    client1 = zeep.Client(wsdl='http://localhost:8081/AcronisAutotests/IClientMachinesView?Wsdl')
    client1.service.Initialize(1)
    client1.service.LoadViewInvoke()
    
    print("Machines:", client1.service.GetMachines())
    
    # --------------------------------------------------------------
    
    client2 = zeep.Client(wsdl="http://localhost:8081/AcronisAutotests/ISelectCompanyView?Wsdl")
    client2.service.Initialize(1)
    client2.service.LoadViewInvoke()
    
    print("Partners:", client2.service.GetPartners())
For `client1` everything is OK - I receive correct answer, but for `client2` there's an issue:

    Machines: []
    Traceback (most recent call last):
    File "C:\...\lib\site-packages\zeep\wsdl\definitions.py", line 146, in get
    return self._operations[key]
    KeyError: 'GetPartners'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "C:\...\lib\site-packages\zeep\client.py", line 69, in __getitem__
    self._binding.get(key)
    File "C:\...\lib\site-packages\zeep\wsdl\definitions.py", line 148, in get
    raise ValueError("No such operation %r on %s" % (key, self.name))
    ValueError: No such operation 'GetPartners' on {http://tempuri.org/}BasicHttpBinding_IClientMachinesView
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "C:/.../wsdl_check.py", line 28, in <module>
    print("Partners:", client2.service.GetPartners())
    File "C:\...\lib\site-packages\zeep\client.py", line 60, in __getattr__
    return self[key]
    File "C:\...\lib\site-packages\zeep\client.py", line 71, in __getitem__
    raise AttributeError('Service has no operation %r' % key)
    AttributeError: Service has no operation 'GetPartners'
    
    Process finished with exit code 1
I don't have idea why `GetPartners` method wasn't found. I've tried to execute the same commands via SoapUI - everything is working correctly. 

Is it known issue?

**Comment by mvantellingen** [comment]
There should not be any issue with using multiple wsdl files (there is no global state).

Seems more like an issue with the second wsdl, but it references localhost so i cant really inspect it for you.
