### ISSUE TITLE
authentication fails

### ISSUE THREAD

**Issue by chipnesh** [mvantellingen/python-zeep#703]
from __future__ import print_function

from requests.auth import HTTPBasicAuth 
from requests import Session
from zeep import Client
from zeep.transports import Transport
user= 'login'
pas = 'pasword'

session = Session();
session.auth = HTTPBasicAuth(user, pas)
session.verify = False
client = Client('https://hog.aplana.com/sdk/vimService.wsdl',transport=Transport(session=session))
client.service._binding_options['address'] = 'https://hog.aplana.com/sdk/vimService.wsdl'

print(client.service.RetrieveServiceContent({"value":"ServiceInstance","type":"ServiceInstance"}))

**Comment by chipnesh** [comment]
I'm trying to call the wsdl method for this, I need authentication, but it does not work, use the authentication method specified in the example that I'm doing wrong I get the following error  https://webdav.aplana.com/monosnap/DK_2018-03-13_16.39.50.png

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.

**Comment by evandrix** [comment]
*bump*
