### ISSUE TITLE
get_element() struggles with name spaces, the manual is wrong, or I misread the manual

### ISSUE THREAD

**Issue by matecsaj** [mvantellingen/python-zeep#704]
1. The version of zeep 2.5.0
2. The WSDL you are using http://developer.ebay.com/webservices/latest/ebaySvc.wsdl
3. An example script

# hint, the version number is at the very end of the WSDL

from lxml import etree
import zeep

ebay = 'http://developer.ebay.com/webservices/latest/ebaySvc.wsdl'
namespace = 'http://schemas.xmlsoap.org/wsdl/'
tag = 'documentation'

# this prints the version
wsdl = etree.parse(ebay)
for element in wsdl.iter('{'+namespace+'}*'):
    if tag in element.tag:
        for child in element:
            print(child.text)

# want to accomplish the same with zeep
client = zeep.Client(wsdl=ebay)
element = client.get_element('wsdl:'+tag)   # crashes, my best guess after reading zeep's docs
#element = client.get_element(tag)          # crashes, expected it fail, no harm in trying
#element = client.get_element('ns0:'+tag)   # crashes, zeep docs example has ns0 for the namespace, maybe 0 is an index
#element = client.get_element('ns1:'+tag)   # crashes
#element = client.get_element('ns2:'+tag)   # crashes
#element = client.get_element('ns3:'+tag)   # crashes
#element = client.get_element('ns4:'+tag)   # crashes
#element = client.get_element('ns5:'+tag)   # crashes
#element = client.get_element('ns6:'+tag)   # crashes
#element = client.get_element('ns7:'+tag)   # crashes
#element = client.get_element('ns8:'+tag)   # crashes
#element = client.get_element('ns9:'+tag)   # crashes, the index idea is not working out
#element = client.get_element('{'+namespace+'}'+tag)    #crashes, thought I'd mimic lxml
#element = client.get_element('{'+namespace+'}:'+tag)   #crashes, hybrid of zeep docs and lxml
#element = client.get_element(namespace+':'+tag)    #crashes, another hybrid of zeep docs and lxml
for child in element:   # element doesn't appear to be iterable, so this will likely crash too
    print(child.text)

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by matecsaj** [comment]
Respectfully, I did provide a 25+ line script. It demonstrates a way to achieve the goal with the lxml library followed by 15 failed attempts to do the same with zeep's get_element member function.

Perhaps the way I separated the code into three chunks, with bolded remarks, made it appear otherwise.

**Comment by regolith** [comment]
I don't think `get_element()` is for your use case. It's for getting the zeep versions of elements defined in `<wsdl:types>`, not for extracting etree xml elements from the wsdl.

Seems like you will have to continue using etree separately to get this functionality. (Unless there is some way to get at the etree elements for zeep's parsed wsdl that I don't know of)
