### ISSUE TITLE
Too many open files issues

### ISSUE THREAD

**Issue by botev** [mvantellingen/python-zeep#705]
Hi,
I'm using zeep for accessing a SOAP service. However, for some reason it seems that there is an issue with zeep closing sockets or some temporary files as after some period of time I always get the same error:
```
'Connection aborted.', OSError(24, 'Too many open files'))
```
Is there any workaround this?

**Comment by mvantellingen** [comment]
Could you please provide more info? (Like the wsdl?)

**Comment by shrhawk-entertainer** [comment]
any update on this ?

**Comment by nguyendon** [comment]
I am running into this issue as well when I am load testing. It looks like any newly created sockets are never closed by the application. They sit in `CLOSE_WAIT` indefinitely.
