### ISSUE TITLE
python3 -mzeep url gives 401 client error

### ISSUE THREAD

**Issue by reteps** [mvantellingen/python-zeep#708]
my command: `python3 -mzeep https://pearson:m0bApP5@cms.powerschool.com/pearson-rest/services/PublicPortalServiceJSON?wsdl`

I get an error: 
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://pearson:m0bApP5@cms.powerschool.com/pearson-rest/services/PublicPortalServiceJSON?wsdl`

going to `https://cms.powerschool.com/pearson-rest/services/PublicPortalServiceJSON?wsdl` and authenticating manually with `pearson` and `m0bApP5` works, but why doesn't this?

**Comment by reteps** [comment]
wrong auth form (digest needed)

**Comment by zhan9san** [comment]
Hi reteps,
I encounter the same issue with the HTTPDigestAuth.

Could you help to figure it out?

Thanks very much

Python version: 3.7.0
zeep version: 3.3.1
**Error: 401 Client Error: Unauthorized for url**

Example code:
```
from requests import Session
from requests.auth import HTTPDigestAuth

import zeep
from zeep.transports import Transport

session = Session()
session.auth = HTTPDigestAuth('username', 'password')
transport_with_basic_auth = Transport(session=session)

client = zeep.Client(
    wsdl='http://example.domain.com/ReportServer/ReportExecution2005.asmx?wsdl',
    transport=transport_with_basic_auth
)
```

**Comment by reteps** [comment]
I ended up with this

session = requests.session()
session.auth = requests.auth.HTTPDigestAuth(api_username, api_password)
self.client = zeep.Client(wsdl=self.url + "?wsdl",transport=zeep.transports.Transport(session=session))
