### ISSUE TITLE
zeep.exceptions.TransportError: Server returned HTTP status 404 (no content available)

### ISSUE THREAD

**Issue by reteps** [mvantellingen/python-zeep#709]
error: `zeep.exceptions.TransportError: Server returned HTTP status 404 (no content available)`

context:
+ command ` login = client.service.login(username="steng",password="95340",userType=2)`
+ url `cms.powerschool.com/pearson-rest/services/PublicPortalServiceJSON?wsdl`
+ section `login(username: xsd:string, password: xsd:string, userType: xsd:int) -> return: ns2:ResultsVO`

code:

```
#!/usr/bin/env python3
import zeep, requests
def createClient(base_url):
    if base_url[:-1] != "/":
        base_url += "/" 
    session = requests.Session()
    session.auth = requests.auth.HTTPDigestAuth("pearson","m0bApP5")
    url = base_url + "pearson-rest/services/PublicPortalServiceJSON?wsdl"
    return zeep.Client(wsdl=url,transport=zeep.transports.Transport(session=session))

client = createClient("https://cms.powerschool.com")

login = client.service.login(username="steng",password="XXXXX",userType=2)
```

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by reteps** [comment]
I got it! I had to use service to define the namespace.
