### ISSUE TITLE
Add example in documentation for setting transport timeout

### ISSUE THREAD

**Issue by tkocmathla** [mvantellingen/python-zeep#71]
It would be useful to see an example in the documentation that showed how to set a timeout on the underlying Transport object (http://docs.python-zeep.org/en/latest/transport.html)

Something as simple as:

    from zeep import Client
    from zeep.transports import Transport
    c = Client(wsdl='...', transport=Transport(timeout=10))

**Comment by mvantellingen** [comment]
Yeah agree, will look at it when i have some time. Or if you want to send a PR then that would be even better 😉

**Comment by mvantellingen** [comment]
closed via #76

**Comment by mateuszzz88** [comment]
As a new user I find current example slightly confusing. 
Reading https://python-zeep.readthedocs.io/en/master/transport.html I have a feeling that `timeout=` sets timeout for operations POST/GET.
Reading https://python-zeep.readthedocs.io/en/master/api.html#transport however suggests that it should be `operation_timeout=` 

Perhaps it would be better if example shown both options and explained the difference?
