### ISSUE TITLE
soapenv instead of soap-env

### ISSUE THREAD

**Issue by xovbd** [mvantellingen/python-zeep#710]
Hi,

I use **zeep 2.5.0**

## Problem
The SOAP-Server only accepts a SOAP-request with **`<soapenv>`**-Tag's instead of **`<soap-env>`**-Tag's and I didn't find a way to change this via a built-in option.

**good** XML snippet:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <ns0:transferRequest xmlns:ns0="http://my-funny.url/v1">
      ...
    </ns0:transferRequest>
  </soapenv:Body>
</soapenv:Envelope>
```

**bad** XML snippet:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:transferRequest xmlns:ns0="http://my-funny.url/v1">
      ...
    </ns0:transferRequest>
  </soap-env:Body>
</soap-env:Envelope>
```

## workaround
I tried to change the namespace Tag with
`client.set_ns_prefix('soapenv', 'http://schemas.xmlsoap.org/soap/envelope/')`
but the soap-serializer(?) will sort the namespaces alphabetical and use **soap-env** instead of **soapenv**

This is the resulting XML with the given ns-prefix:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:transferRequest xmlns:ns0="http://my-funny.url/v1">
      ...
    </ns0:transferRequest>
  </soap-env:Body>
</soap-env:Envelope>
```

My actual _workaround_ is the following patch of `zeep\wsdl\messages\soap.py`
```
@@ -46,9 +46,14 @@
 
     def serialize(self, *args, **kwargs):
         """Create a SerializedMessage for this message"""
-        nsmap = {
-            'soap-env': self.nsmap['soap-env']
-        }
+
+        if 'soapenv' not in self.wsdl.types._prefix_map_custom:
+            nsmap = {
+                'soap-env': self.nsmap['soap-env']
+            }
+        else:
+            nsmap = {}
+        
         nsmap.update(self.wsdl.types._prefix_map_custom)
 
         soap = ElementMaker(namespace=self.nsmap['soap-env'], nsmap=nsmap)
```

**Comment by mvantellingen** [comment]
This is not something I want to solve in zeep. This is really, really a dumb bug in the server

**Comment by davidolmo** [comment]
@mvantellingen , I'm facing the same problem. Is there any way to solve this from clientside without changing Zeep source files?

**Comment by impinchi** [comment]
I'm having he same issue but that patch didnt work for me :(

**Comment by 1986webdeveloper** [comment]
I have the same issue. How can I fix it?

**Comment by zdog234** [comment]
@mvantellingen I am also running into the same issue. Doing a bit of googling, it seems like there was a period of time where some java soap stuff used `soapenv` instead of `soap-env`.

Whatever the reason, there's _zero_ possibility that these legacy soap systems are getting such a significant patch, so I would implore you for an option to use `soapenv` instead. Of course I can always fork and implement @xovbd 's patch, but it'd be way less overhead if I could just `pip install zeep` instead of going through the work of incorporating my fork into our enterprise apps (my company gets really finnicky about forks / any packages that don't come from pypi)

I get that it's a problem with these servers though, so I totally get it if you'd rather not deviate from the actual SOAP spec

**Comment by quique0194** [comment]
Well I found a way to "hack" zeep in order to use `soapenv` instead of `soap-env`. It consists in modifying the body right before sending the post to the server. You just need to create your own Transport, and use it:

```
class TransportSoapenv(Transport):

    @staticmethod
    def replace_soapenv(etree):
        from zeep.wsdl.utils import etree_to_string
        message = etree_to_string(etree)
        message = message.replace(b'soap-env:', b'soapenv:')
        message = message.replace(b'soap-env=', b'soapenv=')
        return message

    def post_xml(self, address, envelope, headers):
        message = TransportSoapenv.replace_soapenv(envelope)
        return self.post(address, message, headers)

```

**Comment by faccini-bs** [comment]
> class TransportSoapenv(Transport):
> 
>     @staticmethod
>     def replace_soapenv(etree):
>         from zeep.wsdl.utils import etree_to_string
>         message = etree_to_string(etree)
>         message = message.replace(b'soap-env:', b'soapenv:')
>         message = message.replace(b'soap-env=', b'soapenv=')
>         return message
> 
>     def post_xml(self, address, envelope, headers):
>         message = TransportSoapenv.replace_soapenv(envelope)
>         return self.post(address, message, headers)

I defined your class under classes.py and tried
```python
import classes as cl
client = Client(
   WSDL_PATH, 
   plugins=[history], 
   # transport=Transport(session=session)
   transport=cl.TransportSoapenv(session=session)
)
response = client.service.getVersion(majorRelease='3')

# logs sent xml to file
f.nodeToXml(history.last_sent["envelope"], f"{str(time.time())[:9]}version-request.xml")
```
And I see it didn't change the soap-env
Thank You for the code above, You've done enough already, just leaving this here for the record. Maybe You see a quick mistake on my code
