### ISSUE TITLE
Usage of complexType that is an extension of string

### ISSUE THREAD

**Issue by crackytsi** [mvantellingen/python-zeep#715]
Hi,
I have the following small XSD entry

Now I want to call this entry with operation "operation(StringType)"
Unfortunately thie first parameter is of type String, and then there is the required attribute "type" and the 2 optionals.
How can I call this?
(note that this is an extension of xsd:string)

```
            <xsd:complexType name="StringType">
                <xsd:simpleContent>
                    <xsd:extension base="xsd:string">
                        <xsd:attribute fixed="String" name="type" type="xsd:string" use="required"/>
                        <xsd:attribute name="mandatory" type="xsd:boolean" use="optional"/>
                        <xsd:attribute name="readonly" type="xsd:boolean" use="optional"/>
                    </xsd:extension>
                </xsd:simpleContent>
            </xsd:complexType>
```

**Comment by mvantellingen** [comment]
You can see the syntax with ``python -mzeep <wsdl>``. It should be something like:

``operation("my-string", _attr_1={'type': 'foobar'})``
