### ISSUE TITLE
Parsing http raw string

### ISSUE THREAD

**Issue by Haigutus** [mvantellingen/python-zeep#716]
I had an issue with web server sending me back HTTP raw string, so I added quick fix in loader.py maybe something nicer can be done.

1. The version of zeep  - 1.4.1
2. The WSDL you are using - https://gist.github.com/Haigutus/f2b5871b3fb86bff4de1ebe5bc09409d
3. An example script

from requests import Session
from requests.auth import HTTPBasicAuth  # or HTTPDigestAuth, or OAuth1, etc.
from zeep import Client
from zeep.transports import Transport

WSDL_path = 'http://{path}/ws/madesInWSInterface.wsdl'

session = Session()
session.auth = HTTPBasicAuth("user", "pass")

transport = Transport(session = session)
client = Client(WSDL_path, transport = transport, strict=False)

service = client.create_service(
    '{http://mades.entsoe.eu/}MadesEndpointSOAP12',
    'http://{path}/ws/madesInWSInterface')

print(service.ConnectivityTest("38V-EE-OPDM----S", "A04"))

Issue details:

Error:

Traceback (most recent call last):
  File "C:\Users\kristjan.vilgo\Desktop\MADES_client.py", line 44, in <module>
    print(service.ConnectivityTest("38V-EE-OPDM----S", "A04"))
  File "C:\Python27\lib\site-packages\zeep\client.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 120, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 153, in process_reply
    doc = parse_xml(content, self.transport)
  File "C:\Python27\lib\site-packages\zeep\loader.py", line 44, in parse_xml
    return fromstring(content, parser=parser, base_url=base_url)
  File "C:\Python27\lib\site-packages\defusedxml\lxml.py", line 144, in fromstring
    elementtree = rootelement.getroottree()
AttributeError: 'NoneType' object has no attribute 'getroottree'

Content value:

'------=_Part_11_475907916.1522225137501\r\nContent-Type: application/xop+xml; charset=utf-8; type="application/soap+xml"\r\n\r\n<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/><env:Body><ns3:ConnectivityTestResponse xmlns:ns3="http://mades.entsoe.eu/"><messageID>e197659d-db34-4953-af99-bc209ec0dc07</messageID></ns3:ConnectivityTestResponse></env:Body></env:Envelope>\r\n------=_Part_11_475907916.1522225137501--'

Ugly fix in loader.py:

def extract_xml_from_http(raw_string):

    xml_start = raw_string.find('<')
    xml_end = raw_string.rfind('>') + 1

    if xml_start > -1 and xml_end > 0:

        return raw_string[xml_start:xml_end]

    else:

        print("No xml found in raw HTTP string")
        return raw_string

def parse_xml(content, transport, base_url=None, strict=False):
    """Parse an XML string and return the root Element.

    :param content: The XML string
    :type content: str
    :param transport: The transport instance to load imported documents
    :type transport: zeep.transports.Transport
    :param base_url: The base url of the document, used to make relative
      lookups absolute.
    :type base_url: str
    :param strict: boolean to indicate if the lxml should be parsed a 'strict'.
      If false then the recover mode is enabled which tries to parse invalid
      XML as best as it can.
    :type strict: boolean
    :returns: The document root
    :rtype: lxml.etree._Element

    """
    recover = not strict
    parser = etree.XMLParser(
        remove_comments=True, resolve_entities=False, recover=recover)
    parser.resolvers.add(ImportResolver(transport))
    content = extract_xml_from_http(content)  ###Added fix###
    try:
        return fromstring(content, parser=parser, base_url=base_url)
    except etree.XMLSyntaxError as exc:
        raise XMLSyntaxError("Invalid XML content received (%s)" % exc.msg)

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by mvantellingen** [comment]
Note, I need a runnable script (which I can execute locally)

**Comment by Haigutus** [comment]
Please explain, the script is added and also the message it is not able to parse. I am not able to provide you the system that it is interfacing.

**Comment by mvantellingen** [comment]
```requests.exceptions.ConnectionError: HTTPConnectionPool(host='%7bpath%7d', port=80): Max retries exceeded with url: /ws/madesInWSInterface.wsdl (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x106c5f5f8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))```

When running your script. (I know, {host} is not a valid hostname, that is why this isn't a runnable script)
