### ISSUE TITLE
Debug parameter to print out sent and received messages [Improvement]

### ISSUE THREAD

**Issue by Haigutus** [mvantellingen/python-zeep#717]
In soap.py add functionality to check if client has debug option true, to print out and save last sent message

def send(self, client, options, operation, args, kwargs):
        """Called from the service

        :param client: The client with which the operation was called
        :type client: zeep.client.Client
        :param options: The binding options
        :type options: dict
        :param operation: The operation object from which this is a reply
        :type operation: zeep.wsdl.definitions.Operation
        :param args: The args to pass to the operation
        :type args: tuple
        :param kwargs: The kwargs to pass to the operation
        :type kwargs: dict

        """
        envelope, http_headers = self._create(
            operation, args, kwargs,
            client=client,
            options=options)

        

        response = client.transport.post_xml(
            options['address'], envelope, http_headers)

        operation_obj = self.get(operation)

        # If the client wants to return the raw data then let's do that.
        if client.raw_response:
            return response

        if client.debug == True: # DEBUG

          client.last_message_out = envelope # DEBUG
          client.last_message_in = response # DEBUG
          print "\n --- Message sent --- \nto: {} \nheader:{} \nmessage:\n".format(options['address'], http_headers)  # DEBUG
          print etree.tostring(envelope, pretty_print=True) # DEBUG
          print "\n --- Message recieved --- \n"  # DEBUG
          print response.content                          # DEBUG

        return self.process_reply(client, operation_obj, response)

Output would look like this:

 --- Message sent --- 
to: http://10.1.21.50:9090/ws/madesInWSInterface 
header:{'SOAPAction': '"http://mades.entsoe.eu/CheckMessageStatus"', 'Content-Type': 'application/soap+xml; charset=utf-8; action="http://mades.entsoe.eu/CheckMessageStatus"'} 
message:

<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
  <soap-env:Body>
    <ns0:CheckMessageStatusRequest xmlns:ns0="http://mades.entsoe.eu/">
      <messageID>01241a1f-da1b-4659-8327-f81553366e8c</messageID>
    </ns0:CheckMessageStatusRequest>
  </soap-env:Body>
</soap-env:Envelope>

 --- Message recieved --- 

<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value></env:Code><env:Reason><env:Text xml:lang="en">CheckMessageStatusFault</env:Text></env:Reason><env:Detail><ns3:CheckMessageStatusError xmlns:ns3="http://mades.entsoe.eu/"><errorCode>MESSAGE_NOT_FOUND</errorCode><errorID>fc58c661-dd00-4d05-9eac-4db0ae1283fa</errorID><errorMessage>Message with message ID 01241a1f-da1b-4659-8327-f81553366e8c was not found.</errorMessage><messageID>01241a1f-da1b-4659-8327-f81553366e8c</messageID><errorDetails>Message with message ID 01241a1f-da1b-4659-8327-f81553366e8c was not found.</errorDetails></ns3:CheckMessageStatusError></env:Detail></env:Fault></env:Body></env:Envelope>

**Comment by mvantellingen** [comment]
This can be done with http://docs.python-zeep.org/en/master/plugins.html#historyplugin
