### ISSUE TITLE
proxy?

### ISSUE THREAD

**Issue by YAmikep** [mvantellingen/python-zeep#72]
Hello

Is there an easy way to provide a proxy to use?

Thanks

**Comment by mvantellingen** [comment]
Another perhaps easier way is to set ``client.transport.session.proxies = {}``. See http://docs.python-requests.org/en/master/api/#requests.Session.proxies

**Comment by YAmikep** [comment]
Thanks guys. I used @mvantellingen way and it worked.

**Comment by brandond** [comment]
You really should just call rebuild_proxies on the prepared request before you send it off. This will automatically pull in any proxy configuration from the environment, without making the user poke at the Session object on their own.
 http://docs.python-requests.org/en/master/api/#requests.Session.rebuild_proxies
