### ISSUE TITLE
test_tornado_transport.py is failing on Debian

### ISSUE THREAD

**Issue by mbehrle** [mvantellingen/python-zeep#724]
Perhaps a bit related to https://github.com/mvantellingen/python-zeep/issues/679.
See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893948

The relevant bits are:

Some recent change in unstable (Python 3.6?) makes python-zeep FTBFS. This applies to version 2.4.0 as well as 2.5.0.

https://tests.reproducible-builds.org/debian/history/python-zeep.html
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/python-zeep.html

...

=================================== FAILURES ===================================
_____________________ TornadoAsyncTransportTest.test_load ______________________

self = <tests.test_tornado_transport.TornadoAsyncTransportTest testMethod=test_load>
mock_httpclient_fetch = <MagicMock name='fetch' id='140541565526928'>

    @pytest.mark.requests
    @patch('tornado.httpclient.HTTPClient.fetch')
    @gen_test
    def test_load(self, mock_httpclient_fetch):
        cache = stub(get=lambda url: None, add=lambda url, content: None)
        response = HTTPResponse(HTTPRequest('http://tests.python-zeep.org/test.xml'), 200)
        response.buffer = True
        response._body = 'x'
        mock_httpclient_fetch.return_value = response
    
        transport = TornadoAsyncTransport(cache=cache)
    
>       result = transport.load('http://tests.python-zeep.org/test.xml')

tests/test_tornado_transport.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
zeep/transports.py:110: in load
    content = self._load_remote_data(url)
zeep/tornado/transport.py:38: in _load_remote_data
    client = httpclient.HTTPClient()
/usr/lib/python3/dist-packages/tornado/httpclient.py:81: in __init__
    gen.coroutine(lambda: async_client_class(**kwargs)))
/usr/lib/python3/dist-packages/tornado/ioloop.py:577: in run_sync
    self.start()
/usr/lib/python3/dist-packages/tornado/platform/asyncio.py:112: in start
    self.asyncio_loop.run_forever()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def run_forever(self):
        """Run until stop() is called."""
        self._check_closed()
        if self.is_running():
            raise RuntimeError('This event loop is already running')
        if events._get_running_loop() is not None:
            raise RuntimeError(
>               'Cannot run the event loop while another loop is running')
E           RuntimeError: Cannot run the event loop while another loop is running

/usr/lib/python3.6/asyncio/base_events.py:412: RuntimeError
------------------------------ Captured log call -------------------------------
selector_events.py          65 DEBUG    Using selector: EpollSelector
selector_events.py          65 DEBUG    Using selector: EpollSelector
selector_events.py          65 DEBUG    Using selector: EpollSelector
==================== 1 failed, 410 passed in 57.41 seconds =====================
Exception ignored in: <bound method HTTPClient.__del__ of <tornado.httpclient.HTTPClient object at 0x7fd26215bd68>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/httpclient.py", line 85, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/tornado/httpclient.py", line 89, in close
    if not self._closed:
AttributeError: 'HTTPClient' object has no attribute '_closed'
E: pybuild pybuild:330: test: plugin distutils failed with: exit code=1: cd /build/1st/python-zeep-2.4.0/.pybuild/cpython3_3.6_zeep/build; python3.6 -m pytest tests
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 3.6 returned exit code 13
make: *** [debian/rules:6: build] Error 25

**Comment by mvantellingen** [comment]
This seems to be fixed?

**Comment by mbehrle** [comment]
No, not fixed. Just excluded the failing test to keep python-zeep in testing: https://salsa.debian.org/tryton-team/python-zeep/commit/cab45e2df48e6c8e33b70a2ae6adcceadb7d336b

**Comment by mvantellingen** [comment]
Might be fixed in next release
