### ISSUE TITLE
AttributeError: Service has no operation 'XXXXXXXXXXXXXXXX'

### ISSUE THREAD

**Issue by Bunny1991** [mvantellingen/python-zeep#728]
I am getting 2 errors in Client.py below and I'm not sure what needs to be done to fix these errors, actually i have to implement a service method which is accepting 14 parameters and having very complex hierarchy of SOAP request.
zeep\client.py", line 60, in __getattr__ return self[key]
zeep\client.py", line 71, in __getitem__

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
