### ISSUE TITLE
Zeep fails with "TransportError" if response.content is None

### ISSUE THREAD

**Issue by ThreePinkApples** [mvantellingen/python-zeep#739]
Running Zeep v2.5.0

Looks quite funny when you get a 200 but it fails with TransportError
```
TransportError Server returned HTTP status 200 ()
```

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
