### ISSUE TITLE
Unable to resolve type {urn:appsdata}userType

### ISSUE THREAD

**Issue by JustasBelevicius** [mvantellingen/python-zeep#746]
Hey,
First of all, amazing module, I totally love even though I have just started using it 😄 
I have encountered some problems while trying to initialize the client (It might be the issue on my part as well, so if there is nothing that you can do I will totally understand).

1. **Version of zeep:** 2.5.0
2. **WSDL:** http://www.swimpro.lt/component/csoap/apps-data-feed?wsdl
3. **Script:** I'm just trying to initialize the client
```
Client = new Client(wsdl) 
OR 
python -mzeep http://www.swimpro.lt/component/csoap/apps-data-feed?wsdl)
```

Also, my service is using NuSoap 0.9.5, which, if I am correct, is basically SOAP 4

Thanks in advance,
**_JB_**

**Comment by mvantellingen** [comment]
The WSDL references ``tns:userType`` which doesn't exist, so this looks like an bug on the server end
