### ISSUE TITLE
Namespace element (ns0:ArrayOf_xsd_anyType) cannot be found

### ISSUE THREAD

**Issue by samuel-fonseca** [mvantellingen/python-zeep#751]
1. Running zeep 2.5.0
2. Python 3.6
3. [WSDL File](https://gist.github.com/brazucaz/840ea70171213fc46cb79be4d5da4e8b) (GitHub gist)

So I think I may have stumble upon a potential issue. I have the WSDL above from an API I am trying to use. However, I have not been able to use the `ArrayOf_xsd_anyType` attribute needed to consume the API.

So I have tried finding the element using zeep's `get_element()` function which triggers an error:

```python
def call (self):
    client = self.Client
    return client.get_element('ns0:ArrayOf_xsd_anyType')
```

Produces this error:

```sh
Traceback (most recent call last):
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\schema.py", line 565, in _get_component
    return items[qname]
KeyError: <lxml.etree.QName object at 0x041397E8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HandleSonis.py", line 114, in <module>
    print(sonis.call())
  File "HandleSonis.py", line 80, in call
    arguments = client.get_element('ns0:ArrayOf_xsd_anyType')
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\client.py", line 271, in get_element
    return self.wsdl.types.get_element(name)
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\schema.py", line 130, in get_element
    return self._get_instance(qname, 'get_element', 'element')
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\schema.py", line 243, in _get_instance
    raise last_exception
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\schema.py", line 239, in _get_instance
    return method(qname)
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\schema.py", line 531, in get_element
    return self._get_component(qname, self._elements, 'element')
  File "C:\Users\brazucaz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\zeep\xsd\schema.py", line 580, in _get_component
    location=self._location)
zeep.exceptions.LookupError: No element 'ArrayOf_xsd_anyType' in namespace http://cfc. Available elements are:  -
```

Which I imagine is caused because there is no `ArrayOf_xsd_anyType` in namespace 0 (`ns0`). However, when I look for the params the API is expecting:

```python

def get_client_info(self):
	for service in self.Client.wsdl.services.values():
		print( "service:", service.name)
		for port in service.ports.values():
			operations = sorted(
				port.binding._operations.values(),
				key=operator.attrgetter('name'))
			for operation in operations:
				print( "method :", operation.name)
				print( "  input :", operation.input.signature())
				print( "  output:", operation.output.signature())
```

To which I receive this response:

```sh
service: SoapapiService
method : doAPISomething
  input : user: xsd:string, pass: xsd:string, comp: xsd:string, meth: xsd:string, hasReturnVariable: xsd:string, argumentdata: ns0:ArrayOf_xsd_anyType
  output: doAPISomethingReturn: None
None
```

As you can see above, `ArrayOf_xsd_anyType` is under `ns0`. Which I then try to change the namespace to 1, 2, 3, and 4. But none of them will work either.

So I am just wondering if the `WSDL` file is the issue of if zeep is not interpreting this correctly.

I appreciate any responses to help me figure this out!

Cheers

**Comment by passion4code** [comment]
I was looking around the issues for a semi-related problem, and ran across your post. I think you are experiencing this because you are trying to reference a `<complexType />` in your wsdl, not an `<element />`.

For types, I think you would access it like this: `client.get_type('ns0:ArrayOf_xsd_anyType')`

**Comment by brazucaz** [comment]
@passion4code thank you so much for responding.

I just figured something out after looking at your response and found something similar to this on StackOverflow:

```python
def prepare_arguments(self):
  factory = self.Client.type_factory('ns0')
  ArrayOfAnyType = factory.ArrayOf_xsd_anyType
  ArrayOfString = factory.ArrayOf_xsd_string

  arguments = ArrayOfAnyType([
    ArrayOfString({'key0', 'value'}),
    ArrayOfString({'key1', 'value}),
    ArrayOfString({'key2', 'value'})
  ])
  
  return arguments
```
Which returns me something like this:

```sh
[['key0', 'value'], ['key1', 'value'], ['key2', 'value']]
```

If I check the `type()` I get back this:

```python
type(arguments)
# <class 'zeep.objects.ArrayOf_xsd_anyType'>
```

Which, then, triggers a similar error

```sh
TypeError: Any element received object of type 'ArrayOf_xsd_string', expected lxml.etree._Element or builtins.dict
See http://docs.python-zeep.org/en/master/datastructures.html#any-objects for more information
```

I am not sure why it's not accepting this input.

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by brazucaz** [comment]
@mvantellingen, I tried being as descriptive of the issue as possible... I am careful with what I share not to leak any private information.

I will have to make some adjustments and remind myself of the issue. I have shifted that part of the project to PHP (thankfully, I still have the python code). I will share a script as soon as I can!

**Comment by brazucaz** [comment]
@mvantellingen 

Okay, I've got something together. This will not actually perform any actions, it's an not connected to the actual API. However, it will trigger the error I have having with the type for `argumentdata` argument in the SOAP API element.

The error is the same I have on a my side, so it should be sufficient for testing purposes:
https://gist.github.com/brazucaz/1e3bb54d6325278367767c7155ab06cd

Let me know if this is sufficient.

**Comment by brazucaz** [comment]
Are there any updates on the status of this issue?

Maybe remove the `needs-example-script` tag, or is the script provided before not enough?

**Comment by GytisT** [comment]
@mvantellingen hello, any updates on this? Facing he exact same issue here.

**Comment by samuel-fonseca** [comment]
@GytisT nothing here; still waiting.

**Comment by lingfish** [comment]
I'm having the same issue/error as per the end of https://github.com/mvantellingen/python-zeep/issues/751#issuecomment-389374908

**Comment by samuel-fonseca** [comment]
@lingfish I don't think the issue has been fixed it. I have moved on from Python back to PHP for this specific software

**Comment by lingfish** [comment]
@mvantellingen any thoughts here?  I've put together a test case that highlights it too.

**Comment by samuel-fonseca** [comment]
@lingfish can you attach your case scenario to this thread so we can use for trying to find a fix?

**Comment by lingfish** [comment]
Sure, can do. I'm pretty sure I'm not meant to publicly distribute the WSDL 
of this commercial product - any way to send it to you privately?

**Comment by samuel-fonseca** [comment]
@lingfish email? Or via a dropbox shared link?

**Comment by lingfish** [comment]
Sure... to Michael?

My test case is just a rip from @mvantellingen 's tests, just so that I don't need the actual API up.

**Comment by lingfish** [comment]
Well, I'll go ahead and mail @mvantellingen the WSDL and test case.

**Comment by lingfish** [comment]
No response... Looks like this project has stalled.

**Comment by samuel-fonseca** [comment]
@lingfish I honestly don't know, man. After I posted my example code I never heard back. At the time I decided to simply switch back to PHP; it didn't take much of my time; I just wrote a RESTful API which would make the call in PHP and return the results in a JSON format, then I would do what I needed in Python.
