### ISSUE TITLE
Invalid SSL certificate at https://docs.python-zeep.org/

### ISSUE THREAD

**Issue by vovanz** [mvantellingen/python-zeep#754]
When you google something like `python soap` the first link in search results (for me, at least) leads to https://docs.python-zeep.org/ (notice **https**), but when you follow this link the page won't load normally because of invalid ssl certificate. It looks quite confusing at first.

Currently, it attempts to use a certificate that was issued for `*.readthedocs.org` which obviously doesn't work for `docs.python-zeep.org`.

I think that you probably should get an ssl certificate (you can get a free cert from Let's Encrypt) and follow [this instruction](https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl) to enable ssl properly.

**Comment by mvantellingen** [comment]
Fixed, thanks
