### ISSUE TITLE
Tests failing in PyCharm IDE due to invalid path when py.tests executed from ./tests dir by default

### ISSUE THREAD

**Issue by jonathanelscpt** [mvantellingen/python-zeep#755]
**Version: 2.5.0**

Like most IDE's, PyCharm has a built-in function to run all tests from within the IDE.  This defaults to executing from `./tests` dir.  When this happens, there are approx. test 47 failures which don't occur if executed from the root dir.

The problems are all due to invalid relative path assumptions:

e.g.:

```
tests\test_client.py:10 (test_bind)
def test_bind():
>       client_obj = client.Client('tests/wsdl_files/soap.wsdl')
```

resulting in `tests` duplication in the path:
`url = 'C:\\Users\\jonathan.els\\develop\\pvt-repos\\python-zeep\\tests\\tests\\wsdl_files\\soap.wsdl'`

It's easy enough to get around this (just change the execution dir), but the test paths should be adjusted to prevent this

**Comment by mvantellingen** [comment]
Your welcome to submit a PR to fix it. I run pytest from the cmdline
