### ISSUE TITLE
Passing HTTP Headers in thread safe way

### ISSUE THREAD

**Issue by skraynev** [mvantellingen/python-zeep#758]
Hi guys.

I use zeep 1.6.0 (also tried 2.5.0) for communication with GoogleAdwords API.
According official docs (https://developers.google.com/adwords/api/docs/guides/call-structure#request) it requires to pass soapheaders (application authorization, like - developer token) and http_headers (system authorization - user token). It works ok for one user, where Session can be used for passing http_headers:
```
from requests import Session
from zeep import Client
from zeep.transports import Transport

session = Session()
session.headers.update({'Authorization' : 'Bearer ACCESS_TOKEN'})
soapheaders = {
   'clientCustomerId': 'CLIENT_ID',
   'developerToken': 'DEVELOPER_TOKEN',
}
transport = Transport(session=session)
client = Client(
    'https://adwords.google.com/api/adwords/cm/v201802/CampaignService',
    transport=transport)
result = getattr(client.service, 'get')(
    _soapheaders=soapheaders,               
    **kwargs                                  
)['body']['rval']                             
```

The same approach works for several users with different tokens (in one thread):
```
from requests import Session
from zeep import Client
from zeep.transports import Transport

session = Session()
transport = Transport(session=session)
client = Client(
    'https://adwords.google.com/api/adwords/cm/v201802/CampaignService',
    transport=transport)

creds_list = [
      (CLIENT_ID_1, ACCESS_TOKEN_1), 
      (CLIENT_ID_2, ACCESS_TOKEN_2)
]
for creds in creds_list:
   session.headers.update({'Authorization' : 'Bearer %s' % creds[1] } )
   soapheaders = {
      'clientCustomerId': creds[0],
      'developerToken': 'DEVELOPER_TOKEN',
   }
   result = getattr(client.service, 'get')(
       _soapheaders=soapheaders,               
       **kwargs                                  
   )['body']['rval']
```

The issue comes in situation when I have to process several users in threads. There are two solutions here:
1. create client for each thread 
    **it works**, but I met some memory leaks issues. I will try to prepare clear repro and post another issue, if it will be related with zeep.)
2. create one client for all threads. 
   **it does not work now**, because setting http_headers parameters in Session is not thread safe.

So I would like to know: does it make sense to add http_headers processing in similar way with soapheaders?

I tried to implement it locally by changing https://github.com/mvantellingen/python-zeep/blob/2.5.0/src/zeep/wsdl/bindings/soap.py#L68-L72:
```
        custom_http_headers = kwargs.pop('custom_http_headers', {})
        serialized = operation_obj.create(*args, **kwargs)
        self._set_http_headers(serialized, operation_obj)

        envelope = serialized.content
        http_headers = serialized.headers
        if custom_http_headers:
                http_headers.update(custom_http_headers)
```
P.s. unfortunately I can not pass any kind of creds for running examples, but I suppose example above can be used for another system, where you may check it.

**Comment by mvantellingen** [comment]
In master you can now do:

```
with client.settings(extra_http_headers=custom_http_headers):
    client.service.dosomething()
```

**Comment by skraynev** [comment]
Awesome! Thank you.
