### ISSUE TITLE
authentication on different gateway how to change bindings

### ISSUE THREAD

**Issue by karstengo** [mvantellingen/python-zeep#762]
HTTP auth on different service location

e.g. for https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl

you need to authenticate with a special https://cig.dhl.de/services/sandbox/soap server.
Is it somehow possible to achieve this? 

```
wsdl = "https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl"

servicename="https://cig.dhl.de/services/sandbox/soap",
session = Session()
session.auth = HTTPBasicAuth(user, password)
session.url = servicename

transport = Transport(
        cache=SqliteCache(),
        session=session,
        )   
print(dir(transport))
client = Client(
        wsdl=wsdl, 
        transport=transport
        )   
```

in this example it does not authenticate me  via cig.dhl... 

```
  <wsdl:service name="GVAPI_2_0_de">
    <wsdl:port name="GKVAPISOAP11port0" binding="bcs:GKVAPISOAP11Binding">
      <soap:address location="https://cig.dhl.de/services/production/soap"/>
    </wsdl:port>
  </wsdl:service>
```

or may I need to change those then for sandbox-testing?
also I tried to change the service endpoint, but may this might be not correct?
But this does not work. If i use same http-auth-credentials with curl it works.

```
service = client.create_service(
        '{http://dhl.de/webservices/businesscustomershipping}GKVAPISOAP11Binding',
        servicename,
        )
```

This sends it always over: ```zeep.transports: HTTP Post to https://cig.dhl.de/services/production/soap:
```

instead of ```https://cig.dhl.de/services/sandbox/soap```

**Comment by regolith** [comment]
I am guessing that after you do `service = client.create_service(...)` you are still making your calls using `client.service.some_method(...)` rather than using the new service proxy you created (`service.some_method(...)`), and that is why it continues to use the default url.

**Comment by mvantellingen** [comment]
I think @regolith is right. Further more, please use stackoverflow for support questions. I really like to keep github issues for bug reports
