### ISSUE TITLE
Apply ecef5a8b and 47cffb96 to http.py

### ISSUE THREAD

**Issue by marksteward** [mvantellingen/python-zeep#765]
Just passing by while trying to debug something and noticed that while 79578dd applied the buggy code to both soap and http transports, the subsequent improvements only apply to the soap.py transport:

ecef5a8b Improve upgrading http urls to https (#269)
47cffb96 Fixed error while processing service port for HTTPS urls. (#268)

They should probably also be copied to http.py if that's still used.

**Comment by mvantellingen** [comment]
Can you create a PR for this? Thanks

**Comment by mwisslead** [comment]
I also stumbled upon this bug and it didn't look like @marksteward or anyone was fixing this so I submitted a PR myself.
