### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by ryandeng1** [mvantellingen/python-zeep#766]
Does Zeep close connections after sending a request from client to server?
Is there a way to do so?

This is because I think the webserver I am using does not close connections after responding to them and I was wondering if there was a way to manually tell the server to close the connection after a client sends them a request.

Thanks

**Comment by mvantellingen** [comment]
Zeep by default uses the requests library for handling the connection. Please see http://docs.python-requests.org/en/master/

**Comment by abhishar03** [comment]
The link says 404, any other documentation for this?

**Comment by philosophicles** [comment]
For anyone else finding this via search, the current documentation URL for the `requests` library is https://requests.readthedocs.io/en/master/.

**Comment by JemPak** [comment]
You can use `client.transport.session.close()` if you need to close the connection.
