### ISSUE TITLE
can't deserialize empty response

### ISSUE THREAD

**Issue by nikeighley** [mvantellingen/python-zeep#77]
If an empty response is returned an exception is thrown

`<?xml.version="1.0".encoding="UTF-8"?>
<SOAP-ENV:Envelope.xmlns:
 SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema".xmlns:ns="
 http://wsdl/AlarmSoap.wsdl">
	<SOAP-ENV:Body><ns:GetAlarmEventsBySessionResponse>
		</ns:GetAlarmEventsBySessionResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`
`
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/soap.py", line 250, in process_reply
    return self.output.deserialize(node)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/messages.py", line 206, in deserialize
    if len(item._xsd_type.properties()) == 1:
AttributeError: 'NoneType' object has no attribute '_xsd_type'
`

WSDL
[AlarmSoap.txt](https://github.com/mvantellingen/python-zeep/files/313916/AlarmSoap.txt)

**Comment by mvantellingen** [comment]
Fixed i think :)
