### ISSUE TITLE
create_message returning empty node

### ISSUE THREAD

**Issue by duduklein** [mvantellingen/python-zeep#772]
Hi, I was trying to get the XML that is sent to the server through the create_message method, but my node is empty.

Here is the code to reproduce it with zeep 2.5.0 (from Pypi):

```
from zeep import Client
base_url = "http://espace.recette.geodis.com/geolabel/services/RechercherLocalite?wsdl"
client = Client(base_url)
auth = client.get_element("ns0:authenticationInfo")
h = auth(userName="123456", password="qwerty")
client.set_default_soapheaders([h])
node = client.create_message(client.service, "findLocalite", codePays="FR", codePostal="38630")
```

Just print `node.text` and you will see it's empty. Doing `client.service.findLocalite(codePays="FR", codePostal="38630")` with the correct username and passowrd works correctly.

**Comment by regolith** [comment]
`node` is an xml element, so `node.text` gets the text directly contained by the node, not the string representation of the xml. try:
```
from lxml import etree
etree.tostring(node)
```

**Comment by mvantellingen** [comment]
Yup, use etree.tostring()
