### ISSUE TITLE
Assertion error in visitor.py when xs:all contains an xs:annotation

### ISSUE THREAD

**Issue by alanpowell** [mvantellingen/python-zeep#773]
If the XSD contains an <xs:all> which contains an <xs:annotation> then parsing fails with an assertion error in function visit_all in visitor.py

Console log:
  File "C:\Program Files (x86)\Python27\lib\site-packages\zeep\xsd\visitor.py", line 892, in visit_all
    assert None not in result
AssertionError

Moving the assertion to the parent complextype does not cause an error. Note: I don't own the WSDL so cannot change it.

<xs:complexType name="CT1">
                <xs:all>
					<xs:annotation>
						<xs:documentation>
							some information
						 </xs:documentation>
					</xs:annotation>
                   <xs:element name="e1" type="xs:string" minOccurs="1"/>
                   <xs:element name="e2" type="xs:string" minOccurs="1"/>				   
                </xs:all>
</xs:complexType>

You can reproduce with command: 
python -mzeep https://api3.jasperwireless.com/ws/schema/Terminal.wsdl

Python 2.7, Zeep 2.5.0

**Comment by martinlowinski** [comment]
Same error with Python 3.6, Zeep 2.5.0 and the WSDL from https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/geschaeftskundenversand-api/2.2/geschaeftskundenversand-api-2.2.wsdl However, there is no `xs:all` in the XSD.
