### ISSUE TITLE
Error in Client instantiate: ValueError: Invalid tag name 'string[]'

### ISSUE THREAD

**Issue by gbrennon** [mvantellingen/python-zeep#780]
I'm developing a WSDL client and when I call Client I'm receiving this ValueError.

Zeep version: 3.0
Python version: 3.6
WSDL URL: http://acessows.sytes.net:9191/recorte/webservice/20150600/service/escritorios.php?WSDL

Error:
- ValueError: Invalid tag name 'string[]'

**Comment by gbrennon** [comment]
up

**Comment by mvantellingen** [comment]
down

**Comment by davideferre** [comment]
I'm facing the same issue. Instantiating a `Client` with the wsdl url raise a `ValueError: Invalid tag name 'string[]'`. I've also tried to setup a settings with `strict=False, xml_huge_tree=True` but the result is the same.

Zeep version 3.4.0
Python version 3.6

I've validated my xml  with w3c validator and it says "No errors found".

Anyone can help me trying to solve this error?

**Comment by gotfredsen** [comment]
Same problem:

```
  File "/home/bg/.local/lib/python3.8/site-packages/zeep/utils.py", line 36, in as_qname
    return etree.QName(namespace, local)
  File "src/lxml/etree.pyx", line 1831, in lxml.etree.QName.__init__
  File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name 'string[]'
```

Python 3.8.3
zeep 3.4.0
lxml 4.5.1

I also validate my WDSL - no problem

As this uses `lxml`, will it help to use an earlier version?

**Comment by davideferre** [comment]
> Same problem:
> 
> ```
>   File "/home/bg/.local/lib/python3.8/site-packages/zeep/utils.py", line 36, in as_qname
>     return etree.QName(namespace, local)
>   File "src/lxml/etree.pyx", line 1831, in lxml.etree.QName.__init__
>   File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
> ValueError: Invalid tag name 'string[]'
> ```
> 
> Python 3.8.3
> zeep 3.4.0
> lxml 4.5.1
> 
> I also validate my WDSL - no problem
> 
> As this uses `lxml`, will it help to use an earlier version?

In my case there's an error on web service side. All is fine in this package.

**Comment by gotfredsen** [comment]
Ahh ok.
I got it to work by reading in the WDSL and then passing it to keep:

```
    wdsl =  urllib.request.urlopen(wsdlurl).read().decode('utf-8')
    client = zeep.Client(wsdl=wdsl)
```
