### ISSUE TITLE
Problem with validation simple type with restriction/enumeration 

### ISSUE THREAD

**Issue by MikeBernson** [mvantellingen/python-zeep#784]
The follow script has two elements that should create an errors.
Elements AvailableFormActions and FormType are not valid by restriction in wsdl

I am running version 3.0 from pypi
`from zeep import Client

from datetime import date

def set_form_base(client, form_type, parent_dln=None):
    ns2 = client.type_factory('ns2')
    kw = {}
    kw['IsDirty'] = False
    kw['IsEntityNew'] = False
    kw['SubmissionType'] = 'NewSubmission'
    kw['AvailableFormActions'] = ns2.FormActions(['SubmittableXX'])
    kw['IsSsasForm'] = False
    kw['IsPasrrForm'] = False
    kw['IsParentFormInCompletedStatus'] = False
    kw['FormType'] = ns2.FormTypes('RTN3618X')
    kw['CurrentSection'] ='NotSet'
    kw['InitialSectionIdentifier'] = 'NotSet'
    kw['IsFormActionClickedA'] = False
    kw['IsFormActionClickedB'] = False
    kw['IsPL1AdmittedtoNFClicked'] = False
    kw['FoundNFMatch'] = False
    kw['MediaType'] = 0
    kw['ReceivedDate'] = date(1, 1, 1)
    kw['CurrentStatus'] = 0
    kw['Source'] = 'NotSet'
    kw['TestProductionIndicator'] = 'Production'

    form_type = client.get_type('ns2:RTN3618Form')
    form = form_type(**kw)
    return form
        
client = Client("https://securereg.tmhp.org/careformsExternal/ExternalService.asmx?WSDL")
form = set_form_base(client, "ns1:RTN3618Form")

results = client.create_message(client.service, 'Submit3618',
        form=form, userName='XXX', password='XXXX',
        softwareKey='XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX')
from lxml import etree
print etree.tostring(results, pretty_print=True)
`
``
`[bug.zip](https://github.com/mvantellingen/python-zeep/files/2208106/bug.zip)
`

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
