### ISSUE TITLE
Error when trying UsernameToken and Signature together and signing. 

### ISSUE THREAD

**Issue by mitchea5** [mvantellingen/python-zeep#788]
Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
    3.0.0
2. The WSDL you are using
`   https://community.workday.com/sites/default/files/file-hosting/productionapi/Integrations/v29.1/Integrations.wsdl`

I am attempting to connect to an endpoint that requires a username and certificate authentication. 

There are two issues I am running into so far:

1) For some reason the userid was not being added so the previous developer was trying to add it via  plugin:

 ```
 session = Session()
    session.verify = 'pubkey'
    transport = Transport(session=session)
    client = Client(
        wsdl=myurl, transport=transport,
        wsse=Signature('privkey,'pubkey),
        plugins=[RequestHeaderPlugin()],
        )

```
The plugin adds the username token (and password if in debug mode).

```
 class RequestHeaderPlugin(Plugin):
        """
        Modify the request header and add Username and Password to the Security header created by
        the wsse:Signature call
        """
        def egress(self, envelope, http_headers, operation, binding_options):
            maker = ElementMaker(
                namespace='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd')
            if args.nopasswd:
                node = maker.UsernameToken(
                    maker.Username(userid),
                )
            else:
                node = maker.UsernameToken(
                    maker.Username(userid),
                    maker.Password(password) ,
                )
            security = get_security_header(envelope)
            security.append(node)

```

When I specify the no password option I get the following message back:

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault xmlns:wd="urn:com.workday/bsvc"><faultcode>SOAP-ENV:Client.authenticationError</faultcode><faultstring>invalid username or password</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>`

So reviewing this, it sounds like it is not necessary to do this, this should work:

`http://docs.python-zeep.org/en/master/wsse.html?highlight=x509#usernametoken-and-signature-together`

So:

 ```
  session = Session()
    session.verify =pubkey
    user_name_token = UsernameToken(userid)
    signature = Signature(privkey,pubkey),
    transport = Transport(session=session)
    client = Client(
        wsdl=myurl, transport=transport,
        wsse=[user_name_token,signature]
        )

```
But when I try that I get:

`(<class 'AttributeError'>, AttributeError("'list' object has no attribute 'apply'",), <traceback object at 0x7f631d446bc8>)`

2) The endpoint supports the following algorithms. Is there somewhere I can/need to change in signature.py to get it to work? My key is SHA 256 and cannot be downgraded. 

`Digest`

```
SHA256 
SHA512
```

`Signature`

```
RSA_SHA256 
RSA_SHA1 

```
`Transform`

`ENVELOPED `

`Canonicalization`
```

INCLUSIVE
INCLUSIVE_WITH_COMMENTS 
EXCLUSIVE 
EXCLUSIVE_WITH_COMMENTS 
```

**Comment by mitchea5** [comment]
It appears as though the documentation has been updated but the release has not. There were several changes made on June 17th but the 3.0.0. release was June 16th. Adding in the additional commits stopped the first error.

**Comment by mvantellingen** [comment]
Yes, the documentation by default points to the master branch (its just readthedocs/sphinx).
