### ISSUE TITLE
Error create_message 

### ISSUE THREAD

**Issue by dsxcz** [mvantellingen/python-zeep#791]
Hi, 

1. Version: 3.0.0
2. WSDL agnostic
3. Error occures just in testing case when creating message and generating XML (no sending requests), so no client initialized...

Error:
```
  File "/usr/local/c2avenv/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 54, in create_message
    envelope, http_headers = self._create(operation, args, kwargs)
  File "/usr/local/c2avenv/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 92, in _create
    if client.settings.extra_http_headers:
AttributeError: 'NoneType' object has no attribute 'settings'

```
Possibly patch attached.

[patch.diff.txt](https://github.com/mvantellingen/python-zeep/files/2221039/patch.diff.txt)

**Comment by mvantellingen** [comment]
Your patch seems correct, but while trying to reproduce I'm wondering if there is ever a case where the client is None in that method. Can you provide (as requested when you created the issue btw) a runnable example script?

**Comment by mvantellingen** [comment]
See ba05097b1f45811895c7863813058fdfd519561b

**Comment by dsxcz** [comment]
Problem occurs after update to version 3.0. Therefore  I looked deeper to my code and it turns out I'm using create_message little bit different (it's in debug branch to show exact XML request). 
Runable function to reproduce error:
```
def test_create_message_xml():
    client_obj = client.Client('tests/wsdl_files/soap.wsdl')
    data = client_obj.service._binding.create_message(
        'GetLastTradePrice', tickerSymbol="ZEEP")
    assert data
    # from lxml import etree
    # print(etree.tostring(data))
```

**Comment by mvantellingen** [comment]
Ah yeah that is not supported anymore. The official api is client.create_message
