### ISSUE TITLE
Pass a dict as parameter in a operation

### ISSUE THREAD

**Issue by tng10** [mvantellingen/python-zeep#8]
Hi, 

First of all, I'd like to say that this is a very nice soap library for python.

```
<message name="SearchFilter">
<part name="user" type="xsd:string"/>
<part name="password" type="xsd:string"/>
<part name="parameters" type="tns:searchFilterIn"/>
</message>
```

We have the following code:

```
from zeep import Client
client = Client("http://some-soap-endpoint?WSDL") 
parameters_info = {"type": "some-value"}
client.service.SearchFilter("user", "password'" parameters=parameters_info)
```

The question is how can I pass these parameters? Is this correct? Thanks

**Comment by lorenzog** [comment]
Hi, I've bumped on the library recently and I think it's nice too. I think what you need to do requires using something like:

    parameters_info = client.get_type('ns1:some-value')
    # then you can populate the object
    parameters_info.foo = "bar"
    # and assuming the SearchFilter call expects a 'parameters' parameter...
    client.service.SearchFilter(parameters=parameters_info)

May I also suggest using something like `ipython` to do tab-completion of the various functions?

**Comment by tng10** [comment]
Thanks man! Now it is working properly!
I will start using ipython for tab-completion and other features as well.
