### ISSUE TITLE
After upgrading to Adwords 13.0 I am facing the following problem in my application

### ISSUE THREAD

**Issue by thamukannan** [mvantellingen/python-zeep#807]
[error]     self._db_path, detect_types=sqlite3.PARSE  _DECLTYPES)
[error] OperationalError: unable to open database file

It appears that the system is not able to open the cache file. I have tried changing the file access and owner permissions and still no change.

**LINUX, PYTHON2.7, DJANGO**

Kindly help.

**Comment by mvantellingen** [comment]
Probably a filesystem permission issue
