### ISSUE TITLE
Passing argument for a complex type Any

### ISSUE THREAD

**Issue by saikiranp80** [mvantellingen/python-zeep#809]
Hi,

I have a soap request that take phone object which contains this vendorconfig parameter.
<xsd:complexType name="XVendorConfig">
		<xsd:sequence>
			<xsd:any maxOccurs="unbounded" minOccurs="0" namespace="##local" processContents="skip"/>
		</xsd:sequence>
	</xsd:complexType>

When i do get_phone, it returns a phone object which contains vendor config with list of lxml.etree._Element objects.

so how can i pass phone object with vendor config as argument to update_phone(phone)? when i pass it as a dict {'_value_1': [{'param1': 'value1'}, {'param2': 'value2'}]} i get the following error..

dict doesn't have a 'value'

so i looked at the code for any where it is throwing this error

line no 161: https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/xsd/elements/any.py

how can i pass the vendor config as dict so that i can resolve the above error.

there are other options to use zeep.xsd.AnyObject or create lxml.etree._Element, but i would like to know if i can pass it as dict as dict is also accepted as per Any class.

Thank you
saikiran

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
