### ISSUE TITLE
ValueError: No visitor defined for '{http://www.w3.org/1999/xhtml}head'

### ISSUE THREAD

**Issue by kdheepak** [mvantellingen/python-zeep#81]
I'm getting the above error. Do you know what the problem might be?

**Comment by mvantellingen** [comment]
Well I think an invalid schema is loaded. Need way more info to help you out :-)

**Comment by kdheepak** [comment]
I had a feeling that that may have not been enough information at the time I opened this issue. I was unfortunately not able to download the files then. I've now attached an Archive of the files that reproduce this error - [Archive.zip](https://github.com/mvantellingen/python-zeep/files/319575/Archive.zip)

**Comment by mvantellingen** [comment]
So it seems that the WSDL you are loading is really legacy (but yeah it's soap). It has an xsd:import statement for namespace="http://www.w3.org/XML/1998/namespace" without schemaLocation attribute. I've removed the invalid fallback to try to import based on the namespace alone.

If you update the import statement from the types.xsd to add "schemaLocation="http://www.w3.org/XML/1998/namespace.xsd" then it will still fail since the wsdl references elements defined in the types.xsd but since xml schema import are not transitive it can't reach it. If you add wsdl:import types.xsd in the wsdl's types definition then it still doesn't work because well, http://www.w3.org/XML/1998/namespace.xsd uses a legacy xml namespace (and see the contents in that file, it basically says 'DONT USE THIS, ITS OLD') 😄 

Soo you need to hack the wsdl / xsd's a bit too make it work i'm afraid.

**Comment by kdheepak** [comment]
Wow. Thanks for taking a detailed look at this. If I changed the namespace.xsd file to something more recent, would that solve the problem? Or does the file that references namespace.xsd need to be updated completely?

**Comment by dr-leo** [comment]
Hello,

congrats to what looks like a promising and much needed effort.

I ran into the same problem with current code-base from github. The initial WSDL comes from imf.org,
a serious source for SDMX data. See script and transcript below. 

suds_py3 coped with it up to a point before
running into an infinite recursion. I'm sure you guys can do better.

Leo


import zeep
url = 'http://dataservices.imf.org/sdmx21/SDMX_WCF_Service21.svc?wsdl'
c = zeep.Client(wsdl=url)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\stefan\Documents\dev\pysdmx\imf_session.py in <module>()
      3 url = 'http://dataservices.imf.org/sdmx21/SDMX_WCF_Service21.svc?wsdl'
      4 location = 'https://registry.sdmx.org/schemas/v2_1/SDMXMessage.xsd'
----> 5 c = zeep.Client(wsdl=url)

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\client.py in __init__(self, wsdl, wsse, transport, service_name, port_name
)
     50
     51         self.transport = transport or Transport()
---> 52         self.wsdl = Document(wsdl, self.transport)
     53         self.wsse = wsse
     54

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\wsdl\wsdl.py in __init__(self, location, transport)
     60         document = self._load_content(location)
     61
---> 62         root_definitions = Definition(self, document, self.location)
     63         root_definitions.resolve_imports()
     64

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\wsdl\wsdl.py in __init__(self, wsdl, doc, location)
    153         self.parse_imports(doc)
    154
--> 155         self.types = self.parse_types(doc)
    156         self.messages = self.parse_messages(doc)
    157         self.port_types = self.parse_ports(doc)

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\wsdl\wsdl.py in parse_types(self, doc)
    302         return Schema(
    303             schema_node, self.wsdl.transport, self.location,
--> 304             self.wsdl._parser_context)
    305
    306     def parse_messages(self, doc):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\schema.py in __init__(self, node, transport, location, parser_context)

     26         if node is not None:
     27             self._root = SchemaDocument(
---> 28                 node, transport, location, self._parser_context, locatio
n)
     29
     30             self._root.resolve()

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\schema.py in __init__(self, node, transport, location, parser_context,
 base_url)
    171
    172             visitor = SchemaVisitor(self, parser_context)
--> 173             visitor.visit_schema(node)
    174
    175     def __repr__(self):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\visitor.py in visit_schema(self, node)
     95         parent = node
     96         for node in node.iterchildren():
---> 97             self.process(node, parent=parent)
     98
     99     def visit_import(self, node, parent):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\visitor.py in process(self, node, parent)
     47         if not visit_func:
     48             raise ValueError("No visitor defined for %r" % node.tag)
---> 49         result = visit_func(self, node, parent)
     50         return result
     51

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\visitor.py in visit_import(self, node, parent)
    175         schema = self.schema.__class__(
    176             schema_node, self.schema._transport, location,
--> 177             self.parser_context, base_url)
    178
    179         self.schema._imports[namespace] = schema

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\schema.py in __init__(self, node, transport, location, parser_context,
 base_url)
    171
    172             visitor = SchemaVisitor(self, parser_context)
--> 173             visitor.visit_schema(node)
    174
    175     def __repr__(self):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\visitor.py in visit_schema(self, node)
     95         parent = node
     96         for node in node.iterchildren():
---> 97             self.process(node, parent=parent)
     98
     99     def visit_import(self, node, parent):

C:\Users\stefan\Anaconda3\envs\py35\lib\site-packages\zeep-0.14.0.dev0-py3.5.egg
\zeep\xsd\visitor.py in process(self, node, parent)
     46         visit_func = self.visitors.get(node.tag)
     47         if not visit_func:
---> 48             raise ValueError("No visitor defined for %r" % node.tag)
     49         result = visit_func(self, node, parent)
     50         return result

ValueError: No visitor defined for '{http://www.w3.org/1999/xhtml}head'

In [2]:

**Comment by mvantellingen** [comment]
Hi, could you please open new issues instead of commenting on existing closed?

**Comment by dr-leo** [comment]
Well taken. I just thought it would be acceptable to comment on a
closed issue instead of opening a new on under the same title. Perhaps
you can reopen it.

The code example I've given should be sufficient to reproduce the issue.

Thanks for all your hard work and your responsiveness.

Leo
