### ISSUE TITLE
XMLParseError("Unexpected element %r" % elements[0].tag)

### ISSUE THREAD

**Issue by polsobol** [mvantellingen/python-zeep#821]
The zeep module has a problem with parsing XML respose.
XMLParseError("Unexpected element %r" % elements[0].tag)
zeep.exceptions.XMLParseError: Unexpected element 'user'

Details:
1. Zeep 3.1.0
2. [WSDL](https://www.innovaphone.com/wsdl/pbx10_00.wsdl)
3. [pbxPollResponse](https://gist.github.com/polsobol/0e673ff60a5ecd7a7dd5bc3645e1d421)

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
