### ISSUE TITLE
p12 key format for wsse

### ISSUE THREAD

**Issue by zbynekdrlik** [mvantellingen/python-zeep#824]
Is it possible to use keys from p12 file for wsse.

**Comment by mitchea5** [comment]
Yes, but you'll need openssl to extract the keys and root CA (if applicable). Available on virtually all linux distributions and cygwin.

Breaking Apart a PFX into Private Key, Certificate, and CA Chain

https://operational.io/openssl-commonly-used-commands/

**Comment by daking83** [comment]
You could manage it with the Python OpenSSL package.
This example extracts the keys and stores them for the current user (setting the right permissions first!)
The functions `getKey()` and `getCert()` provide the pathnames to the newly generated files. So you could provide these to the Python `Session`.
```python
pkcs12 = PKCS12Manager(p12file, p12pass)
session = Session()
session.cert = (pkcs12.getCert(), pkcs12.getKey())
```


```python
import os
from OpenSSL import crypto

class PKCS12Manager():

    def __init__(self, p12file, passphrase):
        self.p12file = p12file
        self.unlock = passphrase
        self.webservices_dir = ''
        self.keyfile = ''
        self.certfile = ''

        # Get filename without extension
        ext = os.path.splitext(p12file)
        self.filebasename = os.path.basename(ext[0])

        self.createPrivateCertStore()
        self.p12topem()

    def getKey(self):
        return self.keyfile

    def getCert(self):
        return self.certfile

    def createPrivateCertStore(self):
        home = os.path.expanduser('~')
        webservices_dir = os.path.join(home, '.webservices')
        if not os.path.exists(webservices_dir):
            os.mkdir(webservices_dir)
        os.chmod(webservices_dir, 0o700)
        self.webservices_dir = webservices_dir

    def p12topem(self):
        p12 = crypto.load_pkcs12(file(self.p12file, 'rb').read(), self.unlock)

        # PEM formatted private key
        key = crypto.dump_privatekey(crypto.FILETYPE_PEM, p12.get_privatekey())

        self.keyfile = os.path.join(self.webservices_dir, self.filebasename + ".key.pem")
        open(self.keyfile, 'a').close()
        os.chmod(self.keyfile, 0o600)
        with open(self.keyfile, 'w') as f:
            f.write(key)


        # PEM formatted certificate
        cert = crypto.dump_certificate(crypto.FILETYPE_PEM, p12.get_certificate())

        self.certfile = os.path.join(self.webservices_dir, self.filebasename + ".crt.pem")
        open(self.certfile, 'a').close()
        os.chmod(self.certfile, 0o644)
        with open(self.certfile, 'w') as f:
            f.write(cert)
```

**Comment by mvantellingen** [comment]
Thanks for the help :-)

**Comment by preeth1** [comment]
I am getting "Unresolved reference 'file'" when I try to use your code, I am using Python 3.7.3. Is there a missing import?

**Comment by diegocatalao** [comment]
@preeth1 
``
with open(self.p12file, 'rb') as file:
  p12 = crypto.load_pkcs12(file.read(), self.unlock)``

**Comment by diegocatalao** [comment]
@preeth1 
``python
    with open(self.p12file, 'rb') as file:
      p12 = crypto.load_pkcs12(file.read(), self.unlock)
``

**Comment by diegocatalao** [comment]
@preeth1 
Try:
`with open(self.p12file, 'rb') as file: p12 = crypto.load_pkcs12(file.read(), self.unlock)`

**Comment by diegocatalao** [comment]
Probably you have a new errors:
binary string to string use .decode('utf-8')

f.write(key.decode('utf-8'))

**Comment by BryceStevenWilley** [comment]
Maybe I'm commenting on a dead thread, but is there any reason zeep can't handle PKCS12 files directly, without splitting? I'm not an expert with xmlsec, but all that's happening signatures here is: https://github.com/mvantellingen/python-zeep/blob/a29b5ce8ec7879b020dd66c6ad9fcb0c9b7fe1c2/src/zeep/wsse/signature.py#L35

and xmlsec does seem to have a `xmlsec.KeyFormat.PKCS12_PEM` key that can load PKCS12 files (https://github.com/mehcode/python-xmlsec/blob/18cbae111e2d1afff99687211aadb49c33c4a8f5/src/constants.c#L410). Is there something else that would block extending `Signature` to take PKCS as well that I'm missing? I'd be willing to implement this if it would work.
