### ISSUE TITLE
Documentation for 2.5.0?

### ISSUE THREAD

**Issue by denizdogan** [mvantellingen/python-zeep#828]
I'm working on a project where we use Zeep 2.5.0 and was wondering if the documentation for that particular version is still available online? I can only seem to find the documentation for the latest version of the package. Thanks!

**Comment by NeuroWinter** [comment]
You can use the tags option when looking at the docs folder in github. 
I am not 100% sure that this is the right docs though.

https://github.com/mvantellingen/python-zeep/tree/2.5.0/docs
