### ISSUE TITLE
how to use zeep with a proxy

### ISSUE THREAD

**Issue by vipin-kumar-tomar** [mvantellingen/python-zeep#829]
I have a proxy server provided as SOAP endpoint which actually handle the SOAP request and interact with actual soap server.
As I dont' have a wsdl link so my question is, will zeep work in this scenario. If yes, then how?
If no, can you please suggest some other library which may handle this scenario or a decent way to do this.
I am able to send the request and get response using "requests". But that use xml as input and output both.

Let me know if you require more information.

**Comment by vipin-kumar-tomar** [comment]
thanks for your clarification!
I got a wsdl copy from the vendor and it works fine now.

**Comment by mvantellingen** [comment]
you can also check the requests documentation, since that is used for http calls
