### ISSUE TITLE
zeep v3.1.0 failing to parse response from a service with Complex WSDL structure

### ISSUE THREAD

**Issue by ramprasadkolla4** [mvantellingen/python-zeep#835]
1. The version of zeep  -- 3.1.0
2. The WSDL you are using
[xmlmgmt.zip](https://github.com/mvantellingen/python-zeep/files/2439194/xmlmgmt.zip)
3. And most importantly, a [runnable example script]
`from requests import Session
from requests.auth import HTTPBasicAuth
from zeep import Client, xsd
from zeep.transports import Transport
import warnings

warnings.filterwarnings("ignore")
session = Session()
session.verify = False

session.auth = HTTPBasicAuth('user', 'pwd#22222222')
client = Client('../xmlmgmt/xml-mgmt.wsdl',transport=Transport(session=session))
service = client.create_service('{http://www.datapower.com/schemas/management/wsdl}xml-mgmt-soap', 'https://myserver:5550/service/mgmt/3.0')
mpg = service.operation(domain="GuidanceCare", **{"get-config":{"class":"MultiProtocolGateway"}})
print(mpg)`

Sample request that works:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:man="http://www.datapower.com/schemas/management">
   <soapenv:Header/>
   <soapenv:Body>
     <man:request domain="GuidanceCare">
         <man:get-config class="MultiProtocolGateway"/>
      </man:request>
   </soapenv:Body>
</soapenv:Envelope>

Sample response when I set raw_response=True in client.settings:
[get_config_resp.txt](https://github.com/mvantellingen/python-zeep/files/2439231/get_config_resp.txt)

I believe zeep is unable to parse the response. Getting below error:
[zeep_parse_error.txt](https://github.com/mvantellingen/python-zeep/files/2439243/zeep_parse_error.txt)

Please help me understand the issue and a possible solution to fix it.

Thanks!

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
