### ISSUE TITLE
Help/Issue(?) with argument ArrayOf_xsd_anyType

### ISSUE THREAD

**Issue by degubellini** [mvantellingen/python-zeep#856]
Hello,
I need help to create a call to an operation that has arguments of type ArrayOf_xsd_anyType
I read 
https://python-zeep.readthedocs.io/en/master/datastructures.html

and I have tried everything but I can't figure it out how to do it 

wsdl file is here
https://gist.github.com/degubellini/c51360eea2c54d8556afbec24171e6d2

I am using zeep 2.5.0

I want to create a Auto Discovery Entry whose signature is 
createAutoDiscoveryEntry(in0: ns0:ResourceIdentityInfo, in1: ns12:AutoDiscoveryInfo) -> createAutoDiscoveryEntryReturn: ns0:ResourceIdentityInfo

Now type AutoDiscoveryInfo is 

<complexType name="AutoDiscoveryInfo">
<sequence>
<element name="accountCredentials" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="autoDiscoveryType" nillable="true" type="xsd:string"/>
<element name="communityCredentials" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="description" nillable="true" type="xsd:string"/>
<element name="excludeRanges" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="id" nillable="true" type="tns2:ResourceIdentityInfo"/>
<element name="includeRanges" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="mappedDeviceServer" nillable="true" type="tns2:ResourceIdentityInfo"/>
<element name="privPassCredentials" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="pullAfterAutoDisc" nillable="true" type="xsd:string"/>
<element name="seedRanges" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="snmpV3Credentials" nillable="true" type="impl:ArrayOf_xsd_anyType"/>
<element name="useArpCache" type="xsd:boolean"/>
</sequence>
</complexType>

To make some tests I used this script (I took out sensible information)

https://gist.github.com/degubellini/113a818154c8d3a83f0e20d34d4fab70

and I have tried to assign to accountCredentials both  list_acctCredentialRII and acctCredentialRIIv2 but I get the same error that is 

"[...]
  File "/home/diego/virtual-env/django2.0/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/home/diego/virtual-env/django2.0/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 117, in render
    self.validate(value, render_path)
  File "/home/diego/virtual-env/django2.0/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 170, in validate
    self._validate_item(val, render_path)
  File "/home/diego/virtual-env/django2.0/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 197, in _validate_item
    "See http://docs.python-zeep.org/en/master/datastructures.html"
TypeError: Any element received object of type 'ResourceIdentityInfo', expected lxml.etree._Element or builtins.dict
See http://docs.python-zeep.org/en/master/datastructures.html#any-objects for more information"

I have checked http://docs.python-zeep.org/en/master/datastructures.html#any-objects 
but not luck on how to to do it or if there is a bug somewhere 

Any help please?

Thanks

Please note: calling config_AutoDiscoveryInfo I assigned zeep.xsd.SkipValue to many arguments to try to isolate the problem

**Comment by degubellini** [comment]
Hello,
anyone that could,please, address me to the right direction in relation to this? or is this a bug?

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
