### ISSUE TITLE
Unable to parse response that is an array of objects

### ISSUE THREAD

**Issue by peris** [mvantellingen/python-zeep#857]
1. Version of zeep = 3.1.0
2. WSDL = http://www.agrisensys.eu/soap/service.php?wsdl
3. Have generated a runnable script; I was able to see the response that comes back in the response (enabled debugging);

Issue: Unable to parse the response which contains an arrayOfObjects (defined in the schema) and still. 

Response is printed properly for operations that return single object.

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
