### ISSUE TITLE
Zeep performance Python2 vs Python3

### ISSUE THREAD

**Issue by Antho42** [mvantellingen/python-zeep#860]
Hi,

We used Zeep 3.1 in Python2, and when we migrate to Python3, every request take 3 more time than in Python2...

For example (very easy)

`from zeep import Client`
`from zeep.cache import SqliteCache`
`from zeep.transports import Transport`
`transport = Transport(cache=SqliteCache(), timeout=2)`
`client = Client(ws_url, transport=transport)`

Is this normal ? Is there something to do (param Zeep or Python3) to having the same performance ?

Thank you for your help.

**Comment by mvantellingen** [comment]
I did a lot of benchmarking in zeep to keep it as fast as possible. Please provide profiles of py2 va py3
