### ISSUE TITLE
Verify bug using  UsernameToken and Signature together in WSSE

### ISSUE THREAD

**Issue by csotomon** [mvantellingen/python-zeep#861]
Using WS-Security (WSSE) and if you want to use UsernameToken and Signature together, the client.wsse parameter is a list.

`from zeep import Client `
`from zeep.wsse.username import UsernameToken `
`from zeep.wsse.signature import Signature `
`user_name_token = UsernameToken('username', 'password')) `
`signature = Signature(private_key_filename, public_key_filename) `
`client = Client( 'http://www.webservicex.net/ConvertSpeed.asmx?WSDL',wsse=[user_name_token, signature])`

But when you run the code you will have this error:

**File "C:\Python\Python36\lib\site-packages\zeep\wsdl\bindings\soap.py", line 184, in process_reply
    client.wsse.verify(doc)
AttributeError: 'list' object has no attribute 'verify'**

The problem is that **soap.py** in line 184 is not checking if client.wsse is a list.

`if client.wsse:`
`            client.wsse.verify(doc)`

**Comment by csotomon** [comment]
I have created a merge request fixing it.

[https://patch-diff.githubusercontent.com/raw/mvantellingen/python-zeep/pull/862](https://patch-diff.githubusercontent.com/raw/mvantellingen/python-zeep/pull/862.patch)

**Comment by csotomon** [comment]
I added a test script, now you can accept the merge request

**Comment by mvantellingen** [comment]
The tests fail, I'm closing this issue. Lets continue in the PR
