### ISSUE TITLE
code maintenance

### ISSUE THREAD

**Issue by csotomon** [mvantellingen/python-zeep#865]
Is the developer team checking the bug reports and the merge request?

**Comment by mvantellingen** [comment]
There is no team. It’s just me all alone ;-)

Getting zeep to where it is now took quite some effort and free time. A lot of the issues are actually support requests with most of the time not a lot of info. So taking things slower as to keep my spirit up

**Comment by ron819** [comment]
> There is no team. It’s just me all alone ;-)
> 
> Getting zeep to where it is now took quite some effort and free time. A lot of the issues are actually support requests with most of the time not a lot of info. So taking things slower as to keep my spirit up

Note that there are 0 issues with "help wanted" tag so it's hard for new contributes to know with what to start...

**Comment by mvantellingen** [comment]
Even triaging all the incoming issues is quite some work :(

**Comment by mvantellingen** [comment]
Hell, most people create an issue without even formatting their code. Or don't provide any easy way to reproduce their issue, but instead require me to get their script even running on my laptop (~45 minutes of work) before i can even try to diagnose it. 

It's all really ungrateful work. But that's the open source community nowadays apparently.

**Comment by mvantellingen** [comment]
Just in 3 minutes, these issue:
 - #857 
 - #859
 - #839
 - #843

Ok, I think you all get the point :-)

**Comment by csotomon** [comment]
I'm agree with @ron819 if you need help, you can ask to the community about that, your library is very good and i know that a lot of people will be happy helping you.

**Comment by ron819** [comment]
@mvantellingen if someone open an issue and does not met the guidelines than close it.  It's ok to close an issue as it is a question and refer the user to stackoverflow. 

I suggest you to add a "good first issue" tag and also milestones to be used as a road map. Even if you know how to fix something don't fix it right away. let the community a chance to get involved. Give pointers/ideas/direction to the fix...  It's hard work at fist but once people are involved you can promote them with privileges to help you out.

**Comment by renatovico** [comment]
I love python-zeep and talk about the goodness in using he every day

**Comment by OmerJog** [comment]
@deronnax massive amount of low quality questions usually resulted by:
1. Lack of properly maintained docs with fully explained examples.
2. Lack of actual support on Stack-Overflow.

Take https://github.com/pandas-dev/pandas for example. They have vivid community on stack-ovweflow as well as well written docs + dozens of topics in their Github daily. Take a look over their closed topics you won't see many dumb questions. They are only 2 "head" committers in the project.

If project contributes are also involved with stack-overflow it helps for users to get answers when searching Google.
Regarding this project I can say first hard - It's hard to find answers. Even on stack-overflow most examples are for suds, so I'm not surprised many "dumb" questions are showing up here.
