### ISSUE TITLE
How to convert suds to zeep?

### ISSUE THREAD

**Issue by OmerJog** [mvantellingen/python-zeep#872]
I have a code which connects to SOAP API (Python 3.6):

```
    from suds.client import Client
    from suds import WebFault
        def bronto_data(self, page_num):
            self.bApi = Client(self.BRONTO_WSDL)
            session_id = self.bApi.service.login(self.TOKEN)
            session_header = self.bApi.factory.create("sessionHeader")
            filter_type = self.bApi.factory.create("filterType")
            self.contact_filter = self.bApi.factory.create("contactFilter")
            session_header.sessionId = session_id
            self.bApi.set_options(soapheaders=session_header)
            self.contact_filter.listId.append(contacts_list_id)
            self.contact_filter.type = filter_type.AND
            return self.bApi.service.readContacts(self.contact_filter, True, [], page_num)
```

This code works however since suds is deprecated I want to replace it with zeep library.

I couldn't find in the docs what are the equivalents of `service` & `factory`. Or info for easy convert from suds to zeep.

Can anyone give input on this?

**Comment by tpazderka** [comment]
The equivalent of `factory` is `type_factory()`. `service` is the same both in `zeep` and `suds`.

**Comment by OmerJog** [comment]
> type_factory

According tot he docs the type_factory is function that takes argument name space. I don't have that in suds.. what is that?

**Comment by tpazderka** [comment]
It takes the namespace of the object you are trying to create. But in this case, if you are creating a single object, then you might to create just that directly: https://python-zeep.readthedocs.io/en/master/datastructures.html#creating-objects

**Comment by OmerJog** [comment]
@tpazderka sorry I still don't understand what you are refiring.

The self.contact_filter will be contacted with more objects. I posted one to make it simple.

**Comment by tpazderka** [comment]
I think that you need something like this:
`session_header = self.bApi.get_type("ns0:sessionHeader")`
That should be equivalent to the code you have. You can replace the `ns0` byt the full namespace specified in WSDL file.
