### ISSUE TITLE
Possible bug for schema elements without targetNamespace

### ISSUE THREAD

**Issue by apollo13** [mvantellingen/python-zeep#879]
I am trying to get a WSDL file from a 3rd party company to work. During parsing zeep fails to properly map some messages and therefore some operations (See details below). From what I can gather is that the main problem seems to be that the `xsd:element` for `Add` has no `targetNamespace` and when resolving zeep prefixes with the `targetNamespace` of `wsdl:definitions`: https://github.com/mvantellingen/python-zeep/blob/c39197853e681fea773d5f6265b5971cfdf879d7/src/zeep/wsdl/parse.py#L36-L43

I am not sure if this is a bug in zeep or the WSDL, I can neither find a definitive answer in the XML Schema specs, nor in the WSDL ones. What I was able to find is from ws-i (http://www.ws-i.org/Profiles/BasicProfile-1.1.html#Schema_targetNamespace_Structure):
```
 R2105 All xsd:schema elements contained in a wsdl:types element of a DESCRIPTION MUST have a targetNamespace attribute with a valid and non-null value, UNLESS the xsd:schema element has xsd:import and/or xsd:annotation as its only child element(s). 
```
But I do not know if the `targetNamespace` from the `wsdl:definitions` should get inherited. I'll happily try to code a patch in zeep if you think this is  a bug in zeep.

**Version:** zeep==3.1.0
**WSDL:** https://apolloner.eu/~apollo13/Calculator.wsdl
**Example Script:**
```python
from lxml import etree
from zeep import Client

client = Client('https://apolloner.eu/~apollo13/Calculator.wsdl')

node = client.create_message(client.service, 'Add', [], {'a': 3, 'b': 4})

print(etree.tostring(node, pretty_print=True))
```
**Output:**
```
/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py:338: UserWarning: The wsdl:message for '{http://Example.org}ICalculator_Add_InputMessage' contains an invalid part ('parameters'): invalid xsd type or elements
  warnings.warn(str(exc))
/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py:338: UserWarning: The wsdl:message for '{http://Example.org}ICalculator_Add_OutputMessage' contains an invalid part ('parameters'): invalid xsd type or elements
  warnings.warn(str(exc))
/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/wsdl/definitions.py:130: UserWarning: The wsdl:operation 'Add' was not found in the wsdl:portType '{http://Example.org}ICalculator'
  warnings.warn(str(exc))
Forcing soap:address location to HTTPS
Traceback (most recent call last):
  File "/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/wsdl/definitions.py", line 149, in get
    return self._operations[key]
KeyError: 'Add'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/test.py", line 8, in <module>
    client.service, 'Add', [], {'a': 3, 'b': 4})
  File "/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/client.py", line 131, in create_message
    operation_name, args, kwargs, client=self)
  File "/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 63, in _create
    operation_obj = self.get(operation)
  File "/home/florian/dev/bap/bap-services/.venv/lib/python3.6/site-packages/zeep/wsdl/definitions.py", line 151, in get
    raise ValueError("No such operation %r on %s" % (key, self.name))
ValueError: No such operation 'Add' on {http://Example.org}DefaultBinding_ICalculator
```

**Comment by mvantellingen** [comment]
Could you check if the master branch works? I think the inheritance part of targetNamespace was indeed missing. See https://support.liquid-technologies.com/kb/a17/chameleon-schemas-schemas-without-a-target-namespace.aspx

Thanks for you work on Django btw 👍

**Comment by apollo13** [comment]
Would you be okay with me sharing the original WSDL with you somehow? I rather not post it public without an okay from the other company.

**Comment by apollo13** [comment]
I have the beginnings of a patch in https://github.com/apollo13/python-zeep/commit/488901a13589f735848430f4fdcb1586fe6baeed -- it sadly breaks to other tests; have to dig in (pointers appreciated :))

**Comment by mvantellingen** [comment]
Sure, you can mail the wsdl to michaelvantellingen@gmail.com

Regarding the failing unittest ```test_no_target_namespace```. I did a quick fix on my end too and ran into the same failing unittest. It's actually basically the same scenario's as your xsd but it asserts the opposite result. I'm wondering if that unittest is actually ok.

**Comment by apollo13** [comment]
The one thing I was wondering is also if the fix is on the wrong level. Ie the test makes sense for xsd, but wsdl requires a bit of different rules maybe… But I am somewhat at a loss here with all the (non-)specs.

**Comment by mvantellingen** [comment]
Could you give master a try again? I think i found a good solution which hopefully doesn't break other wsdl's. (Although then we should add tests for those cases)

**Comment by apollo13** [comment]
@mvantellingen Wow, that does actually fix the WSDL parsing issues. Many thanks! The remaining issue now is that if I call the ImportPMS method from the WSDL I did send you, then zeep generates two `soap:Body` elements, like this -- do you have any hints on where to look?
```
<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope">
   <soap-env:Body>
      <soap-env:Body>
		<!-- function call here -->
      </soap-env:Body>
   </soap-env:Body>
</soap-env:Envelope>
```

**Comment by apollo13** [comment]
I seem to see the reverse of https://github.com/mvantellingen/python-zeep/commit/4bd6e9dded4427f432ea5d3e7e8eda1a3d227376 -- ie I already have a body, but now the code again wraps it :)

**Comment by apollo13** [comment]
Okay, I think this issue could be closed; the WSDL parsing works fine now. Thanks you again!

I have opened a PR (#883) with a new issue that I run into; the PR only consists of a failing test and a description of where it fails and how. No idea where the correct point for a fix would be.

**Comment by mvantellingen** [comment]
Thanks :-)
