### ISSUE TITLE
SOAP response with PDF attachment throwing error

### ISSUE THREAD

**Issue by mrcoolhp** [mvantellingen/python-zeep#885]
Below is my web service call using Zeep
"from zeep import Client
client = Client('http://<IP/Servicename>/saw.dll/wsdl/v12')
service=client.bind('SAWSessionService')
sessionid=service.logon('obiadmin','Comcast01')
print(sessionid)
result=client.get_type('{urn://oracle.bi.webservices/v12}AnalysisExportResult')
exeopt=client.get_type('{urn://oracle.bi.webservices/v12}AnalysisExportExecutionOptions')
eo=exeopt(async=True,useMtom=False,refresh=True)
service=client.bind('AnalysisExportViewsService')
result=service.initiateAnalysisExport('//shared//Test//Check_GV2','PDF',executionOptions=eo,sessionID=sessionid)
service.completeAnalysisExport(queryID='PNdokn2oCqc7z5QVQRIvQQ',sessionID=sessionid)"

on last line of web service call, I should get below response along with PDF attachment.
{
    'viewData': None,
    'mimeType': 'application/pdf',
    'queryID': 'PNdokn2oCqc7z5QVQRIvQQ',
    'exportStatus': 'Done'
}

But there was some issue in Parsing,
I have installed zeep pacakge from master link as per below link on my research on this issue
https://github.com/mvantellingen/python-zeep/issues/301
https://github.com/mvantellingen/python-zeep/pull/302
my zeep version is 3.1.0

When I pass this request in SoapUI, i'm getting proper response with attachment, where as it fails in Zeep. Please find the below attachments
[SoapRequest.txt](https://github.com/mvantellingen/python-zeep/files/2658479/SoapRequest.txt)
[SoapResponse.txt](https://github.com/mvantellingen/python-zeep/files/2658480/SoapResponse.txt)
[Error.txt](https://github.com/mvantellingen/python-zeep/files/2658481/Error.txt)

Need your inputs on this.
Thanks

**Comment by mrcoolhp** [comment]
@mvantellingen - Could you please provide your thoughts on this ?

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
