### ISSUE TITLE
Rethinking the use of Chameleon schemas in #879

### ISSUE THREAD

**Issue by apollo13** [mvantellingen/python-zeep#887]
This is a follow up to #879. After the fixes there I was finally able to generate demo SOAP requests.

For tests I am using the WSDL from the tests itself:

https://github.com/mvantellingen/python-zeep/blob/713c779db7699b3c13fc9b1948eb3c6cfe32d828/tests/test_wsdl.py#L1040-L1106

I am attaching several requests using multiple clients.

First off, **SOAP UI:**
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body>
      <Add>
         <a>?</a>
         <b>?</b>
      </Add>
   </soapenv:Body>
</soapenv:Envelope>
```
Then against **Liquid studio** (which got mentioned in the previous issue):
```xml
<SOAP-ENV:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <Add xmlns:tns="http://Example.org" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <a>-3439</a>
      <b>1611</b>
    </Add>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
And then **zeep** itself (on master)
```xml
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
   <soap-env:Header xmlns:wsa="http://www.w3.org/2005/08/addressing">
      <wsa:Action>http://Example.org/ICalculator/Add</wsa:Action>
      <wsa:MessageID>urn:uuid:e1036f6a-04e1-459b-8795-a27f14a4da81</wsa:MessageID>
      <wsa:To>http://127.0.0.1:8000</wsa:To>
   </soap-env:Header>
   <soap-env:Body>
      <ns0:Add xmlns:ns0="http://Example.org">
         <ns0:a>3</ns0:a>
         <ns0:b>3</ns0:b>
      </ns0:Add>
   </soap-env:Body>
</soap-env:Envelope>
```

Zeep is the only client inheriting the target namespace of the wsdl definition; this might be wrong. Do you have any ideas what the "correct" approach is? The results are clearly different (no namespace vs a namespace)

**Comment by apollo13** [comment]
I have "fixed" the remaining test failure (https://github.com/apollo13/python-zeep/commit/4de539e86aefbd59599d33d5df0ae68ba1ecc824). Not sure if the test is wrong or the code needs more work. It basically boils down to how references should get resolved if they are not fully qualified…

**Comment by apollo13** [comment]
I've found a few more things in the XML schema docs; I'll write them up in another comment later and try to fix it.

**Comment by apollo13** [comment]
I think I was able to fix it in #888, would be glad to know what you think of it @mvantellingen

**Comment by mvantellingen** [comment]
I've merged it. Too be honest I'm not 100% sure that this is the correct approach, but it seems to work for you and doesn't break anything else so it seems valid. Better then that it doesn't get in soap land :-)

Thanks again

**Comment by apollo13** [comment]
Thank you! Yes, there is a high chance that another edge case will need more code to handle it -- but as you pointed out, this is mostly SOAP's fault :)
