### ISSUE TITLE
ImportError: cannot import name 'Schema'

### ISSUE THREAD

**Issue by joshuaduffy** [mvantellingen/python-zeep#89]
Getting this issue against `zeep=0.9.1` - same issue on `zeep=0.9.0` too

`=================================== ERRORS ====================================
____________________ ERROR collecting tests/soap/client.py ____________________
tests\soap\client.py:1: in <module>
    from zeep import Client
MY_ENV_REDACTED\lib\site-packages\zeep\__init__.py:1: in <module>
    from zeep.client import Client  # noqa
MY_ENV_REDACTED\lib\site-packages\_pytest\assertion\rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
MY_ENV_REDACTED\lib\site-packages\zeep\client.py:4: in <module>
    from zeep.wsdl import Document
MY_ENV_REDACTED\lib\site-packages\zeep\wsdl\__init__.py:1: in <module>
    from zeep.wsdl.wsdl import Document  # noqa
MY_ENV_REDACTED\lib\site-packages\_pytest\assertion\rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
MY_ENV_REDACTED\lib\site-packages\zeep\wsdl\wsdl.py:14: in <module>
    from zeep.xsd import Schema
E   ImportError: cannot import name 'Schema'
===================== 13 passed, 1 error in 0.35 seconds ======================`

I'm working in a virtual environment against Python 3.5.1. It seems to work if I import via the interpreter but not when I am working on my virtual environment and running my tests via `py.test`

**Comment by joshuaduffy** [comment]
Seems to be resolved in `0.10.0dev0`

**Comment by mvantellingen** [comment]
Ok, cool 👍
