### ISSUE TITLE
Zeep throws error when parsing valid wsdl file

### ISSUE THREAD

**Issue by NMO13** [mvantellingen/python-zeep#898]
First, I am not an expert with SOAP and wsdls. I hope I did not make any mistake.
But I think the parser can't parse the wsdl.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
Version: 3.1.0

2. The WSDL you are using
https://webservice.simu.myksv.at/NASApp/axis/services/urn:ksv-premium?wsdl

3. And most importantly, a [runnable example script](http://docs.python-zeep.org/en/master/reporting_bugs.html) which exposes the problem.

```
from zeep import Client
from requests import Session
from zeep.transports import Transport
session = Session()
client = Client('https://webservice.simu.myksv.at/NASApp/axis/services/urn:ksv-premium?wsdl',
                                transport=Transport(session=session))
```

4. Error message:

> Traceback (most recent call last):
>   File "<stdin>", line 2, in <module>
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/client.py", line 62, in __init__
>     wsdl, self.transport, settings=self.settings)
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 85, in __init__
>     root_definitions.resolve_imports()
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 237, in resolve_imports
>     binding.resolve(self)
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 128, in resolve
>     operation.resolve(definitions)
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 453, in resolve
>     self.output.resolve(definitions, self.abstract.output_message)
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 289, in resolve
>     self.body = self._resolve_body(info['body'], definitions, parts)
>   File "/home/osboxes/.virtualenvs/sb/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 430, in _resolve_body
>     element = part.element.clone()
> AttributeError: 'NoneType' object has no attribute 'clone'

When I try the same wsdl here, it works: https://www.plumvoice.com/soaptester/

**Comment by FlorianSchwendinger** [comment]
I get the same error, but with a few small changes in 
`zeep.wsdl.messages.soap.DocumentMessage._resolve_body`
I was able to get the client started.

This is the modified version:
```py
    def _resolve_body(self, info, definitions, parts):
        name = etree.QName(self.nsmap["soap-env"], "Body")

        if not info or not parts:
            return None

        # If the part name is omitted then all parts are available under
        # the soap:body tag. Otherwise only the part with the given name.
        if info["part"]:
            part_name = info["part"]
            sub_elements = [parts[part_name].element]
        else:
            sub_elements = []
            for part_name, part in parts.items():
                if not part.element is None:
                    element = part.element.clone()
                    element.attr_name = part_name or element.name
                    sub_elements.append(element)
        
        if len(sub_elements) == 0:
            return None
        elif len(sub_elements) > 1:
            self._is_body_wrapped = True
            return xsd.Element(name, xsd.ComplexType(xsd.All(sub_elements)))
        else:
            self._is_body_wrapped = False
            return sub_elements[0]
```

I am not sure if the changes I made make sense in the bigger picture of your entire code base. I was just trying to get the client running and this worked.

Hope this helps.
