### ISSUE TITLE
zeep trying to acces www.w3.org when out of internet

### ISSUE THREAD

**Issue by francoisihry** [mvantellingen/python-zeep#906]
Hi,

I need to access a WSDL host that is locally connected to the host running my script.
Here is my script
```
class Auth(AuthBase):
    def __init__(self, username, password, host):
        self.basic = HTTPBasicAuth(username, password)
        self.host = host

    def __call__(self, r):
        if r.url.startswith(self.host):
            return self.basic(r)
        else:
            return r
wsdl = 'https://<LOCAL_URL>/ProtectManager/services/v2011/incidents?wsdl'
user = "xxxx"
password = "xxxx"
session = Session()
session.auth = Auth(user, password, "https://<LOCAL_URL>")
session.verify = False
transport = Transport(session=session)
client = Client(wsdl=wsdl, transport=transport, settings=Settings(strict=False))
```
The host where my zeep script is running is not connected to the internet.
I am getting the above error : 
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.w3.org', port=80): Max retries exceeded with url: /2005/05/xmlmime (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002D323946128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))`

Any idea how to fix it without modifying the zeep library ?

**Comment by Smorrebrod** [comment]
Hi,
Got the same problem due to proxy settings which blocks the access to w3.org.

However i havent found a way to fix that without either changing the query in the zeep library directly, or setting up the files locally and point the w3 adresses to that location.

**Comment by francoisihry** [comment]
> 
> 
> Hi,
> Got the same problem due to proxy settings which blocks the access to w3.org.
> 
> However i havent found a way to fix that without either changing the query in the zeep library directly, or setting up the files locally and point the w3 adresses to that location.

Hi @Smorrebrod I found the trick!

Download the xmlmime file (http://www.w3.org/2005/05/xmlmime) and set it locally. Then load it in cache using the SqliteCache class. The library will no more try to connect to the internet:

```
from zeep.cache import SqliteCache
with open("/path/to/the/file/xmlmime.xml", mode="rb") as f:
    filecontent = f.read()
    cache = SqliteCache(timeout=None)
    cache.add("http://www.w3.org/2005/05/xmlmime", filecontent)
    cache.add("https://www.w3.org/2005/05/xmlmime", filecontent)
```

**Comment by igoldin74** [comment]
I am experiencing same issue. Is there a more straight way of mitigating this issue?
