### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by omfgroflbbq** [mvantellingen/python-zeep#91]
@mvantellingen: As stated in #73, you don't seem to be an advocate for 
last_sent() / last_received() functions, but some api's send their sessionid's in the response headers (e.g. twinfield). As of now, it appears to be impossible to obtain these response headers using zeep.

**Comment by mvantellingen** [comment]
Okay, that might be something we want to support, but I need to think about this some more.

For now you can of course subclass the transport class and implement the logic there yourself. That should be pretty straight-forward and might even be the best method for the long run.

**Comment by mvantellingen** [comment]
Should be fixed with the HistoryPlugin (assuming you mean the http headers)
