### ISSUE TITLE
How to resolve Import error

### ISSUE THREAD

**Issue by SamanthPy** [mvantellingen/python-zeep#916]
I have installed zeep by using pip in python 3.6. I am getting below error when i am importing zeep 

from zeep import Client
ImportError: cannot import name 'Client'

**Comment by freitasdfb** [comment]
Hi, SamanthPy ! 

Do a pip freeze command and see all your installed packages

**Comment by SamanthPy** [comment]
Zeep is in list but still it is throwing error

**Comment by mvantellingen** [comment]
Sorry, this seems to be an user error. Give stackoverflow a try

**Comment by Xenoamor** [comment]
And ensure there's no `zeep.pyc` in the folder
