### ISSUE TITLE
run_until_complete in asyncio/transport.py

### ISSUE THREAD

**Issue by kefirbandi** [mvantellingen/python-zeep#917]
Hi,
this is not an issue, rather a question regarding a line in the code for my own education. Feel free to ignore if inappropriate.

In asyncio/transport.py lines 78-79:
```
        # Block until we have the data
        self.loop.run_until_complete(_load_remote_data_async())
```

The question is why do we block explicitly if this is supposed to be an async call?

Please forgive me if this question sounds stupid, I'm only starting to understand python's asyncio

Thanks.

**Comment by lVlayhem** [comment]
transport.load() is executed inside Client.__init__(), which is sync.
zeep still doesn't support async WSDL load.
