### ISSUE TITLE
Add support for ws-addressing

### ISSUE THREAD

**Issue by mvantellingen** [mvantellingen/python-zeep#92]

**Comment by mariten** [comment]
@mvantellingen please add this, it seems your library is not usable until this functionality is available.  Many SOAP servers now require `action` in the HTTP header.  See here: http://stackoverflow.com/questions/16445945/no-action-header-was-found-error-message-while-using-soap-webservice

**Comment by swrichards** [comment]
@mariten one workaround for this is to use the `_soapheaders` kwarg in your service calls, e.g.:

```
from lxml.builder import ElementMaker
import uuid

WSA = ElementMaker(namespace='http://www.w3.org/2005/08/addressing')

wsa_els = [
    WSA.Action('http://some-action'),
    WSA.To('http://some-address'),
    WSA.MessageID('uuid:{}'.format(uuid.uuid4()))
]

client.service.someCall(arg='foo',_soapheaders=wsa_els)

**Comment by mariten** [comment]
Hi @swrichards ,

Thanks for your post.  That would work well for a service that had no required headers.  However, in my case:

1. the SOAP service I'm calling is authentication-based.  I did actually already try passing an `Action` in the `_soapheaders` I have to send, however zeep has an error saying `unexpected keyword argument 'Action'` -- this is unfortunately because the demand for `Action` to be passed is not specified in the XML the same way as the actual headers needed for this call, so zeep thinks passing `Action` violates the SOAP signature.
2. This does not solve the problem of also passing the action in the HTTP headers.  Currently, zeep only passes `Content-Type`, and nothing else.  The server I'm calling requires `action` be specified there as well.

I'm considering hacking the library and trying to manually perform the `post_xml` call myself within my code.

I may potentially just use CURL for this whole process as a temporary solution, and then switch to this library when it has added support for WSA.  Looks like @mvantellingen is doing frequent development on this library, so seems like WSA support will be available sooner than the format of the service I'm calling will change.

**Comment by mvantellingen** [comment]
This is now added to master (see 156e33601b4afc849177df44c8e1fd350bf3d72c). Unfortunaly I have currently no access to a soap server which requires wsa so i'm not really able to test it.

**Comment by mariten** [comment]
@mvantellingen Thanks for the quick work !!! :+1: 

I updated to Zeep 0.15.0 and tried.  It appears to not be working "out of the box".  Let me play around a bit more and look more carefully at your commit and get back to you later this week.

**Comment by erwaller** [comment]
@mvantellingen I just tried master (https://github.com/mvantellingen/python-zeep/commit/d44f3fc73f6f2a9b567be3ece077d018cc49cfa6) against a soap server which requires wsa and zeep generated a request roughly equivalent to:

```
curl -XPOST \
    --header 'Content-Type: application/soap+xml; charset=utf-8' \
    "https://testing.sro4.com/SeatGeek/WebLink/12345/api.do/soap/" \
    --data-binary '<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns1="http://toptix.com/2008" xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://www.w3.org/2005/08/addressing">
  <ns0:Header xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/">
    <wsa:Action>http://toptix.com/2008/ISecurityFacade/Connect</wsa:Action>
    <wsa:MessageID>urn:uuid:a669b72c-4b3e-4b5a-bd00-2019ae6aed4b</wsa:MessageID>
    <wsa:To>https://testing.sro4.com/SeatGeek/WebLink/12345/api.do/soap/</wsa:To>
  </ns0:Header>
  <soap-env:Body>
    <ns1:ISecurityFacade_Connect_RequestMsg>
      <ns1:ApplicationChannel>bSRO</ns1:ApplicationChannel>
      <ns1:ExplicitAuthentication>true</ns1:ExplicitAuthentication>
      <ns1:SalePointId>10000000-0000-0000-0000-000000000001</ns1:SalePointId>
      <ns1:TenantCompanyId>12345</ns1:TenantCompanyId>
      <ns1:UserLogin>nobody</ns1:UserLogin>
      <ns1:UserPassword>redacted</ns1:UserPassword>
    </ns1:ISecurityFacade_Connect_RequestMsg>
  </soap-env:Body>
</soap-env:Envelope>'
```

There seem to be two problems. The first, as @mariten mentioned, is that the `action=` specifier is missing from the Content-Type header, and the second is that the soap header seems to get an incorrect namespace (which appears to be coming from within zeep).

Correcting those two issues manually in the curl command gives you something like:

```
curl -XPOST \
    --header 'Content-Type: application/soap+xml; charset=utf-8; action="http://toptix.com/2008/ISecurityFacade/Connect"' \
    "https://testing.sro4.com/SeatGeek/WebLink/12345/api.do/soap/" \
    --data-binary '<?xml version="1.0" encoding="utf-8"?>
<soap-env:Envelope xmlns:ns1="http://toptix.com/2008" xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://www.w3.org/2005/08/addressing">
  <soap-env:Header>
    <wsa:Action>http://toptix.com/2008/ISecurityFacade/Connect</wsa:Action>
    <wsa:MessageID>urn:uuid:a669b72c-4b3e-4b5a-bd00-2019ae6aed4b</wsa:MessageID>
    <wsa:To>https://testing.sro4.com/SeatGeek/WebLink/12345/api.do/soap/</wsa:To>
  </soap-env:Header>
  <soap-env:Body>
    <ns1:ISecurityFacade_Connect_RequestMsg>
      <ns1:ApplicationChannel>bSRO</ns1:ApplicationChannel>
      <ns1:ExplicitAuthentication>true</ns1:ExplicitAuthentication>
      <ns1:SalePointId>10000000-0000-0000-0000-000000000001</ns1:SalePointId>
      <ns1:TenantCompanyId>12345</ns1:TenantCompanyId>
      <ns1:UserLogin>nobody</ns1:UserLogin>
      <ns1:UserPassword>redacted</ns1:UserPassword>
    </ns1:ISecurityFacade_Connect_RequestMsg>
  </soap-env:Body>
</soap-env:Envelope>'
```

You're welcome to use that server to test against. An incorrect request gives a 500 whereas a correct one should give you a proper login error b/c the username/password are made up. Here's some sample code:

```python
from zeep import Client
from zeep.transports import Transport


wsdl = "https://testing.sro4.com/SeatGeek/WebLink/12345/get.resource/wsdl/ISecurityFacade"

client = Client(wsdl=wsdl)
security = client.bind("SecurityService", "Http_ISecurityFacade")

auth_args = {'UserLogin': 'nobody', 'UserPassword': 'redacted', 'SalePointId': "10000000-0000-0000-0000-000000000001",
             'TenantCompanyId': 12345, 'ApplicationChannel': 'bSRO', 'CultureName': None, 'ExplicitAuthentication': True}
security.Connect(**auth_args)
```

**Comment by vashek** [comment]
@erwaller: I have opened pull request #193 for the namespace issue.

**Comment by mvantellingen** [comment]
The content-type issue was fixed via #211 , #193 was also merged. 

So it should work now, @erwaller are you able to confirm that?

**Comment by mvantellingen** [comment]
Assuming this now works as intended. Please report new issues in new tickets. Thanks for the reports/help!

**Comment by erwaller** [comment]
@mvantellingen just confirmed that zeep, specifically `0.22.0` from pypi, now works out of the box against the soap service in question, thanks!
