### ISSUE TITLE
Lists.asmx from SharePoint 2010 throws ValueError: No schema for namespace=http://www.w3.org/2001/XMLSchema

### ISSUE THREAD

**Issue by sebasmonia** [mvantellingen/python-zeep#99]
I updated to latest to fix the issue reported here https://github.com/mvantellingen/python-zeep/issues/81 and then ran into this new one.

I'm already suffering SharePoint, save me from hops I'm jumping through to work with SUDS and NTML...Zeep handles that part SO MUCH BETTER.

[Listsasmx.txt](https://github.com/mvantellingen/python-zeep/files/332154/Listsasmx.txt)

**Comment by mvantellingen** [comment]
Should be fixed now! Thanks for the kind words :-)

**Comment by sebasmonia** [comment]
Worked perfectly. Thanks!

**Comment by kdheepak** [comment]
@sebasmonia How did you update to the latest?

**Comment by sebasmonia** [comment]
Assuming you don't have git installed:
1. Download ZIP of master
2. Unzip, open cmd in unzipped folder
3. Run the command "python setup.py install"

This will override your current installation from PyPI with the one you just downloaded.

**Comment by kdheepak** [comment]
Ah. Thanks for that answer. I misunderstood what you meant when you said "updated to latest", I thought you updated to a more recent version of Sharepoint.
