### ISSUE TITLE
Timestamp on Signature (x509) WSSE

### ISSUE THREAD

**Issue by Gdar1127** [mvantellingen/python-zeep#996]
Hello, 
I was checking all the main code of zeep and  previous issues, but could not find any relative to add Timestamp and created expired nodes when signature class is used. ¿Is this avaibale or any clue how could I implemented? , really appreciated.

**Comment by Gdar1127** [comment]
> available

**Comment by Bliph** [comment]
I face the same issue and solved it by writing a small new signature class. This also avoids the problem with verification of the response signature mentioned in #997 and #822. It does not seem that zeep supports response verificarion using a different certificate, (which is a bit strange). Note that I am a bit new to Python, so I might have missed something obvious in the zeep library. Anyways, the following class solved my problems:

```
class BinarySignatureTimestamp(BinarySignature):
    def apply(self, envelope, headers):
        security = utils.get_security_header(envelope)

        created = datetime.utcnow()
        expired = created + timedelta(seconds=1 * 60)

        timestamp = utils.WSU('Timestamp')
        timestamp.append(utils.WSU('Created', created.replace(microsecond=0).isoformat()+'Z'))
        timestamp.append(utils.WSU('Expires', expired.replace(microsecond=0).isoformat()+'Z'))

        security.append(timestamp)

        super().apply(envelope, headers)
        return envelope, headers

# Override response verification and skip response verification for now...
# Zeep does not supprt Signature verification with different certificate...
# Ref. https://github.com/mvantellingen/python-zeep/pull/822/  "Add support for different signing and verification certificates #822"
    def verify(self, envelope):
        return envelope
```

Usage: 
```
client = Client(wsdl=wsdl, wsse=BinarySignatureTimestamp(key_pem_filename, crt_pem_filename, key_pem_password))
```

**Comment by Gdar1127** [comment]
Thank you for your help and detailed explanation (it's very helpful for new people on wsse) , I'll give it a try. Yesterday I was checking with debug and a realized that the webservice responded 500 or didn't respponse and zeep printed SignatureVerificationFailed. I'll check more and see later if I found the solution.

**Comment by Bliph** [comment]
For debugging purposes, I would suggest to set 
```client.settings.raw_response = True```
This will return the raw xml data response in stead of a parsed document.

**Comment by Gdar1127** [comment]
Thanks @Bliph , the class that you sent worked perfectly adding the timestamp. Unfortunately I stilll can get the response from web service but I'll keep trying, Just for the reference, are the positions of elements important? As timestamp were added below my binaryToken, but on soup gui were on top.

**Comment by epetrovski** [comment]
The `BinarySignatureTimestamp()` class from @Bliph fixed the issue with timestamp and the issue with different signing and verification certificates for me. Have you considered a pull request, @Bliph?
