### ISSUE TITLE
ERROR: SignatureVerificationFailed using BinarySignature class

### ISSUE THREAD

**Issue by Gdar1127** [mvantellingen/python-zeep#997]
Hello, 
Im trying to connect to a ws with wsse using a x509 certificate for authentication(CA cert), but I'm always getting this issue: ,I tried on soapgui and always get a response. Is is possible that you help me or guide me what could be the possible cause?

Thanks, here the details:

1. The version of zeep 
>>> 3.4.0
2. The WSDL you are using 
>>>  wsdl = 'https://vpfe-hab.dian.gov.co/WcfDianCustomerServices.svc?wsdl'
3. runnable script Im using: 
>>> https://drive.google.com/file/d/1bLK2d6MEGCpHlSZeoJrP5f-gXM7lEhGj/view?usp=sharing
4. Traceback: 
>>> https://pastebin.com/9TK5chKY

**Comment by Bliph** [comment]
I belive this could be the same as #822 (Add support for different signing and verification certificates)

**Comment by Gdar1127** [comment]
thanks  @FuriosoJack , I'll check your code and also implement the class that @Bliph gave. If I figure it out using zeep I'll paste here the solution as I know many new people will use this webservice now days.

**Comment by Gdar1127** [comment]
Hello @FuriosoJack , I've reviewed the php code, unfortunately my acknowledge is only python. I saw that you were able to go further and get some DIAN response, would you mind to share your implementation attempt with zeep? btw the solution of  remove the verification of the response signature worked with me as I don't have the raise exception now. :-)

**Comment by Gdar1127** [comment]
My problem was related to wsa.py . The web service didn't respond if ws-addressing was not correct, so timeout... as no response existed the SignatureVerificationFailed was raised. But using debugging I and changing some things now I'm able to get a not successful response, but at least some response. Thanks for the quick reply.
